### ISSUE TITLE
Invalid Signature after enrolling MOK

### ISSUE THREAD

**Issue by worsedoughnut** [linux-surface/linux-surface#100]
After enrolling the MOK.cer from MokManager, and then re-enabling Secure Boot (Microsoft & 3rd party CA), I get the following error after passing the Surface logo during boot:

```
error: /boot/vmlinuz-5.5.4-surface has invalid signature
error: you need to load the kernel first
```

### Environment
- Hardware model: SL3 Intel
- Distribution: kubuntu 19.10

</details>

**Comment by qzed** [comment]
The testing releases are signed with a different key: https://github.com/linux-surface/linux-surface/blob/feature/pkg-repo/pkg/keys/surface.cer. This key will also be used for all future releases once #86 lands.
