### ISSUE TITLE
Power Button: Suspend vs Hibernate

### ISSUE THREAD

**Issue by torgeros** [linux-surface/linux-surface#1009]
The "suspension mode" for display timeout vs pressing the power button seems to differ. In the power settings, the options say "Automatic **Suspend**: When on battery power" and "Power Button Behavior: **Suspend**".

When the display times out, I can wake the device by pressing a key on the keyboard, like I would expect from a *suspended* device. However, when I press the power button, the device can only be re-activated by pressing the power button again, not from a keyboard input. Without knowing too much about about linux power modes, I would guess this is hibernation rather than suspend.

I would like my power button to turn the screen off and lock the device, but for example not pause currently playing music or active downloads.

### Environment

- Hardware model: Surface Pro 5 / 2017
- Kernel version: `Linux SurfaceTorge 6.0.12-surface #5 SMP PREEMPT_DYNAMIC Sun Dec 11 14:19:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: Ubuntu

<small>can't provide dmesg output because it is too long, I can provide a file if necessary</small>

**Comment by qzed** [comment]
Generally, when the display times out the device is not suspended. It's still running. So when you press the power button, it enters suspend. When you press it again, it exits suspend.

Also normally/by default, you can't wake the device via keyboard on Linux. You can enable that by setting the `power/wakeup` attribute to `enabled` on the corresponding USB device. See e.g. the answer [here](https://askubuntu.com/questions/848698/wake-up-from-suspend-using-wireless-usb-keyboard-or-mouse-for-any-linux-distro) and the comments below.

> I would like my power button to turn the screen off and lock the device, but for example not pause currently playing music or active downloads.

Just for clarification: While Windows has its active standby mechanism, allowing downloading of updates during "suspend", Linux doesn't really support this kind of active-but-suspended behavior (meaning you either have your device suspended or active). At least not yet. So you'd need to leave it running in "display off" mode.

Unfortunately I don't think there's any configuration option to make the power button behave the way you want (at least not in Gnome or Systemd), but you could use the Windows+L key combination to lock it, which should also turn off the display. There might also be a way to write a script that listens to power button events and does that for you (in which case Gnome/systemd would need to be set to ignore the button).

**Comment by NP-chaonay** [comment]
@torgeros
1) you could check if system really in suspend, see this comment https://askubuntu.com/a/1103944 .
2) if it really do hibernation in normal way (not test mode too), it will start from 0 (meaning that it booting from Surface logo (UEFI of device or the BIOS firmware of device)
3) stayed tuned...

**Comment by NP-chaonay** [comment]
@ torgeros  @ qzed 
> Just for clarification: While Windows has its active standby mechanism, allowing downloading of updates during "suspend", Linux doesn't really support this kind of active-but-suspended behavior (meaning you either have your device suspended or active). At least not yet. So you'd need to leave it running in "display off" mode.

IMHO, Linux should be able to acheieve similar (not that much but not less) to that "active standby" (officially called by MS as "modern standy"/"connected/disconnected standby").

 On Windows side, I think when modern standby happens, it suspend all app that not non-UWP kernel/critical component.
 So the only app running are: kernel + allowed UWP app + critical/kernel-mode app + some allowed app

And it has some better integration by having dynamic suspend/resume of device in driver code I think (I think Linux Auto Runtime 
 PM management is most similar, but I don't know if it that near 100% similar, but it is actually depends on driver too ) 

so to acheived this on Linux as much as possible, we have to simulute the user-defined low power mode:
1) have some mechanism to suspend userspace process (can do it manually by making script, but make sure that the app does not failure or misbehaved after these suspension)
2) good driver written at Runtime PM + userspace/kernelspace daemon (if required)
3) auto limit CPU freq/core when user-defined low power mode in active. (so ex: music player should not use more than 1Ghz but in some case that app request, then let limit go beyond.)

**Comment by qzed** [comment]
@NP-chaonay Yes. For the most part I believe the "modern standby" is just suspending most of the user-space applications. We already have opportunistic s0ix which I don't think is that much different from the s2idle state it enters during the actual "suspend" on Linux (as far as I know, s2idle is just putting the processor in some idle loop and setting all peripherals/extended parts into a low power state; so with runtime power management you would already get the low power states for the extended devices and the processor will enter the idle loop when it doesn't have anything to do).

If I remember correctly, there were some patches for suspending individual applications / processes (although that might have been already possible for some time and I might be misremembering things). So I think this mostly depends on user-space (which has to decide what to suspend and when) and wouldn't need much support from the kernel.

**Comment by qzed** [comment]
Also, ideally those devices would still support S3 (suspend-to-ram) in their firmware... but that's a whole other story.
