### ISSUE TITLE
INT3472:00: No sensor module config

### ISSUE THREAD

**Issue by julesfcht** [linux-surface/linux-surface#1012]
Hello,

I installed ubuntu 22.04 (dual boot with Windows 11) and the linux-surface kernel for now 3 weeks. And since 1 week I am unable to boot on ubuntu, I see this message and nothing else (it's blocked on this message) :

int3472-discrete INT3472:00: No sensor module config
int3472-discrete INT3472:00: error -EINVAL: Failed to map regulat
int3472-discrete INT3472:01: No sensor module config
int3472-discrete INT3472:01: error -EINVAL: Failed to map regulat
int3472-discrete INT3472:02: No sensor module config
int3472-discrete INT3472:02: error -EINVAL: Failed to map regulat

and nothing after, I have tried to wait but it's like that for almost 2 hours.

I've done nothing particular since the installation of ubuntu and the linux-surface kernel.

### Environment

- Hardware model: Surface Pro 7
- Kernel version: can't do the commande since i can't boot (and it's hard to copy from recovery mode)
- Distribution: Ubuntu 22.04

<details><summary>`dmesg` output</summary>

```
can't do the commande since i can't boot (and it's hard to copy from recovery mode)

```

</details>

Thank you for your help !

**Comment by NP-chaonay** [comment]
could you try disable secure boot (WARNING that this will discard hibernateion state of Windows even you have put SB on before resume (maybe))

**Comment by julesfcht** [comment]
Thank you a lot, I had not disabled the secure boot... I can close this issue thank to you !
