### ISSUE TITLE
dGPU power limits

### ISSUE THREAD

**Issue by makinbacon21** [linux-surface/linux-surface#1016]
The SLS dGPU sucks power so quickly that it dies *while plugged in to full powered charger* when playing games for a while. I realize that Windows nerfed its power limits, but the limits here are far too high. Charging speed is as expected, as is power supply, but the laptop gets extremely hot and falls to 0% battery.

### Environment

- Hardware model: Surface Laptop Studio (with 3050 Ti laptop GPU)
- Kernel version: `Linux fedora 6.0.12-1.surface.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Dec 9 14:57:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: Fedora 37
- Driver: NVIDIA non-free via Optimus/PRIME

`dmesg` should be irrelevant for this

**Comment by qzed** [comment]
I have no idea how to limit power on the dGPU. This might be Nvidia proprietary stuff...

**Comment by makinbacon21** [comment]
I could mess with `nvidia-smi` till I get nice profiles...I wonder if y'all could ship a package with a systemd service that just executes `nvidia-smi` on boot based on limits we could find from Windows/find from some basic hw testing...or I could cook up a frontend but I'm pretty busy at the moment.

**Comment by makinbacon21** [comment]
Nevermind...`nvidia-smi` did not like that.
```
Changing power management limit is not supported for GPU: 00000000:F3:00.0.
```
I'll continue to investigate.

**Comment by NP-chaonay** [comment]
What is your battery capacity?

And battery on 50% must be enough to keep machine running on max power of dGPU

Maybe you could test problem on Windows too

**Comment by makinbacon21** [comment]
Like I said before (or at least implied), it works fine on windows, and I had full battery, with maximum possible charging power. Not sure how I would check actual battery capacity, but again that should be irrelevant. Windows sets hard power limits, but the Linux driver is preventing me from doing so. Perhaps the gpu fw Linux package doesn't include proper limits. I'll investigate another day.

**Comment by makinbacon21** [comment]
As it turns out, a recent `nvidia-gpu-firmware` update seems to have at least partially resolved the issue and I haven't had such an experience since. If i find more info relating to settings power limits, I will reopen this.
