### ISSUE TITLE
Ubuntu: apt upgrade fails with Error 404 

### ISSUE THREAD

**Issue by pepilyser** [linux-surface/linux-surface#1019]
Hello everyone, 
I'm here because I don't see what could I do about this issue.
First i'll go with the issue : I finish with four 404 errors when I want to upgrade linux-headers-surface and linux-image-surface.

Here is the output of `sudo apt upgrade` :
```
Err:1 https://pkg.surfacelinux.com/debian release/main amd64 linux-headers-6.0.1
2-surface amd64 6.0.12-surface-3
404  Not Found [IP: 2a01:4f8:c17:268c::1 443]                                 
Err:2 https://pkg.surfacelinux.com/debian release/main amd64 linux-headers-surfa
ce amd64 6.0.12-surface-3                                                       
404  Not Found [IP: 2a01:4f8:c17:268c::1 443]                                 
Err:3 https://pkg.surfacelinux.com/debian release/main amd64 linux-image-6.0.12-
surface amd64 6.0.12-surface-3                                                 
404  Not Found [IP: 2a01:4f8:c17:268c::1 443]                                 
Err:4 https://pkg.surfacelinux.com/debian release/main amd64 linux-image-surface
 amd64 6.0.12-surface-3                                                        
404  Not Found [IP: 2a01:4f8:c17:268c::1 443]                                 

E: Failed to fetch https://pkg.surfacelinux.com/debian/pool/main/l/linux-upstrea
m/linux-headers-6.0.12-surface_6.0.12-surface-3_amd64.deb  404  Not Found [IP: 2
a01:4f8:c17:268c::1 443]                                                        
E: Failed to fetch https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface
/linux-headers-surface_6.0.12-surface-3_amd64.deb  404  Not Found [IP: 2a01:4f8:
c17:268c::1 443]                                                                
E: Failed to fetch https://pkg.surfacelinux.com/debian/pool/main/l/linux-upstrea
m/linux-image-6.0.12-surface_6.0.12-surface-3_amd64.deb  404  Not Found [IP: 2a0
1:4f8:c17:268c::1 443]
E: Failed to fetch https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface
/linux-image-surface_6.0.12-surface-3_amd64.deb  404  Not Found [IP: 2a01:4f8:c1
7:268c::1 443]
```

I already have tried the solutions of #625 and if I'm here it's because it didn't work.
I'm clearly not good at all when it comes to kernel and linux systems issues.
So I was wondering if this issue could come from my Ubuntu being 20.04.5 and maybe I should update to Ubuntu 22 ?

### Environment

- Hardware model: Surface Pro 7, Intel i7-1065G7, 16Go RAM
- Kernel version: Linux surface 6.0.9-surface `#1` SMP PREEMPT_DYNAMIC Thu Nov 24 19:45:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 20.04.5 LTS x86_64

**Comment by Alicazs** [comment]
It seems try to fetch file of kernel version 6.0.12-surface-3, when you type in the address bar of your browser with above link like https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface/linux-image-surface_6.0.12-surface-3_amd64.deb, 
nothing downloaded, but when you changed it to 6.0.12-surface-5 like
https://pkg.surfacelinux.com/debian/pool/main/l/linux-surface/linux-image-surface_6.0.12-surface-5_amd64.deb,
a deb package will be download.
Change to the latest version should fix the issue

**Comment by pepilyser** [comment]
> 

Hello and thanks for your help!
Could you please explain to me how should I change to the last version ?
I tried to manually change the values in `/var/lib/apt/list/pkg.surfacelinux.com_debian_dists_release_main_binary-amd64_Packages` but I got an error about the size of the files, so, after changing the size values, I have another error about the size of the files like this : `File has unexpected size (2474 != 2274)` ...

Maybe forcing the thing like this wasn't the best idea, but if you could tell me what should I do to solve/repair this or what should I search for, I would be grateful. 

I also tried to download and `dpkg -i /home/prim/Downloads/linux-image-surface_6.0.12-surface-5_amd64.deb` from your link and `apt --fix-broken install` but I got the same errors.

**Comment by Alicazs** [comment]
Did you run `sudo apt update` before upgrade? seems package cache outdate.

**Comment by pepilyser** [comment]
> 

Of course I did

**Comment by qzed** [comment]
I can't reproduce this with a freshly set up container. As @Alicazs said, this looks like and outdated cache using old links.

**Comment by pepilyser** [comment]
So i fixed the 404 error by editing like this `sudo nano pkg.surfacelinux.com_debian_dists_release_main_binary-amd64_Packages`
with those data to change : 
```
Hashes of received file:                                                     
    - SHA256:3478140544637e66d75dd2a669b9ce0139bf27bb29dbd1072caffa921e4a6303           
    - SHA1:488ebe416467cd9214664ae9944a553f012c50ca
    - MD5Sum:404b1ae7df9caf7cefbce1692280b230
    - Filesize:73681430
```

But now even after a new `apt update` and `apt upgrade` the header and image packages don't upgrade.
I still don't understand why but since my 404 error part is now done i'll close this issue. Thanks for your help and for your hard work.
