### ISSUE TITLE
Singletouch not working (SP7 & kernel 5.5.6-surface)

### ISSUE THREAD

**Issue by randomizeduser** [linux-surface/linux-surface#102]
Singletouch does not work with the new kernel. I have tried it on Linux Mint MATE and additionally on GNOME.

**Hardware:** `Surface Pro 7`
**Kernel:** `Linux sp7 5.5.6-surface #1 SMP Wed Feb 26 15:14:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
**OS:** `Linux Mint 19.3 MATE (& GNOME)`

[dmesg.log](https://github.com/linux-surface/linux-surface/files/4264430/dmesg.log)

**Comment by StollD** [comment]
Since the IPTS driver didn't even load according to your log, I checked our build config and noticed that the IPTS driver wasn't even being built in the 5.5.6-1 releases. I fixed the issue and started new builds, so please try again once 5.5.6-2 is available in the repos.

**Comment by randomizeduser** [comment]
Awesome! I just checked and it is working now with 5.5.6-2! Thank you!!!
