### ISSUE TITLE
Virtual Keyboard SOS

### ISSUE THREAD

**Issue by Boffice** [linux-surface/linux-surface#1021]
Hello,

Due to liquid damage base of my surface book 2 is heavily damaged, However Tablet is switching on.

I want to access my system and do some backup, unfortunately i have enabled disk encryption on fedora and password dialog is not supported by touch keyboard.

As workaround i tried to connect usb keyboard to my base but it is totally dead and does not have power at all.

Unfortunately it is very difficult to find 15` SB2 in my country it is not soled in stores and i was not able to find anybody that has same device to use their base for password. 

Only solution i have in mind is ether purchasing used base from Ebay or opening up the tablet removing SSD and connecting it to a different computer. 

Hope that i am missing something and somebody from here can give me better advise.

**Comment by qzed** [comment]
One alternative that I can think of is getting a Surface Dock. That should give you USB over the Surface Connect port. I think there might also be some third-party adapters from Surface Connect port to USB for data, but you will need to make sure that it's not just for charging.

**Comment by Boffice** [comment]
@qzed thanks for prompt response, unfortunately motherboard on base is totally destroyed it is not reacting to type-C as well for docking station.

I tied to search 3rd party adapters for tablet there are lots of different accessories for surface pro but was not able to find anything on surface book.

**Comment by NP-chaonay** [comment]
> One alternative that I can think of is getting a Surface Dock. That should give you USB over the Surface Connect port. I think there might also be some third-party adapters from Surface Connect port to USB for data, but you will need to make sure that it's not just for charging.

but since SB2 required base for charging this is gonna be tough btw.

@Boffice so yeah maybe I think I suggest you to buy the base unless you want to buy new device, so you can remove ssd (but I not sure if we able to find adaptor for surface ssd)

**Comment by NP-chaonay** [comment]
>  base from Ebay

maybe the not bad idea, since your country dont have anyone import that

**Comment by qzed** [comment]
@Boffice What I meant with dock was something like this: https://www.microsoft.com/en-us/d/surface-dock/8qrh2npz0s0p. You might be able to get one cheaper than the base. All you need is something that can break out the proprietary Surface Connect adapter to a USB port, as long as the Surface Connect port on the tablet still works.

Note that the tablet itself has that port, not just the base. It's the middle (larger) of the three connectors at the bottom and also used to connect the tablet with the base.

**Comment by Boffice** [comment]
@qzed Ok so you mean that i could technically connect [charging port ](https://guide-images.cdn.ifixit.com/igi/FvK4fsCS2YGUWDgY.medium) to USB dock if i find adapter like [this one](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDsRFvSTNDKstG3zJvRyHSHA5PzOB1Ot4U-w&usqp=CAU) and connect the keyboard through the dock station right ?

**Comment by qzed** [comment]
Correct. Unfortunately I haven't found one with data capability, but I haven't looked that long. The next best "official" thing to that is the Surface Dock.

**Comment by Boffice** [comment]
I have found the wizard that was able to restore the base, thank you all for advises.
