### ISSUE TITLE
Non-functional autofocus for rear camera Surface go 2

### ISSUE THREAD

**Issue by FlyingPC** [linux-surface/linux-surface#1022]
Hardware: Surface Go 2
Distro: Fedora 37
Kernel: 6.0.12-1.surface
libcamera build from repository (last commit)

Problem :
Last August, the rear camera's autofocus was working. But, I recently tested again and found that it no longer works.

I tried looking for a libcamera commit that was working (around last August) with autofocus but couldn't find one. Therefore, I think the problem comes from the kernel.

**Comment by FlyingPC** [comment]
Here is the output of qcam :
"""
[0:39:32.913634636] [9512]  INFO Camera camera_manager.cpp:299 libcamera v0.0.3+10-0a8ac1ee
[0:39:32.968496469] [9523] ERROR V4L2 v4l2_device.cpp:92 'dw9719 2-000c': Failed to open V4L2 device '': Aucun fichier ou dossier de ce type
[0:39:32.968624536] [9523] ERROR CameraSensor camera_sensor.cpp:501 'ov8865 2-0010': Lens initialisation failed, lens disabled
[0:39:33.000939927] [9523] ERROR IPAProxy ipa_proxy.cpp:149 Configuration file 'ov8865.yaml' not found for IPA module 'ipu3'
[0:39:33.003659914] [9523]  INFO IPU3 ipu3.cpp:1206 Registered Camera[0] "\_SB_.PCI0.LNK0" connected to CSI-2 receiver 0
[0:39:33.020537561] [9523] ERROR IPAProxy ipa_proxy.cpp:149 Configuration file 'ov5693.yaml' not found for IPA module 'ipu3'
[0:39:33.021198924] [9523]  INFO IPU3 ipu3.cpp:1206 Registered Camera[1] "\_SB_.PCI0.LNK1" connected to CSI-2 receiver 1
[0:39:34.796592988] [9512]  INFO Camera camera.cpp:1026 configuring streams: (0) 1280x720-NV12
Using software format conversion from 842094158
[0:39:35.028395346] [9523]  INFO V4L2 v4l2_videodevice.cpp:1820 /dev/video10[46:cap]: Zero sequence expected for first frame (got 1)
[0:39:35.039887799] [9523]  INFO V4L2 v4l2_videodevice.cpp:1820 /dev/video2[34:cap]: Zero sequence expected for first frame (got 1)
[0:39:35.040341503] [9523]  INFO V4L2 v4l2_videodevice.cpp:1820 /dev/video4[37:cap]: Zero sequence expected for first frame (got 1)
"""

**Comment by PhilDevProg** [comment]
Same on the Go3 with both cameras.

**Comment by djrscally** [comment]
@FlyingPC sorry I missed this. Can you give me outputs from lsmod and dmesg to look at please?

**Comment by FlyingPC** [comment]
@djrscally my surface go unfortunately does not start anymore. So I can no longer answer to your question.

I'll try to see if I can fix it but it seems complicated! :-)

**Comment by FlyingPC** [comment]
Maybe @PhilDevProg can give the output of lsmod and dmesg.

**Comment by PhilDevProg** [comment]
@FlyingPC djrscally already has my output due to another camera issue and I don't really know if I really have the same issue as you. Maybe it's just because my lens doesn't work. (@djrscally already found out what's the problem and showed a fix in the main Camera issue but I haven't gotten it to work yet because it needs to build the kernel which I failed)

**Comment by PhilDevProg** [comment]
Okay, I now have the lens working and the autofocus works sometimes when the rear camera sees the same picture for a very long time...
<details>
<summary>
lsmod output
</summary>
Module                  Size  Used by
uhid                   20480  1
sch_ingress            16384  1
af_key                 49152  0
v4l2loopback           65536  0
vsock_loopback         16384  0
vmw_vsock_virtio_transport_common    49152  1 vsock_loopback
vmw_vsock_vmci_transport    36864  0
vsock                  53248  5 vmw_vsock_virtio_transport_common,vsock_loopback,vmw_vsock_vmci_transport
vmw_vmci              118784  1 vmw_vsock_vmci_transport
nfnetlink_log          24576  2
xfrm_interface         24576  0
xfrm6_tunnel           16384  1 xfrm_interface
tunnel4                16384  1 xfrm_interface
tunnel6                16384  2 xfrm_interface,xfrm6_tunnel
veth                   36864  0
overlay               176128  2
loop                   36864  4
nft_masq               16384  1
bridge                360448  0
stp                    16384  1 bridge
llc                    16384  2 bridge,stp
tls                   131072  2
uinput                 20480  0
rfcomm                 94208  16
snd_seq_dummy          16384  0
snd_hrtimer            16384  1
nft_objref             16384  1
intel_rapl_msr         20480  0
nf_conntrack_netbios_ns    16384  1
nf_conntrack_broadcast    16384  1 nf_conntrack_netbios_ns
nft_fib_inet           16384  1
nft_fib_ipv4           16384  1 nft_fib_inet
nft_fib_ipv6           16384  1 nft_fib_inet
nft_fib                16384  3 nft_fib_ipv6,nft_fib_ipv4,nft_fib_inet
nft_reject_inet        16384  6
nf_reject_ipv4         16384  1 nft_reject_inet
nf_reject_ipv6         20480  1 nft_reject_inet
nft_reject             16384  1 nft_reject_inet
nft_ct                 20480  16
nft_chain_nat          16384  4
nf_nat                 57344  2 nft_masq,nft_chain_nat
dw9719                 16384  1
nf_conntrack          167936  5 nf_nat,nft_ct,nf_conntrack_netbios_ns,nf_conntrack_broadcast,nft_masq
nf_defrag_ipv6         24576  1 nf_conntrack
nf_defrag_ipv4         16384  1 nf_conntrack
snd_sof_pci_intel_skl    16384  0
ip_set                 61440  0
snd_sof_intel_hda_common   212992  1 snd_sof_pci_intel_skl
soundwire_intel        53248  1 snd_sof_intel_hda_common
soundwire_generic_allocation    16384  1 soundwire_intel
soundwire_cadence      45056  1 soundwire_intel
snd_sof_intel_hda      20480  1 snd_sof_intel_hda_common
nf_tables             282624  318 nft_ct,nft_reject_inet,nft_fib_ipv6,nft_objref,nft_fib_ipv4,nft_masq,nft_chain_nat,nft_reject,nft_fib,nft_fib_inet
nfnetlink              20480  6 nf_tables,ip_set,nfnetlink_log
snd_sof_pci            24576  2 snd_sof_intel_hda_common,snd_sof_pci_intel_skl
snd_sof_xtensa_dsp     20480  1 snd_sof_intel_hda_common
bnep                   28672  2
snd_sof               335872  2 snd_sof_pci,snd_sof_intel_hda_common
mei_hdcp               24576  0
snd_sof_utils          20480  1 snd_sof
mei_pxp                20480  0
soundwire_bus         126976  3 soundwire_intel,soundwire_generic_allocation,soundwire_cadence
snd_soc_avs           172032  0
snd_soc_hda_codec      28672  1 snd_soc_avs
snd_soc_skl           217088  0
snd_soc_hdac_hda       28672  2 snd_sof_intel_hda_common,snd_soc_skl
snd_hda_ext_core       36864  5 snd_soc_avs,snd_soc_hda_codec,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl
snd_soc_sst_ipc        20480  1 snd_soc_skl
snd_soc_sst_dsp        36864  1 snd_soc_skl
intel_rapl_common      32768  1 intel_rapl_msr
snd_soc_acpi_intel_match    73728  3 snd_sof_intel_hda_common,snd_soc_skl,snd_sof_pci_intel_skl
snd_soc_acpi           16384  3 snd_soc_acpi_intel_match,snd_sof_intel_hda_common,snd_soc_skl
qrtr                   53248  4
intel_tcc_cooling      16384  0
gpio_tps68470          16384  2
x86_pkg_temp_thermal    20480  0
snd_hda_codec_hdmi     86016  1
intel_powerclamp       20480  0
coretemp               20480  0
snd_soc_core          389120  7 snd_soc_avs,snd_soc_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl
kvm_intel             389120  0
snd_compress           28672  1 snd_soc_core
ac97_bus               16384  1 snd_soc_core
snd_hda_codec_realtek   172032  1
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_hda_codec_generic    98304  1 snd_hda_codec_realtek
ledtrig_audio          16384  1 snd_hda_codec_generic
snd_hda_intel          61440  2
snd_intel_dspcfg       36864  5 snd_soc_avs,snd_hda_intel,snd_sof,snd_sof_intel_hda_common,snd_soc_skl
kvm                  1126400  1 kvm_intel
snd_intel_sdw_acpi     20480  2 snd_sof_intel_hda_common,snd_intel_dspcfg
irqbypass              16384  1 kvm
iwlmvm                528384  0
rapl                   20480  0
intel_cstate           20480  0
mac80211             1298432  1 iwlmvm
libarc4                16384  1 mac80211
snd_hda_codec         184320  9 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_codec_realtek,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_hda_core          114688  12 snd_hda_codec_generic,snd_soc_avs,snd_hda_codec_hdmi,snd_soc_hda_codec,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_codec_realtek,snd_sof_intel_hda_common,snd_soc_hdac_hda,snd_soc_skl,snd_sof_intel_hda
snd_hwdep              16384  1 snd_hda_codec
intel_uncore          217088  0
snd_seq                94208  7 snd_seq_dummy
snd_seq_device         16384  1 snd_seq
snd_pcm               151552  13 snd_soc_avs,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_sof_utils,snd_soc_skl,snd_hda_core,snd_pcm_dmaengine
snd_timer              49152  3 snd_seq,snd_hrtimer,snd_pcm
wmi_bmof               16384  0
pcspkr                 16384  0
binfmt_misc            28672  1
snd                   126976  19 snd_hda_codec_generic,snd_seq,snd_seq_device,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm
iwlwifi               413696  1 iwlmvm
soundcore              16384  1 snd
mei_me                 53248  2
vfat                   24576  1
btusb                  65536  0
fat                    94208  1 vfat
btrtl                  28672  1 btusb
btbcm                  24576  1 btusb
btintel                49152  1 btusb
btmtk                  16384  1 btusb
joydev                 28672  0
cfg80211             1101824  3 iwlmvm,iwlwifi,mac80211
mei                   172032  5 mei_hdcp,mei_pxp,mei_me
bluetooth             876544  46 btrtl,btmtk,btintel,btbcm,bnep,btusb,rfcomm
rfkill                 36864  9 iwlmvm,bluetooth,cfg80211
idma64                 20480  0
ipu3_cio2              53248  0
intel_pch_thermal      20480  0
intel_xhci_usb_role_switch    16384  0
hid_sensor_gyro_3d     20480  0
hid_sensor_accel_3d    20480  1
hid_sensor_als         20480  1
hid_sensor_magn_3d     20480  1
ipu3_imgu             241664  0
hid_sensor_rotation    20480  0
hid_sensor_incl_3d     20480  0
hid_sensor_trigger     20480  15 hid_sensor_gyro_3d,hid_sensor_incl_3d,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_magn_3d,hid_sensor_rotation
hid_sensor_iio_common    20480  7 hid_sensor_gyro_3d,hid_sensor_trigger,hid_sensor_incl_3d,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_magn_3d,hid_sensor_rotation
industrialio_triggered_buffer    16384  1 hid_sensor_trigger
videobuf2_dma_sg       20480  2 ipu3_cio2,ipu3_imgu
kfifo_buf              16384  1 industrialio_triggered_buffer
videobuf2_memops       20480  1 videobuf2_dma_sg
videobuf2_v4l2         40960  2 ipu3_cio2,ipu3_imgu
videobuf2_common       86016  5 ipu3_cio2,videobuf2_v4l2,videobuf2_dma_sg,ipu3_imgu,videobuf2_memops
industrialio          106496  12 industrialio_triggered_buffer,hid_sensor_gyro_3d,hid_sensor_trigger,hid_sensor_incl_3d,kfifo_buf,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_magn_3d,hid_sensor_rotation
ov8865                 40960  1
ov7251                 32768  0
ov5693                 28672  1
v4l2_fwnode            32768  4 ipu3_cio2,ov7251,ov5693,ov8865
v4l2_async             32768  6 v4l2_fwnode,ipu3_cio2,ov7251,ov5693,dw9719,ov8865
intel_skl_int3472_tps68470    20480  0
tps68470_regulator     16384  5
clk_tps68470           16384  2
videodev              315392  10 v4l2_async,ipu3_cio2,ov7251,videobuf2_v4l2,ov5693,v4l2loopback,videobuf2_common,dw9719,ov8865,ipu3_imgu
mc                     73728  10 v4l2_async,videodev,ipu3_cio2,ov7251,videobuf2_v4l2,ov5693,videobuf2_common,dw9719,ov8865,ipu3_imgu
intel_skl_int3472_discrete    20480  1
soc_button_array       20480  0
surface_hotplug        20480  0
intel_hid              28672  0
acpi_pad              184320  0
sparse_keymap          16384  1 intel_hid
zram                   36864  2
dm_crypt               61440  1
hid_sensor_hub         32768  8 hid_sensor_gyro_3d,hid_sensor_trigger,hid_sensor_iio_common,hid_sensor_incl_3d,hid_sensor_als,hid_sensor_accel_3d,hid_sensor_magn_3d,hid_sensor_rotation
intel_ishtp_hid        28672  0
i915                 3436544  147
drm_buddy              20480  1 i915
crct10dif_pclmul       16384  1
drm_display_helper    208896  1 i915
crc32_pclmul           16384  0
rtsx_pci_sdmmc         32768  0
crc32c_intel           24576  5
polyval_clmulni        16384  0
polyval_generic        16384  1 polyval_clmulni
mmc_core              225280  1 rtsx_pci_sdmmc
ghash_clmulni_intel    16384  0
nvme                   61440  3
sha512_ssse3           53248  0
i2c_hid_acpi           16384  0
cec                    81920  2 drm_display_helper,i915
ttm                    94208  1 i915
nvme_core             196608  4 nvme
ucsi_acpi              16384  0
nvme_common            24576  1 nvme_core
typec_ucsi             53248  1 ucsi_acpi
rtsx_pci              110592  1 rtsx_pci_sdmmc
intel_ish_ipc          32768  0
intel_ishtp            69632  2 intel_ishtp_hid,intel_ish_ipc
typec                  90112  1 typec_ucsi
i2c_hid                40960  1 i2c_hid_acpi
video                  65536  1 i915
wmi                    45056  2 video,wmi_bmof
pinctrl_sunrisepoint    28672  5
hid_multitouch         36864  0
ip6_tables             36864  0
ip_tables              36864  0
fuse                  176128  9
</details>
<details>
<summary>
dmesg output
</summary>
x
</details>

**Comment by Lijwent** [comment]
Any fix for the autofocus ? It's the same on the surface pro 5 with ubuntu 22.04 and the last version of libcamera

**Comment by djrscally** [comment]
@Lijwent can you share the output of dmesg and lsmod please (@PhilDevProg's issue is different and now fixed)? Sorry @FlyingPC for the delay on this one, I'll try to get back to figuring out what went wrong - did you get your surface booting again?

**Comment by Lijwent** [comment]
@djrscally If it helps, the autofocus doesn't work for close objects, I was trying to scan a QRcode
[lsmod.txt](https://github.com/linux-surface/linux-surface/files/10870275/lsmod.txt)
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/10870277/dmesg.txt)
Thanks for any help you can give

**Comment by djrscally** [comment]
@Lijwent ah; but does it "work" in the sense that it _tries_ to autofocus, it just struggles on some objects?

**Comment by Lijwent** [comment]
> @Lijwent ah; but does it "work" in the sense that it _tries_ to autofocus, it just struggles on some objects?

@djrscally It tries to autofocus but it doesnt work, I tried the trick to go from further away to closer to force it to autofocus, but it stays blured, even after waiting a while

**Comment by djrscally** [comment]
> > @Lijwent ah; but does it "work" in the sense that it _tries_ to autofocus, it just struggles on some objects?
> 
> @djrscally It tries to autofocus but it doesnt work, I tried the trick to go from further away to closer to force it to autofocus, but it stays blured, even after waiting a while

OK. The actual functioning of the autofocus is really outside the scope of this project - it needs to be handled within the libcamera development process (as that's the library that runs the autofocus). Can you log that problem on https://bugs.libcamera.org/ perhaps?

The issue FlyingPC has is different, but the dmesg output you posted has lead me to understand the problem, so thank you for that!

**Comment by djrscally** [comment]
@FlyingPC [this tree](https://github.com/djrscally/kernel/tree/v6.1-surface-devel/ov7251_discrete) or the patch pasted below should fix your issue. None of my devices exhibits the problem unfortunately, so I can't test it. If you (or anyone else with a Surface that _isn't_ one of the Go line could test it and let me know the results that would be appreciated.

```diff
diff --git a/drivers/platform/x86/intel/int3472/discrete.c b/drivers/platform/x86/intel/int3472/discrete.c
index 974a132db651..e31acae1199a 100644
--- a/drivers/platform/x86/intel/int3472/discrete.c
+++ b/drivers/platform/x86/intel/int3472/discrete.c
@@ -108,6 +108,9 @@ static int skl_int3472_map_gpio_to_sensor(struct int3472_discrete_device *int347
 {
        const struct int3472_sensor_config *sensor_config;
        char *path = agpio->resource_source.string_ptr;
+       const struct acpi_device_id ov7251_ids[] = {
+               { "INT347E" },
+       };
        struct gpiod_lookup *table_entry;
        struct acpi_device *adev;
        acpi_handle handle;
@@ -130,6 +133,14 @@ static int skl_int3472_map_gpio_to_sensor(struct int3472_discrete_device *int347
                }
        }
 
+       /*
+        * In addition to the function remap table we need to bulk remap the
+        * "reset" GPIO for the OmniVision 7251 sensor, as the driver for that
+        * expects its only GPIO pin to be called "enable".
+        */
+       if (!strcmp(func, "reset") && acpi_match_device_ids(int3472->sensor, ov7251_ids))
+               func = "enable";
+
        /* Functions mapped to NULL should not be mapped to the sensor */
        if (!func)
                return 0;
```

**Comment by FlyingPC** [comment]
@djrscally sorry, I couldn't repair my surface book 2 (it's quite complicated to disassemble...).

**Comment by djrscally** [comment]
Np, I'll see if anyone else can try. What happened to it!?

**Comment by qzed** [comment]
I can give it a try later, once I'm back at my workstation (in ~ 4 hours).

**Comment by qzed** [comment]
@djrscally I still get the "cannot get enable gpio" with your tree.

**Comment by djrscally** [comment]
Nuts...ok - I'll try to dump a bunch of debug output into there and push again later today so we can see why that's not worked.

**Comment by djrscally** [comment]
@qzed OK I pushed again...bit minimal but I'm struggling to see where it can be failing other than that point!

**Comment by qzed** [comment]
Thanks, I'll give it a try and let you know. I'll also can also try to figure out what's going wrong.

**Comment by qzed** [comment]
Found one issue: [`acpi_match_device_ids()`](https://elixir.bootlin.com/linux/latest/C/ident/acpi_match_device_ids) returns `0` if it matches and `-ENOENT` if it doesn't... gotta love the functions that do the opposite of what they're named after xD

So replacing
```c
	if (!strcmp(func, "reset") && acpi_match_device_ids(int3472->sensor, ov7251_ids)) {
```
with
```c
	if (!strcmp(func, "reset") && !acpi_match_device_ids(int3472->sensor, ov7251_ids)) {
```
does the trick. Maybe [`acpi_match_device()`](https://elixir.bootlin.com/linux/latest/C/ident/acpi_match_device) is better for readability here, because that actually does (more or less) what its name says.

Now it fails with `-EREMOTEIO`. Let me first check that that isn't a hardware issue on my side again... after that I'll post some logs.

**Comment by qzed** [comment]
So if I'm not mistaken, it fails here: https://elixir.bootlin.com/linux/v6.1.2/source/drivers/media/i2c/ov7251.c#L932, which seems to be the first register access of the driver.

**Comment by djrscally** [comment]
Yep so it's not powered on. Which device do you have again so I can look at
the DSDT?

**Comment by djrscally** [comment]
OK, and if you run `sudo i2cdetect -r -y 3` I expect no device at address 0x60. If you then run `sudo gpioset --mode=wait 0 85=1 130=1` and then try i2cdetect again, the device should show up...does that happen?

After checking i2cdetect again hit enter on gpioset so it finishes and run `sudo gpioset 85=0 130=0` to make sure they're off.

**Comment by qzed** [comment]
> OK, and if you run `sudo i2cdetect -r -y 3` I expect no device at address 0x60.

Correct.

> If you then run `sudo gpioset --mode=wait 0 85=1 130=1` and then try i2cdetect again, the device should show up...does that happen?

Yes. There's the one at 0x60 and then also another(?) at 0x70.

Should I try to increase the timeout in the driver?

**Comment by qzed** [comment]
> Should I try to increase the timeout in the driver?

Tried setting that to 100ms, didn't work.

**Comment by djrscally** [comment]
@qzed OK. At least it shows up alright, and that means something in the handling code is screwed up. I think the polarity is wrong; let me push an update for you (and I'll fix the acpi matching)

**Comment by djrscally** [comment]
@qzed ok ready to test when you're able.

**Comment by djrscally** [comment]
Aaaand force pushed again with a less hacky fix.

**Comment by qzed** [comment]
Awesome, that seems to work:
```
[   29.994970] ov7251 i2c-INT347E:00: OV7251 revision 7 (1F) detected at address 0x60
```

**Comment by qzed** [comment]
Any way I can test the sensor?

**Comment by djrscally** [comment]
Sweet! I'll upstream that, and open a PR here. You can currently run:

```bash
#!/bin/bash

# Get the devnode
VDEV=$(media-ctl -d1 -e "ipu3-cio2 2");

# Set links and format
media-ctl -d1 -l "'ov7251 3-0060':0 -> 'ipu3-csi2 2':0[1]";
media-ctl -d1 -V "'ipu3-csi2 2':0 [fmt:Y10_1X10/640x480]";
v4l2-ctl -d "$VDEV" --set-fmt-video="width=640,height=480,pixelformat=4";

# Capture
v4l2-ctl -d "$VDEV" --stream-mmap --stream-to=/home/djrscally/ov7251.bin --stream-count=1;

# Convert
ipu3-unpack ~/ov7251.bin ~/ov7251.raw
raw2rgbpnm -s 640x480 -f Y10 ~/ov7251.raw ~/ov7251.ppm
```

To capture from it, where "ipu3-unpack" in libcamera/utils/ipu3 and "raw2rgbpnm" is at git://salottisipuli.retiisi.org.uk/~sailus/raw2rgbpnm.git. The image will likely be very dark because of the non-functional IR LED. Now that it works on the Surface I'm working on getting libcamera to work with this camera in its IPU3 pipeline (which it currently doesn't because it works differently to the others), and then I'll see what I can do about getting the IR LED to work for the discrete type PMIC.

**Comment by qzed** [comment]
Nice, that worked! It's rotated 90° and I can barely see anything, but it's an image, yay.

**Comment by djrscally** [comment]
@qzed try maxing the exposure of the sensor;

```
VSDEV=$(media-ctl -d1 -e 'ov7251 3-0060')
v4l2-ctl -d $VSDEV -c exposure=1500
```

and then run the capture script again; it might be reasonably visible.

**Comment by qzed** [comment]
Ah neat, I basically just saw some and white in the background where my window was. But some tweaking with gimp produced reasonable output. Bit noisy, but I guess that's to be expected at the moment without the LED (and probably also some config tuning). So all in all looks like the sensor driver is doing it's job correctly.

**Comment by qzed** [comment]
The patch is in the latest release. I believe this can be closed then?

**Comment by djrscally** [comment]
I think so yes.
