### ISSUE TITLE
SB1 Unable to detach screen

### ISSUE THREAD

**Issue by msc5** [linux-surface/linux-surface#1023]
I am completely unable to detach the screen. I hold the screen detach button (next to the F12 key) and it turns red, but nothing happens. It stays this way indefinitely until I press and hold it again, and it turns off.

I also saw this message in journalctl, I don't know if it is helpful:
``` Dec 30 15:13:30 laptop kernel: surface_pro3_button MSHW0040:00: Tablet mode is not supported```

### Environment

- Hardware model: Surface Book 1
- Kernel version: ```Linux laptop 6.0.12-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Fri, 09 Dec 2022 13:40:50 +0000 x86_64 GNU/Linux```
- Distribution: Arch Linux

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/10326341/dmesg.txt)

**Comment by qzed** [comment]
A red light means that the EC blocked/aborted the process.

First of all, certain conditions (like tablet battery empty) can block detachment. However, there is also a sort of "software lock", which can be set by Windows when it detects applications running on the dGPU. On Linux, we currently don't have a way to communicate with the EC of the SB1, so we don't have a way to disengage that lock when it's been set on Windows.

So depending on why it's blocking the detachment, you can try either charging it up (if it's low battery) or booting into Windows (if it's the software lock). Alternatively, you can also try doing a two-button reset (press power and volume up button when the device is on until it reboots into UEFI), which (I think) should reset the software lock.

**Comment by qzed** [comment]
The `surface_pro3_button MSHW0040:00: Tablet mode is not supported` message has nothing to do with the detachment process. As I've written above: A red light means that the EC blocked the detachment process. And since we don't have a way to communicate with the EC on Linux at the moment, there's nothing we can do to tell it to stop that. You'll have to boot into windows and try detaching there.

**Comment by qzed** [comment]
See also #93 for the issue for EC support.
