### ISSUE TITLE
OSK shift key acts like caps lock

### ISSUE THREAD

**Issue by lsitongia** [linux-surface/linux-surface#1025]
- Hardware model: Surface Go 2
- Kernel version: Linux surface 6.0.12-surface #5 SMP PREEMPT_DYNAMIC Sun Dec 11 14:19:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

- Distribution: Ubuntu 

OSK shift key acts like caps lock

Type the shift key on the on screen keyboard
Type a character It s capitalized.
The keyboard stays all caps.
Type another character. It is capitalized.
Type the shift key. The keyboard reverts back to lower case.

The expected behavior is, as with many phones for example, is to automatically revert to lower case after one upper case letter is output.

**Comment by qzed** [comment]
Which OSK do you mean? The OSK in UEFI/the bootloader is provided by firmware. So there's nothing we can do about that. And the OSK showing up in Linux is provided by your desktop environment (so Gnome if you're using Ubuntu). You'd have to bring that up with them.

**Comment by NP-chaonay** [comment]
your defination of OSK can be either OSK by Surface firmware or Linux program itself

Neither of these Linux-surface manipulate, and may not considered as bug. This is seem to be feature feedback or how-to of settings.

By the way it is out-of-scope of community and I not know if we can change that behaviour of OSK on Ubuntu. (For OSK by firmware, we cannot do anything about it)

**Comment by lsitongia** [comment]
I thought I closed this a couple of days ago. I understand now. I will look to Gnome about this issue.

**Comment by lsitongia** [comment]
Ah, got it. Thanks for the pointer. That  explains why no one has talked about it here. :-)
