### ISSUE TITLE
Surface Pro 7 with Manjaro/Archlinux can't use the Secure Boot

### ISSUE THREAD

**Issue by yblpoi** [linux-surface/linux-surface#1032]
Chinglish, please understand

- Device: Surface Pro 7 i7 16GB 1TB SSD
- GNU/LINUX: Manjaro

I finished the installation as the Wiki, and everything else worked fine. Only the security boot option is problematic.

The details are as follows:
After the linux-surface-secureboot-mok package is installed, the certificate import page is not displayed after the PC restarts.
The certificate installation page is displayed by setting USB device boot priority. However, the system still fails to boot after you enter the password and restart.
While the problem is harmless, the red color on the startup screen still makes me feel bad.
How can I solve it?

**Comment by qzed** [comment]
Unfortunately setting up secureboot on Arch Linux is a bit involved and most of this is not Surface specific. You will need to set up `shim` with a custom key. This is described [here](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim_with_key). If you plan on using GRUB (which IIRC might be the only bootloader that properly works with the latest shim version, maybe systemd-boot works as well but I don't know that), you will need some extra steps, described [here](https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot#shim_with_key_and_GRUB).
