### ISSUE TITLE
dpkg: Fehler beim Bearbeiten des Paketes virtualbox-dkms (--configure):

### ISSUE THREAD

**Issue by kwai-chang** [linux-surface/linux-surface#1035]
Fehler beim Bearbeiten des Paketes virtualbox-dkms

### Environment

- Hardware model:  SP4
- Kernel version:  Linux surfacx 6.1.3-surface
- Distribution: MX Linux 
- Virtualbox 7.04
 
-Mit Kernel 5.18 laüft es einwandfrei, dort fehlt aber die Touchscreen und Pen Unterstützung

```

virtualbox-dkms (7.0.4-dfsg-4~mx21+1) wird eingerichtet ...
Unable to init server: Verbindung ist gescheitert: Verbindungsaufbau abgelehnt

(frontend:8941): Gtk-WARNING **: 11:32:03.140: cannot open display: 
debconf: kann Oberfläche nicht initialisieren: Gnome
debconf: (DISPLAY problem?)
debconf: greife zurück auf die Oberfläche: Dialog
Removing old virtualbox-7.0.4 DKMS files...
Deleting module virtualbox-7.0.4 completely from the DKMS tree.
Loading new virtualbox-7.0.4 DKMS files...
Building for 6.1.3-surface
Building initial module for 6.1.3-surface
Error! Bad return status for module build on kernel: 6.1.3-surface (x86_64)
Consult /var/lib/dkms/virtualbox/7.0.4/build/make.log for more information.
dpkg: Fehler beim Bearbeiten des Paketes virtualbox-dkms (--configure):
 »installiertes virtualbox-dkms-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 10 zurück
Fehler traten auf

**Comment by kwai-chang** [comment]
make: Verzeichnis „/usr/src/linux-headers-6.1.3-surface“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o
gcc: error: unrecognized command-line option ‘-mharden-sls=all’
gcc: error: unrecognized command-line option ‘-mharden-sls=all’

**Comment by chymian** [comment]
same thing happens with ithc-module, which is necessary to run IPTSD
https://github.com/quo/ithc-linux

>make: Verzeichnis „/usr/src/linux-headers-6.1.3-surface“ wird betreten
>warning: the compiler differs from the one used to build the kernel
>The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
>You are using: gcc (Debian 10.2.1-6) 10.2.1 20210110

**Comment by qzed** [comment]
It looks like this is due to the compiler version being different. I'll try to find some time and see if there's a better way to fix this (realistically we'd probably have to provide a kernel for each Ubuntu/Debian version which might be a bit too much maintenance overhead), but for now you can try commenting out the unrecognized command-line options as described in #1017.

**Comment by StollD** [comment]
This specific error should be fixable by disabling `CONFIG_SLS`: https://github.com/torvalds/linux/blob/6feb57c2fd7c787aecf2846a535248899e7b70fa/arch/x86/Makefile#L207-L209

**Comment by qzed** [comment]
Can anyone check if that is the only command-line option that causes issues or are there more?

**Comment by kwai-chang** [comment]
> Can anyone check if that is the only command-line option that causes issues or are there more?

I would like to check, but do not know where to disabling config_SLS. Pls Info in which file this has to be change

**Comment by kwai-chang** [comment]
I edited makefile but error persits

DKMS make.log for virtualbox-7.0.4 for kernel 6.1.3-surface (x86_64)
Mo 16. Jan 11:35:46 CET 2023
make: Verzeichnis „/usr/src/linux-headers-6.1.3-surface“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110

**Comment by kwai-chang** [comment]
What is bad as well, if updated to surface kernel, it does not help to boot by another kernel. virtualbox cannot be started anymore

**Comment by qzed** [comment]
Is that the full error? Because it looks like this is only a warning. It should compile even with different GCC versions.

> I would like to check, but do not know where to disabling config_SLS. Pls Info in which file this has to be change. Understand that it has to be makefile, but it is generated while setup process

What I meant was that you could look in `/usr/src/linux-headers-*-surface/` and search for the `-mharden-sls=all` option (e.g. via `grep`) and comment that out. If the module compiles after that and only shows the warning above, we can add that to the config and hopefully everything should work well with the next build.

**Comment by kwai-chang** [comment]
> What I meant was that you could look in `/usr/src/linux-headers-*-surface/` and search for the `-mharden-sls=all` option (e.g. via `grep`) and comment that out. If the module compiles after that and only shows the warning above, we can add that to the config and hopefully everything should work well with the next build.

I could not find that option at this place, only in .config there is sls
Also if booting with another kernel, the error persits, so this option must be at a different place

**Comment by kwai-chang** [comment]
I have found something similar to that in path 
/usr/src/linux-kbuild-6.0/scripts/Makefile.build
The error get a bit different


DKMS make.log for virtualbox-7.0.4 for kernel 6.1.3-surface (x86_64)
Mo 16. Jan 12:48:20 CET 2023
make: Verzeichnis „/usr/src/linux-headers-6.1.3-surface“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o
gcc: error: unrecognized command-line option ‘-mharden-sls=all’
gcc: error: unrecognized command-line option ‘-mharden-sls=all’
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o
gcc: error: unrecognized command-line option ‘-mharden-sls=all’
gcc: error: unrecognized command-line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
gcc: error: unrecognized command-line option ‘-mharden-sls=all’
gcc: error: unrecognized command-line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o] Fehler 1
gcc: error: unrecognized command-line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o] Fehler 1
gcc: error: unrecognized command-line option ‘-fzero-call-used-regs=used-gpr’
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o] Fehler 1
make[1]: *** [scripts/Makefile.build:500: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv] Fehler 2
make: *** [Makefile:1998: /var/lib/dkms/virtualbox/7.0.4/build] Fehler 2
make: Verzeichnis „/usr/src/linux-headers-6.1.3-surface“ wird verlassen

**Comment by qzed** [comment]
So we have at least
- `-mharden-sls=all` which is controlled by `CONFIG_SLS`
- `-fzero-call-used-regs=used-gpr` which is controlled by `CONFIG_ZERO_CALL_USED_REGS`

It does still complain about the first one though... so it's not cleared/removed everywhere. Can you post the output of `ls -al /usr/src/`? My guess based on your log is that those should be set in `/usr/src/linux-headers-6.1.3-surface/Makefile`.

**Comment by qzed** [comment]
I've disabled both options in https://github.com/linux-surface/linux-surface/commit/6e3ac8ba31dc55de19fef6def2bcb0d22fcccec6. So hopefully things work with that, but we might need to disable more stuff.

**Comment by kwai-chang** [comment]
Can you post the output of `ls -al /usr/src/`? My guess based on your log is that those should be set in `/usr/src/linux-headers-6.1.3-surface/Makefile`.

<b>root@surfacx</b></font>:<font color="#5555FF"><b>~</b></font># ls -al /usr/src/
insgesamt 876
drwxr-xr-x 10 root root   4096 16. Jan 12:33 .
drwxr-xr-x 14 root root   4096 13. Jan 02:43 ..
drwxr-xr-x  8 root root   4096 13. Jan 02:52 8812au-5.13.6
drwxr-xr-x  4 root root   4096 13. Jan 02:51 broadcom-sta-6.30.223.271
drwxr-xr-x  4 root root   4096 13. Jan 02:48 linux-headers-6.0.0-6mx-amd64
drwxr-xr-x  4 root root   4096 13. Jan 02:48 linux-headers-6.0.0-6mx-common
drwxr-xr-x  6 root root   4096 16. Jan 10:29 linux-headers-6.1.3-surface
lrwxrwxrwx  1 root root     23 15. Dez 23:19 linux-kbuild-6.0 -&gt; ../lib/linux-kbuild-6.0
drwxr-xr-x  7 root root   4096 13. Jan 02:52 rtl8821ce-5.5.2.1+git20220911
drwxr-xr-x  8 root root   4096 13. Jan 02:52 rtl8821cu-5.12.0
drwxr-xr-x 11 root root   4096 16. Jan 10:45 virtualbox-7.0.4
-rw-r--r--  1 root root 854678  9. Dez 00:46 virtualbox.tar.bz2
<font color="#FF5555"><b>root@surfacx</b>

**Comment by qzed** [comment]
Okay, so new kernels should be available now. Can give those (v6.1.6) a try?

**Comment by kwai-chang** [comment]
> Okay, so new kernels should be available now. Can give those (v6.1.6) a try?

Just tried but new kernel not available (apt update / apt upgrade / alle Pakete aktuell)

**Comment by qzed** [comment]
Any chance you already installed it? Should be in the repo since late last night

**Comment by qzed** [comment]
Oh okay you're right, sorry. It's in the GitHub repo but somehow the server didn't get updated.

@StollD could you check if anything went wrong?

**Comment by StollD** [comment]
CentOS randomly decided to run `chown root:root` on the webservers root directory, so git reported an error when trying to pull the repo. Should work now.

**Comment by kwai-chang** [comment]
updated to 6.1.6 but still error

DKMS make.log for virtualbox-7.0.4 for kernel 6.1.6-surface (x86_64)
Di 17. Jan 16:12:37 CET 2023
make: Verzeichnis „/usr/src/linux-headers-6.1.6-surface“ wird betreten
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o
  CC [M]  /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tools/objtool/objtool)
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tools/objtool/objtool)
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o] Fehler 1
make[2]: *** Datei „/var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvSem.o“ wird gelöscht
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tools/objtool/objtool)
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tools/objtool/objtool)
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o] Fehler 1
make[2]: *** Datei „/var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/linux/SUPDrv-linux.o“ wird gelöscht
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tools/objtool/objtool)
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tools/objtool/objtool)
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o] Fehler 1
make[2]: *** Datei „/var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrvGip.o“ wird gelöscht
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./tools/objtool/objtool)
./tools/objtool/objtool: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./tools/objtool/objtool)
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o] Fehler 1
make[2]: *** Datei „/var/lib/dkms/virtualbox/7.0.4/build/vboxdrv/SUPDrv.o“ wird gelöscht
make[1]: *** [scripts/Makefile.build:500: /var/lib/dkms/virtualbox/7.0.4/build/vboxdrv] Fehler 2
make: *** [Makefile:1998: /var/lib/dkms/virtualbox/7.0.4/build] Fehler 2
make: Verzeichnis „/usr/src/linux-headers-6.1.6-surface“ wird verlassen

**Comment by qzed** [comment]
I guess that means that the system we used to build the kernel and in this case the misc. utilities shipped with it is too new. So ideally we'd switch back to an older Ubuntu or Debian container, but then we need a newer python version on that because of the build script updates to cod/mainline (the Ubuntu kernel sources we use).

This might take me a bit to figure out. Unfortunately I'm a bit busy the next two weeks, so I'm not sure if I can get this done before that.

**Comment by kwai-chang** [comment]
maybe there is way to complie it by myself. With MX-Linux main function on surface are working. Only touchscreen /camera won't work.

**Comment by qzed** [comment]
I think one quick thing you could try is copying the `objtool` binary from the distro kernel. According to #1017 you might also need to copy `fixdep` und `modpost`: I think the following might work:

```
sudo cp /usr/src/linux-headers-6.1.6-surface/tools/objtool/objtool /usr/src/linux-headers-6.1.6-surface/tools/objtool/objtool.old
sudo cp /usr/src/linux-headers-6.0.0-6mx-amd64/tools/objtool/objtool /usr/src/linux-headers-6.1.6-surface/tools/objtool/objtool

sudo cp /usr/src/linux-headers-6.1.6-surface/scripts/basic/fixdep /usr/src/linux-headers-6.1.6-surface/scripts/basic/fixdep.old
sudo cp /usr/src/linux-headers-6.0.0-6mx-amd64/scripts/basic/fixdep /usr/src/linux-headers-6.1.6-surface/scripts/basic/fixdep

sudo cp /usr/src/linux-headers-6.1.6-surface/scripts/mod/modpost /usr/src/linux-headers-6.1.6-surface/scripts/mod/modpost.old
sudo cp /usr/src/linux-headers-6.0.0-6mx-amd64/scripts/mod/modpost /usr/src/linux-headers-6.1.6-surface/scripts/mod/modpost
```

You may need to replace `linux-headers-6.0.0-6mx-amd64` with another version.

**Comment by qzed** [comment]
@kwai-chang Can you try the latest kernel?

**Comment by groengpx** [comment]
The release notes for iptsd explicitly state:

> Support on Debian based distributions only goes back to the latest LTS release (Debian 11 and Ubuntu 22.04).

Does that mean that the linux-surface support for 20.04 is now 'officially' EOL, or is there, pending this issue, still a chance that 20.04 will continue to work?

**Comment by StollD** [comment]
That only applies to iptsd. It's just not feasable to build a relatively modern C++ codebase on distributions with horrendously outdated compilers and libraries. It might still work, but I am not actively trying to make it work.

The debian / ubuntu kernel is built on 20.04 again now, so this issue might be already solved.

**Comment by groengpx** [comment]
As for iptsd:
```
$ LANG=C sudo apt install iptsd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 iptsd : Depends: libsdl2-2.0-0 (>= 2.0.12) but 2.0.10+dfsg1-3 is to be installed
E: Unable to correct problems, you have held broken packages.
```

So yeah, that doesn't work anymore. It is also not strictly necessary, since touch input works fine without iptsd (just not multitouch). But maybe sdl version requirement can be relaxed?

On-topic, as for the kernel: I just tried updating a 20.04 tablet to the latest linux-surface kernel. Everything went fine. Touch still works. My problems with dkms are now indeed gone. Partially because one of my required modules was ithc, which is now included in the linux-surface kernel. And one of my other modules builds just fine, without any hacks.

Thanks for your help. I can't speak for the other people here, but if it is up to me, this issue can now indeed be closed.

**Comment by StollD** [comment]
> So yeah, that doesn't work anymore. It is also not strictly necessary, since touch input works fine without iptsd (just not multitouch). But maybe sdl version requirement can be relaxed?

For that it would have to be built against an older version, so an older release of Debian and Ubuntu. And that comes with all the issues of also downgrading other libraries and compilers.

I could move the debugging tools into a seperate package so that the daemon package itself can install. But that would only be a band-aid, I dont test the older distributions, so it might break again at any time.

**Comment by kwai-chang** [comment]
> > So yeah, that doesn't work anymore. It is also not strictly necessary, since touch input works fine without iptsd (just not multitouch). But maybe sdl version requirement can be relaxed?
> 
> For that it would have to be built against an older version, so an older release of Debian and Ubuntu. And that comes with all the issues of also downgrading other libraries and compilers.
> 
> I could move the debugging tools into a seperate package so that the daemon package itself can install. But that would only be a band-aid, I dont test the older distributions, so it might break again at any time.

Perfect work, while installing rebuilding new kernel. Update dkms automatically THANKS a lot
