### ISSUE TITLE
Surface got frozen using Fedora's 6.0.17 kernel when initiating cifs network disk

### ISSUE THREAD

**Issue by Nexxkinn** [linux-surface/linux-surface#1037]
If I initiate a network disk connection with cifs, my device becomes frozen and unresponsive if I use `kernel-surface` 6.0.17, but works fine when I switch to Fedora's 6.0.14 and 6.1.5

Might be related, but there is a known kernel network bug on Fedora's 6.0.16-6.0.18 and has been reported from a blog

https://utcc.utoronto.ca/~cks/space/blog/linux/KernelBindBugIn6016

### Environment

- Hardware model: Surface Pro 2017
- Kernel version: 6.0.17
- Distribution: Fedora 37

**Comment by NP-chaonay** [comment]
is caps lock responding?

**Comment by qzed** [comment]
v6.1.6 is currently building. So hopefully that's fixed with that too.

**Comment by Nexxkinn** [comment]
Currently running `kernel-surface` 6.1.6 and it doesn't crash now.

closing the issue.
