### ISSUE TITLE
Multi-touch is not working with Surface Pro 8 on the latest kernel

### ISSUE THREAD

**Issue by k4ever** [linux-surface/linux-surface#1048]
[Description of the bug or feature]
Multi-touch is not working with the Surface Pro 8 on the latest kernel (6.1.9-arch1-1-surface). It was working before the kernel update.

### Environment

- Hardware model: Surface Pro 8
- Kernel version: 6.1.9-arch1-1-surface
- Distribution: EndeavourOS/Arch Linux

```
please provide a copy of `dmesg` here if possible
[mydmesg.log](https://github.com/linux-surface/linux-surface/files/10562842/mydmesg.log)


```

</details>

After upgrading to the new kernel, I noticed that multi-touch wasn't working in KDE Plasma. I double checked in GNOME and Firefox (pinch to zoom). Multi-touch is broken!

**Comment by k4ever** [comment]
Pen support has stopped working also

**Comment by qzed** [comment]
What's the output of `systemctl status $(iptsd-find-service)`?

**Comment by qzed** [comment]
@StollD Based on the log I think ITHC might work without `hid-generic`... so that udev rule needs adjusting...

**Comment by k4ever** [comment]
> 

systemctl status $(iptsd-find-service)
    iptsd@dev-hidraw0.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

**Comment by qzed** [comment]
Okay, and I assume if you run `systemctl start $(iptsd-find-service)` manually, everything works fine?

**Comment by k4ever** [comment]
> Okay, and I assume if you run `systemctl start $(iptsd-find-service)` manually, everything works fine?

No. When I run it manually I get asked for a password. After I enter my password, the terminal returns nothing (a blank line), and multi-touch still doesn't work.

**Comment by qzed** [comment]
Did anything new appear in the kernel log when you tried that?

**Comment by qzed** [comment]
Also does `systemctl status $(iptsd-find-service)` show anything different after running that command?

**Comment by k4ever** [comment]
After running systemctl restart $(iptsd-find-service), this is what I see in journctl:

Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 01 20:13:57 kelvin-surfacepro8 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=iptsd@dev-hidraw0 comm="systemd" exe="/usr/li>
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: Deactivated successfully.
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
Feb 01 20:13:57 kelvin-surfacepro8 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=iptsd@dev-hidraw0 comm="systemd" exe="/usr/lib>

It looks like it's starting, then immediately stopping.

Running systemctl status $(iptsd-find-service) shows the same thing:
○ iptsd@dev-hidraw0.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

Feb 01 20:08:23 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: Deactivated successfully.
Feb 01 20:08:23 kelvin-surfacepro8 systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
Feb 01 20:09:52 kelvin-surfacepro8 systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 01 20:09:52 kelvin-surfacepro8 systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Feb 01 20:09:52 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: Deactivated successfully.
Feb 01 20:09:52 kelvin-surfacepro8 systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: iptsd@dev-hidraw0.service: Deactivated successfully.
Feb 01 20:13:57 kelvin-surfacepro8 systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.

**Comment by qzed** [comment]
Does manually runing `sudo iptsd /dev/hidraw0` work?

**Comment by k4ever** [comment]
[kelvin@kelvin-surfacepro8 ~]$ sudo iptsd /dev/hidraw0
[sudo] password for kelvin: 
[20:23:07.341] [error] Failed to open /dev/ipts/0: No such file or directory

**Comment by qzed** [comment]
What's the version of your `iptsd` package? That looks like it might be outdated.

**Comment by k4ever** [comment]
pacman -Q --info iptsd
Name            : iptsd
Version         : 1.0.0-1

**Comment by qzed** [comment]
What confuses me is the `/dev/ipts/0` in the error message. Is it possible that you installed iptsd manually before and it somehow runs an older version? I guess you could check that e.g. via `which iptsd`.

**Comment by k4ever** [comment]
which iptsd
/usr/local/bin/iptsd

**Comment by k4ever** [comment]
..I've only ever install iptsd using the installation instructions for Arch (for the kernel).

**Comment by qzed** [comment]
Yeah, that looks like some other installation. The one from our packages should be located in `/usr/bin/iptsd`.

Can you try running `/usr/bin/iptsd /dev/hidraw0`?

Also, you should probably remove that (maybe try to fully uninstall the `iptsd` package before that, then remove all remaining iptsd related files and install the package again)?

**Comment by k4ever** [comment]
Ok, that did it!

sudo /usr/bin/iptsd /dev/hidraw0
[sudo] password for kelvin: 
[20:50:13.323] [info] Metadata:
[20:50:13.323] [info] rows=46, columns=68
[20:50:13.323] [info] width=27389, height=18259
[20:50:13.323] [info] transform=[408.79105,0,0,0,405.75555,0]
[20:50:13.323] [info] unknown=1, [178,182,180,1,178,182,180,1,90,171,100,20,172,177,175,2]
[20:50:13.331] [info] Connected to device 045E:0C37

Multi-touch is working again. That's weird because I have never installed another version of iptsd. I literally just used pacman to update my system, like I do every other day. There was a surface-kernel update in the packages, just like whenever there has been a new release for the past year. I approved the updates, then rebooted the system once it was finished. That's all I did...

**Comment by k4ever** [comment]
...Now, how do I get rid of this ghost version of iptsd?

**Comment by k4ever** [comment]
This is the only version of iptsd my system shows as installed:
![iptsd](https://user-images.githubusercontent.com/2502512/216212667-3132bb89-ecc7-4913-b5c4-0680a907ea10.png)

**Comment by k4ever** [comment]
..but clearly there is a phantom version that I never installed
![phantom-iptsd](https://user-images.githubusercontent.com/2502512/216212957-b234ce0c-fd0f-4aa0-a269-382f0e140617.png)

**Comment by qzed** [comment]
You could uninstall it via `pacman -Rns iptsd` which should remove all config files as well. Then run `find /usr/local -name ipts` to find any rogue files under `/usr/local` (or use `find / -name ipts` to search for them on the whole device). Then remove those files (but be careful to remove only the iptsd files and not other stuff like kernel modules if you search on the whole device) and install `iptsd` again.

There's also still the problem that the systemd service somehow exits. And the service also doesn't seem to auto-start. But it's probably best if you first remove the other installation to make sure that that doesn't cause any issues.

**Comment by jiangqucheng** [comment]
I upgraded my kernel to 6.1.9-surface today on my SP8 with Ubuntu 20.04. Exact same thing happened. The Multitouch & Pen not working. 
Previously I was using kernel 6.1.3, everything works smoothly.

**Comment by k4ever** [comment]
> I upgraded my kernel to 6.1.9-surface today on my SP8 with Ubuntu 20.04. Exact same thing happened. The Multitouch & Pen not working. Previously I was using kernel 6.1.3, everything works smoothly.

Try running sudo /usr/bin/iptsd /dev/hidraw0 and see if that works..

**Comment by jiangqucheng** [comment]
It works. I'm now figuring out how to start it when booting.

**Comment by k4ever** [comment]
> It works. I'm now figuring out how to start it when booting.

That's the issue I'm running into now. We used to be able to just run systemctl enable iptsd, but that doesn't seem to work anymore.

**Comment by qzed** [comment]
Can you try replacing `hid-multitouch` with `hid-generic` in [this line](https://github.com/linux-surface/iptsd/blob/266916fee0362ce72f30d6759d55b25cfc41d4b9/etc/udev/50-ipts.rules#L2) in `/lib/udev/rules.d/50-ipts.rules` and reboot?

**Comment by jiangqucheng** [comment]
> Can you try replacing `hid-multitouch` with `hid-generic` in [this line](https://github.com/linux-surface/iptsd/blob/266916fee0362ce72f30d6759d55b25cfc41d4b9/etc/udev/50-ipts.rules#L2) in `/lib/udev/rules.d/50-ipts.rules` and reboot?

Here comes the hero! Everything works again! Thank you so much!

**Comment by k4ever** [comment]
> Can you try replacing `hid-multitouch` with `hid-generic` in [this line](https://github.com/linux-surface/iptsd/blob/266916fee0362ce72f30d6759d55b25cfc41d4b9/etc/udev/50-ipts.rules#L2) in `/lib/udev/rules.d/50-ipts.rules` and reboot?

That did it! Thanks!

**Comment by k4ever** [comment]
Whew! I thought I was going to be forced to go back to Windows 11 for a few days!

**Comment by StollD** [comment]
Could you run `cat /sys/class/hidraw/$(basename $(iptsd-find-hidraw))/device/report_descriptor > descriptor.bin` and upload the file it creates? I would be curious what the native HID descriptor on ITHC looks like, and why it doesn't use hid-multitouch.

@qzed Could you check what HID driver spi-hid uses on SPX?

**Comment by rotech** [comment]
Same for me with Surface Laptop 4.  Multitouch was working previously with iptsd and ithc compiled manually, changing the line to hid-generic with the new kernel updates worked for me. 
[descriptor.bin.gz](https://github.com/linux-surface/linux-surface/files/10565164/descriptor.bin.gz)

**Comment by jiangqucheng** [comment]
The hid-multitouch is tagged on another device, 045E:09AF, hidraw5. 
![image](https://user-images.githubusercontent.com/12996850/216262763-bd64d253-c573-4608-ac3c-b3a54e6cbd61.png)
![image](https://user-images.githubusercontent.com/12996850/216263278-d8e5402d-368b-4afe-99cb-00363cb8e747.png)
And the descriptor is from hidraw0. 
[hidraw0_report0.zip](https://github.com/linux-surface/linux-surface/files/10566453/hidraw0_report0.zip)

**Comment by StollD** [comment]
> Same for me with Surface Laptop 4. Multitouch was working previously with iptsd and ithc compiled manually, changing the line to hid-generic with the new kernel updates worked for me. [descriptor.bin.gz](https://github.com/linux-surface/linux-surface/files/10565164/descriptor.bin.gz)

Thank you, this clears some things up. On Surface Pro 7, Microsoft included a dummy touch device into the HID descriptor, which triggers hid-multitouch. I had assumed that that would be included on all newer devices too.

> The hid-multitouch is tagged on another device, 045E:09AF, hidraw5.

That is probably your touchpad.

**Comment by qzed** [comment]
> @qzed Could you check what HID driver spi-hid uses on SPX?

It uses `hid-generic` as well.

**Comment by StollD** [comment]
A new version of iptsd with the fix is not available in the repo.

**Comment by k4ever** [comment]
> A new version of iptsd with the fix is not available in the repo.

Did you mean to write "A new version of iptsd with the fix is now available in the repo?"

**Comment by k4ever** [comment]
Just updated to the new iptsd package. Everything is working great. Thanks for the quick fix!

**Comment by quo** [comment]
@StollD
Possibly a cleaner solution would be to add an option to iptsd (e.g. `--check-device`), which would cause iptsd to check if the HID descriptor has the correct usage IDs, and immediately exit with 0 or 1 to indicate if it does (of course this could also be a separate small program). Then you should be able to use that as an extra condition in the hidraw udev rule (`PROGRAM="iptsd --check-device ..."`), instead of matching on the drivers.

**Comment by StollD** [comment]
The driver isnt really a problem by itself. The hidraw device that both expose works exactly the same. But @qzed noticed one issue: On his device, ipts gets first bound to hid-generic. At the same time, hid-multitouch is loaded, and the HID device gets recreated. This causes an extremly fast start -> stop -> start sequence for iptsd. And sometimes it seems to be actually start -> start -> stop, because of udev / systemd being somewhat concurrent, which breaks touch.

The solution was to never start iptsd on the device created by hid-generic and instead wait for the one from hid-multitouch. We blindly applied that to all drivers, when only IPTS really needed it, as far as I can tell. So we could in theory also remove the match for hid-generic.

Your suggestion is still pretty useful, because at the moment, iptsd will probably not handle devices that expose a normal HID interface through ITHC correctly. So I will keep it in mind, thank you!

**Comment by quo** [comment]
I see. Is it not possible to make ipts bind to hid-generic instead of hid-multitouch?

> On Surface Pro 7, Microsoft included a dummy touch device into the HID descriptor, which triggers hid-multitouch.

I just compared the SP7 and SP7+ descriptors, and the only difference as far as I can tell is that SP7 has the single touch descriptor at the top as an Application collection, whereas SP7+ has it at the end as a Logical collection. The SL4 descriptor posted above is identical to the SP7+ descriptor (except for a different maximum stylus position). So I don't see how the SP7 descriptor could trigger hid-multitouch if the SP7+/SL4 don't do that with ithc?

**Comment by StollD** [comment]
The two descriptors I have include a Contact Identifier, if this is present the kernel will use hid-multitouch.

* https://gist.github.com/archseer/80e33f90b02db83da0d88d95af1eb3a9#file-hid-c-L309
* https://elixir.bootlin.com/linux/latest/source/drivers/hid/hid-core.c#L787

**Comment by quo** [comment]
On the SP7, the ff09 collection is missing, but it's still loading hid-multitouch. But if I remove `ipts->hid->group = HID_GROUP_MULTITOUCH;` then it does use hid-generic.

It looks like the report is only scanned by the kernel if the group is not already set:
https://elixir.bootlin.com/linux/v6.1.9/source/drivers/hid/hid-core.c#2740

So if ipts sets it to HID_GROUP_GENERIC instead of HID_GROUP_MULTITOUCH, it should use hid-generic even on devices with a Contact ID. And since ipts is not a multitouch driver itself, I think that would make more sense than setting it to HID_GROUP_MULTITOUCH anyway.

**Comment by qzed** [comment]
@quo Could this have any implications on single-touch behavior when iptsd is not running?

**Comment by quo** [comment]
I wouldn't expect it to, since single touch seems to work fine with ithc.
