### ISSUE TITLE
Fedora Default Kernel Updater doesn't work at all

### ISSUE THREAD

**Issue by PhilDevProg** [linux-surface/linux-surface#1054]
[Description of the bug or feature]

Sinec the last kernel update of Fedora Grub always defaults to the newest kernel which isn't the surface kernel. I already tried the guide in the Wiki again but it doesn't work.

### Environment

- Hardware model: Surface Go 3 (i3)
- Kernel version: 6.1.8-2.surface.fc37.x86_64
- Distribution: Fdora 37

**Comment by StollD** [comment]
Does running `grubby --set-default /boot/vmlinuz*surface*` manually work?

Could you please post the output of `journalctl -eu default-kernel.service`?

**Comment by PhilDevProg** [comment]
@StollD 

> Does running grubby --set-default /boot/vmlinuz*surface* manually work?

No, it doesn't.

Here's the output of `journalctrl -eu default-kernel.service`:

> ~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- No entries --

**Comment by StollD** [comment]
> No, it doesn't.

And what does it output? You have to give me something I can work with other than "It doesnt work", because for me the script works perfectly fine.

**Comment by PhilDevProg** [comment]
@StollD Sorry, here is th output:

> The default is /boot/loader/entries/79313791f9e84bbbaf576b5a9e428ec2-6.1.8-2.surface.fc37.x86_64.conf with index 2 and kernel /boot/vmlinuz-6.1.8-2.surface.fc37.x86_64

**Comment by StollD** [comment]
Thats weird because that is exactly what it should say.

Did you make any changes to the default grub config? Or did you maybe even switch to a different bootloader (like systemd-boot)?

**Comment by PhilDevProg** [comment]
No, I didn't. But I enabled auto decryption via Clevis and TPM2 which doesn't work anymore too. Maybe that has something to do with it. Btw the Grub Boot Menu only showed up recently. It was never there before.

**Comment by PhilDevProg** [comment]
I reinstalled Fedora and now it works. 🤷

**Comment by PhilDevProg** [comment]
I just updated the GRUB Config Files and now this happens again. I can run grubby and it has the correct output but it won't default to the surface kernel...

**Comment by StollD** [comment]
Could you post the exact command you ran to update grub.cfg?

Could you please also upload your grub.cfg (`/boot/grub2/grub.cfg`) and your grubenv file (`/boot/grub2/grubenv`)?

**Comment by PhilDevProg** [comment]
I updated GRUB via `sudo grub2-mkconfig -o /etc/grub2-efi.cfg` and `sudo  grub2-mkconfig -o /etc/grub2.cfg`.
[grub.zip](https://github.com/linux-surface/linux-surface/files/10773998/grub.zip)

**Comment by StollD** [comment]
Hmm, this is weird. Your grub.cfg looks a bit different than mine: [grub.cfg.txt](https://github.com/linux-surface/linux-surface/files/10775171/grub.cfg.txt)

Your grub doesnt use blscfg to load the available kernels. Instead it has them all written into the grub.cfg. My assumption is that there are some differences between the manual entries and the entires generated by the blscfg module, and that the grubby tool only works with the blscfg entries.

Could you upload your `/etc/default/grub` maybe? I am trying to understand why your grub is not using blscfg.

**Comment by PhilDevProg** [comment]
@StollD Sure:
[grub.zip](https://github.com/linux-surface/linux-surface/files/10775199/grub.zip)

**Comment by StollD** [comment]
Could you upload the updated grub.cfg and /etc/default/grub files?

**Comment by PhilDevProg** [comment]
@StollD 
[grub.zip](https://github.com/linux-surface/linux-surface/files/10776963/grub.zip)

**Comment by PhilDevProg** [comment]
@StollD 
[grub.zip](https://github.com/linux-surface/linux-surface/files/10776968/grub.zip)

**Comment by StollD** [comment]
Your grub.cfg looks fine, its using blscfg now... At this point I have really no idea what could be going on.

Could you upload your `/boot/grub2/grubenv` again?

**Comment by PhilDevProg** [comment]
@StollD Here: [grubenv.txt](https://github.com/linux-surface/linux-surface/files/10777514/grubenv.txt)

**Comment by PhilDevProg** [comment]
It now works...
