### ISSUE TITLE
Installing LTS release (4.19) to fix touchscreen problems

### ISSUE THREAD

**Issue by manumerous** [linux-surface/linux-surface#106]
### Problem Description

Dear All, 
I read in the [Announcements and Updates](https://github.com/linux-surface/linux-surface/issues/96#issuecomment-591720969) that installing the LTS release (4.19) Kernel would fix the multi-touch problem. I assume this is also a linux-surface specific kernel from this repo? I searched in the documentation but didn't find any hints on how to do this. 

Adding the Debian Repository worked fine for me but when installing the required packages using the following command from your [installation guide](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup):
`sudo apt-get install linux-headers-surface linux-image-surface linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface`
It seems to automatically download linux-image-surface amd64 5.5.7-1. How can i reset this to install LTS release (4.19)? 

### Environment

- Hardware model:  Surface Pro 4
- Kernel version:  5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Ubuntu 18.04.4 LTS

Anyways thanks for the help and the good work! I hope someone can help me. 
Greetings Manuel

</details>

**Comment by chrismin13** [comment]
While I'm not on Ubuntu, I believe you have to specify that you want the LTS release. So, instead the command you use should be:
`sudo apt-get install linux-headers-surface-lts linux-image-surface-lts linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface`

As you can see, all I added was -lts, as that's how the repos are on Arch, so I assume it's the same on Debian. Please try it again, and if this is the correct package, we should probably update the documentation to make it clearer which release is good for what and how it can be installed.

**Comment by manumerous** [comment]
The installation went smooth with the command and my multi-touch is working again. Thanks a lot for the fast and precise help!
