### ISSUE TITLE
SB2: Pen stops working after short time of use, IPTSD Error message or crash

### ISSUE THREAD

**Issue by Expletium** [linux-surface/linux-surface#1062]
### Context
The problem has existed for quite some time, but has recently become significantly worse.
I've been using Linux on my Surface for quite some time, but it's only recently that I've started using the stylus very often and now I'm also dependent on it.
I have already searched GitHub, but I have not found the error once.

At first I suspected, since I have been using the surface-linux kernel for some time and also used the "old" IPTS, that the "new" version interferes with the old one and reinstalled Fedora, but the error code remains the same, both were installed via _dnf install iptsd_. 

The programs I use are among others RNOTE and Xournal++, both installed as flatpak and can run exclusively on Wayland through flatseal.

## Issue
The pen works perfectly as soon as you use it, but after a while it either stops writing abruptly or fixes a point on the display that the program assumes is the pen and multitouch no longer works, only singletouch.

If you now look at the output of _'iptsd@*.service'_, iptsd is either crashed or still running and you always get the same error message (with the same error code _[when crashed]_).
While the status of the _iptsd-find-hidraw_ service continues to run.

By restarting the _'iptsd@*.service'_ the pen can be used again, but not always.
By _sudo iptsd /dev/hidraw1_ the pen can also be used again, but also there the error message of _'iptsd@*.service'_ comes after a short time when using the pen in the terminal.

IPTSD crashes only after slight use of the pen, time does not matter in my opinion.

However, if you only use multitouch gestures and do not use the stylus, this works flawlessly.

### Additional Information

- When I type _'sudo iptsd-show $(sudo iptsd-find-hidraw)'_ the error message appears in the terminal: **error: XDG_RUNTIME_DIR is invalid or not set in the environment**. First, a black window opens, but when I tap on the screen with my finger, the gray background with the touch detection appears, but there I can only "stimulate" the touchscreen with my finger, pen inputs are not displayed. Don't know if thats supposed to happen or not.
- Another peculiarity with _'sudo iptsd-show $(sudo iptsd-find-hidraw)'_ is that single fingers with small movement are processed very accurately and quickly, but as soon as several fingers touch the touchscreen and move, that this is processed extremely delayed after a short time.
- The different variables in the IPTSD config do not affect / improve the pen support.
Both in the vanilla config and when changing the values of "TemporalWindow", "Blop Dection" or other things, the same problems occur with the pen, without noticeable difference.
- It makes no difference if the pen is connected via Bluetooth or not, in my case I disabled Bluetooth in the Bios to avoid problems with the Wifi if they still exist.
- All software is up to date.
- LUKS disk encryption is used.
- Performance modes does not make a difference.
- Surface-Aggregator and Surface-Control packages are installed.
- Ram utilization is around 2,2-3GB / 8GB when crashes happen.
- IPTSD-Calibration values used in the iptsd.conf file does not make a difference
- DGPU, even if non existant, is blacklisted via Bios and file. _(Nvidia)_
- Freshly installed Fedora with Surface-Kernel, no other software installed besides RNote and Flatseal (+ all software provided in the install manual)
- Used pen always with detached screen.

### Environment

- Hardware model: **Surface Book 2 13,5"** _(2019) (i5-8350u, 8gb Ram, no dgpu)_
- Kernel version: **6.1.11-1.surface**.fc37.x86_64
- Distribution: **Fedora Workstation 37**
- Window manager: Wayland
- Desktop enviroment: Gnome

<details><summary>`iptsd@*.service` output</summary>

```
● iptsd@dev-hidraw1.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: active (running) since Sat 2023-02-18 17:22:07 CET; 4min 17s ago
       Docs: https://github.com/linux-surface/iptsd
   Main PID: 1134 (iptsd)
      Tasks: 1 (limit: 9387)
     Memory: 4.4M
        CPU: 1.134s
     CGroup: /system.slice/system-iptsd.slice/iptsd@dev-hidraw1.service
             └─1134 /usr/bin/iptsd /dev/hidraw1

Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.044] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.144] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.245] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.347] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.447] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.549] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.651] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.754] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.855] [warning] Failed to write input event: Bad file descriptor
Feb 18 17:23:04 p-s iptsd[1134]: [17:23:04.958] [warning] Failed to write input event: Bad file descriptor

```

</details>

<details><summary>`status $(iptsd-find-hidraw)` output</summary>

```
● dev-hidraw1.device - /dev/hidraw1
    Follows: unit currently follows state of sys-devices-pci0000:00-0000:00:16.4-0000:00:16.4\x2d3e8d0870\x2d271a\x2d4208\x2d8eb5\x2d9acb9402ae04-0000:045E:0021.0003-hidraw-hidraw1.dev>
     Loaded: loaded
     Active: active (plugged) since Sat 2023-02-18 17:22:06 CET; 5min ago
      Until: Sat 2023-02-18 17:22:06 CET; 5min ago
     Device: /sys/devices/pci0000:00/0000:00:16.4/0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04/0000:045E:0021.0003/hidraw/hidraw1

```

</details>

<details><summary>`dmesg` output</summary>

```
"Comment is too long (maximum is 65536 characters)"

Thats why I uploaded a .txt file, hope thats okay.


[dmesg.txt](https://github.com/linux-surface/linux-surface/files/10774753/dmesg.txt)
```

</details>

**Comment by StollD** [comment]
> Don't know if thats supposed to happen or not.

iptsd-show only supports testing the touchscreen, so that is expected.

> as soon as several fingers touch the touchscreen and move, that this is processed extremely delayed after a short time

I noticed the same. I *think* it is because of the visualization code, but I haven't had the chance yet to take a look.

> The different variables in the IPTSD config do not affect / improve the pen support.

On the earlier devices (SP4 until SP7) the pen data is processed directly by the hardware. We directly get coordinates and simple bitfields for stuff like "is the side button pressed". iptsd only parses and forwards that data to the kernel, so there is very little that you could (and would want to) configure.

The error messages I see look like the uinput device that iptsd uses just died. I was able to reproduce that issue, but only with a second pen. Maybe your pen is sending inconsistent serial numbers, so iptsd sees more than one pen. I doubt that you are actually using two pens, because I dont think that feature ever worked correctly.

I pushed a change to GitHub that fixes the issue by removing the support for multiple pens. You can download a compiled and packaged version of iptsd with that change here: https://github.com/linux-surface/iptsd/actions/runs/4212550491, scroll down and download the artifact with the name `<your-distro>-latest`. It would be great if you could give that a try.

**Comment by StollD** [comment]
You can keep your pen, don't worry. 

The multi-pen support doesn't work at all (as in: all it does is break iptsd, you cannot actually use two pens at the same time), so removing it for now helps more than it harms.

The code has been out for years, but noone ever reported that it doesn't work. And I didn't own a second pen until recently, so I couldn't test if it actually works. I guess its pretty safe to say that nobody actually uses it.
