### ISSUE TITLE
[SP3] Pen tracking out of calibration

### ISSUE THREAD

**Issue by LBrinston** [linux-surface/linux-surface#1071]
~Upgraded surface-linux kernel on the weekend. Pen started becoming unstable (skipping strokes, only starting to draw part way through strokes, etc) earlier today. Then randomly stopped registering strokes entirely twenty minutes ago. Gestures and touch input using my fingers still works but cannot get anything out of the pen.~

~I can see that the pen is still connected via the bluetooth GUI and bluetouthctl but can't get stoke data to register in xournal++ or the little wacom "test your settings" widget in settings. I've tried swapping tips and batteries to no effect.~

Update:
Have now tried several sets of new batteries only to realize that the surface is detecting the pen BUT it's way out of calibration in terms of determining it's position (thinks it's ~7cm down and right of its actual position).  So I can get stroke data to register but it's so out of wack in terms of positioning that it's not usable.

Running the touch screen calibration available in the Ubuntu settings menu under the wacom drivers makes no difference in terms of confused pen position.

`evtest` shows that it's detecting  pen events (see below)

~I think it might have something to do with iptsd? Base on this [issue](https://github.com/linux-surface/linux-surface/issues/1045) I tried to do narrow it down but didn't manage to get beyond it seems like iptsd keeps getting deactivated even if I restart it.~

iptsd isn't used on SP3 so please ignore the rest of this post.

If I try to check on it's status I get:
```
loach@hippoglossus:~ $ systemctl status $(iptsd-find-service)
info: unrecognized option '--property=TAGS'
info: unrecognized option '--property=TAGS'
○ iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd
```
If I try to restart it, I get:
```
loach@hippoglossus:~ $ systemctl restart $(iptsd-find-service)
info: unrecognized option '--property=TAGS'
info: unrecognized option '--property=TAGS'
```
If I try to get it to just talk to the pen (I also tried using the complete path and got the same result):
```
loach@hippoglossus:~ $ sudo iptsd $(iptsd-find-hidraw)
info: unrecognized option '--property=TAGS'
info: unrecognized option '--property=TAGS'
DEVICE is required
Run with --help for more information.
```

So I removed/reinstalled it via apt, rebooted and rechecked it's status:
```
loach@hippoglossus:~ $ systemctl status $(iptsd-find-service)
info: unrecognized option '--property=TAGS'
info: unrecognized option '--property=TAGS'
○ iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

Feb 22 15:45:54 hippoglossus systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 22 15:45:54 hippoglossus systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Feb 22 15:45:54 hippoglossus systemd[1]: iptsd@-.service: Deactivated successfully.
Feb 22 15:45:54 hippoglossus systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
Feb 22 15:55:38 hippoglossus systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 22 15:55:38 hippoglossus systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Feb 22 15:55:38 hippoglossus systemd[1]: iptsd@-.service: Deactivated successfully.
Feb 22 15:55:38 hippoglossus systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
```

Every time I try to start or restart iptsd.service it immediately stops.
```
The "DEVICE is required" line actually pops up in several spots including if I just run:
loach@hippoglossus:~ $ iptsd --help
Usage: iptsd [OPTIONS] DEVICE

Positionals:
  DEVICE FILE REQUIRED        The hidraw device to read from.

Options:
  -h,--help                   Print this help message and exit
```

Which does clarify anything for me personally. I don't know if that is related or not? I don't know what device file or where to find it.

### Environment

- Hardware model: Surface Pro 3 - Intel® Core™ i7-4650U CPU @ 1.70GHz × 4
- Kernel version: 
```Linux hippoglossus 6.1.12-surface #2 SMP PREEMPT_DYNAMIC Mon Feb 20 01:41:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```
- Distribution: Ubuntu 22.04.2 LTS

<details><summary>`dmesg` output</summary>
[dmesg_output.txt](https://github.com/linux-surface/linux-surface/files/10809262/dmesg_output.txt)
</details>

**Comment by StollD** [comment]
Surface Pro 3 does not use IPTS, so iptsd won't work with it.

Did you check if the pen battery is empty? When I still had a surface pen, the issues you mentioned usually indicated that the battery was dying.

And the errors from `iptsd-find-hidraw` are an Ubuntu issue that I will have to fix, so thank you for bringing that to my attention.

**Comment by LBrinston** [comment]
> Surface Pro 3 does not use IPTS, so iptsd won't work with it.
> 
> Did you check if the pen battery is empty? When I still had a surface pen, the issues you mentioned usually indicated that the battery was dying.
> 
> And the errors from `iptsd-find-hidraw` are an Ubuntu issue that I will have to fix, so thank you for bringing that to my attention.

Oh...well my bad then : P
What is handling the SP3's touch screen? Wacom drivers?
I have tired other batteries (and am about to go grab a second set to be sure). I don't know how reliable the power reporting for the pen is but the OS thinks it's at 95%. The cell itself has dropped to 1.45V so if that's the issue re-chargeables are totally out the window which is a shame.

**Comment by LBrinston** [comment]
Update:
Two sets of new batteries has made no difference. 
But what I have just noticed is that the touchscreen IS detecting the pen but its treating it as a mouse cursor AND it's confused about it's position as the mouse cursor is tracking it's position ~7cm off on a diagonal. I initially missed this as it's so far off that the cursor is actually off screen in many places.

**Comment by LBrinston** [comment]
Update: Switching the Xorg has "fixed" the problem. 
I have no idea what is actually causing the issue under Wayland. So far as I'm aware I had been using Wayland since I installed 22.04 ~ a month ago  ¯\_(ツ)_/¯
