### ISSUE TITLE
Bluetooth doesn't work on Surface Pro 7 with Kali Linux

### ISSUE THREAD

**Issue by DaneeSkripter** [linux-surface/linux-surface#1077]
Hello, 
I have problem with bluetooth on my Surface Pro 7, I am using Kali Linux, cause it's Debian-derived distribution.
When I turn on bluetooth, it doesn't show any audio devices, i tried connect my headphones on Windows and works fine.

### Environment
- Hardware model: Surface Pro 7
- Kernel version: 6.1.13-surface
- Distribution: Kali Linux (Debian)

**Comment by DaneeSkripter** [comment]
Little detail, i'm using GNOME, not Xfce, if that matters.

**Comment by qzed** [comment]
The Pro 7 should be using Intel WiFi. Do you have the respective firmware for that installed (I think it should be in linux-firmware)?

**Comment by DaneeSkripter** [comment]
Yes, I have installed linux-surface kernel, WiFi works normally, but bluetooth not well, it can see other devices like TV, but no audio device.
When I run ``systemctl status bluetooth`` it show this:
```bash
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: src/profile.c:ext_register_record() Failed to register service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: src/profile.c:ext_register_record() Failed to register service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: src/profile.c:ext_register_record() Failed to register service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/a2dp.c:a2dp_add_sep() Unable to register A2DP service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/media.c:media_endpoint_create() Unable initialize endpoint for UUID 0000110a-0000-1000-8000-00805f9b34fb
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/media.c:app_register_endpoint() Unable to register endpoint :1.63:/MediaEndpoint/A2DPSource/ldac_hq: Invalid a>
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/a2dp.c:a2dp_add_sep() Unable to register A2DP service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/media.c:media_endpoint_create() Unable initialize endpoint for UUID 0000110b-0000-1000-8000-00805f9b34fb
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/a2dp.c:a2dp_add_sep() Unable to register A2DP service record
úno 28 10:48:50 Dan-Surf bluetoothd[2611]: profiles/audio/media.c:media_endpoint_create() Unable initialize endpoint for UUID 0000110a-0000-1000-8000-00805f9b34fb

```

**Comment by DaneeSkripter** [comment]
Hello again, I found solution, I've been using Kali Linux 2020.4, now I downloaded latest version of Kali (2022.4). At first it didn't work, but when I type `systemctl start bluetooth`, it works fine now. No errors in `systemctl status bluetooth`.
