### ISSUE TITLE
[Alder Lake] Intel Thread Director and battery life / performance

### ISSUE THREAD

**Issue by peter-marshall5** [linux-surface/linux-surface#1084]
Just thought I should mention that mainline Linux currently does not have support for Intel's Thread Director. This is required for the proper assignment of processes to performance or efficiency cores on this generation's new big-little architecture. Performance does not seem to be impacted much for me with the stock `linux-surface` kernel in comparison with Windows 11, but the battery life seems to be shorter on Linux than on Windows.

My testing on a custom kernel with a similar config to the Fedora linux-surface kernel, with the initial patches that enable support for Intel's Thread Director applied, seems to indicate that battery life is almost doubled with this feature. The tablet also seems to stay much cooler while on battery; It would get uncomfortably warm under relatively little load without the patches applied. I haven't tested the performance thoroughly enough yet to determine if there's much improvement.

[The patchset to enable Intel's Thread Director](https://marc.info/?l=linux-kernel&m=167574609418577&w=2)
[The patchset that the former depends on](https://marc.info/?l=linux-kernel&m=167574542018327&w=2)

**Comment by qzed** [comment]
Thanks, that sounds like we should definitely consider carrying these patches. Are you aware of any current/expected issues with those or do they seem close to ready?

**Comment by peter-marshall5** [comment]
So far I am not aware of any issues or regressions caused by this patchset. They do seem to be close to being merged into mainline, but that could still take a bit of time.

These patches seem to be incompatible with the current implementations of alternative schedulers like BMQ and PDS, but this does not currently matter for the `linux-surface` kernel.

**Comment by qzed** [comment]
Great, I'll have a look at them and apply them after that if I can't spot any big complaints on the ML.

One disclaimer though: I can't guarantee that I'll be able to fix things if they break, or if some merge conflicts come up. If that happens, I'll probably have to remove them again, at least until I can find the time to sort that out.

**Comment by qzed** [comment]
I've applied the patches and am currently testing them on my SB2. So far things look good. However, it looks like there's still a bit of discussion around https://lore.kernel.org/lkml/20230207045838.11243-7-ricardo.neri-calderon@linux.intel.com/ and some other patches in that series, so that's something to keep in mind.

**Comment by qzed** [comment]
New kernels are building.

**Comment by qzed** [comment]
Kernels are out, let me know if there are any issues and I can re-open this one (or just open new ones).

**Comment by qzed** [comment]
I've removed the patches again due to the suspend/resume issues reported in #1120.
