### ISSUE TITLE
Surface Pro 6 pen detection

### ISSUE THREAD

**Issue by ClementRasp** [linux-surface/linux-surface#1089]
[Description of the bug or feature]
Hi, I don't know if this is already reported, I don't find when I search.
I have a Surface Pro 6. And I can't connect my pen. It works, I can use it but he not appair in the setting so i can't configure it :
![image](https://user-images.githubusercontent.com/80109473/224503991-933a45d3-be4e-4a1c-b0ee-10d1b7bc6fcf.png)

It's in french but it's said : 
Please place your pen on the targets on the edge of the tablet to set it up.

### Environment

- Hardware model:  Surface Pro 6
- Kernel version:  Linux clem-pc 6.2.2-surface #2 SMP PREEMPT_DYNAMIC Tue Mar  7 01:10:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Ubuntu

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by PhilDevProg** [comment]
Have you installed the package `libwacom-surface`?

**Comment by LeVraiCrab** [comment]
Yes, I have the 2.6.0-1 version

**Comment by PhilDevProg** [comment]
Just to be sure: Your pen is the official Surface Pen made by Microsoft and not by someone on e. g. Ebay, right?

**Comment by qzed** [comment]
As long as the pen works, it shouldn't matter whether it's an original or some third-party one.
