### ISSUE TITLE
won't boot on zfs 

### ISSUE THREAD

**Issue by k-dannemand** [linux-surface/linux-surface#109]
Hi

are zfs not compiled with in the sureface kernel?

i just did ubuntu 20.04 install and running on zfs.
but when i install the sureface kernel

(sudo apt-get install linux-headers-surface linux-image-surface linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface)

and reboot into the sureface kernel i just get stuck on boot with

"Fail to load ZFS modules
  manually load the modules and exit "

it works fine on ubuntus own kernel.

**Comment by StollD** [comment]
You cannot use the binary modules that ubuntu uses by default, as they are tied to a specific kernel build. You have to install `zfs-dkms` to use zfs.

**Comment by k-dannemand** [comment]
@StollD  !! that worked, thnaks a alot ! 

you should throw that in the install guide. 

all it takes is a 'apt get install zfs-dkms'
