### ISSUE TITLE
[SLS Ubuntu] apt update:  "E:Conflicting values set for option Signed-By regarding source"

### ISSUE THREAD

**Issue by bluelambdax11** [linux-surface/linux-surface#1097]
[Description of the bug or feature] 
Note: I'm not skilled in Ubuntu so I just google and follow prompts.
1.) I want to update from linux header 6.2.2 to the latest
2.) Also, issue powering down, restarting, sleep/hibernate. It freezes at "kvm: exiting hardware virtualization" and only shuts down if I hold powerbutton for 10 seconds.

>sudu apt update
output: E: Conflicting values set for option Signed-By regarding source https://pkg.surfacelinux.com/debian/ release: /var/lib/extrepo/keys/surface-linux.asc != 
E: The list of sources could not be read.

### Environment

- Hardware model: Surface Laptop Studio
- Kernel version: Linux study-SLS 6.2.2-surface #2 SMP PREEMPT_DYNAMIC Tue Mar  7 01:10:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

- Distribution: Debian/Ubunto (via the guide)

<details><summary>`dmesg` output</summary>

```
<!-- [   26.475307] rfkill: input handler disabled
[   26.523578] audit: type=1400 audit(1679160188.394:51): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=1917 comm="snap-confine" capability=12  capname="net_admin"
[   26.523584] audit: type=1400 audit(1679160188.394:52): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=1917 comm="snap-confine" capability=38  capname="perfmon"
[   27.191408] audit: type=1326 audit(1679160189.062:53): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.snap-store.snap-store pid=1917 comm="snap-store" exe="/snap/snap-store/638/usr/bin/snap-store" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fb0aed4973d code=0x50000
[   27.738787] audit: type=1400 audit(1679160189.610:54): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=2149 comm="snap-confine" capability=12  capname="net_admin"
[   27.738793] audit: type=1400 audit(1679160189.610:55): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=2149 comm="snap-confine" capability=38  capname="perfmon"
[   27.790539] audit: type=1326 audit(1679160189.662:56): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.snapd-desktop-integration.snapd-desktop-integration pid=2225 comm="snapd-desktop-i" exe="/snap/snapd-desktop-integration/49/usr/bin/snapd-desktop-integration" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7fc32291173d code=0x50000
[   30.394125] audit: type=1400 audit(1679160192.266:57): apparmor="DENIED" operation="open" class="file" profile="snap.snap-store.snap-store" name="/etc/PackageKit/Vendor.conf" pid=1917 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   30.602003] audit: type=1400 audit(1679160192.474:58): apparmor="DENIED" operation="open" class="file" profile="snap.snap-store.snap-store" name="/etc/appstream.conf" pid=1917 comm="snap-store" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[   70.763489] audit: type=1400 audit(1679160360.219:59): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=2473 comm="snap-confine" capability=12  capname="net_admin"
[   70.763497] audit: type=1400 audit(1679160360.219:60): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/18357/usr/lib/snapd/snap-confine" pid=2473 comm="snap-confine" capability=38  capname="perfmon"
[   70.800607] audit: type=1400 audit(1679160360.255:61): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.firefox" name="/var/lib/" pid=2495 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   70.801045] audit: type=1400 audit(1679160360.255:62): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.firefox" name="/var/lib/" pid=2495 comm="5" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   71.915879] audit: type=1326 audit(1679160361.372:63): auid=1000 uid=1000 gid=1000 ses=3 subj=snap.firefox.firefox pid=2473 comm="firefox" exe="/snap/firefox/2432/usr/lib/firefox/firefox" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f635757c73d code=0x50000
study@study-SLS:~$ 
-->

```

</details>

**Comment by StollD** [comment]
Did you use extrepo to enable the repository? That integration is not maintained by us, so we can't really support it.

Please try the manual method of setting up the repository, to see if that fixes it. If it does, you should report the extrepo issue to its upstream: https://salsa.debian.org/extrepo-team/extrepo-data

**Comment by bluelambdax11** [comment]
> Did you use extrepo to enable the repository? That integration is not maintained by us, so we can't really support it.
> 
> Please try the manual method of setting up the repository, to see if that fixes it. If it does, you should report the extrepo issue to its upstream: https://salsa.debian.org/extrepo-team/extrepo-data

Thank you. I ran >extrepo disable and was then able to run the manual setup of the repository, which then worked for doing >apt update

I can now move on to fixing the shutdown hanging issue!

**Comment by vitalygashkov** [comment]
I confirm shutdown/restart/sleep issue. Same problem on latest kernel version (6.2.10).

**Comment by qzed** [comment]
Let's discuss the shutdown problem in #1101.

I'm closing this as I think that the original problem is not an issue on our side and should be discussed on the extrepo site instead. But feel free to comment if there's anything that I should be aware of in that regard.
