### ISSUE TITLE
Surface Book 2 : linux-image-surface - Could not locate dkms.conf file

### ISSUE THREAD

**Issue by dparkar** [linux-surface/linux-surface#112]
Attempting to install for the first time. Upon running : 

`sudo apt-get install linux-headers-surface linux-image-surface linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface`

The post configuration of "linux-image-surface" doesn't succeed. Throws 'Could not locate dkms.conf file'

Running on Ubuntu 18.04.

- Hardware model: Surface Book 2
- Kernel version: Linux dp-ubuntu 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Debian
```
dparkar@dp-ubuntu:~$ sudo apt-get install linux-headers-surface linux-image-surface linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface
[sudo] password for dparkar: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libwacom-surface is already the newest version (1.2-3).
linux-headers-surface is already the newest version (5.5.7-1).
linux-libc-dev-surface is already the newest version (5.5.7-1).
linux-surface-secureboot-mok is already the newest version (2.0.0).
surface-ipts-firmware is already the newest version (1.0.0).
The following NEW packages will be installed:
  linux-image-surface
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/61.5 MB of archives.
After this operation, 275 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package linux-image-surface.
(Reading database ... 274878 files and directories currently installed.)
Preparing to unpack .../linux-image-surface_5.5.7-1_amd64.deb ...
Unpacking linux-image-surface (5.5.7-1) ...
Setting up linux-image-surface (5.5.7-1) ...
 * dkms: running auto installation service for kernel 5.5.7-surface                                                                                                               
Error! Could not locate dkms.conf file.
File:  does not exist.
                                                                                                                                                                           [fail]
run-parts: /etc/kernel/postinst.d/dkms exited with return code 4
update-initramfs: Generating /boot/initrd.img-5.5.7-surface
Sourcing file `/etc/default/grub'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-5.5.7-surface
Found initrd image: /boot/initrd.img-5.5.7-surface
Found linux image: /boot/vmlinuz-4.15.0-88-generic
Found initrd image: /boot/initrd.img-4.15.0-88-generic
Found linux image: /boot/vmlinuz-4.15.0-76-generic
Found initrd image: /boot/initrd.img-4.15.0-76-generic
Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/BootMgFW.efi
Adding boot menu entry for EFI firmware configuration
done
dpkg: error processing package linux-image-surface (--configure):
 installed linux-image-surface package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-surface
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Same for lts version : 

```
dparkar@dp-ubuntu:~$ sudo apt install linux-image-surface-lts
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  linux-image-surface-lts
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/54.2 MB of archives.
After this operation, 247 MB of additional disk space will be used.
Selecting previously unselected package linux-image-surface-lts.
(Reading database ... 274878 files and directories currently installed.)
Preparing to unpack .../linux-image-surface-lts_4.19.106-1_amd64.deb ...
Unpacking linux-image-surface-lts (4.19.106-1) ...
Setting up linux-image-surface-lts (4.19.106-1) ...
 * dkms: running auto installation service for kernel 4.19.106-surface-lts                                                                                                        Error! Could not locate dkms.conf file.
File:  does not exist.
                                                                                                                                                                           [fail]
run-parts: /etc/kernel/postinst.d/dkms exited with return code 4
update-initramfs: Generating /boot/initrd.img-4.19.106-surface-lts
Sourcing file `/etc/default/grub'
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.19.106-surface-lts
Found initrd image: /boot/initrd.img-4.19.106-surface-lts
Found linux image: /boot/vmlinuz-4.15.0-88-generic
Found initrd image: /boot/initrd.img-4.15.0-88-generic
Found linux image: /boot/vmlinuz-4.15.0-76-generic
Found initrd image: /boot/initrd.img-4.15.0-76-generic
Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/BootMgFW.efi
Adding boot menu entry for EFI firmware configuration
done
dpkg: error processing package linux-image-surface-lts (--configure):
 installed linux-image-surface-lts package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-image-surface-lts
E: Sub-process /usr/bin/dpkg returned an error code (1)

```
Note that I can use the kernel, i.e. login and when I do 'uname -r' returns 5.5.7-surface.

**Comment by dparkar** [comment]
Anyone ?

**Comment by qzed** [comment]
The `dkms.conf` file is usually provided by the repective dkms package. No clue why this should be missing. Maybe try re-installing any dkms packages that you have installed after installing the kernel.

**Comment by dparkar** [comment]
@qzed In this case, its saying that 'linux-image-surface' is missing the dkms.conf correct ?

**Comment by qzed** [comment]
As far as I can tell from the log, it complains that the error occurs during processing steps required for `linux-image-surface-lts`. That package only triggers dkms rebuilds (as should any other kernel package). It is not responsible for content added by other dkms packages, including `dkms.conf` files. Specifically, `dkms.conf` files are used by _kernel module packages_ (e.g. `nvidia-dkms`) to tell the module build system what that specific module contains and where it should be installed to.

To troubleshoot dkms stuff, you should probably have a look at the output of `dkms status`. Likely that will show you what kernel module (and thereby what package) caused that issue.

**Comment by dparkar** [comment]
> dparkar@dp-ubuntu:~$ dkms status
> evdi, 4.2.29: added
> Error! Could not locate dkms.conf file.
> File:  does not exist.

**Comment by qzed** [comment]
What is the output of `ls -l /var/lib/dkms`?

**Comment by qzed** [comment]
Can you also check on which dkms module the `dkms.conf` is missing by checking that
```
/var/lib/dkms/<module_name>/<module_version>/source/dkms.conf
```
exists (for the respective module name and version)? If you've found the module for which it doesn't exist, try re-installing the corresponding package.

**Comment by dparkar** [comment]
> dparkar@dp-ubuntu:~$ ls -l /var/lib/dkms
> total 8
> -rw-r--r-- 1 root root    6 Aug 31  2016 dkms_dbversion
> drwxr-xr-x 4 root root 4096 Mar 27 11:18 evdi

Interestingly this helped me : https://bbs.archlinux.org/viewtopic.php?id=151965 (See #6). Basically deleted an older version of evdi.

Now I get the following : 

> dparkar@dp-ubuntu:~$ sudo apt upgrade
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Calculating upgrade... Done
> The following packages have been kept back:
>   cuda-drivers libnvidia-cfg1-440 libnvidia-compute-440 libnvidia-compute-440:i386 libnvidia-decode-440 libnvidia-decode-440:i386 libnvidia-encode-440
>   libnvidia-encode-440:i386 libnvidia-fbc1-440 libnvidia-fbc1-440:i386 libnvidia-gl-440 libnvidia-gl-440:i386 libnvidia-ifr1-440 libnvidia-ifr1-440:i386
>   nvidia-compute-utils-440 nvidia-dkms-440 nvidia-driver-440 nvidia-kernel-source-440 nvidia-utils-440 xserver-xorg-video-nvidia-440
> 0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.
>

**Comment by dparkar** [comment]
Thanks ! @qzed !!!
