### ISSUE TITLE
dptf_power INT3407:00: Unsupported event [0x82]

### ISSUE THREAD

**Issue by frankusb** [linux-surface/linux-surface#1122]
### Environment

- Hardware model: Surface Book 2
- Kernel version: Linux frank-Surface-Book-2 6.2.10-surface #1 SMP PREEMPT_DYNAMIC Tue Apr 11 23:02:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Kubuntu 23.04

<details><summary>`dmesg` output</summary>

```
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/11295973/dmesg.txt)

```

</details>

This Surface Book 2 has two 0% batteries that will not charge. Under Windows it powers off randomly every 30-60 minutes or so. Not so under Linux. Also the touch screen appears to be only partially working on the right side of the screen, not the left.

I noticed that the dmesg is constantly logging:
[   13.531594] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   13.540299] dptf_power INT3407:00: Unsupported event [0x82]
[   13.613205] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   13.614318] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   13.620423] dptf_power INT3407:00: Unsupported event [0x82]
[   15.268304] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   15.269497] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   15.278010] dptf_power INT3407:00: Unsupported event [0x82]
[   15.354705] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   15.355762] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   15.356769] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   18.359278] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   18.360241] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   18.361266] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   21.616981] dptf_power INT3407:00: Unsupported event [0x82]
[   21.633355] dptf_power INT3407:00: Unsupported event [0x82]
[   21.644409] dptf_power INT3407:00: Unsupported event [0x82]
[   21.671156] dptf_power INT3407:00: Unsupported event [0x82]
[   21.677290] dptf_power INT3407:00: Unsupported event [0x82]
[   21.705499] dptf_power INT3407:00: Unsupported event [0x82]
[   21.714538] dptf_power INT3407:00: Unsupported event [0x82]
[   22.224550] dptf_power INT3407:00: Unsupported event [0x82]
[   22.316089] dptf_power INT3407:00: Unsupported event [0x82]
[   23.960157] dptf_power INT3407:00: Unsupported event [0x82]
[   24.044307] dptf_power INT3407:00: Unsupported event [0x82]
[   25.700086] dptf_power INT3407:00: Unsupported event [0x82]
[   25.785704] dptf_power INT3407:00: Unsupported event [0x82]
[   27.445948] dptf_power INT3407:00: Unsupported event [0x82]
[   27.526975] dptf_power INT3407:00: Unsupported event [0x82]
[   29.180625] dptf_power INT3407:00: Unsupported event [0x82]
[   29.264529] dptf_power INT3407:00: Unsupported event [0x82]
[   29.306128] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   30.912878] dptf_power INT3407:00: Unsupported event [0x82]
[   30.995156] dptf_power INT3407:00: Unsupported event [0x82]
[   32.743863] surface_serial_hub serial0-0: rx: parser: invalid payload CRC
[   32.743871] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[   32.744868] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping

**Comment by frankusb** [comment]
Yes, see attached.
[surface_aggregator.txt](https://github.com/linux-surface/linux-surface/files/11297686/surface_aggregator.txt)

**Comment by qzed** [comment]
It looks like the majority of messages is coming through correctly. More failures than I'd like to see, but it shouldn't be critical, meaning it's not a communication issue with the EC.

So I don't think there's anything we can do regarding the battery. Based on your report, I'm assuming that this is a hardware failure. The difference between Windows powering off randomly and Linux not is probably just a difference in how both treat that failure (note that powering off on low battery is handled by user-space on Linux).

**Comment by frankusb** [comment]
Thanks, I am not looking for a battery solution, only to report the error messages. I'm happy to be able to use the system as is.

**Comment by mirogl** [comment]
Hi @qzed 

I got also recently a used Surface Book 2 with two 0% batteries not charging. Replaced the keyboard battery by myself and it is working now without any problems under Ubuntu 23.04 and linux-surface kernel  debian-6.2.13-1 - Also nvidia GPU is running and games - no problem. But I have also this message and the problem, that in Windows 11 the device randomly reboots every Minute without any error i could found. 
Therefore I'm also interested, if these messages in dmesg gives any hint onthe original problem.
I attached my debug dmesg and my battery status - any difference to the reports from @frankusb  ?

Thanks
miro
[surface_battery.txt](https://github.com/linux-surface/linux-surface/files/11367880/surface_battery.txt)


[surface_dmesg.txt](https://github.com/linux-surface/linux-surface/files/11367877/surface_dmesg.txt)

**Comment by mirogl** [comment]
> 

Hi,
you are right - sometimes they are not included - i repeated "sudo dmesg | grep skipping -A20" until i got an result - sometimes no result after 10 tries I got this one:

`
[  911.433496] surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping
[  911.433540] surface_serial_hub serial0-0: ptl: transmitting non-sequenced packet 000000004e9c8994
[  911.433545] surface_serial_hub serial0-0: tx: sending data (length: 10)
[  911.433548] tx: 00000000: aa 55 04 00 00 00 31 4e ff ff
[  911.433555] surface_serial_hub serial0-0: ptl: successfully transmitted packet 000000004e9c8994
[  911.433558] surface_serial_hub serial0-0: ptl: completing packet 000000004e9c8994 (status: 0)
[  911.433561] surface_serial_hub serial0-0: ptl: releasing packet 000000004e9c8994
[  911.434117] surface_serial_hub serial0-0: rx: received data (size: 16)
[  911.434121] rx: 00000000: aa 55 80 7f 00 43 66 d5 80 02 00 01 01 83 13 02
[  911.434124] surface_serial_hub serial0-0: rx: parser: not enough data for payload
[  911.434153] surface_serial_hub serial0-0: rx: received data (size: 54)
[  911.434155] rx: 00000000: 00 00 00 00 00 50 46 00 00 50 46 00 00 01 00 00
[  911.434157] rx: 00000010: 00 4c 1d 00 00 00 00 00 00 00 00 00 00 2d 00 00
[  911.434159] rx: 00000020: 00 e8 03 00 00 ff ff ff ff ff ff ff ff e8 03 00
[  911.434160] rx: 00000030: 00 e8 03 00 00 0a
[  911.434163] surface_serial_hub serial0-0: rx: parser: not enough data for payload
[  911.434340] surface_serial_hub serial0-0: rx: received data (size: 16)
[  911.434342] rx: 00000000: 00 00 00 0a 00 00 00 4d 31 30 33 30 39 31 31 00
[  911.434344] surface_serial_hub serial0-0: rx: parser: not enough data for payload
[  911.434377] surface_serial_hub serial0-0: rx: received data (size: 51)
[  911.434379] rx: 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 38 30 30 38
`

Thanks
miro

**Comment by qzed** [comment]
@frankusb 

> That's interesting as I don't see any messages of the form:
> surface_serial_hub serial0-0: rx: parser: invalid start of frame, skipping

These messages could be (and I think likely are) an entirely different issue. Your second log shows that while some messages have a corrupt start sequence, generally a second try is successful. So it should not impact the battery info, which in both Windows and our Linux driver re-tries up to a total of 3 times before failing.

**Comment by qzed** [comment]
>  I got also recently a used Surface Book 2 with two 0% batteries not charging. Replaced the keyboard battery by myself and it is working now without any problems under Ubuntu 23.04 and linux-surface kernel debian-6.2.13-1 - Also nvidia GPU is running and games - no problem. But I have also this message and the problem, that in Windows 11 the device randomly reboots every Minute without any error i could found.

The only thing that I can think of is that it's doing some emergency thing because it thinks that the tablet battery is empty. Generally, the discharge behavior on the Surface Books doesn't allow for a battery to be completely empty during normal use, so Windows could try to shut down in an attempt to prevent full discharge (which generally kills a Li-ion battery). I'm not sure if there's a way to prevent that, but you could check in the Windows Event Viewer if that mentions some reason for the shutdown (if you haven't already).

**Comment by mirogl** [comment]
Hi @qzed,
I ordered a new battery for the tablet and will retest it, as soon as I have exchange it - then we know, if is related to it.

Thanks
Miro

**Comment by qzed** [comment]
@mirogl Thanks for checking that. I guess it makes sense that the controller may behave somewhat weirdly if a battery is dead. I'm going to close this then because there's really not much we can do here.
