### ISSUE TITLE
Fedora 38 Silverblue/Kintoite: wiki instructions don't work

### ISSUE THREAD

**Issue by plata** [linux-surface/linux-surface#1128]
Following https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#fedora-silverblue gives:
```
package kernel-devel-matched-6.2.13-300.fc38.x86_64 requires kernel-core = 6.2.13-300.fc38, but none of the providers can be installed
```

Only
```
rpm-ostree override replace ./*.rpm
```
seems to work but I'm not sure if there are other effects.

### Environment

Running in a virtual machine.

**Comment by ttoommxx** [comment]
Can you report the command that gave you that error?

**Comment by plata** [comment]
from the linked documentation:
```
rpm-ostree override replace ./*.rpm \
	--remove kernel-core \
	--remove kernel-modules \
	--remove kernel-modules-extra \
        --remove libwacom \
        --remove libwacom-data \
	--install kernel-surface \
	--install iptsd \
        --install libwacom-surface \
        --install libwacom-surface-data
```

**Comment by ttoommxx** [comment]
did you input the previous commands (enable the repo and download the fake kernel as rpm)?

**Comment by plata** [comment]
Yes, sure.

From what I understand, the instructions have been written for an older version of Fedora and should now be updated to match the latest state.

**Comment by ttoommxx** [comment]
They worked fine on my machine! Maybe there are better instructions to
avoid the so called dirty hack but idk, haven't seen anything like that
around

**Comment by plata** [comment]
You're also on Fedora 38 Kinoite?

**Comment by ttoommxx** [comment]
Fedora Silverblue. try the following: first update your system `rpm-ostree update && rpm-ostree upgrade`. Then install the repo from the linux webguide, wget the fake rpm packange and run the above commands.

**Comment by plata** [comment]
It indeed worked now. No idea what went wrong initially.

Just one question: the guide says
> This package will print instructions to the terminal, so please install it on its own, not as part of a bigger batch of packages.

I didn't see any instructions. Is this still remark still correct or could the `surface-secureboot` install be included in the other command?

**Comment by plata** [comment]
If I try to include this in an ostree native container (see https://github.com/plata/ublue-surface/pull/3), I still get:
```
error: Could not depsolve transaction; 1 problem detected:
 Problem: package kernel-devel-matched-6.2.15-300.fc38.x86_64 from @System requires kernel-core = 6.2.15-300.fc38, but none of the providers can be installed
  - conflicting requests
```

**Comment by ttoommxx** [comment]
> Just one question: The guide says
> 
> > This package will print instructions to the terminal, so please install it on its own, not as part of a bigger batch of packages.
> 
> I didn't see any instructions. Is this remark still correct or could the `surface-secureboot` install be included in the other command?

Oh I did that manually, the package didn't work for me either. Doing manually is just that easy, you fine instruction in the wiki in the secure boot section. Let me know if that works. Remember that you can only do that if your pc has secure boot already enabled, so need to boot with standard kernel first

**Comment by ttoommxx** [comment]
Looks like the package `kernel-devel-matched` was somehow installed. If you don't need it include it in the remove when you run the command to remove kernel and install the new kernel

**Comment by plata** [comment]
```
--remove kernel-devel-matched
```
fix it.

Now I get:
```
grub2-probe: error: failed to get canonical path of `overlay'.
No path or device is specified.
Usage: grub2-probe [OPTION...] [OPTION]... [PATH|DEVICE]
Try 'grub2-probe --help' or 'grub2-probe --usage' for more information.
dracut: WARNING: running in hostonly mode in a container!!
dracut: No '/dev/log' or 'logger' included for syslog logging
dracut-install: ERROR: installing '/root'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.roWXFh/initramfs /root
```
I'm not really sure that this is related to `linux-surface` in particular. So I can understand if you prefer to close this issue at this point. However, if you know how this could be fixed, it would be greatly appreciated.

**Comment by ttoommxx** [comment]
> ```
> --remove kernel-devel-matched
> ```
> 
> fix it.
> 
> Now I get:
> 
> ```
> grub2-probe: error: failed to get canonical path of `overlay'.
> No path or device is specified.
> Usage: grub2-probe [OPTION...] [OPTION]... [PATH|DEVICE]
> Try 'grub2-probe --help' or 'grub2-probe --usage' for more information.
> dracut: WARNING: running in hostonly mode in a container!!
> dracut: No '/dev/log' or 'logger' included for syslog logging
> dracut-install: ERROR: installing '/root'
> dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.roWXFh/initramfs /root
> ```
> 
> I'm not really sure that this is related to `linux-surface` in particular. So I can understand if you prefer to close this issue at this point. However, if you know how this could be fixed, it would be greatly appreciated.

I am quite confused, are you running the commands in the container? Or in the man os? Looks like you are running them in the container

**Comment by plata** [comment]
I'm trying to include linux-surface in the container. So yes, the commands are part of the Containerfile. According to https://github.com/coreos/layering-examples/blob/main/replace-kernel/Containerfile this should work generally.

**Comment by ttoommxx** [comment]
> I'm trying to include linux-surface in the container. So yes, the commands are part of the Containerfile. According to https://github.com/coreos/layering-examples/blob/main/replace-kernel/Containerfile this should work generally.

I am quite confused of what you are saying. If you install it using rpm-ostree it will be automatically layered. If you install it in the container (toolbox or distrobox) is definitely NOT going to work!

**Comment by plata** [comment]
This is not in a container in Silverblue. I'm building an [ostree native container](https://coreos.github.io/rpm-ostree/container/). If it works, you will be able to rebase Silverblue to that container and have the kernel available out of the box.

**Comment by ttoommxx** [comment]
> This is not in a container in Silverblue. I'm building an [ostree native container](https://coreos.github.io/rpm-ostree/container/). If it works, you will be able to rebase Silverblue to that container and have the kernel available out of the box.

oh I see, something like a git branch or tag? sorry, I am unfamiliar to how to do that. I think it is better to close this thread since the original problem was solved and then open a new one with your problem!

**Comment by plata** [comment]
Yes, it's somewhat similar. In case you're interested, check out ublue.it, it explains it pretty clearly.
