### ISSUE TITLE
Surface Pro 7 Freezes on Reboot

### ISSUE THREAD

**Issue by Wumpotamus** [linux-surface/linux-surface#113]
Hi, I recently installed Manjaro on my Surface Pro 7, but whenever I reboot, it freezes, I have to manually reboot through power button and it then loads up. I'm not actually able to get anything useful out of dmesg to report though.
### Environment

- Hardware model: Surface Pro 7
- Kernel version: Linux drew-sp 5.5.8-arch1-1-surface #1 SMP PREEMPT Fri, 06 Mar 2020 13:37:35 +0000 x86_64 GNU/Linux
- Distribution: Manjaro GNOME

**Comment by archseer** [comment]
What about `journalctl -b -1` which retrieves logs from the previous boot?

**Comment by Wumpotamus** [comment]
@archseer I have no idea what to be looking for, but here's what it outputs.
[output.txt](https://github.com/linux-surface/linux-surface/files/4303772/output.txt)
`

**Comment by slabko** [comment]
Does it freeze on Microsoft logo or while Linux is booting up? I have issue when it freezes on Microsoft logo.

**Comment by Wumpotamus** [comment]
Microsoft logo @slabko

**Comment by droric** [comment]
I had this issue and I worked around it by chain loading grub with rEFInd.  Also I had to put reboot=pci in the kernel options.

**Comment by Wumpotamus** [comment]
Adding `reboot=pci` to rEFInd has fixed my problem, but maybe there should be something in the wiki for that?

**Comment by qzed** [comment]
@Wumpotamus Agreed, I've added a wiki page: https://github.com/linux-surface/linux-surface/wiki/Surface-Pro-7.

**Comment by archseer** [comment]
Oh sorry, I misread the issue initially, I thought it would freeze up every second boot.

I had that parameter documented before for SL3 here: https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3#rebooting-gets-stuck-at-the-surface-logo

**Comment by archseer** [comment]
Closing since it's resolved
