### ISSUE TITLE
Red lock still on

### ISSUE THREAD

**Issue by Lawman1966** [linux-surface/linux-surface#1139]
[Description of the bug or feature]

### Environment

- Hardware model: 
- Kernel version: 
- Distribution: 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by Lawman1966** [comment]
Im new on here and also new to Ubuntu. So be easy on me,lol. I installed Ubuntu on my surface pro 6 and it seems to be running pretty good so far. But when i tried installing the kernel i had problems. When it came to the blue screen, the screen came up and went right back off. I wasn't able to sign in. Can someone help me with this issue? Thanks

**Comment by qzed** [comment]
> When it came to the blue screen, the screen came up and went right back off.

There should be a menu that you need to navigate through. I assume that didn't work?

You may need to enable secureboot in UEFI before the key can be enrolled. Note, however, that booting into the linux-surface kernel won't work with secureboot enabled until you have enrolled the key. Therefore, you need to boot into the stock Ubuntu kernel with secureboot enabled (which should work), enroll the key there, reboot, and follow through the blue menu (mokutil). After that, you should finally be able to boot into the linux-surface kernel with secureboot.

To (re-)enroll the key, you can either uninstall and re-install the `linux-surface-secureboot-mok` package or run
```
sudo mokutil --import /usr/share/linux-surface-secureboot/surface.cer
```

**Comment by Lawman1966** [comment]
Qzed. Thank you brother. It seems to be working now. much appreciated.

**Comment by qzed** [comment]
> It seems to be working now.

Closing this then.
