### ISSUE TITLE
User guide specifies incorrect pacakge name for `linux-surface-headers-lts`

### ISSUE THREAD

**Issue by mstr3336** [linux-surface/linux-surface#114]
# Description

The user guide states:

> The LTS kernel can be installed via the -lts suffix on the kernel packages (e.g. linux-image-surface-lts, linux-surface-headers-lts, and linux-libc-dev-surface-lts on Debian). 

However, running:

```bashe t
sudo apt-get install linux-surface-headers-lts
```

I get:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-surface-headers-lts
```
By searching the issues for "lts",  https://github.com/linux-surface/linux-surface/issues/106#issuecomment-594153157 tell me: 

> While I'm not on Ubuntu, I believe you have to specify that you want the LTS release. So, instead the command you use should be:
> `sudo apt-get install linux-headers-surface-lts linux-image-surface-lts linux-libc-dev-surface surface-ipts-firmware linux-surface-secureboot-mok libwacom-surface`

This works.

# Action Needed

Update the LTS / multitouch section of the install guide to reflect the correct name for the `lts` headers OR rename that package so it matches the non-lts headers, but with a suffix.

**Comment by archseer** [comment]
Fixed on the wiki. Feel free to make any additional changes since all the content is publicly editable.
