### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by Lawman1966** [linux-surface/linux-surface#1142]
[Description of the bug or feature]

### Environment

- Hardware model: 
- Kernel version: 
- Distribution: 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by qzed** [comment]
Can you provide some more details? Also please check with `uname -a` if you are running a `-surface` kernel.

**Comment by Lawman1966** [comment]
Thank you. I think its resolved now.

**Comment by qzed** [comment]
I will close this then. Please feel free to ping me here or open a new issue if the problem persists/comes back.
