### ISSUE TITLE
Problems with installing linux-surface-secureboot-mok

### ISSUE THREAD

**Issue by dustin0116** [linux-surface/linux-surface#116]
### Problem
Everytime I try to install the linux-surface-secureboot-mok package, I get this:
```bash
warning: cannot resolve "mokutil-git", a dependency of "linux-surface-secureboot-mok"
:: The following package cannot be upgraded due to unresolvable dependencies:
      linux-surface-secureboot-mok
```

I then try to install mokutil-git myself from AUR, but whenever I run makepkg on the PKGBUILD, I get this whenever it starts prepare():
```bash
==> ERROR: A failure occurred in prepare().
    Aborting...
```

Is it something wrong with the PKGBUILD file? If so, how can I fix it?

### Environment

- Hardware model: Surface Laptop
- Kernel version: 5.5.8-arch1-1-surface
- Distribution: Arch Linux

**Comment by archseer** [comment]
mokutil / mokutil-git seems to be on AUR only. Make sure to install it with something like [yay](https://github.com/Jguer/yay) first. Personally I just don't use Secure Boot :)

@qzed Is there any reason we depend on the -git version?

**Comment by qzed** [comment]
As @archseer mentioned, you'll need to install it via an AUR helper, or alternatively install `mokutil-git` manually.


@archseer 
> is there any reason we depend on the -git version?

Not any more. When I set it up the non`-git` version did not compile. Seems to be fixed as of [11/2019](https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=mokutil&id=4143672f924ff9a83e3fb82da3a2d13fece065a3), so we should probably switch back to that.

**Comment by dustin0116** [comment]
Installing with yah works, thanks. It was weird how it didn’t work when I tried to install it manually.
