### ISSUE TITLE
[Fedora] no such file or directory for "default-kernel.{path,service}"

### ISSUE THREAD

**Issue by YosypC** [linux-surface/linux-surface#1165]
### Description

I'm following [this](https://github.com/linux-surface/linux-surface/tree/master/contrib/fedora-default-kernel) guide and the terminal tells me both default-kernel.path and default-kernel.service cannot be found.

### Environment

- Hardware model: SP8
- Kernel version: Linux yosyp-surface-fedora 6.3.6-2.surface.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun  9 17:33:07 UTC 2023 x86_64 GNU/Linux
- Distribution: Fedora 38

[dmesg.zip](https://github.com/linux-surface/linux-surface/files/11717348/dmesg.

**Comment by qzed** [comment]
The readme there assumes that you download the files from that page.

However, with the latest kernels, we've packaged that service and you can simply run `sudo systemctl enable --now linux-surface-default-kernel.path` (and `sudo linux-surface-default-kernel.sh` to update it immediately). I've updated the wiki accordingly.

**Comment by YosypC** [comment]
> The readme there assumes that you download the files from that page.
> 

I am a moron. Thank you. I completely ignored that part of the webpage.

> However, with the latest kernels, we've packaged that service and you can simply run `sudo systemctl enable --now linux-surface-default-kernel.path` (and `sudo linux-surface-default-kernel.sh` to update it immediately). I've updated the wiki accordingly.

Great!
