### ISSUE TITLE
Fans not working

### ISSUE THREAD

**Issue by SwagSpaad** [linux-surface/linux-surface#1174]
Hello everyone, i've recently upgraded my OS to Fedora 38. I dont know if is a OS bug or something else, but i'll explain my problem. I've installed hyprland wm and i had problems about watching videos on the browser. I fixed this problem but i noticed that while i'm watching videos on firefox the computer starts heating and seems fans are not working. I've tried a stress-test using s-tui and even if cpu reaches 80°C fans doesnt start. 
I tried to check fans rpm with ls_sensors but it doesnt display. 
Is there a way to force my fans rpm? It heats so much and its impossible to use it in tablet mode for xournalpp. Anyone has the same problem? 

### Environment

- Hardware model: Surface Pro 8
- Kernel version: Linux fedora 6.3.8-1.surface.fc38.x86_64
- Distribution: Fedora 38

`sensors` output:
```
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +38.0°C  

BAT1-virtual-0
Adapter: Virtual device
in0:          12.38 V  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +29.9°C  (low  = -273.1°C, high = +81.8°C)
                       (crit = +85.8°C)
Sensor 1:     +29.9°C  (low  = -273.1°C, high = +65261.8°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +42.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +38.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +39.0°C  (high = +100.0°C, crit = +100.0°C)
Core 2:        +40.0°C  (high = +100.0°C, crit = +100.0°C)
Core 3:        +39.0°C  (high = +100.0°C, crit = +100.0°C)

```

**Comment by qzed** [comment]
Fans are controlled by the EC, so there's no _direct_ way that the OS can influence this. There is, however, the "platform profile". Fedora/Gnome should have full integration for this and you should be able to change it in the menu in the top right corner (maybe also check `/sys/firmware/acpi/platform_profile` directly to check that setting it via the menu worked; see https://docs.kernel.org/userspace-api/sysfs-platform_profile.html).

You can try a couple of different settings for that. Any of the performance-oriented modes should result in a more aggressive fan curve, whereas the power-saver mode does seem to reduce fan speed quite drastically (and maybe is more akin to a quiet mode; at least on my SB2).

**Comment by SwagSpaad** [comment]
Does performance-oriented mode affect the battery draining?

**Comment by SwagSpaad** [comment]
The fact is i want fans to spin faster because in these days during normal tasks seems like cpu usage is higher and it overheats a lot, but even on a temperature of 80°C i cant hear fans spinning. I dont know if is a temporary issue.

**Comment by qzed** [comment]
> Does performance-oriented mode affect the battery draining?

It might. I'm honestly not quite sure what the profile changes apart from the fan curve.

As an alternative, you can also try setting up a thermald config to keep the CPU cooler. So decreasing CPU power/speed instead of increasing the fan speed.
