### ISSUE TITLE
v4l2loopback doesn't work on Fedora, Surface Pro 6

### ISSUE THREAD

**Issue by ShawkMusic** [linux-surface/linux-surface#1176]
[Description of the bug or feature]

### Environment

- Hardware model:  Surface Pro 6
- Kernel version:  Linux fedora 6.3.7-1.surface.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 14 16:58:44 UTC 2023 x86_64 GNU/Linux
- Distribution:  Fedora

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>
I just want to get the camera working on Discord. I tried to follow https://github.com/linux-surface/linux-surface/wiki/Camera-Support#gstreamer-loopback-device-for-other-applications, which, since i have secure boot, leads me to https://github.com/umlaeute/v4l2loopback/wiki/Secure-Boot, which tells me to run `sudo /usr/src/kernels/$(uname -r)/scripts/sign-file sha256 ./OBS.priv ./OBS.der $(modinfo -n v4l2loopback)`, but then I get this error:

```
modinfo: ERROR: Module v4l2loopback not found.
zsh: no such file or directory: /usr/src/kernels/6.3.7-1.surface.fc38.x86_64/scripts/sign-file
```

The directory /usr/src/kernels/6.3.7-1.surface.fc38.x86_64/ doesn't exist. What am I supposed to do?
Also I have the package `v4l2loopback` from the Fedora repositories. Why isn't that working either? Am I supposed to install some other package?

**Comment by farline99** [comment]
Hello. You should install akmod-v4l2loopback and kernel-surface-devel packages. Reboot and try again 😉

**Comment by ShawkMusic** [comment]
> Hello. You should install akmod-v4l2loopback (RPM Fusion repo) and kernel-surface-devel packages. Reboot and try again 😉 P.S. https://pkgs.org/ site is awesome. Originally I found loopback package in RPM Fusion repo there.

Thanks for the reply

I installed `akmod-v4l2loopback` and ran the command again and got the exact same error
