### ISSUE TITLE
Wrong path to the database file

### ISSUE THREAD

**Issue by tio-trom** [linux-surface/linux-surface#1187]
When I try to refresh the database I get a 404 error because the Link it tries to access is `https://pkg.surfacelinux.com/arch/Linux-surface.db` with capitalized L. Instead of `https://pkg.surfacelinux.com/arch/linux-surface.db` - I am unsure where the error is. Can you please check.

**Comment by qzed** [comment]
Any chance you capitalized the section name in /etc/pacman.conf when adding the repo?

**Comment by tio-trom** [comment]
No...

This is what I have
```

[linux-surface]
Server = https://pkg.surfacelinux.com/arch/
```

**Comment by tio-trom** [comment]
ohh I see in the name...Sorry I just realized

**Comment by tio-trom** [comment]
I do not know how that happened. Sorry and thanks!
