### ISSUE TITLE
IPC_CLASSES config does not get set

### ISSUE THREAD

**Issue by Dariqq** [linux-surface/linux-surface#1188]
[Description of the bug or feature]

When looking at the resulting kernel `.config` of the surface kernel in the repositories I noticed that  the config `IPC_CLASSES`  is missing for fedora and debian (the config file is in  `/boot/)` although the `linux-surface/configs/surface-6.*.config` file should enable it.

All other config options are set as expected.

I also can't find any reference to the option in the patched linux source code code (for v6.3.12 and v6.4.2). using a `grep -r`.

### Steps to reproduce

With the surface kernel installed on the current system
```
grep "IPC_CLASSES" /boot/config-*-surface*
```
returns empty while .e.g

```
grep "SURFACE" /boot/config-*-surface*
```
does not.

I don't have an Alder-Lake CPU and am testing in virtual machines (fedora38 and ubuntu 22.04).

**Comment by qzed** [comment]
Ah, thanks for noticing this. That option was introduced together with a patchset for the Intel Thread Director. Unfortunately, that patchset caused some errors and we had to remove it again (see https://github.com/linux-surface/linux-surface/issues/1084 and https://github.com/linux-surface/linux-surface/issues/1120). I've removed that option now (bd88c8280783f406c0db67de4fa95678dbce5433).
