### ISSUE TITLE
Instruct NixOS users to build their own kernel

### ISSUE THREAD

**Issue by meedstrom** [linux-surface/linux-surface#1190]
The NixOS instructions don't work for now, at least for Intel Surface Pro.

It seems that nixos-hardware has made an oversight so that they're pulling a commit of linux-surface that doesn't have the 6.0 kernel anymore, and then trying to build the 6.0 kernel.  Background: https://discourse.nixos.org/t/surface-pro-4-nixos-hardware-nixos-rebuild-error/27101  There are also some other issues with IPTSD.

I propose adding an alternative instruction to the install page, that NixOS users can just specify their own kernel build, linking to the example https://github.com/NixOS/nixpkgs/issues/240612#issuecomment-1635859341

**Comment by qzed** [comment]
Sounds reasonable. Feel free to edit that in the wiki.
