### ISSUE TITLE
Shorten metadata expiry date on Fedora Silverblue.

### ISSUE THREAD

**Issue by ttoommxx** [linux-surface/linux-surface#1197]
I am running Fedora Silverblue 38 with kernel-surface. Sometimes an update gets pushed fairly quickly on the releases in Github but, running 'rpm-ostree upgrade' does not seem to be working. I figured the problem being that the expiry date of the metadata of the repo is prob at least 24h (couldn't actually find the exact time). Why not shorten it to, say, 30 minutes? This way critical updates would get picked up much faster

**Comment by StollD** [comment]
We could do that, but I am kinda worried that it will add unneccessary load on the server that is hosting the metadata.

We also couldn't apply this change for existing installations, only for people who do a fresh install. And we ususally dont have critical releases, so its should be fine if everything gets a bit delayed.

The default is 48 hours btw. You can change it by putting `metadata_expire=30m` into `/etc/yum.repos.d/linux-surface.repo`.

**Comment by ttoommxx** [comment]
Thank you, I guess you are right, hopefully critical updates get then announced properly then!
