### ISSUE TITLE
Installation Failed - Packages have Unmet Dependencies

### ISSUE THREAD

**Issue by Lynxen** [linux-surface/linux-surface#1201]
When attempting to install, I get the error below. All previous steps have been completed.

The following packages have unmet dependencies:
 linux-headers-surface : Depends: linux-headers-6.4.6+ (= 6.4.6+-1) but it is not going to be installed
 linux-image-surface : Depends: linux-image-6.4.6+ (= 6.4.6+-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

### Environment

- Hardware model: Surface Pro 2017
- Kernel version: Linux lynxen-Surface-Pro 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 22.04 LTS

**Comment by Lynxen** [comment]
This exact error also happened on a fresh ZorinOS installation.

**Comment by fattabbydev** [comment]
I'm also seeing this behavior on Ubuntu 22.04 on a clean install.

**Comment by StollD** [comment]
The latest packages are currently broken because I overlooked something while refactoring the build scripts and now their package name is wrong. I pulled the broken ones from the repo and new builds should be ready in a few hours. Sorry for this.

**Comment by fattabbydev** [comment]
Things happen! Thanks for the quick response @StollD ☺️
