### ISSUE TITLE
SurfaceBook2 hung up on reboot after kernel installation.

### ISSUE THREAD

**Issue by Zico36** [linux-surface/linux-surface#1202]
Hello all. First of all, thank you for this wonderful project! Looking to install Ubuntu on my Surface Book 2. 
Having already installed Ubuntu I now wanted to install the kernel. I followed the instructions and everything went according to plan. Finally I failed because the blue screen where I should enter the MOK key 'surface' did not appear after the reboot. The surface hung up and remained alone with MS logo. After turning off secureboot completely I was able to boot back into grub and start Ubuntu from there. 

Anyway, I tried uninstalling and reinstalling the linux-surface-secureboot-mok package to trigger the process again. However, I get stuck in the same loop again. 

After looking through the issues here I tried to enter the key manually via: 

sudo mokutil --import /usr/share/linux-surface-secureboot/surface.cer. 

I got the message that it is already enrolled. 

How can i fix my installation to boot directly into Ubuntu after startup?

**Comment by Ramen-LadyHKG** [comment]
try run this command again `sudo mokutil --test-key /usr/share/linux-surface-secureboot/surface.cer.`

If it's already enrolled, I don't think you need to do it again.

what happens if Secure boot enable? cannot boot into the system?

**Comment by Ramen-LadyHKG** [comment]
> Hello there,
> I have the exact same problem except that turning off secureboot didn't allow me to get out of the MS logo screen... Any idea?

What's your UEFI firmware version number?
392/394?
https://github.com/linux-surface/linux-surface/issues/1162

**Comment by PaoloRondot** [comment]
Version number is 394.779.768

**Comment by Ramen-LadyHKG** [comment]
> Version number is 394.779.768

You need to downgrade

or not using grub/shim from fedora/Ubuntu

**Comment by Ramen-LadyHKG** [comment]
> Version number is 394.779.768

read my file about downgrade
[Surface – Linux not booting after UEFI firmware update issue.pdf](https://docs.google.com/document/d/1HxZmOYyqZc28vXW1nDai0VP44HoJ34suQU4cNyzylq4/edit?usp=sharing)

**Comment by PaoloRondot** [comment]
I must say I'm a bit confused... I read that it's not possible anymore to downgrade and also even read that downgrading didn't help ..

Another thing is that now I cannot boot from a USB stick on my computer anymore, it doesn't work.. And if I understood correctly I need to boot from a USB stick in the downgrading procedure.

**Comment by Ramen-LadyHKG** [comment]
> I must say I'm a bit confused... I read that it's not possible anymore to downgrade and also even read that downgrading didn't help ..
> 
> Another thing is that now I cannot boot from a USB stick on my computer anymore, it doesn't work.. And if I understood correctly I need to boot from a USB stick in the downgrading procedure.

I'm not sure your issue is related to ours either but AFAIK, `394` breaks Fedora, Untunu. 


Downgrade is possible through linux tools, like 
`fwudpmgr. 


Number of users told me that downgrade works. 
https://www.reddit.com/r/SurfaceLinux/comments/14n3prp/repost_surface_uefi_firmware_update_xxxxxx7680/

Why you cannot boot from usb?

You don't actually need to boot from an USB, as long as you have access to any Distro of Linux on your machine.
> like maybe, create a empty partition and make it bootable
> boot from USB just makes life easier 


What distro of Linux are you trying boot from USB on your surface?

**Comment by PaoloRondot** [comment]
So until this morning I only had windows 11. I followed the instructions to dual boot for Ubuntu 23.04.
It worked good but then I tried installing the secure boot key and I started having the problem of getting stuck on the surface logo.
Now when in UEFI, when I reorder to boot again on the USB stick to have somehow access again to Ubuntu it doesn't work, and just starts windows.
How can I have access to a Linux distro on my surface then to downgrade?

Also, thank you very much for taking the time to help me !

**Comment by PaoloRondot** [comment]
It looks like there's no way I can downgrade if I cannot boot from my USB stick anymore...

**Comment by Zico36** [comment]
> > Version number is 394.779.768
> 
> read my file about downgrade [Surface – Linux not booting after UEFI firmware update issue.pdf](https://docs.google.com/document/d/1HxZmOYyqZc28vXW1nDai0VP44HoJ34suQU4cNyzylq4/edit?usp=sharing)

Hello everyone and sorry for not replying for a while. I just wanted to let you know that downgrading the UEFI solved my problem. Thank you very much for this detailed guide. Great work!
