### ISSUE TITLE
Cannot find root after upgrade to 6.4.7

### ISSUE THREAD

**Issue by tomasz-kowalski** [linux-surface/linux-surface#1214]
Cannot boot after upgrade to kernel 6.4.7 on arch. Root not found. Downgrading to 6.4.6 fixes it.

### Environment

- Hardware model: Surface 5 (2017)
- Kernel version: 6.4.7-arch1-1-surface
- Distribution: Arch Linux

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by qzed** [comment]
What filesystem is your root partition? Any chance it's ZFS and the respective dkms module broke on the latest kernels? Also, are you able to boot the 6.4.7 (or later) kernel shipped by Arch?

**Comment by tomasz-kowalski** [comment]
Root filesystem is ext4. I can boot the newest Arch kernel. 
`$ uname -a 
Linux sloop 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux`
And I can boot 6.4.6-arch1-1-surface.

**Comment by qzed** [comment]
Can you try to get some kind of log (if necessary a picture) that could help debug this?

**Comment by tomasz-kowalski** [comment]
Ahhh... probably simply a corrupted file. Somewhat strange because pacman did not complain. However, now everything works:
`$ uname -a
Linux sloop 6.4.7-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Fri, 28 Jul 2023 17:35:22 +0000 x86_64 GNU/Linux
`
Sorry for raising alarm!

**Comment by qzed** [comment]
No worries. That is possible. Could be something didn't get properly flushed to disk.

I'll close this issue then.
