### ISSUE TITLE
Firefox pipewire support but no camera

### ISSUE THREAD

**Issue by ttoommxx** [linux-surface/linux-surface#1215]
The new release of Firefox (116) added experimental pipewire support for camera but even after enabling it (in about:config) it won't see it. Is it normal? Am I missing something? Qcam works correctly on the other side

**Comment by qzed** [comment]
Maybe @kbingham can help here?

**Comment by kbingham** [comment]
Yes Firefox has released pipewire support so we can use that now. But pipewire needs to be configured correctly to use libcamera.

**Comment by ttoommxx** [comment]
> Yes Firefox has released pipewire support so we can use that now. But pipewire needs to be configured correctly to use libcamera.

Do you know how to do it or you have a reference guide that I can follow?

**Comment by kbingham** [comment]
I've "done" it a couple of times, but not in the last 6 months or so - so I can't remember the details. The best place to get support is the pipewire channels:

- https://matrix.to/#/#pipewire:matrix.org

Can you ask there please? - and where possible - write down any guide to support others doing the same at https://github.com/linux-surface/linux-surface/wiki/Camera-Support ?

**Comment by ttoommxx** [comment]
Will try, though I am not an expert so might come back here with more specific questions

**Comment by kbingham** [comment]
Capturing some of the discussion (but this should be moved/written on the wiki when it works)

In firefox: navigate to "about:config" and look for the option `media.webrtc.camera.allow-pipewire`

Ensure that pipewire is using libcamera. "wpctl status" will list the video devices and show if they are manged by v4l2 or libcamera.

If they are managed by v4l2 it may be that the libcamera plugin is missing. On Fedora this is packaged as `pipewire-plugin-libcamera`

**Comment by ttoommxx** [comment]
The issue is solved, I updated the guide.

**Comment by kbingham** [comment]
https://github.com/linux-surface/linux-surface/wiki/Camera-Support#firefox - thanks. Have you managed a video call with it now ? (Does https://meet.jit.si/linux-surface 'just work' now?)
