### ISSUE TITLE
RPM: running kernel gets removed on update

### ISSUE THREAD

**Issue by Cyborgscode** [linux-surface/linux-surface#122]
Surface Pro 4 
Fedora 30
kernel-surface-5.5.9-2.fc30.x86_64     

While running 5.5.8-1  and updating to 5.5.9-2, the kernel 5.5.8-1 got removed. 

This is considered bad behaviour, as you may end up with a not working system.  The running kernel shall never be removed on updates. You won't find any major distro out there, who ignores this.

first check if an old package exists
remove it, if it's not the running kernel
then install package in parallel: 
$ rpm -ivh --oldpackage new-kernel.rpm

**Comment by archseer** [comment]
This is dependent on how your distro does things, all we do is package up the kernel. Arch definitely doesn't do this on mainline and/or minor version bumps. (But we do allow you to have the normal kernel installed besides the surface one so you can always boot back to that)

From what I can tell [Fedora doesn't do that either](https://askbot.fedoraproject.org/en/question/112530/downgrade-kernel/)

**Comment by StollD** [comment]
Fedora does do it, for the stock kernels. You will have only the last one in the repository, but the last three ones stick around on the disk.

I tried to get the same behaviour for the surface kernel at some point, but this is not documented at all so I simply gave up. Even if a new surface kernel fails, you can always boot one of the three remaining stock kernels and downgrade it from there, as we keep around the old versions in the repository and on Github releases.

Even if you remove the stock kernel (I dont even know if that is possible), Fedora will create a rescue kernel + initramfs on installation that never changes, and that you can use to boot a system where the kernel doesn't work anymore.

If you know how to add that behaviour, feel free to submit a pull request. It needs to be done in the specfile, as we cannot script how dnf will update packages.

**Comment by Cyborgscode** [comment]
it's done in the kernel-core scripts. Just adopt it from here:

postinstall scriptlet (using /bin/sh):

if [ `uname -i` == "x86_64" -o `uname -i` == "i386" ] &&
   [ -f /etc/sysconfig/kernel ]; then
  /bin/sed -r -i -e 's/^DEFAULTKERNEL=kernel-smp$/DEFAULTKERNEL=kernel/' /etc/sysconfig/kernel || exit $?
fi
preuninstall scriptlet (using /bin/sh):
/bin/kernel-install remove 5.5.8-100.fc30.x86_64 /lib/modules/5.5.8-100.fc30.x86_64/vmlinuz || exit $?
posttrans scriptlet (using /bin/sh):
/bin/kernel-install add 5.5.8-100.fc30.x86_64 /lib/modules/5.5.8-100.fc30.x86_64/vmlinuz || exit $?
postinstall scriptlet (using /bin/sh):

if [ `uname -i` == "x86_64" -o `uname -i` == "i386" ] &&
   [ -f /etc/sysconfig/kernel ]; then
  /bin/sed -r -i -e 's/^DEFAULTKERNEL=kernel-smp$/DEFAULTKERNEL=kernel/' /etc/sysconfig/kernel || exit $?
fi
preuninstall scriptlet (using /bin/sh):
/bin/kernel-install remove 5.5.6-100.fc30.x86_64 /lib/modules/5.5.6-100.fc30.x86_64/vmlinuz || exit $?
posttrans scriptlet (using /bin/sh):
/bin/kernel-install add 5.5.6-100.fc30.x86_64 /lib/modules/5.5.6-100.fc30.x86_64/vmlinuz || exit $?
postinstall scriptlet (using /bin/sh):

if [ `uname -i` == "x86_64" -o `uname -i` == "i386" ] &&
   [ -f /etc/sysconfig/kernel ]; then
  /bin/sed -r -i -e 's/^DEFAULTKERNEL=kernel-smp$/DEFAULTKERNEL=kernel/' /etc/sysconfig/kernel || exit $?
fi
preuninstall scriptlet (using /bin/sh):
/bin/kernel-install remove 5.5.7-100.fc30.x86_64 /lib/modules/5.5.7-100.fc30.x86_64/vmlinuz || exit $?
posttrans scriptlet (using /bin/sh):
/bin/kernel-install add 5.5.7-100.fc30.x86_64 /lib/modules/5.5.7-100.fc30.x86_64/vmlinuz || exit $?

**Comment by StollD** [comment]
Sorry, but I don't think that contains the proper solution.

The `postinstall` script simply updates the package name for the kernel that GRUB will use as the new default when you update it.

The `kernel-install` script that is called by `preuninstall` and `posttrans` is just a script that copies the kernel binary and other configs from `/lib/modules/$(uname -r)` into `/boot`, so thats not the key either.

Any tricks that could be done through install scripts in the specfile are not gonna give the same behaviour as the stock kernel. We cannot stop the removal of a package in the install scripts, but for stock these packages stay do stay around. This needs to be done either through some metadata that is parsed by dnf, or through the dnf configuration itself.

Of course we could script it and have the package keep three kernels around as files, not as packages. But frankly. that feels even more dirty than only having one surface kernel and four stock kernels that you can fall back to.

**Comment by StollD** [comment]
So, I looked through the kernel.spec file (which is pretty much hell), and I think I figured out how to do this. 

The stock kernel does it by having the kernel package provide `installonlypkg(kernel)`, which is part of the default values for the `installonlypkgs` dnf config option:
```
~ $ dnf config-manager --dump | grep installonlypkgs
installonlypkgs = kernel, kernel-PAE, installonlypkg(kernel), installonlypkg(kernel-module), installonlypkg(vm), multiversion(kernel)
```

This list cannot be edited by the package, as dnf does not support a `conf.d` directory, and I don't want the package to edit `/etc/dnf/dnf.conf` directly.

If you want to get the behaviour of the stock kernel for the surface kernel package, running this should be enough:
```
~ $ sudo dnf config-manager --save --setopt='installonlypkgs=kernel-surface'
```

Alternatively, we could think about having the surface kernel package provide `multiversion(kernel)`. This is not used on fedora, and only in the default list for using dnf on openSUSE. If our package would provide this, the behaviour would be automatic for every installation. Although I think that adding the above command to the setup guide would be the better way.

**Comment by StollD** [comment]
After some more testing it seems that dnf works differently than I thought in this regard. My initial assumption was that dnf keeps around $n packages providing `installonlypkg(kernel)`, but it actually keeps around $n packages of $pkg_name, if it provides `installonlypkg(kernel)`.

Stock does this for `kernel` and `kernel-devel`: both provide `installonlypkg(kernel)`, and dnf keeps around $n versions for both of them.

This means we can just add `Provides: installonlypkg(kernel)` to kernel-surface and it will work without editing the config.

**Comment by StollD** [comment]
Even more testing revealed that dnf will go haywire if you add `installonlypkg(kernel)` to a package that is already installed, to get it to work you would have to remove the package and reinstall it from the repository.

So for the moment we decided to go with the config approach, to avoid the need for manual intervention by the user: After you installed the 5.5.10-1 version of kernel-surface (which is being built right now), it will provide `installonlypkg(kernel-surface)`. You have to run the following command to add it to the list of packages that dnf will keep around:
```
sudo dnf config-manager --save --setopt='installonlypkgs=installonlypkg(kernel-surface)'
```

You have to run the command **after** you installed 5.5.10-1, otherwise you will run into the same issue: dnf will refuse to install the update.

**Comment by qzed** [comment]
This seems to be fixed.
