### ISSUE TITLE
locked in suspend mode | keyboard not working in suspend mode

### ISSUE THREAD

**Issue by Haennes** [linux-surface/linux-surface#123]
Whenever I suspend my Surface Book2 it won't wake up from sleep, since no input device (touchscreen, touchpad, keyboard) is working. I have to shut the Surface Book down by holding the power button.

[Description of the bug or feature]

- Hardware model: Surface Book 2
- Kernel version: Linux hannes-Surface-Book-2 5.5.8-surface #1 SMP Fri Mar 6 13:40:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Linux Mint 19.3

- dmesg:
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/4333379/dmesg.txt)

**Comment by qzed** [comment]
By default, Linux does not enable wake-up events from the keyboard or other input devices. See e.g. [here](https://askubuntu.com/questions/848698/wake-up-from-suspend-using-wireless-usb-keyboard-or-mouse-for-any-linux-distro) on how you can change that. That being said, you will not be able to wake up the device via touchscreen, as that is disabled while the device is suspended. 

Does the device wake up via the lid or the power button?

You may also want to look at `journalctl -b -1` after you've tried to wake and then force-shut-down the system. This will give you the log from the last boot and may have some other information. I can also see some errors regarding nouveau in the dmesg log, which can also cause issues, e.g. system lock-ups. I recommend you try blacklisting nouveau completely (as described in https://github.com/jakeday/linux-surface/issues/264#issuecomment-427452156) and if needed rely on the nvidia proprietary driver.

**Comment by Haennes** [comment]
I tried enabling USB Devices to wake up after suspend but it sadly did not work. I enabled all devices and it still did not work. The device does not wake up from the lid or power button.

see my journalctl from last boot attached: 
[journalctl-b-a.txt](https://github.com/linux-surface/linux-surface/files/4334457/journalctl-b-a.txt)

Whenever my device powers off it gets stuck at le Linux Mint Logo and does nothing until I force-shut-down. Sometimes, when I press esc, I get the following error message:
1. core dump to |/bin/false pipe failed
After pressing alt + print I get:
2. mwifiex_pcie 0000:01:00.0: info: successfully disconnected from 4c:1b:86:79:03:ba: reason code 
Not sure what this means or if this is even an error.

**Comment by Haennes** [comment]
> I tried enabling USB Devices to wake up after suspend but it sadly did not work. I enabled all devices and it still did not work. The device does not wake up from the lid or power button.
> 
> see my journalctl from last boot attached:
> [journalctl-b-a.txt](https://github.com/linux-surface/linux-surface/files/4334457/journalctl-b-a.txt)
> 
> Whenever my device powers off it gets stuck at le Linux Mint Logo and does nothing until I force-shut-down. Sometimes, when I press esc, I get the following error message:
> 
> 1. core dump to |/bin/false pipe failed
>    After pressing alt + print I get:
> 2. mwifiex_pcie 0000:01:00.0: info: successfully disconnected from 4c:1b:86:79:03:ba: reason code
>    Not sure what this means or if this is even an error.

Blacklisting nouveau solved the power off problem for me! Many thanks!
I would love for waking from suspend to work, but I can live without it. Maybe you have another idea...

**Comment by qzed** [comment]
The journalctl log is a bit short, seems like it's only the top part of it. There should be a lot more stuff in there. Try `journalctl -b -1 > out.log` if you didn't do that already. Without more information (such as a log from trying to suspend/resume) I can't really help you. I suspect that something might be crashing during either suspend or resume, as there are no other errors apparent in the dmesg log. You did try again after blacklisting nouveau?

**Comment by Haennes** [comment]
I now got the whole `journalctl -b -1` Log: [out.log](https://github.com/linux-surface/linux-surface/files/4337951/out.log)

After blacklisting nouveau, I still have no way of waking up from suspend, even after enabling wakeup for all devices.

**Comment by qzed** [comment]
Hmm, I can't see anything that would indicate why it's not working. You could try and see if unloading some modules before suspending (e.g ipts) fixes this. Just to make sure: The power button and lid are working when not suspended?

**Comment by Haennes** [comment]
I got waking up from suspend by pressing the power-button to work, but only sometimes. I can't really see a pattern, except it never works after I closed the lid.
Sometimes pressing the power-button in suspend mode works and sometimes it doesn't.

After the last force-reboot, after the device didn't wake up from suspend after closing the lid, I got the following messages in my journalctl:

ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Removing IPTS
ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: ipts_control_send: error 0x4:-19
ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: ipts_control_send: error 0x7:-19
ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Stopping receive loop
ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Stopping data loop

Maybe this has to do with the problem?

Attached the full journalctl 
[out.log](https://github.com/linux-surface/linux-surface/files/4368596/out.log)

**Comment by qzed** [comment]
Those messages are currently standard behavior when the IPTS module is unloaded. If it doesn't work depending on the way the suspend is initiated this could be a configuration problem. Can you check if this also happens when you run `echo mem | sudo tee /sys/power/state`?

**Comment by Haennes** [comment]
After I ran `echo mem | sudo tee /sys/power/state` and pressed the power-button I was able to get directly back to the desktop (no login screen), where I got asked if I want to shut down the system (normal message when I press the power-button).

**Comment by qzed** [comment]
If that command works reliably, suspend works fine on the kernel side. That would point to a configuration issue, for example something like suspend on lid-close being set up through both Gnome (or your desktop environment) and systemd (in which case you should make sure that only one of those triggers it).

**Comment by Haennes** [comment]
After installing 4.19 I got new problems with suspend. 

I got suspend to work one time after pressing the power button, after which my device froze for about 20 seconds. After trying to suspend my device one more time, it did not work and after I pressed the power button again, my device completely froze and I had to shut it down by force. 

I also got some errors about suspend not working in my journactl [out.log](https://github.com/linux-surface/linux-surface/files/4397406/out.log). On 4.19 my boots where completely error-free, except for some bluetooth and audio errors.

I also tried `echo mem | sudo tee /sys/power/state`. The device froze for some time on a black screen. After hitting the power button I was able to log back in but I was stuck on a frozen desktop for about 20 seconds. 

It now seems like suspend is not working nicely on the kernel side.

Thank you for your support!

**Comment by qzed** [comment]
Two things:
- The GPU hangs might be caused by IPTS. Try running the following commands before suspending:
  ```
  modprobe -r ipts_surface
  modprobe -r intel_ipts
  modprobe -r mei_hdcp
  modprobe -r mei_me
  modprobe -r mei
  ```
- Based on your logs it looks like you're actually suspending (and resuming) three times. Once directly after resuming:
  ```
  Mar 28 16:50:07 SB2-Mint kernel: PM: suspend exit
  Mar 28 16:50:07 SB2-Mint kernel: PM: suspend entry (s2idle)
  ```
  This can be caused by a configuration issue which I've mentioned before. In your log I see a couple of
  ```
  Mar 28 16:48:30 SB2-Mint systemd-logind[863]: Power key pressed.
  ```
  which indicates that `sytemd-logind` tries to handle the power button. I don't know how Cinnamon behaves, however it's based on Gnome and by default Gnome also tries to handle the power button event. Having both systemd and Cinnamon handle the power button will cause havoc, so maybe also try setting `HandlePowerKey` in `/etc/systemd/logind.conf` to `ignore`.

**Comment by Haennes** [comment]
After removing the modules and configuring the `/etc/systemd/logind.conf` I got suspend to work with both closing the lid and the power button. By the way, `modprobe` can't find the module `mei_hdcp`, not sure if this is okay.

In my log I still see lines like
```
Apr 02 19:15:48 SB2-Mint kernel: ACPI: Lid Switch [LID0]
Apr 02 19:15:49 SB2-Mint systemd-logind[874]: Watching system buttons on /dev/input/event0 (Lid Switch)
Apr 02 19:22:33 SB2-Mint systemd-logind[874]: Lid closed.
Apr 02 19:22:37 SB2-Mint systemd-logind[874]: Lid opened.
Apr 02 19:24:01 SB2-Mint systemd-logind[874]: Lid closed.
Apr 02 19:24:36 SB2-Mint systemd-logind[874]: Lid opened.
```
and
```
Apr 02 19:34:04 SB2-Mint systemd-logind[874]: Power key pressed.
Apr 02 19:35:36 SB2-Mint systemd-logind[874]: Power key pressed.
```
although I set the HandlePowerKey and HandleLidSwitch to ignore. The `/etc/systemd/logind.config` settings look like this:
```
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
HandlePowerKey=ignore
#HandleSuspendKey=suspend
#HandleHibernateKey=hibernate
HandleLidSwitch=ignore
#HandleLidSwitchDocked=ignore
#PowerKeyIgnoreInhibited=no
#SuspendKeyIgnoreInhibited=no
#HibernateKeyIgnoreInhibited=no
#LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
#UserTasksMax=33%
```

I'm glad that suspend works by removing the modules. Is there any way to automate this process whenever I want to suspend the device? Do I need to add the modules to the kernel after resuming from suspend?

Thank you!

**Comment by qzed** [comment]
Neat! You can ignore the `mei_hdcp` module if that doesn't exist, the key point is that you need to unload all `mei_<...>` modules that you have on your system.

> Is there any way to automate this process whenever I want to suspend the device?

Yes, see https://github.com/linux-surface/linux-surface/wiki/Known-Issues#sleep-script. Just comment in the `modprobe` lines that you need (and comment out the bluetooth fix if you don't need that).

> Do I need to add the modules to the kernel after resuming from suspend?

You should do so, yes. The sleep script should take care of that.

**Comment by Haennes** [comment]
Thank you very much! Issue closed!
