### ISSUE TITLE
Slim pen 2 constant random button presses

### ISSUE THREAD

**Issue by Joseph-DiGiovanni** [linux-surface/linux-surface#1233]
While using the slim pen 2 on a surface laptop studio I get a constant storm of pen button presses when the tip is pressed to the screen. This causes canvas drags instead of a brush stroke in krita for example making it basically unusable for any serious work.

Issue is present on both libwacom and libwacom-surface.

You can see it happen in this [output of libinput debug-events](https://github.com/linux-surface/linux-surface/files/12458731/libinput.debug-events.txt). I hovered the pen for a second before dragging the pen on the screen a bit. I didn't press the button at all despite many random presses being detected. Its worth noting the button works fine when I actually want to use it and the pen has zero issues in windows.

Even a band-aid fix allowing me to simply disable the button would be greatly appreciated.

### Environment

- Hardware model: Surface Laptop Studio
- Kernel version: linux-surface 6.4.12.arch1.1
- Distribution: Arch Linux

[dmesg output](https://github.com/linux-surface/linux-surface/files/12458779/dmesg.txt)

**Comment by quo** [comment]
You'll want to increase ButtonMinMag in /etc/iptsd.conf.

See also e.g. https://github.com/linux-surface/iptsd/issues/99#issuecomment-1606195833

**Comment by Joseph-DiGiovanni** [comment]
> You'll want to increase ButtonMinMag in /etc/iptsd.conf.

Setting it to 20K as the linked comment suggested fixed it completely. Thank you so much

**Comment by Joseph-DiGiovanni** [comment]
Setting it to 20K as the linked comment suggested fixed it completely. Thank you so much
