### ISSUE TITLE
touchscreen broken in various ways

### ISSUE THREAD

**Issue by erjoalgo** [linux-surface/linux-surface#1235]
### Environment

I'm not sure if this is a linux-surface or gnome, debian issue. Attempting to drag a window using the touchscreen does not work sometimes. See attached repro video.

- Hardware model: Surface Pro 1796 Laptop
- Kernel version: `Linux localhost 6.4.12-surface #1 SMP PREEMPT_DYNAMIC Fri Aug 25 22:33:48 UTC 2023 x86_64 GNU/Linux`
- Distribution: debian bookworm

[dmesg.log](https://github.com/linux-surface/linux-surface/files/12467531/dmesg.log)

**Comment by erjoalgo** [comment]
Repro video:

https://github.com/linux-surface/linux-surface/assets/5349288/1738fe03-092e-4cf2-89e9-1ad723c4de15

**Comment by erjoalgo** [comment]
Here's another video of broken touchscreen movements. This time touch stops working inside a window, but dragging the window is possible:

https://github.com/linux-surface/linux-surface/assets/5349288/8579e32c-c6ff-436c-a6f5-17ee1d5e75ca

**Comment by StollD** [comment]
Unfortunately, we can't do anything about that. It is an issue with your desktop environment.

Linux touchscreen drivers only send the coordinates of the inputs to the applications running in userspace, so your DE and the apps. If the touchscreen works on one app but not on the other, our driver is doing everything right and the DE is throwing away some of the inputs.

**Comment by erjoalgo** [comment]
I understand, thanks for the pointer.
