### ISSUE TITLE
Unresolved dependency: mokutil-git

### ISSUE THREAD

**Issue by nicolas93** [linux-surface/linux-surface#124]
When installing the repositories as described here: https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup
and here: https://github.com/linux-surface/linux-surface/wiki/Package-Repositories
for a Arch-based distro (I used manjaro), the dependency "mokutil-git" cant be installed.

It was no problem since I could just install it via ```yay```, but I thinked it should be fixed in the documentation.

```
[nicolas@surface ~]$ sudo pacman -S linux-surface-headers linux-surface surface-ipts-firmware linux-surface-secureboot-mok
Löse Abhängigkeiten auf...
Warnung: Kann "mokutil-git" nicht auflösen (eine Abhängigkeit von "linux-surface-secureboot-mok")
:: Das folgende Paket kann aufgrund nicht auflösbarer Abhängigkeiten nicht aktualisiert werden:
      linux-surface-secureboot-mok

:: Möchten Sie das obengenannte Paket bei dieser Aktualisierung überspringen? [j/N] 
Fehler: Konnte den Vorgang nicht vorbereiten (Kann Abhängigkeiten nicht erfüllen)
:: Unerfüllbare Abhängigkeit 'mokutil-git', benötigt von linux-surface-secureboot-mok
```
(I hope the error message is understandable despite being in German, sorry for that)

### Environment

- Hardware model: Surface 3
- Kernel version: 5.4.24
- Distribution: Arch/Manjaro

**Comment by qzed** [comment]
> I thinked it should be fixed in the documentation.

Agreed, I've updated the wiki. Feel free to edit it if you have something to add.
