### ISSUE TITLE
Installation failed with Ubuntu 22.04 and Surface Pro 5

### ISSUE THREAD

**Issue by Michdo93** [linux-surface/linux-surface#1240]
Hi,

probably it is because I made a big mistake. But could really use help on what I can do. I have done following:

```
wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" \
	| sudo tee /etc/apt/sources.list.d/linux-surface.list
sudo apt update
sudo apt install linux-image-surface linux-headers-surface libwacom-surface iptsd
sudo apt install linux-surface-secureboot-mok
sudo update-grub
sudo reboot
```

Then I have pressed the power button and hold the volume up button to enter UEFI. Then I enabled the 3rd party ca.

And that is wrong. After installing `linux-surface-secureboot-mok` I had to reboot and then I have to enter the password `SURFACE`. And I think then I have to enable the 3rd party ca.

My problem is that I see the Windows logo and Ubuntu is not booting. I also tried to boot from USB but this is also not working.

So I am looking for a way to reset this completely. I would probably have to access the internal memory and install Windows, or can you think of something else?

Thanks in advance.

**Comment by Sausagerolls** [comment]
Did you find a solution for this? I'm in exactly the same situation as you

**Comment by Michdo93** [comment]
Sadly not. I found a solution for reinstall Windows.

[https://support.microsoft.com/de-de/surface-recovery-image](https://support.microsoft.com/de-de/surface-recovery-image)

But after reinstalling Windows I can only boot Windows. I can reinstall Windows thousand times. It seems that the certificate is missing that I can boot Linux. I have tried my Linux USB stick on other computers and it worked fine. I also tried UNetbootin. In the bootloader it shows UNetbootin but it does not boot Linux in the end.

**Comment by qzed** [comment]
Dud you ever try installing with secureboot completely disabled?

**Comment by qzed** [comment]
Also what do you mean by this exactly?

> My problem is that I see the Windows logo and Ubuntu is not booting. I also tried to boot from USB but this is also not working.

Is it the first logo before the bootloader shows up, does this happen after you select Ubuntu in the bootloader, or does the bootloader not show up in the first place?

**Comment by qzed** [comment]
> but can't boot Linux from USB

Can you be more specific? Where exactly does it fail, and how?

**Comment by Michdo93** [comment]
He does not recognize it. It simply does not boot. What should I say about this? It works on other computers. I have USB in the priority at the top. I can also disable the hard drive, Windows Boot Manager and NXE. It does not boot, although the USB stick goes on other computers. If I insert a USB stick with Windows instead, I can boot via USB.

It will then start Windows normally.

**Comment by Michdo93** [comment]
I found a solution. I used YUMI-exFAT-1.0.2.0 and recreated a bootable USB Stick. Because you kann install keys and certificates with it.

**Comment by qzed** [comment]
So it just jumps to the second boot entry? What happens if you swipe on the USB entry? Does it go back into the UEFI menu? In that case it looks like the USB isn't recognized as an EFI boot medium. It might be possible that it's only legacy BIOS/MBR bootable, which could explain why it works on other machines. In which case I would suggest you try some other way of flashing the USB drive.

Note that for it to be EFI bootable it must have GPT partition scheme and a fat32 partition with an EFI executable at `/EFI/Boot/bootx64.efi`.

**Comment by Michdo93** [comment]
So I tried it today. Now it will not boot after:

```
sudo apt install linux-surface-secureboot-mok
```

Is it possible to make this without rebooting?

**Comment by Michdo93** [comment]
Okay. It now works. I just plugged in the USB stick again and booted Ubuntu, selecting Try Ubuntu. After that I restarted the tablet and was able to boot normally again. Now also have Touch. Strangely enough without this password entry.

**Comment by Darkloresider** [comment]
> Хорошо. Теперь это работает. Я просто снова подключил USB-накопитель и загрузил Ubuntu, выбрав «Попробовать Ubuntu». После этого я перезагрузил планшет и снова смог нормально загрузиться. Теперь еще и Touch. Как ни странно, без этого ввода пароля.

Just faced exactly the same thing: **pro 5, ubuntu, secure-boot and update-grub until reboot** and my surface does not see usb with ubuntu installer image. I tried to create on the main computer the image of recovery (restore windows bootloader), but it is not recognized, with the help of media creation tool at the moment I make windows installer, but frankly I'm down, nothing goes further than the boot screen with the logo or UEFI. Can you tell me more about how you managed to restore the system and certificate keys?

**Comment by Michdo93** [comment]
> > Okay. It now works. I just plugged in the USB stick again and booted Ubuntu, selecting Try Ubuntu. After that I restarted the tablet and was able to boot normally again. Now also have Touch. Strangely enough without this password entry.
> 
> Just faced exactly the same thing: **pro 5, ubuntu, secure-boot and update-grub until reboot** and my surface does not see usb with ubuntu installer image. I tried to create on the main computer the image of recovery (restore windows bootloader), but it is not recognized, with the help of media creation tool at the moment I make windows installer, but frankly I'm down, nothing goes further than the boot screen with the logo or UEFI. Can you tell me more about how you managed to restore the system and certificate keys?
> 
> UPD: media creation tool didn't help, surface still doesn't see it, I will try recovery image, but the fact that it didn't even load windows installation flash drive scares me.

I have used YUMI exFAT. This is a tool under Windows that allows you to create multiple boot USB sticks. So you can load multiple images on it and then you can choose at boot time which of these images you want to boot.

Ventoy Secure Boot is used. You can also select whether to boot via Normal Mode or GRUB. Since Windows is installed, you have to select Normal Mode accordingly.

When you use the program, it formats the USB stick first. For me, this crashed at the first moment. I then formatted the USB stick via Windows and then ran the program again. If you then prepare the USB stick via the program, then it first copies all data on it, so that the stick is multiple bootable. In the course of this boot menu you can install certificates. And then boot your image. Only after this stick is "prepared", you can install one or more images, which can then be booted via this already added boot menu.

Please have a look [here](https://www.pendrivelinux.com/yumi-multiboot-usb-creator/). In the linked page you will find `Is USB Secure Boot Supported?`. There you will see how to install a certificate, for example. I can look again later at home, how the steps were exactly.

I disabled Secure Boot via UEFI before booting from this USB stick. And as written later, after installing Ubuntu and the necessary dependencies, I again did not get a blue screen. Then I went in again via this stick, booted Ubuntu there for testing, so did not reinstall. Have rebooted and then it went without me in a blue screen had to enter the password `surface`.

**Comment by Michdo93** [comment]
Fixed by using a [surface recovery image](https://support.microsoft.com/de-de/surface-recovery-image) for reinstalling Windows and using [YUMI exFAT](https://www.pendrivelinux.com/yumi-multiboot-usb-creator/#Bootable_exFAT_Flash_Drive_Setup_and_USB_Boot_Screen) for installing certificates for booting Linux and installing Ubuntu.

**Comment by Michdo93** [comment]
Fixed by using a [surface recovery image](https://support.microsoft.com/de-de/surface-recovery-image) for reinstalling Windows and using [YUMI exFAT](https://www.pendrivelinux.com/yumi-multiboot-usb-creator/#Bootable_exFAT_Flash_Drive_Setup_and_USB_Boot_Screen) for installing certificates for booting Linux and installing Ubuntu.

**Comment by Darkloresider** [comment]
> Please have a look [here](https://www.pendrivelinux.com/yumi-multiboot-usb-creator/). In the linked page you will find Is USB Secure Boot Supported?. There you will see how to install a certificate, for example.

Are the necessary certificates on this place? (I can't see it now) Anyway, I decided to give up on secure boot, it's too complicated when to disable it and when to enable it, but the fact that the installation image created in the usual way is not bootable is a bit embarrassing.

>  I can look again later at home, how the steps were exactly.
I'll be waiting, thanks for your help

**Comment by Darkloresider** [comment]
I repeated everything as described in microsoft instructions, but my surface just doesn't see this flash drive. Any idea what to do?

**Comment by Darkloresider** [comment]
Solved. 
If recovery image doesn't boot - change USB flash, preferably usb 3.0 flash
