### ISSUE TITLE
Fedora Repo 404 and kernel update issue

### ISSUE THREAD

**Issue by asmuscma** [linux-surface/linux-surface#1244]
I am trying to install updates via dnf and am receiving a 404 error response from the fedora repo of the kernel. 

> Errors during downloading metadata for repository 'pkg.surfacelinux.com_fedora_linux-surface.repo_':
> - Status code: 404 for https://pkg.surfacelinux.com/fedora/linux-surface.repo~/repodata/repomd.xml (IP: 78.47.152.21)

I am also receiving an error when updating that it is trying to update the kernel. 

>Error: Problem: The operation would result in removing the following protected packages: kernel-surface

- Hardware model: Surface Book
- Kernel version: 6.2.14-1.surface.fc38.x86_64
- Distribution: Fedora 38

**Comment by StollD** [comment]
How did you install the repo? That URL it is trying to fetch is completely wrong. It should be https://pkg.surfacelinux.com/fedora/f38/repodata/repomd.xml

**Comment by asmuscma** [comment]
> How did you install the repo? That URL it is trying to fetch is completely wrong. It should be https://pkg.surfacelinux.com/fedora/f38/repodata/repomd.xml

I followed the [installation instructions for Fedora](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#Fedora). I tried adding the repo link you specified and I receive the same 404 error.

**Comment by StollD** [comment]
Could you provide the output of `ls -la /etc/yum.repos.d` and `cat /etc/yum.repos.d/linux-surface.repo`?

**Comment by asmuscma** [comment]
ls -la /etc/yum.repos.d
```total 56
drwxr-xr-x. 1 root root  706 Sep  8 13:28 .
drwxr-xr-x. 1 root root 4680 Aug 31 17:55 ..
-rw-r--r--. 1 root root  376 Aug 24 19:17 _copr:copr.fedorainfracloud.org:jstaf:onedriver.repo
-rw-r--r--. 1 root root  728 Apr  5 19:00 fedora-cisco-openh264.repo
-rw-r--r--. 1 root root 1302 Apr  5 19:00 fedora-modular.repo
-rw-r--r--. 1 root root 1239 Apr  5 19:00 fedora.repo
-rw-r--r--. 1 root root 1349 Apr  5 19:00 fedora-updates-modular.repo
-rw-r--r--. 1 root root 1286 Apr  5 19:00 fedora-updates.repo
-rw-r--r--. 1 root root 1391 Apr  5 19:00 fedora-updates-testing-modular.repo
-rw-r--r--. 1 root root 1344 Apr  5 19:00 fedora-updates-testing.repo
-rw-r--r--. 1 root root  174 May  4 18:50 google-chrome.repo
-rw-r--r--. 1 root root  280 Sep  8 13:28 linux-surface.repo
-rw-r--r--. 1 root root 1312 Apr 13 19:00 rpmfusion-nonfree.repo
-rw-r--r--. 1 root root 1309 Apr 13 19:00 rpmfusion-nonfree-updates.repo
-rw-r--r--. 1 root root 1369 Apr 13 19:00 rpmfusion-nonfree-updates-testing.repo
-rw-r--r--. 1 root root  164 Aug 23 23:24 vscode.repo
```
cat /etc/yum.repos.d/linux-surface.repo
```[linux-surface]
name=linux-surface
baseurl=https://pkg.surfacelinux.com/fedora/f$releasever/
enabled=1
skip_if_unavailable=1
gpgkey=https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc
gpgcheck=1
enabled_metadata=1
type=rpm-md
repo_gpgcheck=0
```

**Comment by StollD** [comment]
> ls -la /etc/yum.repos.d

So this looks normal.

> cat /etc/yum.repos.d/linux-surface.repo

But this is missing `[linux-surface]` on the first line. I dont know DNF well enough, but I imagine that could cause some issues.

https://pkg.surfacelinux.com/fedora/linux-surface.repo is how it should look.

**Comment by asmuscma** [comment]
My fault, I somehow omitted that line from my message.

**Comment by asmuscma** [comment]
I was able to fix the protected package issue by booting into a different kernel. I did a bit of digging and found an [older issue with the same problem](https://github.com/linux-surface/linux-surface/issues/1163) and found out that the kernel packages were restructured.
