### ISSUE TITLE
[SP5][Debian 12.1] MOK password using QWERTY keyboard

### ISSUE THREAD

**Issue by Vanane** [linux-surface/linux-surface#1246]
Hello,
This is not a bug as mush as this is a suggestion for the installation process.
I've spent an hour trying to figure out what I did wrong with my Surface Pro 5, using Debian 12.1 installed from Ventoy.
I basically kept everything as vanilla as possible, went through every single step manually and kept record of all the commands and their outputs.

But no matter what I did, I couldn't find anything about why the damn password that you must write to enroll the key when booting on secure boot (`surface`) wasn't matching with the key.

Turns out, the key disposition in the MOK menu are set to QWERTY. Which isn't particularly a bug, but I feel like this should be added to the docs !

**Comment by qzed** [comment]
Done. Thanks for reporting this!
