### ISSUE TITLE
Installation and Setup guide is missing

### ISSUE THREAD

**Issue by airwavesandtv0** [linux-surface/linux-surface#1253]
The detailed installation and setup guide mentioned in README.md is missing. When trying to reach the link (https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup) the user is asked to create the page, and when navigating to other parts of the wiki the "Installation and Setup" section is marked as being empty.

I presume adding environment details is not relevant but I have done it anyway. I have left dmesg out as I don't fully understand how to share it.

### Environment

- Hardware model: Surface Pro 7
- Kernel version: Linux surface-no 6.5.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:01:01 +0000 x86_64 GNU/Linux
- Distribution: EndeavourOS

**Comment by StollD** [comment]
Some troll renamed the page and now I can't even see what else they changed because it counts as a new page now. Wonderful.

**Comment by StollD** [comment]
Scratch that, GitHub wikis are standard git repos and you can clone them locally and inspect the history. They really just renamed the page, which I reverted.

**Comment by airwavesandtv0** [comment]
Great, now the issue is resolved I assume I close the issue? New to GitHub heh

Thanks for being quick to respond :-)
