### ISSUE TITLE
modinfo fails to find drivers for kernel 6.5.5 and 6.5.6

### ISSUE THREAD

**Issue by Dai-trying** [linux-surface/linux-surface#1266]
[Description of the bug or feature]
During the normal update procedure I noticed that when the new kernel was being built there were a lot of errors like this:-

modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/r8a66597-hcd.ko.zst not found.

This error is repeated approx 1446 times and I have checked the location of these files, and they all exist.

The result is being dropped to initramfs prompt but as no keyboard drivers exist I cannot even try anything to get it working.

I still have the 6.4.12 kernel (working correctly) so i can still use this surface pro 3.

This is the terminal output from issuing the command [apt install --reinstall linux-image-6.5.6-surface]

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/122 MB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 231865 files and directories currently installed.)
Preparing to unpack .../linux-image-6.5.6-surface_6.5.6-surface-1_amd64.deb ...
Unpacking linux-image-6.5.6-surface (6.5.6-surface-1) over (6.5.6-surface-1) ...
Setting up linux-image-6.5.6-surface (6.5.6-surface-1) ...
update-initramfs: Generating /boot/initrd.img-6.5.6-surface
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/r8a66597-hcd.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/ehci-fsl.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/xhci-pci-renesas.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/xhci-pci.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/usb/host/xen-hcd.ko.zst not found.
snip... (because message was too large to post)

modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/virt/lib/irqbypass.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/arch/x86/kvm/kvm.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/iommu/iommufd/iommufd.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/vfio/vfio.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/vfio/vfio_iommu_type1.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/vfio/mdev/mdev.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/i915/kvmgt.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/udl/udl.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/mgag200/mgag200.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/gma500/gma500_gfx.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/gud/gud.ko.zst not found.
modinfo: ERROR: Module /lib/modules/6.5.6-surface/kernel/drivers/gpu/drm/vboxvideo/vboxvideo.ko.zst not found.
Generating grub configuration file ...
Found background image: /usr/share/images/desktop-base/desktop-grub.png
Found linux image: /boot/vmlinuz-6.5.6-surface
Found initrd image: /boot/initrd.img-6.5.6-surface
Found linux image: /boot/vmlinuz-6.5.5-surface
Found initrd image: /boot/initrd.img-6.5.5-surface
Found linux image: /boot/vmlinuz-6.4.12-surface
Found initrd image: /boot/initrd.img-6.4.12-surface
Found linux image: /boot/vmlinuz-5.10.0-26-amd64
Found initrd image: /boot/initrd.img-5.10.0-26-amd64
Warning: os-prober will be executed to detect other bootable partitions.
Its output will be used to detect bootable binaries on them and create new boot entries.
Found Ubuntu 22.04.1 LTS (22.04) on /dev/sda4
Adding boot menu entry for UEFI Firmware Settings ...
done

### Environment

- Hardware model:  Surface pro 3 Intel Core i3-4020Y
- Kernel version: Linux surface 6.4.12-surface #1 SMP PREEMPT_DYNAMIC Fri Aug 25 22:33:48 UTC 2023 x86_64 GNU/Linux

- Distribution: Debian Bookworm

<details><summary>`dmesg` output</summary>
Please note e dmesg output is using 6.4.12 kernel and so not included
</details>

**Comment by StollD** [comment]
Does it work after running `sudo depmod -a`?

**Comment by jonas-s-s-s** [comment]
> Does it work after running `sudo depmod -a`?

Running this didn't change anything. Still the same problem.

**Comment by qzed** [comment]
Can you check whether some module files exist and it's somehow just a different compression? E.g. run
```
ls -al /lib/modules/6.5.6-surface/kernel/drivers/usb/host/
```

**Comment by Dai-trying** [comment]
I tried both depmod commands above but to no avail, here is ls result of the ls command.

dai@surface:~$ ls -al /lib/modules/6.5.6-surface/kernel/drivers/usb/host/
total 188
drwxr-xr-x  2 root root  4096 Oct 12 20:29 .
drwxr-xr-x 24 root root  4096 Oct 10 19:11 ..
-rw-r--r--  1 root root  3470 Oct  9 20:24 bcma-hcd.ko.zst
-rw-r--r--  1 root root  5738 Oct  9 20:24 ehci-fsl.ko.zst
-rw-r--r--  1 root root  2776 Oct  9 20:24 fsl-mph-dr-of.ko.zst
-rw-r--r--  1 root root 20490 Oct  9 20:24 isp116x-hcd.ko.zst
-rw-r--r--  1 root root 12347 Oct  9 20:24 max3421-hcd.ko.zst
-rw-r--r--  1 root root 27605 Oct  9 20:24 oxu210hp-hcd.ko.zst
-rw-r--r--  1 root root 24820 Oct  9 20:24 r8a66597-hcd.ko.zst
-rw-r--r--  1 root root  3976 Oct  9 20:24 sl811_cs.ko.zst
-rw-r--r--  1 root root 15592 Oct  9 20:24 sl811-hcd.ko.zst
-rw-r--r--  1 root root  4094 Oct  9 20:24 ssb-hcd.ko.zst
-rw-r--r--  1 root root 13063 Oct  9 20:24 xen-hcd.ko.zst
-rw-r--r--  1 root root 11047 Oct  9 20:24 xhci-pci.ko.zst
-rw-r--r--  1 root root  7158 Oct  9 20:24 xhci-pci-renesas.ko.zst
-rw-r--r--  1 root root  7651 Oct  9 20:24 xhci-plat-hcd.ko.zst

**Comment by qzed** [comment]
Weird. So the files it complains about earlier are actually there...

**Comment by Dai-trying** [comment]
Yes, I'm just going to try and extract all the .ko files and place them in their respective places to see if that works.... watch this space...

**Comment by qzed** [comment]
I was thinking that maybe something in the system doesn't support zstd compression. But I guess that would need us to recompile the packages. We could try...

**Comment by Dai-trying** [comment]
I did notice that zstd was not installed so installed it before decompressing the files and tried reinstalling again with same results. I'm going to try a reboot and chech again.

**Comment by StollD** [comment]
You can try passing the full path of one of the modules to modinfo and check what it outputs. In a Debian 12 container, this worked fine for me.

**Comment by Dai-trying** [comment]
after decompressing all the .zst files the newly created .ko file can be read by modinfo 

$ sudo modinfo /lib/modules/6.5.6-surface/kernel/drivers/usb/host/xhci-plat-hcd.ko 
filename:       /lib/modules/6.5.6-surface/kernel/drivers/usb/host/xhci-plat-hcd.ko
license:        GPL
description:    xHCI Platform Host Controller Driver
alias:          platform:xhci-hcd
srcversion:     3C817D4B66A9535A8C58157
alias:          acpi*:PNP0D10:*
depends:        
retpoline:      Y
intree:         Y
name:           xhci_plat_hcd
vermagic:       6.5.6-surface SMP preempt mod_unload modversions 
sig_id:         PKCS#7
signer:         Build time autogenerated kernel key
sig_key:        36:18:2C:E2:EF:34:07:8A:2F:FA:D5:3A:1C:7B:C6:94:D9:99:8C:6A
sig_hashalgo:   sha512
signature:      4D:7B:EE:17:F6:09:04:EB:EF:2C:E2:D1:B3:CC:CD:3E:A0:FC:92:AA:
		40:D3:A0:42:D2:11:10:F9:B6:D3:65:F5:B6:ED:1B:5A:A5:BA:5E:32:
		00:C8:12:D7:17:D6:82:24:B4:42:05:60:1D:D5:41:99:B7:03:C3:C2:
		C6:57:89:92:8A:77:D4:57:D2:60:49:87:BC:89:E9:AA:83:53:56:03:
		4B:CA:C8:54:BF:9F:47:C5:36:AC:5A:97:D7:12:2F:42:F9:FB:53:28:
		38:75:B3:D9:C8:18:77:18:17:7C:8B:BF:86:E2:5F:32:B8:6A:98:91:
		E7:D2:72:9A:1D:AF:6D:C5:CA:F8:A7:76:E4:40:42:DD:E9:0E:4F:BC:
		62:81:77:CF:44:5E:6D:54:C7:4F:32:05:97:9F:39:8B:C5:9F:54:68:
		24:46:12:62:F4:5E:8A:3D:96:29:EF:17:B9:EF:E6:C2:BE:92:EF:D3:
		0F:44:98:DD:36:04:D5:5C:36:B3:DC:2B:89:51:30:E4:8C:22:7F:E6:
		BE:F8:21:D0:C1:10:74:5C:0F:51:99:01:09:BE:6B:76:6F:4C:D9:6C:
		41:01:C3:1E:85:2B:3B:B6:A2:70:DA:FB:81:58:D9:6A:24:D9:C0:30:
		38:43:FB:98:C6:36:FF:B8:87:56:28:0B:02:53:BF:F5:A5:04:51:82:
		C9:88:19:06:1E:B8:C4:72:7D:5E:FD:6A:16:60:69:2D:5B:7F:97:DC:
		63:A1:AB:F3:20:45:E1:6E:C7:F2:82:D7:CB:B2:F8:FA:4A:F2:81:5A:
		60:84:BF:B4:C7:0A:66:2D:5A:68:FC:B8:26:CA:80:F3:25:6D:2F:7A:
		B8:81:38:F2:BD:26:11:CB:62:F3:A5:44:85:94:D1:30:10:57:A9:A2:
		17:7B:56:1D:FE:E3:29:10:18:BC:71:FF:31:97:96:1A:8F:AB:48:D7:
		B0:16:EC:F0:2F:75:A2:2C:D3:8E:44:26:90:3F:40:05:B2:D3:C5:25:
		37:52:7C:37:64:1A:22:60:EF:AD:7E:DB:F3:4B:00:C6:AE:44:8B:64:
		BE:5E:E4:76:33:7F:DF:22:AE:88:9D:A8:1A:8A:2A:1B:B2:8B:1E:0B:
		DF:D3:3D:70:FF:D5:0C:E4:99:35:7E:ED:31:0C:55:A1:90:53:D4:05:
		84:BF:4B:FD:E2:F7:B0:29:E3:F3:EF:97:DD:00:C3:FD:0A:FE:1C:50:
		19:9F:44:78:3B:DB:AC:48:8F:A2:AD:FA:4E:4D:89:6B:3F:F0:53:12:
		2C:27:8B:63:9E:48:44:13:9E:10:4E:BA:7C:9F:ED:22:65:7D:D5:0B:
		9C:EB:04:7E:06:46:0D:AE:F6:15:C9:E1

But the errors still exist when trying to (dpkg-)reconfigure the kernel.

**Comment by Dai-trying** [comment]
Just realised I'm using bullseye and not bookworm! and so the version of modinfo installed doesn't use zst compression, the version in bookworm does support it. (Assumption based on dependencies) so I am going look into bumping the OS up a version if possible.
Sorry  for my misleading distro information....

**Comment by Dai-trying** [comment]
After my realisation that I was using debian bullseye and not Debian bookworm I changed sources and updated and now have Debian bookworm running and kernel compiles without issue, Again my apologies for poor info on my part and thanks for every comment which combined have led me to my solution.
I will close this now as it should not be left open due to my error.

**Comment by qzed** [comment]
I think we should rather address this on the package level and use a type of compression that is also compatible with older distros. I'll reopen this issue until I got around to do that.

**Comment by Dai-trying** [comment]
Sorry, i guess i jumped the gun a bit.

**Comment by StollD** [comment]
Interestingly, the ubuntu mainline repo we are using already turned on compression of the kernel modules in a 6.4 release but then turned it off again. See: https://github.com/linux-surface/linux-surface/issues/1203

To revert this, we need to disable `CONFIG_MODULE_COMPRESS_ZSTD` and enable `CONFIG_MODULE_COMPRESS_XZ` or `CONFIG_MODULE_COMPRESS_NONE`. Compressing the modules with zstd reduces the space on disk from 300 MB to 100MB, but almost doubles the size of the deb file.

Since the package is already compressed with xz, compressing the modules with that too might be the most efficient solution.

**Comment by qzed** [comment]
Yeah, I think xz is the best option. It's been supported in kernel longer than zstd, so I'm hoping it is also supported in the older distros.

**Comment by jonas-s-s-s** [comment]
> Just realised I'm using bullseye and not bookworm! and so the version of modinfo installed doesn't use zst compression, the version in bookworm does support it. (Assumption based on dependencies) so I am going look into bumping the OS up a version if possible. Sorry for my misleading distro information....

That's probably the same problem as I had. I'm also running debian bullseye. I'll try to update to bookworm once I have time and see if that solves it.

**Comment by qzed** [comment]
No rush with updating, it would be great if you could test the new kernels with xz module compression before updating. I hope I can get to push that this evening.

**Comment by qzed** [comment]
I've updated our kernel config snippet to enforce xz compression in 020d463b0264089a4c30a0149b119d0a1e69534d. New packages are building.

**Comment by jonas-s-s-s** [comment]
New version seems to be working fine on debian 11. 

```
root@surface:/home/surface# uname -r
6.5.6-surface
root@surface:/home/surface# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by qzed** [comment]
Marking this as solved again. Let me know if the issue persists on some distro version.
