### ISSUE TITLE
Surface Go 2 randomly (?) stops registering touch input on Gnome

### ISSUE THREAD

**Issue by dev-nis** [linux-surface/linux-surface#1284]
[Description of the bug or feature]
Hi,

I recently bought a Surface Go 2 for one of my relatives and installed NixOS on it. As the feature doesn't say I need it, I haven't installed the linux-surface kernel (might be the problem here).
The device works great, however, it sometimes just 'hangs'. You cannot interact with it anymore. The screen still updates (e. g. the time), but no touch requests do anything. Except when the device goes darker before going to sleep, you can stop this by touching the screen.
I'm also not sure if this problem might be a GNOME one?

### Environment

- Hardware model: Surface Go 2 
- Kernel version: Linux herzog-laptop 6.1.45 #1-NixOS SMP PREEMPT_DYNAMIC Fri Aug 11 10:08:27 UTC 2023 x86_64 GNU/Linux
 
- Distribution: NixOS (GNOME)

<details><summary>`dmesg` output</summary>

[dmesg.txt](https://drive.proton.me/urls/9AF36SJGJ8#nY6RNcrgoQzO) 
</details>

**Comment by dev-nis** [comment]
EDIT: a reboot always fixes this for a while (until it happens the next time)

**Comment by StollD** [comment]
This is a GNOME issue, see also https://github.com/linux-surface/linux-surface/issues/1173.

**Comment by dev-nis** [comment]
Ah okay, thanks! So switching to KDE will fix the issue, right?

**Comment by StollD** [comment]
Sorry for the delay, yes, using KDE *should* fix it. If it doesn't, its an issue with our touchscreen driver.

**Comment by dev-nis** [comment]
> This is a GNOME issue, see also #1173.
Thanks for this hint! I used the workaround provided there and it seems to work now.
Thank you very much!

**Comment by KhaaL** [comment]
I also have this issue (https://github.com/linux-surface/linux-surface/issues/1208) but for me the UI freezes aswell, so the clock stops updating. I can still use magic keys to reboot my surface though.
