### ISSUE TITLE
Kernel update 6.5.9-1 does not work

### ISSUE THREAD

**Issue by Banner24** [linux-surface/linux-surface#1287]
[Description of the bug or feature]
After downloading and restarting for the installtion of the kernel 6.5.9-1 from Gnome Software app the installation stops at 14% and reboots.

And the Update is still available on the Gnome Software app.

### Environment

- Hardware model: Surface Pro 7+
- Kernel version: 6.5.8-1.surface.fc39.x86_64
- Distribution: Fedora Linux 39 (Workstation Edition) x86_64

**Comment by StollD** [comment]
What happens when you run `sudo dnf update` in a terminal? For me it updated without an issue.

**Comment by Banner24** [comment]
"Last metadata expiration check: 1:44:32 ago on Thu 09 Nov 2023 05:46:26 PM CET.
Dependencies resolved.
Nothing to do.
Complete!"

Thats what i get.

**Comment by Banner24** [comment]
No idea why but i added : "sudo dnf config-manager \
    --add-repo=https://pkg.surfacelinux.com/fedora/linux-surface.repo"
again and now with the Update Command it works.

Thanks for your  time!
