### ISSUE TITLE
[NOTABUG] Not dual-booting to mitigate 64GB storage issues

### ISSUE THREAD

**Issue by jimjamz** [linux-surface/linux-surface#1297]
It is no longer possible to shrink a fresh Windows 10 or 11 installation enough on a 64GB Surface, to create a second partition that is an adequate size for a regular Linux distro installation.

A fresh Windows 10 install with nothing installed additionally, would only permit a shrinking of the original partition up to 19GB.
After allowing Windows Updates to get the latest firmware update, the shrinking option had been reduced to 8GB.

The install guide does not offer any information or advice on non-dual-boot installations.  I would like to be aware of any pitfalls or gotchas before attempting this, or whether it should even be attempted.

The only alternatives I'm aware of, and are not guaranteed to offer any improvement or indeed work, are to use tools like NTLite to remove components from the Windows ISO, manually insert the drivers required only by the Surface device, and re-install Windows 10 onto the Surface this way to hopefully minimise the storage space the installation accumulates, so that an adequately sized second partition can be created for dual-boot.
Any other suggestions or guidance are welcome.

**Comment by StollD** [comment]
> The install guide does not offer any information or advice on non-dual-boot installations. I would like to be aware of any pitfalls or gotchas before attempting this, or whether it should even be attempted.

In the step that tells you to shrink your Windows partition it says:

> This step can be skipped if you don't want to keep a Windows install.

We could amend that with something like:

> It is safe to remove your Windows installation. The only thing you need Windows for are automatic firmware updates. If you want to reinstall it you can use the surface recovery image [link here] or any standard Windows USB.

**Comment by jahed** [comment]
@StollD You mentioned "automatic" firmware updates specifically. Does that mean there's a way to manually install firmware updates without a Windows installation? The only manual method I've found is to download and run MSI files which I assume can only be done via Windows.
