### ISSUE TITLE
Accommodate rpm-ostree with modified package name

### ISSUE THREAD

**Issue by duke7553** [linux-surface/linux-surface#130]
rpm-ostree, which lies at the core of distros like Fedora Silverblue, currently only detects kernel packages with a package name set to one of several [pre-defined](https://github.com/coreos/rpm-ostree/blob/e6907d209b258388339b26e58a6da8cd022d1081/src/libpriv/rpmostree-core.c#L3776) values. (e.g. kernel) This behavior implies that, when installed as "kernel-surface", the current package is not detected as a kernel. To fix this, I and several others who would like to run Silverblue on our Surface devices would be very satisfied if a package with the uniform name is provided from the Fedora linux-surface repository. Hopefully, this is possible. I'm also very excited to hear more updates about the changes being upstreamed in v5.6 and v5.7. I couldn't find any when searching through the commits for your email. Maybe you can fill me in on this if you get a chance(?)

Anyways, great work!

Related bug: https://github.com/coreos/rpm-ostree/issues/1947
### Environment

- Hardware model: Surface Laptop 3 (Intel)
- Kernel version: All latest
- Distribution: Fedora Silverblue

**Comment by StollD** [comment]
If the surface kernel package would be named just `kernel` it would collide with the package containing the stock kernel. This means two things:
 - The package manager will remove stock kernels, which is something that we want to avoid if possible, in case we screw up so you have a unpatched kernel available that can still boot.
 - In case there are 3 kernels in the default fedora repositories which are newer than the surface kernel, the surface kernel will get removed. Same applies the other way around.

I don't know how much that affects silverblue, but it would definitly affect regular fedora in unpredictable ways. These issues might be solvable for silverblue, but that would mean that we would have to create 4 seperate builds for 4 seperate fedora versions, in 4 seperate repositories. And I don't really want to maintain that, sorry. 

I feel like the proper way to do this is to change rpm-ostree to detect kernel packages by having them provide something like `rpmostree(kernel)`. Then we could simply add that to our packages and they would work automatically.

**Comment by duke7553** [comment]
@StollD Thanks for the speedy response! I'll close this now
