### ISSUE TITLE
Upgrade from Fedora 38 to Fedora 39 fails

### ISSUE THREAD

**Issue by lunaisnotaboy** [linux-surface/linux-surface#1311]
Whenever I try to upgrade Fedora 38 to Fedora 39, the upgrade screen stalls at around 14%, then reboots back into Fedora 38 without an error.

### Environment

- Hardware model: Surface Pro 7
- Kernel version: Linux fedora 6.5.11-2.surface.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 21:44:05 UTC 2023 x86_64 GNU/Linux
- Distribution: Fedora 38

**Comment by lunaisnotaboy** [comment]
> try to run `sudo dnf update --setopt=protect_running_kernel=False` in a terminal I had the same problem. This fixed it for me

That's for upgrading the kernel. I'm talking about upgrading the entire system from Fedora 38 to Fedora 39.

**Comment by AlfredoCubitos** [comment]
after that you can upgrade to Fedora 39

**Comment by AlfredoCubitos** [comment]
ah, I also did an `sudo dnf --refresh upgrade`

**Comment by AlfredoCubitos** [comment]
after I did that I could press the upgrade button in Gnome and every thing works well. Before I had the same behavior as you described.
What is your error? 
My error was "protected kernel"

**Comment by qzed** [comment]
Maybe related to https://discussion.fedoraproject.org/t/f38-to-f39-dnf-system-upgrade-can-fail-on-raspberry-pi/92403? IIRC there where some issues with the hwclock of the Pro 7.

All I can say is that it worked fine on my SB2... so could be something device specific like that.

**Comment by lunaisnotaboy** [comment]
> Maybe related to https://discussion.fedoraproject.org/t/f38-to-f39-dnf-system-upgrade-can-fail-on-raspberry-pi/92403? IIRC there where some issues with the hwclock of the Pro 7.
> 
> All I can say is that it worked fine on my SB2... so could be something device specific like that.

Yeah, this was the fix. Should I close this?

**Comment by qzed** [comment]
Thanks for confirming. Yeah, let's close this.
