### ISSUE TITLE
surface laptop 5, not shutting down fully causing me to reset it by holding the power button down for a long time

### ISSUE THREAD

**Issue by RjManhas** [linux-surface/linux-surface#1314]
hello, i have a surface laptop 5 and from my understanding its not fully shutting down even after the screen turns off causing my having to reset it by holding down the power button. I understand there is ways of fixing them but i dont understand it, could someone please show me how to fix this bug?

**Comment by bentech4u** [comment]
HI

same here, did you find any solutions for this?

**Comment by RjManhas** [comment]
yes, once i installed the drivers and stuff using the pacman install script they have it fixed it for me
