### ISSUE TITLE
Touchscreen Scrolling in a Browser Window not working

### ISSUE THREAD

**Issue by n0valis** [linux-surface/linux-surface#1321]
While the normal scrolling via touchscreen in a system window works like expected, it doesn't in Firefox. It would only select text.
Is this behaviour "normal" like can't be addressed, configured, avoided? 
Or is there something that can be done to make it happen?

### Environment

    Hardware model: Surface Pro 9
    Kernel version: 6.6.6
    Distribution: LMDE6

**Comment by Lucrtz** [comment]
Scrolling should work when following https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#firefox
I am on Wayland and by setting `MOZ_ENABLE_WAYLAND=1` in `/etc/environment` touchscreen works as expected.

**Comment by n0valis** [comment]
Super. Thanks for that hint.
