### ISSUE TITLE
initramfs warnings: Possible missing firmware

### ISSUE THREAD

**Issue by Haennes** [linux-surface/linux-surface#133]
### Description of the bug
Whenever I execute the command update-initramfs, I get the following messages:

    update-initramfs: Generating /boot/initrd.img-5.5.10-surface
    W: Possible missing firmware /lib/firmware/i915/icl_dmc_ver1_09.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/tgl_dmc_ver2_04.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/skl_huc_2.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/skl_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/bxt_huc_2.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/bxt_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/kbl_huc_4.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/kbl_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/glk_huc_4.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/glk_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/kbl_huc_4.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/kbl_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/cml_huc_4.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/cml_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/icl_huc_9.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/icl_guc_33.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/ehl_huc_9.0.0.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/ehl_guc_33.0.4.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/tgl_huc_7.0.3.bin for module i915
    W: Possible missing firmware /lib/firmware/i915/tgl_guc_35.2.0.bin for module i915
    I: The initramfs will attempt to resume from /dev/nvme0n1p6
    I: (UUID=96a80b72-e77b-414f-b51b-ca51fdfd50cf)
    I: Set the RESUME variable to override this.

### Environment

- Hardware model: Surface Book 2
- Kernel version: Linux SB2-Mint 5.5.10-surface #1 SMP Thu Mar 19 11:12:58 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Linux Mint 19.3

### Solution proposed by me
I googled a bit and found the following website: https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915

My solution would be to get the updated firmware from the website above and copy it into the /lib/firmware/i915/ directory. 

Now my question: Is this the proper approach? And if so, do I need to remove the old firmware *.bin? Can I destroy my cpu by adding those firmware?

### dmesg
<details><summary>`dmesg` output</summary>

```
[dmesg.log](https://github.com/linux-surface/linux-surface/files/4368688/dmesg.log)
```

**Comment by qzed** [comment]
Those firmware files should be provided by the `linux-firmware` (sometimes also called `linux-firmware-nonfree`) package of your distribution. Installing that should normally fix this. If you've already installed that then it looks like this package is outdated and you might want to look for an updated one (or update your distribution if it's older). Generally adding firmware files won't break anything, and you shouldn't manually remove them.

**Comment by chasecovello** [comment]
Debian's (and derivatives like Mint's) firmware is older than the 5.5 kernel, which is what seems to cause this problem. If your hardware is working, the warning probably doesn't matter. However, it was annoying me, so I removed all the firmware-* packages except surface-ipts-firmware and manually installed the current firmware from kernel.org. ( ./copy-firmware.sh -v /lib/modules )

**Comment by qzed** [comment]
I see, in that case you should also consider switching to the LTS kernel (by installing `linux-headers-surface-lts`, `linux-image-surface-lts` and `linux-libc-dev-surface-lts` and configuring your bootloader accordingly).

**Comment by Haennes** [comment]
I tried to install the 4.19 alongside 5.5 and got some errors. Here is the installation stdout [4.19.log](https://github.com/linux-surface/linux-surface/files/4377526/4.19-lts.log)
Not sure what I*m missing.
Installing 5.5.10 I got the following errors [5.5.log](https://github.com/linux-surface/linux-surface/files/4377549/ls_install.log)

**Comment by qzed** [comment]
The 5.5 errors seem to come from some dkms packages. Those are likely not compatible with the 5.5. kernel. The dkms packages seem to build fine on the 4.19 kernel, but it looks like there's something wrong with your grub configuration file:
```
/usr/sbin/grub-mkconfig: 35: /etc/default/grub: i915.enable_psr=0: not found
```

**Comment by Haennes** [comment]
I installed the 4.19 kernel and it is running fine. However, whenever I run `update-initramfs -u` I still get the same messages for the 5.5 kernel as posted in my inital post. The first line still starts with:
`update-initramfs: Generating /boot/initrd.img-5.5.10-surface`
I'm not sure if this is the right behavior, since I'm still learning about linux kernels. Shouldn't the initramfs update now work for the 4.19 kernel?

By the way, you guys are doing a great job! Is there a way to support you guys?

**Comment by qzed** [comment]
By installing the LTS kernel you don't automatically uninstall the 5.5 kernel, so you have to do that manually if you want to get rid of it (you can also have it installed in parallel, just like your stock distribution kernel is still installed).

**Comment by Haennes** [comment]
I wouldn't mind having the 5.5 kernel around. 
Whenever I start my System, the default kernel that gets started is the one with the highest number i.e. 5.5. I have to manually select the 4.19 kernel every time I boot. Is there a way to change that behavior?

**Comment by qzed** [comment]
You should be able to set the default kernel in your bootloader config.

**Comment by Haennes** [comment]
Thank you very much!
