### ISSUE TITLE
surface pro 9 touchscreen and pen not working

### ISSUE THREAD

**Issue by dinamitebla** [linux-surface/linux-surface#1330]
Touchscreen and surface slim pen 2 not working

- Hardware model: surface pro 9
- Kernel version: Linux surface 6.6.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 14 Dec 2023 03:45:42 +0000 x86_64 GNU/Linux
- Distribution: Arch linux

dmesg output:
[dmesg.12.23.2023.txt](https://github.com/linux-surface/linux-surface/files/13759486/dmesg.12.23.2023.txt)

**Comment by StollD** [comment]
You are running a standard arch kernel (6.6.7-arch1-1) and not a surface kernel (6.6.6-arch1-1-surface).

The standard kernel does not include the drivers for the touchscreen so you need to use the surface kernel.

**Comment by dinamitebla** [comment]
My mistake, I thought the "Linux surface" in the uname -a output was the "surface" that the installation guide was referring to.

**Comment by dinamitebla** [comment]
Problem solved by switching to the correct kernel
