### ISSUE TITLE
Surface Pro 6 - Live USB won't boot

### ISSUE THREAD

**Issue by Tartarus6** [linux-surface/linux-surface#1335]
### My Goal
Dual booting Fedora 39 and Windows 11

### Research
My issue seems similar to  #1325, but **I've already fully disabled secure boot and TPM**, and it still won't even boot grub.

### Problem
Live USB won't boot. It just thinks for a bit then kicks me back into the UEFI settings. I've tried Ubuntu, Debian, and Fedora and none boot.

The only thing that I've gotten to work is installing **Ubuntu** through [Wubi](https://help.ubuntu.com/community/Wubi). That seems to work great! But It won't let me install the latest version (I could probably upgrade though), and I would much prefer to use Fedora or at least Debian.

**Issue with Wubi (already solved):** The download for `ubuntu-20.04.4-desktop-amd64.iso` always failed. Putting a separately downloaded copy of that file in the same directory as the Wubi exe fixed it.

I've tried the other installer images a few times, but only done extensive testing on the Fedora 39 workstation live image on a 32 GB flash drive, using Rufus to write the images. I've tried:
- Partitioning with **MBR**
  - Booting USB through UEFI just kicks me back into the UEFI after trying to boot.
- Partitioning with **GPT**
  - Same issue as above
- Writing in **ISO** mode
  - Same issue as above
- Writing in **DD** mode
  - Same issue as above
- Using a **Fedora 36** installer instead ([reasoning](https://discussion.fedoraproject.org/t/install-media-dont-boot-in-uefi-mode-on-certain-motherboards/71376))
  - Same issue as above
- Writing installer to disk through **UNetbootin**
  - Had to write installer to the `C: drive` even if a `D: drive` partition existed
  - Tried using my own Live Fedora 39 ISO
  - Tried using Fedora 30 through the built-in downloader (download always failed)
  - After installing, selecting the new option on the windows boot manager always yielded the "Windows failed to start" screen

### Environment
- Hardware model: **Surface Pro 6**
- Distribution: **Fedora**

### Help
Any help in getting Fedora installed would be greatly appreciated. If the solution is already here, I couldn't find it, please point it out if it does exist. Also, if there's some way of installing Fedora through Wubi, or another tool inside windows, that might work.

Thanks for reading this far,
Tar

**Comment by Tartarus6** [comment]
Maybe there's some way to replace my installed Ubuntu with Fedora? I can get a perfectly working Ubuntu image with grub loading up, maybe I could do that then somehow add a Fedora image and boot to it through grub. IDK, kinda grasping at straws.

**Comment by qzed** [comment]
Could be https://github.com/linux-surface/linux-surface/issues/1162.

**Comment by Tartarus6** [comment]
That seems to have worked. I installed fedora from a ventoy flash drive using the grub2 boot option and it worked after rolling back the firmware.

After a while the firmware re-updated and now fedora just boots a blank terminal with nothing but a cursor in the top left. I'll look into a way to prevent the firmware updating itself.

**Comment by Tartarus6** [comment]
It's all working now. The methods from #1162 solved the issue.
