### ISSUE TITLE
Nobara Install on Surface Pro 9

### ISSUE THREAD

**Issue by jojo2203** [linux-surface/linux-surface#1337]
Hello,

I tried to install Nobara Linux (image from 2023-12-30) on a Surface Pro 9. Linux is supposed to have a kernel optimized for Surface Pro. I turned off the security option in the BIOS but I only get to a black screen with the keyboard logo at the bottom right. I've also tried using a USB keyboard - unfortunately unsuccessful. I could enter boot options. Does anyone have any tips on which options make sense?

Thanks.

**Comment by qzed** [comment]
Could be https://github.com/linux-surface/linux-surface/issues/1162.

**Comment by jojo2203** [comment]
Unfortunately not very encouraging. I'll stick with Ubuntu for now. And wait and try again and again. thanks for the link.
