### ISSUE TITLE
Surface Go 3 - NixOS - nixos-rebuild switch fails due to patches/6.1/0009-surface-typecover.patch (?)

### ISSUE THREAD

**Issue by roukydesbois** [linux-surface/linux-surface#1339]
Hello!

It has been a few weeks now that nixos-rebuild switch fails, and it looks like it is due to patches/6.1/0009-surface-typecover.patch that was updated 3 weeks ago. It's my first issue, please tell me if you need more info!

### Environment

- Hardware model: Surface Go 3
- Kernel version: Linux nixos 6.1.62 #1-NixOS SMP PREEMPT_DYNAMIC Wed Nov  8 13:11:05 UTC 2023 x86_64 GNU/Linux
- Distribution: NixOS

<details><summary>`nixos-rebuild switch` output</summary>

```
[...]
applying patch /nix/store/lf6nr283p1vwm6gi5930sqmkmj614197-source/patches/6.1/0009-surface-typecover.patch
patching file drivers/usb/core/quirks.c
patching file drivers/pci/pci-driver.c
patching file drivers/pci/quirks.c
Hunk #1 FAILED at 6070.
1 out of 1 hunk FAILED -- saving rejects to file drivers/pci/quirks.c.rej
patching file include/linux/pci.h
error: builder for '/nix/store/9fnryfbmibipk2h8wlh3783kfm488nc3-linux-config-6.1.62.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/px9hfwahcvw1bp0q2b2hqiiy041f5p2p-linux-6.1.62.drv' failed to build
error: 1 dependencies of derivation '/nix/store/0cskpbag4mn92p0f1lf3l6nra98r7k47-nixos-system-nixos-23.11.2451.2d2ea8eab9e4.drv' failed to build


```

</details>

**Comment by StollD** [comment]
The 6.1 patches are based on 6.1.68 so that's what you need to apply them to. Newer or older versions are not guaranteed to work, because they might change some of the code around our changes, which prevents applying them.

**Comment by qzed** [comment]
FYI, you can check the `surface/*` tags in our [kernel repo](https://github.com/linux-surface/kernel/) for specific versions. Generally, the latest tagged version there should be the one from which the patches were generated.

**Comment by roukydesbois** [comment]
Hello!

I'm closing this issue as I have been able to use a more recent version of the kernel that allowed me to upgrade - it's all explained in https://github.com/NixOS/nixos-hardware/issues/825

Thanks for pointing me to the right direction!
