### ISSUE TITLE
Surface Stylus Vertical Calibration Issue - Ubuntu 22.04

### ISSUE THREAD

**Issue by jhuis003** [linux-surface/linux-surface#1345]
I'm using Ubuntu as my Surface Pro 6 OS and it works great! The only issue I have is with the stylus. In horizontal mode, it works as I need it. When the display is in vertical mode, the stylus acts like it's in horizontal mode. When I go up and down vertically, the mouse goes left and right and vice versa. 

I'm currently using Wayland. I also tried using Xorg and I have the same issue. Everything else functions properly: Multi-touch, horizontal stylus, auto-rotation. Perhaps there's a config file I can edit to reverse this? 

- Hardware model: Surface Pro 6
- Kernel version: 6.6.11-surface-1
- Distribution: Ubuntu 22.04

If you need anymore info I can provide it. This is my first submission.

**Comment by sphh** [comment]
Have you had a look at the issue #1199 and the issues referenced? Maybe there is a solution for you lurking in there?

**Comment by jhuis003** [comment]
> Have you had a look at the issue #1199 and the issues referenced? Maybe there is a solution for you lurking in there?

I've managed to get it working. Looks like the gnome "tablets" settings were messing it up. In dconf editor I went to tablets and it asked me to erase keys. Now it works on any rotation. Thanks for the link helped me down the rabbit hole!

**Comment by sphh** [comment]
Glad it worked!

Could you please list the keys which have to be deleted to help the next person with this problem? (And then you can close your first issue …) Thanks!

**Comment by jhuis003** [comment]
I cant replicate the issue but here's what I remember: 
Go into org/gnome/desktop/peripherals/tablets/ 
Three keys are in there. Delete everything in this folder and reboot.
