### ISSUE TITLE
SP8 Type Cover not detected during disk encryption

### ISSUE THREAD

**Issue by sheosi** [linux-surface/linux-surface#1350]
Hi! First and foremost, thanks for your hard work on making this wonderful computer work. Going into the subject, I've installed Fedora SilverBlue into my SP8, first from version 36 and then upgrading into 38, and after many tries of adding the necessary modules to load in initram I'm using Universal Blue's images (Fedora 39). However, my Type Cover isn't detected yet during disk encryption, I'm still filling this here since they are [using the drivers you recommend](https://github.com/ublue-os/surface/blob/main/system_files/shared/usr/etc/modules-load.d/ublue-surface.conf).

Thanks for your time!

### Environment

- Hardware model: Surface Pro 8
- Kernel version:Linux fedora 6.6.11-1.surface.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 13 12:33:32 UTC 2024 x86_64 GNU/Linux
- Distribution: Fedora Silverblue

**Comment by qzed** [comment]
@sheosi Any chance you can run `ls -al /sys/bus/surface_aggregator` in the initram to check which devices are actually showing up at that point?

**Comment by sheosi** [comment]
@efc64 I've tried adding them, I'm on silverblue, so I tried both the ways by UniversalBlue and also adding them through 
`rpm-ostree initramfs` (the way that's supposed to be done in Silverblue).

@qzed Wouldn't mind to try, do you know how I can instruct dracut to perform it? I could then translate that to  commands for SilverBlue.

**Comment by qzed** [comment]
@sheosi No idea, sorry. I think there should be some way to boot into a shell running in the initramfs. Some silly way to do that could be to change the root UUID to something random (it should then drop you in some emergency shell usually, unless that is disabled). But no idea if that's even possible in Silverblue/UniversalBlue.

**Comment by StollD** [comment]
You can also try adding `init=/bin/bash` or `rdinit=/bin/bash` to the kernel commandline in GRUB

**Comment by sheosi** [comment]
After so much time I finally got it, this is due to how Silverblue works, the howto is here:

[https://github.com/fedora-silverblue/silverblue-docs/pull/176/files](https://github.com/fedora-silverblue/silverblue-docs/pull/176/files)

Heres the TL;DR:

Add the kernel arg for luks to look into the tpm2 device

```sudo rpm-ostree kargs --append=rd.luks.options=tpm2-device=auto```


Enable the initramfs for systemd to load the appropiate module:

```sudo rpm-ostree initramfs --enable --arg=-a --arg=systemd-pcrphase```


Enroll the device into the tpm:

```sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 /dev/boot-device```


Some notes, the device needs to be enrolled when systemd restart, so you can enroll it before the other commands are done. Also, I've read that with a new update, the reroll might have to be redone and luks will ask for your password.
