### ISSUE TITLE
SP7 type cover and touchscreen latency on wake

### ISSUE THREAD

**Issue by dhelgerson** [linux-surface/linux-surface#1357]
[Description of the bug or feature]

when powering on or waking from sleep, both type cover and touchscreen take ~10s to be recognized after input, then is normal

### Environment

- Hardware model: Surface Pro 7, i5-1035G4
- Kernel version: 6.7.2-arch1-1-surface
- Distribution: ArchLinux
- DE: Gnome 45.3

<details>
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/14129675/dmesg.txt)
</details>

**Comment by sertonix** [comment]
If I remember correctly that was the same on windows (10). So not sure if it can be fixed.

**Comment by lcyf9102s** [comment]
I experienced the same condition on 7pro, but not that long, about only 3-4 sec.
also normal on win11.

**Comment by dhelgerson** [comment]
Y'know it's possible that it is present on windows but I never noticed due to it taking much longer to come up anyways.
