### ISSUE TITLE
Surface Pro 8 stuck at Surface logo

### ISSUE THREAD

**Issue by Developer-BB** [linux-surface/linux-surface#1376]
I have a Surface Pro 8 and have installed Ubuntu on it. It runs very well, but when I install this Kernel with the direction and reboot it, my Device only is stuck at the Surface Logo and I can only but from Windows. Every Linux Stick is stuck since the installation.
I have a Surface Pro 8 8GB ram 256GB storage i5

**Comment by Anthadeas** [comment]
I am having the exact same issue. I am hoping someone can comment with help.

**Comment by ruslanbay** [comment]
#1274 or #1162 
Please search on the issue tracker before creating one.

**Comment by Developer-BB** [comment]
I have found a Reddit Post. They said that when I use ventoy to create The USB-Stick, The surface boot. And it works
