### ISSUE TITLE
[SP8] Hardware buttons are not functional

### ISSUE THREAD

**Issue by vistis** [linux-surface/linux-surface#1384]
After updating to kernel version 6.7.6, the hardware buttons (both volume and power) don't do anything when pressed. This was not an issue before the update.

Additionally, GNOME also no longer recognizes them as keys.

### Environment

- Hardware model: Surface Pro 8 (Intel Core i7)
- Kernel version: Linux Surface 6.7.6-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Tue, 27 Feb 2024 19:53:26 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux

**Comment by StollD** [comment]
Can you try reloading the button module?

```
sudo modprobe -r soc_button_array
sudo modprobe soc_button_array
```

Arch changed the pinctrl drivers (which IIRC are required for the button driver) from built-in drivers to modules, so I wonder if this is a race condition. Maybe Arch puts the button driver in the initramfs but not the pinctrl drivers?

**Comment by vistis** [comment]
That fixed it! Thanks a ton!

**Comment by apmyplol** [comment]
Is there a way to make this fix persistent after rebooting without reloading the modules after reach reboot?

**Comment by qzed** [comment]
See https://github.com/linux-surface/linux-surface/issues/1392#issuecomment-1989558759
