### ISSUE TITLE
SL1: Fan driver not working

### ISSUE THREAD

**Issue by WardenScotland** [linux-surface/linux-surface#139]
I have the surface laptop 1 and have been using ubuntu on it for the past 3 months (embarrassing how I only just figured this out). I always wondered why the laptop got abnormally warm. Burn your fingers warm underneath. So I had a search for fan gui controls, and came across lm-sensors. Upon using the sensors command I got this log.
```
charlie@charlielaptop:~$ sensors
pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +42.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +100.0°C, crit = +100.0°C)
Core 0:        +46.0°C  (high = +100.0°C, crit = +100.0°C)
Core 1:        +46.0°C  (high = +100.0°C, crit = +100.0°C)
```
This shows there is no fan inuse, please can someone help me out.

**Comment by qzed** [comment]
AFAIK neither Windows nor the Linux kernel have direct control over the fans, which also means that the fan speed cannot be displayed. Instead, the fans seem to be controlled by the embedded controller (EC) on the device.

On the devices we've tested so far, the fan curve can be changed by setting a specific performance mode on the EC, which might (or might not) improve your situation. Usually this helps if the device is under higher load. We couldn't, however, validate that this also works on the SL1 (and thus have not enabled control for that) as we haven't had anyone to test it yet. If you want to help out, have a look at https://github.com/linux-surface/surface-aggregator-module/issues/18#issuecomment-592878771 and report back there.
