### ISSUE TITLE
KaOS (arch) - "linux-surface  linux-surface-headers  iptsd" cannot be upgraded due to unresolvable "initramfs", "pahole", "libcairomm-1.0.so=1-64"

### ISSUE THREAD

**Issue by brianidavide** [linux-surface/linux-surface#1391]
[Description of the bug or feature]
sudo pacman -S linux-surface linux-surface-headers iptsd
Password: 
resolving dependencies...
**warning: cannot resolve "initramfs", a dependency of "linux-surface"
warning: cannot resolve "pahole", a dependency of "linux-surface-headers"
warning: cannot resolve "libcairomm-1.0.so=1-64", a dependency of "iptsd"**
:: The following packages cannot be upgraded due to unresolvable dependencies:
      linux-surface  linux-surface-headers  iptsd

### Environment

- Hardware model: Surface Pro 4
- Kernel version: Linux davide-surfacepro4 6.6.16-1 #1 SMP PREEMPT_DYNAMIC Tue Feb  6 11:57:28 UTC 2024 x86_64 GNU/Linux
- Distribution: KaOS 2024

Operating System: KaOS (2024) 
KDE Plasma Version: 6.0.1
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.6.16-1 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i5-6300U CPU @ 2.40GHz
Memory: 3.8 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520
Manufacturer: Microsoft Corporation
Product Name: Surface Pro 4
System Version: 124000000000000000000000D:0B:08F:1C:03P:38

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by StollD** [comment]
For what its worth, I cannot reproduce this in an Arch container. `initramfs` should be provided by `makeinitcpio`, and cairomm hasn't been updated since October.

**Comment by brianidavide** [comment]
Thanks.
Changed distro to OpenSUSE
