### ISSUE TITLE
Surface Laptop 1: Keyboard sometimes breaks on boot

### ISSUE THREAD

**Issue by Jelles** [linux-surface/linux-surface#1400]
I'm experiencing intermittent issues with my internal keyboard on my system running KDE Plasma. Occasionally, the internal keyboard fails to respond, resulting in an inability to input keystrokes. When this issue occurs, restarting the system resolves the problem temporarily, but the issue may reoccur after some time. The issue only happens when I boot my system, so either my keyboard works on boot or I have to restart and hope for it to work this time.

### Environment
 - KDE Plasma: (plasmashell 6.0.1)
- Hardware model: Surface Laptop 1
- Kernel version: Linux archlinux 6.7.9-arch1-1-surface #1 SMP PREEMPT_DYNAMIC Sat, 09 Mar 2024 20:28:40 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux

dmesg output was too long: https://pastebin.com/Bp9dzKR2

**Comment by ADernikas** [comment]
Please help I have the same problem

**Comment by qzed** [comment]
Possibly related to #1271 and #1319

**Comment by qzed** [comment]
This should be fixed. Please let me know if the issue still occurs.
