### ISSUE TITLE
After installing ubuntu once, can no longer boot from ubuntu usb bootloader

### ISSUE THREAD

**Issue by Pathsis** [linux-surface/linux-surface#1401]
I installed ubuntu once on my surface laptop studio, and after that I rebooted and could not log into ubuntu, and, I could no longer see ubuntu boot on the USB bootloader, selecting to boot from USB, it only stayed at the Microsoft logo.

I tried installing it on a surface laptop 3 and it did the same thing. When installing, I chose to coexist with windows and set a secure boot password for installing 3rd party drivers.

My guess is that the problem may be in installing the 3rd party driver. Because the first time I installed it, I did not install the 3rd party driver, and I was able to continue installing ubuntu after that. now I can no longer see ubuntu from the USB bootloader, automatically I try to install the 3rd party driver.

What's going on here? Much appreciated.

- Hardware model: surface laptop studio
- Kernel version: 
- Distribution: ubuntu 22.04.4

**Comment by ChrisRichner** [comment]
Hi

Maybe https://github.com/linux-surface/linux-surface/issues/1274 helps.

**Comment by Pathsis** [comment]
Thank you, after research, I have successfully installed Linux on my SLS. Thank you very much! I was already so desperate that I was preparing to switch to Thinkpad.

**Comment by ChrisRichner** [comment]
Your´re welcome, glad I could help. I´ve bought a new Surface Pro 9 and went trough the same struggle a few days ago.

Guess you can close the issue now, right?
