### ISSUE TITLE
SP9 w Ubuntu 22.04 WiFi dropouts

### ISSUE THREAD

**Issue by ChrisLPJones** [linux-surface/linux-surface#1405]
Iv just installed Ubuntu on my Surface Pro 9 along with the kernel from here following the instructions.

Kernel is loaded and everything is working mostly.

My issue is the wifi dropped out after a minute or two from fresh boot. 

After I login Il ping 1.1.1.1 and after a little I stop getting responses.

I noticed in my dmesg I get this warning right as I loose connection 

Ignoring NSS change in VHT Operating Mode Notification from 04:9f5:b:ea:24 with invalid nss 3)

The wifi stays connected to the access point but I loose all connections outside of that.

**Comment by zash1958** [comment]
Have the same using my home WiFi. After switching to the 5G Wlan here solves all problems like this. The 5G is strong in my office and so no further problems up to now

**Comment by CrispyJonesDev** [comment]
Did you experience the problem when connecting to Wifi that was set up with 2.4 and 5g under the same ssid?

I never have this issue connecting to my work wifi that is 2.4 but my home wifi is set to server 2.4 and 5 together on the same ssid.

**Comment by zash1958** [comment]
I have the 2.4G and 5G on separate names. Also other devices have had a problem with the same SSID for both
