### ISSUE TITLE
Can I delete the extra Linux kernel?

### ISSUE THREAD

**Issue by Pathsis** [linux-surface/linux-surface#1408]
Preserving other  linux kernels will result in a failure to install the NVIDIA driver, which always takes effect in other linux kernels instead of linux-surface kernerl.

**Comment by zash1958** [comment]
I have no nVidia card and deleted all non-surface kernels. All runs OK

**Comment by Pathsis** [comment]
Thanks, I realized that I need to  completely remove the other kernels **firstly** and keep only the surface kernel to successfully install the drivers for the Nidia graphics card via `sudo ubuntu-drivers install`. I hope this is useful for others.
