### ISSUE TITLE
120Hz on Surface Pro 8 (128GB/8GB/11th i5)  / Debian  Working?

### ISSUE THREAD

**Issue by tabletseeker** [linux-surface/linux-surface#1411]
Hello, I just wanted to ask if 120Hz is available and working with the latest kernel for Debian.

Kind regards!

**Comment by TheSnowfield** [comment]
As a Pro 9 user, I can tell you it's working perfectly on the Debian for its 120Hz display.
![image](https://github.com/linux-surface/linux-surface/assets/17957399/88c47b3a-645d-49fd-b95b-cd6b18eee51e)

**Comment by LightJack05** [comment]
Yep, can confirm it works on the SP8 (i7/16G/256G).

**Comment by FearlessSpiff** [comment]
> As a Pro 9 user, I am happy to tell you that the kernel perfectly works on the Debian with its 120Hz display. ![image](https://private-user-images.githubusercontent.com/17957399/318278837-88c47b3a-645d-49fd-b95b-cd6b18eee51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MjEzOTUsIm5iZiI6MTcxNTcyMTA5NSwicGF0aCI6Ii8xNzk1NzM5OS8zMTgyNzg4MzctODhjNDdiM2EtNjQ1ZC00OWZkLWI5NWItY2Q2YjE4ZWVlNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDIxMTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MzJmMTRjZGQzMTEzZDk0ZjMyNzg2YTRmMzczNmQwNDBiMzhkY2RkMmZlM2RhODRmNWMwNTE0NTMwZDA2YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MfVyha4Ll94_KJF38rxTk5bkU86hOfA_RhZR6VTYGGU)

Is this with USB-C to HDMI? I just get a black screen on Arch with the latest kernel...

**Comment by tabletseeker** [comment]
> As a Pro 9 user, I am happy to tell you that the kernel perfectly works on the Debian with its 120Hz display. ![image](https://private-user-images.githubusercontent.com/17957399/318278837-88c47b3a-645d-49fd-b95b-cd6b18eee51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4ODE2ODUsIm5iZiI6MTcxNTg4MTM4NSwicGF0aCI6Ii8xNzk1NzM5OS8zMTgyNzg4MzctODhjNDdiM2EtNjQ1ZC00OWZkLWI5NWItY2Q2YjE4ZWVlNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE3NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTQyMTZjMWQzMDJjYmNmMWEwNjdmY2QyZDMxN2NhNDM2NDk2ZmFhYjMxMTVhNTY4MjFiMDI4MjcwMWYxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sAppJ_4m4xJBJrndb6_7e4B8SIgUhkw2gjPNCvhPFo)

Are there any significant technical differences between the Surface Pro 8 and 9 screens?

**Comment by TheSnowfield** [comment]
> Is this with USB-C to HDMI? I just get a black screen on Arch with the latest kernel...

Yes, this USB-C can to HDMI. I bought a Type-C dock station, it has an HDMI port, but I have never tested if it works on Linux. I'll be happy to walk on this problem tonight.

**Comment by TheSnowfield** [comment]
> > As a Pro 9 user, I am happy to tell you that the kernel perfectly works on the Debian with its 120Hz display. ![image](https://private-user-images.githubusercontent.com/17957399/318278837-88c47b3a-645d-49fd-b95b-cd6b18eee51e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4ODE2ODUsIm5iZiI6MTcxNTg4MTM4NSwicGF0aCI6Ii8xNzk1NzM5OS8zMTgyNzg4MzctODhjNDdiM2EtNjQ1ZC00OWZkLWI5NWItY2Q2YjE4ZWVlNTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDE3NDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTQyMTZjMWQzMDJjYmNmMWEwNjdmY2QyZDMxN2NhNDM2NDk2ZmFhYjMxMTVhNTY4MjFiMDI4MjcwMWYxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9sAppJ_4m4xJBJrndb6_7e4B8SIgUhkw2gjPNCvhPFo)
> 
> Are there any significant technical differences between the Surface Pro 8 and 9 screens?

They're the same things I guess.

**Comment by TheSnowfield** [comment]
> Is this with USB-C to HDMI? I just get a black screen on Arch with the latest kernel...

Oops, I got a black screen too. The screen has been identified, but got no graphics on the screen.
> Linux shizuku 6.8.8-surface-1 #1 SMP PREEMPT_DYNAMIC Tue Apr 30 09:10:33 UTC 2024 x86_64 GNU/Linux

![Snipaste_2024-05-20_11-01-33](https://github.com/linux-surface/linux-surface/assets/17957399/ed887635-7fb1-4dff-a351-e38cabdd588c)

**Comment by tabletseeker** [comment]
> Oops, I got a black screen too. The screen has been identified, but got no graphics on the screen.

With a USB-C to HDMI adapter it works if you choose the highest refresh rate and resolution with xrandr.
