### ISSUE TITLE
Touchscreen SP4 issue

### ISSUE THREAD

**Issue by kisisten** [linux-surface/linux-surface#143]
Hi, I've installed the lts kernel from the repository for Debian Buster OS, and all the surface related packages, but I'm unable to get the touchscreen working.
Thanks,
A

**Comment by qzed** [comment]
If you're on the 5.5 kernel, see https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#touch-controls. Specifically:

> - The latest kernel (5.5+) breaks multi-touch support. You'll need to install either a 4.19 (LTS) kernel or a 5.3 series kernel if you want to use multi-touch (note that 5.3 is EOL, meaning you won't receive any security updates; 4.19 is a long-term-support release that will continue to receive security updates until end of 2020). The LTS kernel can be installed via the `-lts` suffix on the kernel packages (e.g. `linux-image-surface-lts`, `linux-headers-surface-lts`, and `linux-libc-dev-surface-lts` on Debian). If you choose to go with the 5.3 kernel, you'll have to manually download and install a [5.3 kernel release](https://github.com/linux-surface/linux-surface/releases/tag/v5.3.18-1).
> - **The latest kernel works with either single-touch OR pen support (you have to choose one or the other). By default pen support is enabled.** If you want to switch to single-touch create a file under `/etc/modprobe.d/ipts.conf`:
>   ```
>   options ipts singletouch=y
>   ```

**Comment by kisisten** [comment]
qzed, I'm using the LTS kernel 4.19.x not on 5.5

**Comment by kisisten** [comment]
The only kernel that works for me is the Jakeday 5.1.11 btw. I've tried the linux-surface kerlnel 5.3 as mentioned in the paragraph you've pasted, but still no touchscreen function.

**Comment by kitakar5525** [comment]
You seems to be affected by this issue (feedback issue that is remain unresolved for a long time on SB1/SP4): https://github.com/linux-surface/linux-surface/wiki/Known-Issues#v419-ipts-touchscreen-driver-stops-working-sp4-and-sb1

**Comment by kisisten** [comment]
Thanks, that did fix the issue.

**Comment by kisisten** [comment]
BTW my version is >> MSHW0078:00

**Comment by kitakar5525** [comment]
Thanks for letting me know the hardware id :)
