### ISSUE TITLE
(debian) kernel 6.8.8-surface-1 + grub enters in boot loop

### ISSUE THREAD

**Issue by nouknouk** [linux-surface/linux-surface#1434]
Hi,

I'm a user of surface-linux on my surface pro 9.

The latest version, `linux-[headers|image]-6.8.8-surface-1` doesn't boot, whereas the previous version  `linux-[headers|image]-6.8.6-surface-1` runs well.

After showing up the grub welcome screen, when I choose kernel 6.8.8, the system show a black screen for 1-2 seconds, then reboots, showing briefly the (black & white) windows logo, then grub again.

Notes:
- kernel 6.8.6 startup is ok.
- windows startup is ok
- secure boot enabled ; key enrolled a while ago, following the [wiki / secureboot](https://github.com/linux-surface/linux-surface/wiki/Secure-Boot#using-the-provided-secure-boot-certificate) page.
- Im' using apt package repository for kernel updates:
```
$ cat /etc/apt/sources.list.d/linux-surface.list 
deb [arch=amd64] https://pkg.surfacelinux.com/debian release main
```
- I'm using linux mint alongside original windows, using grub:
- grub `2.06-2ubuntu7`
- grub-efi-amd64-signed `1.187.6+2.06-2`

### Environment

- Hardware model: Surface Pro 9 ; Core i5 I5-1245U ; 16GB RAM ; 256GB SSD

- Kernel version: cannot get exact version for 6.8.8 as it's not booting, but previous (working) is `Linux nouksurface 6.8.6-surface-1 #1 SMP PREEMPT_DYNAMIC Tue Apr 16 12:48:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`)

- Distribution: Linux Mint 21.1 Mate (x64)

- /boot/[config-6.8.8-surface-1.txt](https://github.com/linux-surface/linux-surface/files/15209151/config-6.8.8-surface-1.txt)

```
$ diff /boot/config-6.8.6-surface-1 /boot/config-6.8.8-surface-1 
3c3
< # Linux/x86 6.8.6 Kernel Configuration
---
> # Linux/x86 6.8.8 Kernel Configuration
556,558c556
< # CONFIG_SPECTRE_BHI_ON is not set
< # CONFIG_SPECTRE_BHI_OFF is not set
< CONFIG_SPECTRE_BHI_AUTO=y
---
> CONFIG_MITIGATION_SPECTRE_BHI=y
```

Best regards.

**Comment by nouknouk** [comment]
nevermind: after a full fresh reinstall of minux mint `21.2`, kernel `6.8.8` is running well.

The root cause was probably elsewhere.

**Comment by buddyabaddon** [comment]
I am seeing this same issue on a Surface Laptop 5.

Ubuntu 22.04.4 LTS
Secure Boot
Disk encryption enabled (requiring boot unlock key)

Kernel 6.8.6 boots fine
Kernel 6.8.8 presents the boot loop behavior described in this issue

I have not wiped and fresh re-installed like @nouknouk.

I too am relying on the same apt package repo and config. Perhaps there is something wrong in the way the kernel package is installed on an existing system vs. fresh install...
