### ISSUE TITLE
Can't get past BusyBox (initramfs) when selecting the linux-surface kernel

### ISSUE THREAD

**Issue by santialur** [linux-surface/linux-surface#1464]
Hi Everyone, I have followed all the instructions on this link: https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup
and guided myself by reading this previous issue: https://github.com/linux-surface/linux-surface/issues/1274
In order to boot the linux-surface kernel (6.8.8-surface-1), but cannot boot into it. It always leads me to a command line "BusyBox". 

On GRUB, I can select my original distro kernel (boots correctly, but doesn't have a battery indicator) and the linux-surface recovery mode, and then the last thing the console spits out is:
```
Gave up waiting fon root file-system device. Common problems:
- Boot args (cat /proc/cmdline)
- Check rootdelay= (did the system wait long enough?) .
- Missing modules (cat /proc/modules: ls /dev)
ALERT! UUID=8093e2a9-b742-47c8-b955-8775cb081082 does not exist.
Dropping to a shell
BusyBox V1.30.1 (Ubuntu 1:1.30.1-7ubuntuB) butIt-in shell (ash)
(intramfs) 
```
Some context:
* I have tried reinstalling Linux Mint from scratch and the same thing happened.
* The UUID shown above is correct, or at least the same shown when I boot into the generic kernel.

### Environment

- Hardware model: Surface Laptop Go 3
- Kernel version: **6.8.8-surface-1** (can't boot) **5.15.0-76-generic** (boots)
- Distribution: Linux Mint 21.2 

 ```
santialur@sg3:~$ blkid
/dev/sda2: UUID="8093e2a9-b742-47c8-b955-8775cb081082" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="a4a1f2c1-b7e0-44cc-99d2-0cd70c23fcb3"
/dev/sda1: UUID="3790-3AC0" BLOCK_SIZE="4096" TYPE="vfat" PARTLABEL="EFI System Partition" PARTUUID="ba029747-10eb-43d4-a755-e243d4d89bad"
```

EDIT: 
Added blkid output

**Comment by qzed** [comment]
I think this should have been fixed by c67bbcf9bfa5541fe6053f2141c8be878c5592ea.
