### ISSUE TITLE
surface pro 9 16 GB 1 Terabyte virtual keyboard and camera not work on kali linux 2024.2 

### ISSUE THREAD

**Issue by mabdiyan** [linux-surface/linux-surface#1475]
Hello, thanks for your good program, kernel image or any name which has 

i have some problems 

virtual (touch) keyboard dose not work on kali linux 2024, 

also both front and back camera not work on kali linux 2024.2 

also i think face detection not work on this kali version or all other linux version 

please solve it

**Comment by mabdiyan** [comment]
also sometimes after use from touch screen, my system was crash

pen work good in your kernel version but touch with hand not work so good

**Comment by mabdiyan** [comment]
howdy github repo claim it able to present a service like microsoft face detection or hello face time detection 

i test it on another asus laptop but it dose not work correctly

that repo was so old and not update correctly, maybe your could use it, fork it or ... into your repo and update it for microsoft surfaces 

thanks a lot ............

**Comment by StollD** [comment]
Kali Linux is supposed to be installed in a VM or on a Live USB that you can boot when you are doing pentesting. It is not a general purpose distribution. It most likely doesn't even *have* a virtual keyboard.

Cameras are unsupported on Surface Pro 9, as you can see on the wiki: https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features
