### ISSUE TITLE
Solus?

### ISSUE THREAD

**Issue by Catley94** [linux-surface/linux-surface#149]
This is a question, not an issue, I do apologise for creating a new issue but I'm curious.

I want to know if this is compatible with Solus? As far as I understand Solus isn't built on anything like debian, fedora etc. according to Distro watch: https://distrowatch.com/table.php?distribution=solus

Has anyone been able to get this to work on Solus?

Thanks,
Sam

**Comment by Catley94** [comment]
Don't worry, I like the plasma desktop environment, so I've gone for Kubuntu which will work, sorry. Please feel free to delete this ticket.

**Comment by qzed** [comment]
To answer the original question: There shouldn't be anything specific stopping this from working on Solus, you'd just have to package it accordingly. I'm not aware of anyone having done that though.
