### ISSUE TITLE
[SurfacePro9][NixOS] Keyboard doesn't work for unlock of encrypted drive at boot, even though it seems modules are loaded

### ISSUE THREAD

**Issue by dev-nis** [linux-surface/linux-surface#1491]
[Description of the bug or feature]
In the first phase of boot, the system asks for the password for my encrypted boot drive. Here, the attached TypeCover-keyboard doesn't work even though it seems that the needed modules are loaded (see Screenshot).

![20240713_162753](https://github.com/user-attachments/assets/902a7ba5-c4fa-4a77-aae4-00fa1a6ebbda)

My configuration for loading the modules looks like this:
`boot.initrd.kernelModules = [ "surface_aggregator" "8250_dw" "surface_hid_core" "surface_hid" "surface_aggregator_registry" "surface_aggregator_hub" "surface_aggregator" "intel_lpss" "intel_lpss_pci" ];`

### Environment

- Hardware model: Surface Pro 9
- Kernel version: 6.9.3 #1-NixOS SMP PREEMT_DYNAMIC
- Distribution: NixOS 24.05

**Comment by jf049** [comment]
These are drivers I add to my initramfs to unlock my drive with LUKS.
`surface_aggregator surface_battery surface_charger surface_fan surface_aggregator_hub surface_aggregator_tabletsw surface_temp surface_platform_profile surface_hid_core surface_hid surface_aggregator_registry intel_lpss intel_lpss_pci pinctrl_tigerlake`
Can you try these ones?

**Comment by dev-nis** [comment]
Wow that worked! I followed the official instructions on the wiki somewhere, but somehow some of the modules you have aren't listed there. Thanks for your help!
