### ISSUE TITLE
surface-control obsolete for just setting power modes?

### ISSUE THREAD

**Issue by tabletseeker** [linux-surface/linux-surface#1498]
Hi, I just want to change power modes on my SP8 and wonder if I even need to install surface-control for that.

As far as I can tell all that's needed is to echo any given power-mode to /sys/firmware/acpi/platform_profile.

A little script like this should also do the trick right?

```
case "$1" in		 
l) mode="low-power"
;;	 
b) mode="balanced"
;;	 
p) mode="performance"
;;
esac

echo "$mode" > /sys/firmware/acpi/platform_profile
```

Thank you for your work btw, you guys are godsend.

**Comment by qzed** [comment]
Correct, that works as well. You could also use something like power-profiles-daemon, which is integrated into the Gnome Desktop and should also set the profile.
