### ISSUE TITLE
6.10 rebase request

### ISSUE THREAD

**Issue by GloriousEggroll** [linux-surface/linux-surface#1510]
In nobara we skipped 6.9 due to some amdgpu related regressions (causing hangs), we are wanting to ship 6.10 but the only remaining patchset holding us back is the linux-surface patches. I tried rebasing myself but it seems some changes were done in ithc-dma.c causing vmap and vunmap that I can't figure out.

**Comment by quo** [comment]
See https://github.com/quo/ithc-linux/commit/42057e411420831e925892a642e9b23bef974869

**Comment by GloriousEggroll** [comment]
> See [quo/ithc-linux@42057e4](https://github.com/quo/ithc-linux/commit/42057e411420831e925892a642e9b23bef974869)

thanks that fixed the issue I was hitting!

**Comment by qzed** [comment]
Sorry, I didn't get around to it on the weekend. It's planned for the coming one though.

**Comment by quo** [comment]
@qzed For 6.10, can you maybe update ithc to master instead of only adding the build fix? This will enable SL6/SP10 support, and fix some DMA errors on SP8. (SL6 also requires iptsd changes for full support, but it won't hurt to have ithc updated already.)
Let me know if you'd prefer I make a pull request.

**Comment by qzed** [comment]
@quo I was planning on doing that actually :)

**Comment by quo** [comment]
Thanks!
Actually I misremembered, it's the SLS2 that still needs some IPTSD changes, SL6 should be fine with just the ithc update.

**Comment by qzed** [comment]
Patches for v6.10 have been added in https://github.com/linux-surface/linux-surface/commit/d44187ae85db717bb9ad91931ec21ff3bd83f5e6. Or https://github.com/linux-surface/kernel/commits/v6.10-surface if you prefer the kernel tree.
