### ISSUE TITLE
Surface Go - Hibernation or suspend to ram

### ISSUE THREAD

**Issue by kyvodul** [linux-surface/linux-surface#1515]
Hello,

I am unable to use "hibernate" or "suspend to ram" with a surface go, is it a hardware limutation or a softaware problem ?
"cat /sys/power/mem_sleep" return only "s2idle", I created swap and update all I can but without success.
Hope anyone can help.

- Hardware model: Surface GO 4
- Distribution: Zorin OS (Ubuntu 22 LTS)

**Comment by qzed** [comment]
Hibernation should work, but might need to be configured.

Suspend-to-ram, on the other hand, is disabled by the ACPI firmware of the device. I think people have tried to enable it again in some other issue, but that requires patching of the ACPI tables (i.e., not something that we can do from the kernel/software side alone).

**Comment by kyvodul** [comment]
Suspend to ram is a great option but hibernation could be an alternative in my case.

I tried to configure it without success, swap is there, grub is configured but ot is still not work. Any clue to configure it ?

Le 4 août 2024 à 21:36, Maximilian Luz ***@***.***> a écrit :

﻿

Hibernation should work, but might need to be configured.

Suspend-to-ram, on the other hand, is disabled by the ACPI firmware of the device. I think people have tried to enable it again in some other issue, but that requires patching of the ACPI tables (i.e., not something that we can do from the kernel/software side alone).

**Comment by qzed** [comment]
> Any clue to configure it?

Unfortunately no, sorry. I've never really used it. Maybe someone else can help you here.

**Comment by kyvodul** [comment]
I hope anyone can help.

Thanks for your help.

Le 5 août 2024 à 00:14, Maximilian Luz ***@***.***> a écrit :

﻿

Any clue to configure it?

Unfortunately no, sorry. I've never really used it. Maybe someone else can help you here.

**Comment by jyap808** [comment]
Hibernate works fine on my SB3 but I'm running Arch. I put my notes up here: https://julianyap.com/pages/2024-04-04-1712257725/#hibernate

Should close this Issue as it's more a generic set up of Hibernation one.

**Comment by kyvodul** [comment]
I asked because I thought it could be a "surface issue", I will check your link.
