### ISSUE TITLE
SL2 won't boot in linux-surface kernel after update.

### ISSUE THREAD

**Issue by CoolDude5385** [linux-surface/linux-surface#1517]
Environment

- Hardware model: Surface Laptop 2 (Intel)
- Kernel version: 6.9.12
- Distribution: Fedora 40

My SL2 had shut down while installing updates for G++, GCC, etc. and also the 6.9.12 kernel that just came for Fedora. My device works on the regular (non-surface) kernel, but the recovery option doesnt work, neither does the 6.9.12 surface kernel.

Edit: removed linux-surface kernel and reinstalled

**Comment by qzed** [comment]
Do you mean that your SL2 crashed/shut down during the update? In that case, you can try reinstalling the packages (using `dnf reinstall ...`).
