### ISSUE TITLE
Stucks in Bootlogo after update 

### ISSUE THREAD

**Issue by kwai-chang** [linux-surface/linux-surface#1533]
I can not give more details to Kerenel because no systemstart is possible, just can chose which kernel sholud be boot.
Standard Kernel boots, but without functionality of mouse, keyboard
Surface Kernel stucks while booting before bootlogo is fully loaded

[Description of the bug or feature]

### Environment

- Hardware model: 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by JJ-82** [comment]
6.10 kernel gave me problems to. I got a black screen with message: "Bluetooth: hci0: Malformed MSFT vendor event: 0x02"

From boot options was able to load the previous one. I purged the 6.10-version.

**Comment by kwai-chang** [comment]
It is not 6.10.3, there must be something in package, without upgrade of package, system works. Only with upgrade to all actual packages, by reboot hangs on bootlogo from debian.

**Comment by kwai-chang** [comment]
Find out package causing systemhang
mx-debian-firmware 23.03.01mx23 .> 24.08.10mx23
![Bildschirmfoto_2024-08-17_10-02-43](https://github.com/user-attachments/assets/68e8d169-3e88-45b1-be92-acec594c8974)

**Comment by qzed** [comment]
Any chance that either blacklisting ipu6 modules (like [here](https://github.com/linux-surface/linux-surface/issues/1516#issuecomment-2269662870)) or v6.10.5 fixes this?

**Comment by kwai-chang** [comment]
Blacklist the drivers, edit (or add) /etc/modprobe.d/blacklist.conf and add

blacklist intel-ipu6
blacklist intel-ipu6-isys

Booting is back, everything runs smooth
also with driver package mx-debian-firmware 24.08.10

**Comment by kwai-chang** [comment]
Blacklist the drivers, edit (or add) /etc/modprobe.d/blacklist.conf and add

blacklist intel-ipu6
blacklist intel-ipu6-isys

Booting is back, everything runs smooth
also with driver package mx-debian-firmware 24.08.10
