### ISSUE TITLE
kernel 6.10.3 causes invalid opcode traps unless GDS mitigation is disabled

### ISSUE THREAD

**Issue by tormodvolden** [linux-surface/linux-surface#1534]
[sorry for double-posting, also at https://github.com/linux-surface/kernel/issues/156]

6.10.3-surface-1 kernel severely broken, causing invalid opcode traps.

Confirmed on Surface Book,  Surface Pro 4, Surface Go 3, etc, across many distributions, in other reports.

Other users, please run `grep traps /var/log/syslog` to see if you are affected.

In my case it is always in libgnutls.so but also libxul.so was reported in #1529.

Some examples:
```
https[4515] trap invalid opcode ip:7bd64c2a03ca sp:7ffeb94d9c80 error:0 in libgnutls.so.30.31.0[1583ca,7bd64c179000+129000]
pool-fwupdmgr[5068] trap invalid opcode ip:7e75c309663e sp:7e75be1fedc0 error:0 in libgnutls.so.30.31.0[15363e,7e75c2f74000+129000]
wireplumber[1026] trap invalid opcode ip:733ef036863e sp:733ee9ffe9c0 error:0 in libgnutls.so.30.31.0[15363e,733ef0246000+129000]

```

Likely the same issue: #1526, #1529

It is not related to the ipu6 issue (ipu6 module blacklisting doesn't help here) of freak007 in #1516 but maybe to the other issues, e.g. the OP's, in that issue report.

For other people to collect most relevant information in one go:
`sudo dmesg | egrep -iw "AVX|GDS|microcode|family:"`

To get the CPU signature that Intel often refers to in their documenation:
`sudo modprobe cpuid && iucode_tool --scan-system`

**Comment by tormodvolden** [comment]
@qzed please let me know if you need more logs.

**Comment by tormodvolden** [comment]
The same happens (but maybe to a lesser degree) with a stock 6.10.3 kernel (6.10.3-061003-generic from https://kernel.ubuntu.com/mainline/v6.10.3/).

**Comment by tormodvolden** [comment]
From a similar (older) bug report (https://bugs.launchpad.net/bugs/2031093) it seems to be related to missing microcode:
```
$ sudo dmesg|grep -i avx
[    0.136540] GDS: Microcode update needed! Disabling AVX as mitigation.
[    0.136542] GDS: Mitigation: AVX disabled, no microcode

```

**Comment by tormodvolden** [comment]
Installing the package intel-microcode (initramfs gets rebuilt) doesn't help:
```
$ sudo dmesg|grep -i microcode
[    0.121823] SRBDS: Mitigation: Microcode
[    0.121833] GDS: Microcode update needed! Disabling AVX as mitigation.
[    0.121835] GDS: Mitigation: AVX disabled, no microcode
[    0.981247] microcode: Current revision: 0x000000f0
[    0.981250] microcode: Updated early from: 0x000000ea

```
This is on Ubuntu 22.04, so the version of intel-microcode is 3.20240514.0ubuntu0.22.04.1.

**Comment by tormodvolden** [comment]
A workaround is to disable the "GDS" mitigation, by adding `gather_data_sampling=off` to the kernel command line.
```
$ sudo dmesg|grep -i microcode
[    0.121547] SRBDS: Mitigation: Microcode
[    0.121548] GDS: Vulnerable: No microcode
[    0.973064] microcode: Current revision: 0x000000f0
[    0.973066] microcode: Updated early from: 0x000000ea
```
The AVX instruction is no longer disabled, and there are no invalid opcode traps any more.

Note this leaves your computer vulnerable to GDS attacks, see e.g. https://wiki.ubuntu.com/SecurityTeam/KnowledgeBase/GDS_Downfall

**Comment by horvathcsabalaszlo** [comment]
I opened the issue "After upgrading, touch inputs are only handled on the top of the screen #1521"
Tested with kernel 6.9, but the issue is the same. :(

**Comment by tormodvolden** [comment]
Alright, that seems not related then even if it also had "invalid opcode" errors.

**Comment by sjwk** [comment]
I've been pulling my hair out with this issue - my first foray into installing Linux (KDE Neon) onto a surface device and it was playing up from the first boot, so was convinced I'd missed some crucial step.  The most obvious symptom that I found was that apt was erroring out talking to https repos.  From there found the gnutls opcode trap and that AVX was being disabled due to not loading CPU microcode.  Felt it more likely to be a surface issue than Neon, as it's kernel related and the surface setup replaces kernel.  Will assume then that it's not my error doing the install and wait :-D

**Comment by tormodvolden** [comment]
@sjwk did you try gather_data_sampling=off ?

**Comment by sjwk** [comment]
> @sjwk did you try gather_data_sampling=off ?

Not yet, but I will.

**Comment by tormodvolden** [comment]
Your Surface Pro 4 should have a 06-8e-09 model CPU so there is a microcode update for it in intel-microcode 20240813. I'd suggest you install the Ubuntu 24.10 package I linked to above, to see if that helps.

**Comment by horvathcsabalaszlo** [comment]
> I've been pulling my hair out with this issue - my first foray into installing Linux (KDE Neon) onto a Surface Pro 4, and it was playing up from the first boot, so was convinced I'd missed some crucial step. The most obvious symptom that I found was that apt was erroring out talking to https repos. From there found the gnutls opcode trap and that AVX was being disabled due to not loading CPU microcode. Will assume then that it's not my error doing the install and wait :-D

I also tried Neon, but wasn't good. Debian+Gnome. Or Ubuntu with Gnome.

**Comment by kwai-chang** [comment]
> I also tried Neon in the past, but wasn't good. Debian+Gnome. Or Ubuntu with Gnome. Plasma Mobile was not so finished, and a lots of bugs.

It is a project build by self engagement from familiar users in there free time, so there might be some bugs. But many bugs are in wrong setup by different system components, by throwing together from debian, Ubuntu or whatever.
I love this project on my surface pro 9 / i7

**Comment by qzed** [comment]
Should be fixed in https://github.com/linux-surface/linux-surface/commit/4439a5efb6516c443df5f52173cb55aef01560d1. I'll try to update the patches and push a new release either this evening or tomorrow. Thanks to @tormodvolden for figuring out that GDS mitigation is the root cause.

**Comment by horvathcsabalaszlo** [comment]
> > I also tried Neon in the past, but wasn't good. Debian+Gnome. Or Ubuntu with Gnome. Plasma Mobile was not so finished, and a lots of bugs.
> 
> It is a project build by self engagement from familiar users in there free time, so there might be some bugs. But many bugs are in wrong setup by different system components, by throwing together from debian, Ubuntu or whatever. I love this project on my surface pro 9 / i7

As i know, the Neon is a project from the developers of KDE. I like KDE and used it until this year extensively on Ubuntu, but Neon's quality was far below my expectations.

**Comment by qzed** [comment]
Can anyone confirm whether this has been fixed in the latest releases?

**Comment by tormodvolden** [comment]
I can confirm that 6.10.5-surface-1 works out-of-the-box, without setting gather_data_sampling=off. There are no "traps" or "invalid opcodes" in dmesg output.

```
$ sudo dmesg | egrep -iw "AVX|GDS|microcode|family:"
[    0.125662] SRBDS: Mitigation: Microcode
[    0.125663] GDS: Vulnerable: No microcode
[    0.125673] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
[    0.126541] smpboot: CPU0: Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (family: 0x6, model: 0x4e, stepping: 0x3)
[    0.969408] microcode: Current revision: 0x000000f0
[    0.969410] microcode: Updated early from: 0x000000ea
```

**Comment by spider720** [comment]
No surface pro 4 still sometimes fails to boot and once logged on has internal errors.

**Comment by qzed** [comment]
@spider720 That sounds like a different problem. Can you post some logs in a new issue?

**Comment by horvathcsabalaszlo** [comment]
> No surface pro 4 still sometimes fails to boot and once logged on has internal errors.

Mine does not. Boots well, works well, without GDS option enabled. Debian Testing. (Didn't check dmesg yet.) Touch only works on Wayland, but that's an other issue.

**Comment by sjwk** [comment]
My only layman's concern is that the fix appears to be simply disabling GDS mitigation on all systems, whether or not they're affected by this glitch?  Isn't that leaving systems open to potential vulnerability?  Do we know why the microcode isn't being loaded, or is it just a case that the microcode package on some releases doesn't contain the appropriate fix?  (hence @tormodvolden suggesting to use the Ubuntu 24.04 package on 22.04 - although I haven't tried that yet)

**Comment by tormodvolden** [comment]
Yes, Intel hasn't upgraded the microcode for older processors to mitigate GDS. So if you have an older processor you have to live with the GDS risk or abstain from using AVX instructions, meaning having all software check for AVX availability instead of blindly assuming it can use it (like the current libgnutls.so and libxul.so do).

If you have a newer processor and microcode updates (intel-microcode package installed), the microcode mitigates GDS.

qzed's change in 6.10.5 doesn't turn off GDS mitigation, it just doesn't enforce it. Enforcing here means: If no microcode mitigation, turn off AVX instructions.

**Comment by sjwk** [comment]
OK, that makes a lot more sense!  Thanks for the explanation!

**Comment by qzed** [comment]
And for some context: Ubuntu's config, which we use as base, had this enforcement turned off ever since the feature came out. And it seems like they might only have enabled it by accident for v6.10.

**Comment by qzed** [comment]
@tormodvolden Ah I missed that. Thanks for correcting me!
