### ISSUE TITLE
Surface Pro 5 suspend on arch not booting back up.

### ISSUE THREAD

**Issue by luketownsend1** [linux-surface/linux-surface#1539]
Hey! For the last week or so, I've had a problem where in the latest versions (6.9.9-6.10.5) suspend does not work on my system running Arch Linux and GNOME. After suspending my computer, pressing the power button will not wake it back up, resulting in me having to hard reboot the device to boot Arch again.

Is there a way to roll back to 6.9.3? I've heard that's still stable. I've tried using the downgrade package to downgrade my firmware, but I can't go that far back because it isn't cached.

**Comment by Gitzzly** [comment]
Same for me here on SLS with Ubuntu 22.04

**Comment by kochmaxence** [comment]
> Is there a way to roll back to 6.9.3? I've heard that's still stable. I've tried using the downgrade package to downgrade my firmware, but I can't go that far back because it isn't cached.

Clone the repo, checkout a previous commit for 6.9.3 (eg. 9a5ca204b2c661f956a9ff31ccad64df1a5b73b9), [build the kernel](https://github.com/linux-surface/linux-surface/tree/master/pkg/arch)

```bash
git clone https://github.com/linux-surface/linux-surface.git
cd linux-surface
git checkout 9a5ca204b2c661f956a9ff31ccad64df1a5b73b9
cd pkg/arch/kernel
PKGEXT=".pkg.tar" MAKEFLAGS="-j8" makepkg -s --skippgpcheck
sudo pacman -U linux-surface-*.pkg.tar
```

I am on 6.9.9 on my SP9 this way.

If you want to avoid upgrade by mistake:

```bash
vim /etc/pacman.conf
```

Find `IgnorePkg` and add `linux-surface` and `linux-surface-headers`

**Comment by qzed** [comment]
Or you can just go to the [releases](https://github.com/linux-surface/linux-surface/releases) page and download and install a package from there...

**Comment by luketownsend1** [comment]
Thanks, guys! This is a great temporary solution and it worked out for me! I really hope this bug gets fixed soon.

**Comment by tormodvolden** [comment]
Did you close the bug because it has been fixed, or because you have found a temporary workaround?
