### ISSUE TITLE
Freezing during boot 

### ISSUE THREAD

**Issue by Yondernieer** [linux-surface/linux-surface#1541]
- Hardware model: Surface Pro 9
- Kernel version: 6.8.0-38-generic
- Distribution: Linux Mint 22 "Wilma"

I sadly don't have any logs to show but when I install the Linux-surface kernel properly, with and without the secure boot key, my device freezes upon boot and can't get past the Linux mint screen. At first I thought it was the MOKmanager and key causing the issue where it wouldn't work with NX mode but after not installing the key and disabling secure boot nothing seems to work I just freeze up that screen every time without fail. Now I'm just not sure what is actually causing my issue. Any ideas?

**Comment by dev-nis** [comment]
I also have this issue on a Surface Pro 9 running NixOS without SecureBoot. Switching back to a configuration from August 7th with Kernel 6.9 doesn't have this issue

Am Mittwoch, 21. August 2024 schrieb Yondernieer:
> 
> 
> - Hardware model: Surface Pro 9
> - Kernel version: 6.8.0-38-generic
> - Distribution: Linux Mint 22 "Wilma"
> 
> I sadly don't have any logs to show but when I install the Linux-surface kernel properly, with and without the secure boot key, my device freezes upon boot and can't get past the Linux mint screen. At first I thought it was the MOKmanager and key causing the issue where it wouldn't work with NX mode but after not installing the key and disabling secure boot nothing seems to work I just freeze up that screen every time without fail. Now I'm just not sure what is actually causing my issue. Any ideas?
> 
> 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/linux-surface/linux-surface/issues/1541
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***

-- 
Gesendet von meinem Sailfish Gerät

**Comment by dev-nis** [comment]
At least for me, it seems it is the same as in #1533 so the fix listed [there](https://github.com/linux-surface/linux-surface/issues/1533#issuecomment-2298120319) works for me

**Comment by mikejmcfarlane** [comment]
> At least for me, it seems it is the same as in #1533 so the fix listed [there](https://github.com/linux-surface/linux-surface/issues/1533#issuecomment-2298120319) works for me

That fix also worked for me on kernel 6.10.5-surface-1. Thanks.

**Comment by derkrasseleo** [comment]
Can confirm blacklisting the ipu6 drivers fixed booting for me

**Comment by mikejmcfarlane** [comment]
![IMG_0876](https://github.com/user-attachments/assets/fac54af3-96f6-416c-8a10-8a6edbdbc8b3)
![IMG_0875](https://github.com/user-attachments/assets/3cc758cd-b6cb-423e-bb82-8f3888378e22)
![IMG_0874](https://github.com/user-attachments/assets/6e2618a4-9d09-43fe-92c7-6d66fe7b2c52)
![IMG_0873](https://github.com/user-attachments/assets/7c64c60c-c163-4de2-b62a-707898b157cb)
![IMG_0871](https://github.com/user-attachments/assets/4c3568db-1431-4378-b2b3-59c5ef989310)
The point where it hung during boot seems different each time. Attached screenshots of a few boots, although they do cover SecureBoot on and off, and also a boot in Recovery mode so not sure if that makes a difference, but not seeing anything to do with errors in ipu6.

**Comment by Yondernieer** [comment]
Problem was solved by blacklisting intel-ipu6 and intel-ipu6-sys.
The booting process is still a bit slow but worth the wait.
#1516 Follow the aforementioned thread.
The stylus and touch screen work just fine with no current issues. 
Thank you guys for the help.
