### ISSUE TITLE
Keyboard not working in busybox after failed boot

### ISSUE THREAD

**Issue by Valerio1474** [linux-surface/linux-surface#1542]
Hi, I think something went wrong while updating the initramfs and now both my kernels fail to boot. I would like to fix my problem but I am facing a stupid problem: my cover keyboard is no longer responding after booting from grub and I don't have a USB keyboard handy to replace it. This is critical, whatever I do to fix the initramfs and even booting from a Debian install USB will have the same keyboard problem. Is there any option to keep the keyboard working after grub selection?

- Hardware model: Surface Pro 9
- Kernel version: 6.9.3
- Distribution: Debian Sid

**Comment by Valerio1474** [comment]
I believe this is a Debian only problem of some sort (keyboad not working), that I solved using an Ubuntu installation USB drive. Then I chrooted my system and solved the failing kernel boot because of a initramfs related issue (bad kmod and libkmod packages).

**Comment by qzed** [comment]
I'm glad you fixed it. For some context: The keyboard-not-working-in-initramfs is an issue of the modules required for the keyboard not being present in the initramfs. See https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption#disk-encryption-on-devices-with-keyboard-connected-via-the-surface-aggregator-module for the modules you need to include. Unfortunately, if you're unable to boot into the full system, it's a bit tricky to include them retroactively, and I think the way you did (with an external drive) it is pretty much the only option.

**Comment by Valerio1474** [comment]
Done adding them to initramfs: your how-to is perfect.
