### ISSUE TITLE
Add patch to allow disabling hibernation on lockdown

### ISSUE THREAD

**Issue by jeduardo** [linux-surface/linux-surface#1543]
Folks, I have been experimenting with hibernate in a Surface Go 3 with an encrypted partition. This works fine as long as I disable SecureBoot, but I need to add the LUKS password on every boot, which detracts from the experience of using the Surface as a tablet. I wanted to bind the LUKS partition to the TPM instead, which requires SecureBoot to be enabled, which disables hibernation.

[This patch](https://gist.github.com/brknkfr/95d1925ccdbb7a2d18947c168dfabbee) adds an option flag to disable only hibernation during kernel lockdown. Would you be open to add this patch to your kernel if I submit a PR?

I figured I'd ask you first before going to the trouble of cloning the repository and building my own packages.

If you are open to it, I will work on a PR. Thanks!

### Environment

- Hardware model: Surface Go 3
- Kernel version: 
- Distribution:

**Comment by qzed** [comment]
Yeah, I think we can include that.

**Comment by jeduardo** [comment]
Thanks @qzed! I'll work on the PR during the next few days.
