### ISSUE TITLE
[SP9] 6.10.5-surface-1 crashes/hangs on boot

### ISSUE THREAD

**Issue by mklss** [linux-surface/linux-surface#1555]
I accidentally did a `apt dist-upgrade` and was left with only 6.10.5-surface-1 and stock, both of which crashed/hung on boot. Fortunately, I could install older kernels because the stock kernel started working (at least via recovery) after some reboots. I have no idea why. The surface kernel boots to password entry for full disk encryption and then fails more or less immediately and apparently without consistent error. The first few times there was a `BUG` line, but I don't remember and couldn't reproduce.

(This issue is a heads up for other surface kernel users, since I have no idea how to diagnose anything.)

**Comment by TomReed123** [comment]
Similar issue here. Surface pro 6, did a fresh Ubuntu 24.04 install and it booted fine, installed the surface extensions and now its back to 3-5 tries to boot. If I can help diagnose this please let me know.

**Comment by Fxzzi** [comment]
can confirm this issue - here is the log I retrieved from kernel 6.10.10:

https://paste.rs/BbfK7

Reverting to latest 6.9 and i can boot again.

**Comment by qzed** [comment]
Could be a duplicate of https://github.com/linux-surface/linux-surface/issues/1516. Can you try blacklisting ipu6 (see https://github.com/linux-surface/linux-surface/issues/1516#issuecomment-2269662870, you may need to replace the `-` with `_`)?

**Comment by mklss** [comment]
Thank you, can confirm. The workaround helps.
