### ISSUE TITLE
Part of 0007-surface-sam.patch has made it to Linux 6.10

### ISSUE THREAD

**Issue by dotlambda** [linux-surface/linux-surface#1557]
Can you remove commit 17af44bcfe971e7b9dddad3735fad70bbda3fbf9 from `patches/6.10/0007-surface-sam.patch`?
It's part of Linux 6.10.7: https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.10.7

**Comment by qzed** [comment]
Yes, sorry, I need to update things and I haven't found any time for that in the last weeks. Hopefully this weekend.

If you want to build from source, you can also try our kernel repo (https://github.com/linux-surface/kernel/) and rebase the latest branch (e.g. v6.10-surface) on top of whatever version you want to build. The patches in here are generated from that.

**Comment by dotlambda** [comment]
> If you want to build from source, you can also try our kernel repo (https://github.com/linux-surface/kernel/) and rebase the latest branch (e.g. v6.10-surface) on top of whatever version you want to build. The patches in here are generated from that.

I prefer using the patches so I can use a newer kernel version than what's in https://github.com/linux-surface/kernel. Just in case there's a security update.

**Comment by qzed** [comment]
I've updated the patches.
