### ISSUE TITLE
Rebase patches for 6.11

### ISSUE THREAD

**Issue by LionHeartP** [linux-surface/linux-surface#1565]
Hey all, I'm trying to compile a 6.11 kernel for Nobara (Fedora base) and I'm hitting the following errors.

```
drivers/platform/surface/surface_aggregator_registry.c:297:36: error: redefinition of ‘ssam_node_group_sl6’
  297 | static const struct software_node *ssam_node_group_sl6[] = {
      |                                    ^~~~~~~~~~~~~~~~~~~
drivers/platform/surface/surface_aggregator_registry.c:281:36: note: previous definition of ‘ssam_node_group_sl6’ with type ‘const struct software_node *[12]’
  281 | static const struct software_node *ssam_node_group_sl6[] = {
      |                                    ^~~~~~~~~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:244: drivers/platform/surface/surface_aggregator_registry.o] Error 1
make[4]: *** [scripts/Makefile.build:485: drivers/platform/surface] Error 2
```

Let me know if I can provide more info. Thanks!

**Comment by qzed** [comment]
I'll try to rebase and add patches for 6.11 on the weekend at latest.

**Comment by babiulep** [comment]
@LionHeartP: if you have the time (and courage...) could you try my rebase effort?
https://github.com/babiulep/linux-surface/tree/master/patches/6.11

Thanx in advance...

**Comment by LionHeartP** [comment]
> @LionHeartP: if you have the time (and courage...) could you try my rebase effort? https://github.com/babiulep/linux-surface/tree/master/patches/6.11
> 
> Thanx in advance...

Kernel compiled fine with these patches and my initial (crude) regression tests passed as well.

Thanks everyone for the quick replies! Leaving the issue open until you close it with the relevant PR.

**Comment by qzed** [comment]
Correct, you need to drop a couple of patches as they have made it upstream. I've already set up a new branch (and built some packages), but haven't gotten around to test them yet.

**Comment by babiulep** [comment]
@Dariqq: could you please try my patches (if you have the time...)?:  
https://github.com/babiulep/linux-surface/tree/master/patches/6.10/  
  
The changes are in 0007-surface-sam.patch (a lot smaller...) and 0010-surface-typecover.patch...

**Comment by qzed** [comment]
Patches for v6.11 have been added, patches for v6.10 have been rebased.
