### ISSUE TITLE
Prompting for "ERROR: module not found: `intel_ipts'"

### ISSUE THREAD

**Issue by haozhou** [linux-surface/linux-surface#157]
[Description of the bug or feature]

### Environment
- Hardware model: Surface Pro 4
- Kernel version: 5.6.3-arch1-1-surface
- Distribution: Arch Linux

I've followed instruction from https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#surface-kernel-installation

`sudo pacman -S linux-surface-headers linux-surface surface-ipts-firmware linux-surface-secureboot-mok
`

Here's the error
```
==> Starting build: 5.6.3-arch1-1-surface
  -> Running build hook: [base]
  -> Running build hook: [udev]
  -> Running build hook: [modconf]
  -> Running build hook: [block]
==> WARNING: Possibly missing firmware for module: aic94xx
==> WARNING: Possibly missing firmware for module: wd719x
  -> Running build hook: [filesystems]
  -> Running build hook: [keyboard]
  -> Running build hook: [fsck]
==> ERROR: module not found: `intel_ipts'
==> Generating module dependencies
==> Creating gzip-compressed initcpio image: /boot/initramfs-linux-surface-fallback.img
==> WARNING: errors were encountered during the build. The image may not be complete.
error: command failed to execute correctly
```

**Comment by StollD** [comment]
On 5.5+ the module is only called `ipts`, not `intel_ipts`. Since you added it to your initramfs, you need to update your mkinitcpio config for the new module name.

**Comment by haozhou** [comment]
Thanks. It helps. 
I'd suggest adding that to the wiki
