### ISSUE TITLE
Fedora 41 missing packages

### ISSUE THREAD

**Issue by Fail-gh** [linux-surface/linux-surface#1578]
[Description of the bug or feature]

### Environment

- Hardware model: Surface Pro 6
- Kernel version: 6.11.0-63.fc41.x86_64
- Distribution: Fedora 41

Missing packages for Fedora 41

**Comment by Lucrtz** [comment]
I just installed Fedora 41 on my Surface Pro 9 and can confirm that the libwacom-surface package is currently not available.

**Comment by otjamin** [comment]
Unfortunately the Fedora 41 packages are also missing from the release. As a workaround you can download the artifacts directly and install them.

1. Go to the [Actions](https://github.com/linux-surface/libwacom-surface/actions) page of the libwacom-surface repo.
2. Select the most recent run from the list and scroll down to download the F41 artifacts.
3. OR: [This](https://github.com/linux-surface/libwacom-surface/actions/runs/10864304626/artifacts/1933433830) is the direct download link.
4. Unzip the archive and run `sudo dnf in --allowerasing *.rpm`. This will install libwacom-surface and the two deps in the folder.

**Comment by qzed** [comment]
> Unfortunately the Fedora 41 packages are also missing from the release.

Yeah... I forgot to add something when setting up the fedora 41 scripts. Thanks @otjamin for the fix! Packages should be in the repo in the next couple of minutes.

**Comment by Lucrtz** [comment]
Perfect, the packages are available, thank you very much! Thanks also to @otjamin, the manual download has worked in the meantime :)
