### ISSUE TITLE
Permission to ship Linux Surface with Ultramarine Linux

### ISSUE THREAD

**Issue by nothingneko** [linux-surface/linux-surface#1579]
Hey, I'm from Ultramarine Linux. We'd like to ship images with the Surface kernel preinstalled to make things a tad easier for our users. I just wanted ti check and make sure this is alright with the maintainers before merging [Ultramarine-Linux/images #48](https://github.com/Ultramarine-Linux/images/pull/48)

**Comment by qzed** [comment]
Sure, feel free to do that.

I can't promise any (timely) support for that from our side right now though if things break. I'll of course try my best to keep things running here, but I'm a bit stretched on time right now.

**Comment by nothingneko** [comment]
That's aokay, in my personal experience you guys have done an amazing job keeping up stability and updates, I'm not concerned at all.

We tend to try handling support downstream before sending them your way, so the majority of simple things should be handled by us.

**Comment by nothingneko** [comment]
Thanks!
