### ISSUE TITLE
Surface laptop 2 - keyboard not working before LUKS encryption passphrase

### ISSUE THREAD

**Issue by lordmoonvalks** [linux-surface/linux-surface#162]
Decided to create this post after few days of struggling with this I'm running 4.19.114-1-surface-lts kernel on Surface Laptop 2 , multitouch and keyboard works great inside the system however internal keyboard is not reacting to input before boot during LUKS encryption passphrase authentication.  

I happened to solve this problem installing this kernel https://github.com/dmhacker/arch-linux-surface and adding those modules to my mkinitcpio.conf  : 
surface_sam_ssh, surface_sam_vhf intel_lpss and intel_lpss_pci 8250_dw
This made keyboard work during LUKS encryption passphrase however this kernel doesn't support multitouch so I installed linux-surface kernel 4.19.114-1-surface-lts again because I rather choose multitouch functioning then keyboard input during encryption.

Anyone have same issues ? Anyone happen to make it both works ?

**Comment by archseer** [comment]
It's all documented. https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-2

**Comment by archseer** [comment]
Oh sorry, I see that you did modify your mkinitcpio. I think you need to run `mkinitcpio -p <preset name>` to rebuild the boot image.

**Comment by archseer** [comment]
Also we now offer prebuilt package repositories which will keep your kernel up to date automatically. Those are the recommended way to run the kernel now: https://github.com/linux-surface/linux-surface/wiki/Package-Repositories#arch-linux-repository

**Comment by lordmoonvalks** [comment]
@archseer tried this but still no input detected before luks encryption. Actually i didnt run mkinit -p linux as i thought it will rebuild original linux kernel? Im not sure how this command should be run then ?    mkinitcpio -p <surface kernel name> ? thanks so much for helping

**Comment by cwyc** [comment]
I also have this issue on Surface Laptop 3 on nixos. It doesn't help to add these kernel modules in my initrd config.

**Comment by archseer** [comment]
@cwyc What does your config look like, are you compiling the kernel with the extra patches? I use a SL3 with NixOS just fine, but I have a custom config. There was also a setup available in nixos-hardware.

**Comment by archseer** [comment]
Afterwards, here's specifically what I had to do to get the modules into initrd https://github.com/archseer/snowflake/blob/c9dfb1edb8ac168d667b6662ab0fcd5f966cf35a/hosts/hyrule/hardware.nix#L14

**Comment by cwyc** [comment]
@archseer I used the nixos-hardware patches:
```nix
{
  imports = [ <nixos-hardware/microsoft/surface> ];
  ...
  boot.initrd.kernelModules = [ "surface_aggregator" "intel_lpss" "intel_lpss_pci" "8250_dw" ];
}
```
Thanks for your help. I won't be able to test any fixes as I don't have this laptop anymore.

**Comment by archseer** [comment]
Per https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3 you need to add surface_aggregator, surface_aggregator_registry, surface_hid_core, and surface_hid, not just surface_aggregator.

**Comment by qzed** [comment]
I believe we can close this issue. With the modules added to the initram as described in the wiki, keyboard should work at that stage.

**Comment by qzed** [comment]
@hardwareadictos As far as I remember, the Go uses USB-HID for the keyboard. The Surface Aggregator modules are not used.

**Comment by hardwareadictos** [comment]
> @hardwareadictos As far as I remember, the Go uses USB-HID for the keyboard. The Surface Aggregator modules are not used.

Than you @qzed, seems that these driver doesnt work on boot, at least for using type cover keyboard, it works but just intermittently, have to enter my decrypt password couple of times till i success :(

Keyboard works well once the system is booted on Fedora, and also works fine on Windows.

Do you have any idea?

**Comment by qzed** [comment]
Unfortunately no, I'd assume it should either work or not work if it'd be an issue with the modules included. The module you need is `usbhid`, but I assume that's already included (that's pretty much a standard requirement for input on all systems these days, not just the Go).

**Comment by hardwareadictos** [comment]
Grepped with lsmod this module and it was not loaded. I just added it tu a custom conf file under modules-load.d and now it still doesnt appear on lsmod. Appears something on dmesg:

![imagen](https://user-images.githubusercontent.com/20403906/169810981-1209db40-3b3f-477a-906b-0cf874195fc4.png)


Anyways on LUKS password prompt at boot, kayboard still doesnt work fine.

**Comment by hardwareadictos** [comment]
Did someone made any progress with this?
