### ISSUE TITLE
Can not boot after 6.12.3 update - failed to load root filesystem

### ISSUE THREAD

**Issue by Kmschr** [linux-surface/linux-surface#1628]
Update: This was fixed by `6.12.3-surface-2`

I tried to update my kernel to 6.12.3, but can not boot into this version. When booting in recovery mode from grub I can see that it fails trying to load the root filesystem. I can still boot into 6.7.6 without error. 

After the 6.12.3 boot fails the keyboard does not function for the initramfs prompt. I added the necessary modules to the initramfs configuration and used update-initramfs for the 6.12.3 kernel version to try and enable keyboard input but it does not appear to add all the modules.

### Environment

- Hardware model: Surface Laptop 3 (AMD)
- Kernel version: `6.7.6-surface-1` to `6.12.3-surface-1`
- Distribution: Debian 12

Contents of `/etc/initramfs-tools/modules`:
```
8250_dw
surface_aggregator
surface_aggregator_registry
hid
hid_generic
usb_hid
surface_hid_core
surface_hid
```

![Snapchat-1254368078](https://github.com/user-attachments/assets/970d4b52-b86e-4d87-ba4e-221fb0aeafeb)

**Comment by lala-rob** [comment]
I have the same problem.

Environment

    Hardware model: Surface 10
    Kernel version: 6.11.10 to 6.12.3-surface-1
    Distribution: Ubuntu 24.04

**Comment by ztelliot** [comment]
```
Hardware model: Surface Book 1
Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1
Distribution: Debian trixie
```

Same problem

**Comment by derkrasseleo** [comment]
Can't confirm 
```
Hardware model: Surface Pro 9
Kernel version: 6.11.4-surface-1 to 6.12.4-surface-1
Distribution: Arch
```

**Comment by schimmi68** [comment]
Hardware: Surface Book 2
Kernel version:  6.10.10-surface-1 to 6.12.3-surface-1
Distribution: PeppermintOs Devuan

Same problem

**Comment by zhoutongmike** [comment]
Hardware model: Surface-Go
Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1
Distribution: Ubuntu 24.04

Same problem

**Comment by mellejwz** [comment]
I have the same. I did have some errors that it failed to find some modules like amd_pc, but I remember having those in an earlier version as well. I'm using a Surface Go 2 with a Pentium 4425Y running Ubuntu 24.04. I'm currently running 6.10.10-surface-1 as obviously 6.12.3 doesn't seem to boot.

**Comment by zhuguangxiang** [comment]
The same bug!

**Comment by fvojtech** [comment]
same issue, Surface Pro 4, Ubuntu

**Comment by tomvomland** [comment]
Same Problem (no keyboard & not booting) on a Surface pro 3.
Updated from 6.10.10-surface-1.

**Comment by junalmeida** [comment]
I started a package upgrade and it failed, so I didn´t reboot. Tons of missing modules and fails on DKMS. Keeping 6.10 for now.

**Comment by mellejwz** [comment]
After that update to 6.12.3 and reverting to 6.10.10 I do have the issue that it gets stuck on the splashscreen, while everything seems to load in the background. I can also log in with ssh, any pointers to what I should check? Restarting gdm fixes it, so I am able to log in, but only until the next reboot.

**Comment by draxel** [comment]
Same issue here!  Booting into 6.10.10 still works fine for now.

Hardware model: Surface Pro 8 (i7)
Kernel version: 6.10.10-surface-1 -> 6.12.3-surface-1
Distribution: Mint 21.3

**Comment by reischle** [comment]
Can confirm. Reverting to 6.10.10 for the moment. OS is Ubuntu 24.04.1 on a Surface Laptop 1 (Intel)

**Comment by runningslow81** [comment]
Same. Zorin 17.2 on Surface Pro 6.
Literally installed Zorin last night and it never booted with the surface kernel after enrolling the mok keys. I thought I must have screwed something up while installing the surface kernel or maybe a weird quirk of Zorin vs Ubuntu.

**Comment by lala-rob** [comment]
I have built a 6.12.4 kernel for testing.
With this the system starts normal.
@qzed maybe you could create a new one?


    Hardware model: Surface 10
    Kernel version: 6.12.4
    Distribution: Ubuntu 24.02

**Comment by Moryason** [comment]
Same issue here. Also reverting to 6.10.10

**Comment by grubzzz** [comment]
Same issue on Surfafe Go 2 running Debian 12. Reverting to previous surface kernel or the stock Debian one boots fine.

**Comment by Kosciany** [comment]
Same issue, Surface 7 Pro, Ubuntu 24

**Comment by davidbitterlich** [comment]
I can also confirm this problem on my Surface Pro 8 with Ubuntu 24.04. Could it be that the btrfs drivers are missing in the kernel? Stick with 6.10 for now.

**Comment by TheJayMann** [comment]
Using debian sid, from what I can tell, when update-initramfs is called, dracut-install is unable to find any kernel module.  When it states that it is unable to find the module, it list the full path of the module, which does exist.  As a test, I also attempted to run update-initramfs against the working 6.10.10 kernel, which works just fine.  The main difference is that the kernel modules in the 6.12.3 package are all gzip (e.g. /lib/modules6.12.3-surface-1/kernel/sound/xen/snd_xen_front.ko.gz), while the previous package were (supposedly based on filename alone) uncompressed (e.g. /lib/modules/6.10.10-surface-1/kernel/sound/xen/snd_xen_front.ko).  My guess is this is the problem, or at least related to it.

**Comment by technosf** [comment]
The 6.12.3 install fails, but does not **_backout_**.

Here is the history and install log from Linux Mint - When the install log refers to previous errors, there were none in the log.

History.log
```
Start-Date: 2024-12-11  13:05:12
Commandline: /usr/sbin/synaptic --hide-main-window --non-interactive -o Synaptic::closeZvt=true --set-selections-file /tmp/tmp_qmf1102 --parent-window-id 54525970
Install: linux-image-6.12.3-surface-1:amd64 (6.12.3-surface-1, automatic), linux-headers-6.12.3-surface-1:amd64 (6.12.3-surface-1, automatic)
Upgrade: firefox-locale-en:amd64 (133.0+linuxmint1+xia, 133.0.3+linuxmint1+xia), linux-image-surface:amd64 (6.10.10-surface-1, 6.12.3-surface-1), thunderbird-locale-en:amd64 (1:128.5.1esr+linuxmint1+xia, 1:128.5.2esr+linuxmint1+xia), linux-headers-surface:amd64 (6.10.10-surface-1, 6.12.3-surface-1), code:amd64 (1.95.3-1731513102, 1.96.0-1733888194), thermald:amd64 (2.5.6-2build2, 2.5.6-2ubuntu0.24.04.1), thunderbird-locale-en-us:amd64 (1:128.5.1esr+linuxmint1+xia, 1:128.5.2esr+linuxmint1+xia), intel-microcode:amd64 (3.20240910.0ubuntu0.24.04.1, 3.20241112.0ubuntu0.24.04.1)
Error: Sub-process /usr/bin/dpkg returned an error code (1)
End-Date: 2024-12-11  13:05:49
```

Install log:
```
Setting up linux-image-6.12.3-surface-1 (6.12.3-surface-1) ...
 * dkms: running auto installation service for kernel 6.12.3-surface-1
Kernel config /lib/modules/6.12.3-surface-1/build/.config not found, modules won't be signed

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.12.3-surface-1 KERNELRELEASE=6.12.3-surface-1 KERNEL_SRC=/lib/modules/6.12.3-surface-1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.3-surface-1 (x86_64)
Consult /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/make.log for more information.
dkms autoinstall on 6.12.3-surface-1/x86_64 failed for ipu6-drivers(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
 * dkms: autoinstall for kernel 6.12.3-surface-1
   ...fail!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
update-initramfs: Generating /boot/initrd.img-6.12.3-surface-1
dracut-install: Failed to find module 'arc_rawmode' /lib/modules/6.12.3-surface-1/kernel/drivers/net/arcnet/arc-rawmode.ko.gz
dracut-install: Failed to find module 'arc_rimi' /lib/modules/6.12.3-surface-1/kernel/drivers/net/arcnet/arc-rimi.ko.gz
..
dracut-install: Failed to find module 'xilinx_gmii2rgmii' /lib/modules/6.12.3-surface-1/kernel/drivers/net/phy/xilinx_gmii2rgmii.ko.gz
Errors were encountered while processing:
 linux-image-6.12.3-surface-1
 linux-image-surface
Log ended: 2024-12-11  13:05:49
```
etc

**Comment by technosf** [comment]
Also cannot uninstall:

```
dpkg -r linux-image-6.12.3-surface-1 linux-headers-6.12.3-surface-1
dpkg: dependency problems prevent removal of linux-image-6.12.3-surface-1:
 linux-image-surface depends on linux-image-6.12.3-surface-1 (= 6.12.3-surface-1).

dpkg: error processing package linux-image-6.12.3-surface-1 (--remove):
 dependency problems - not removing
dpkg: dependency problems prevent removal of linux-headers-6.12.3-surface-1:
 linux-headers-surface depends on linux-headers-6.12.3-surface-1 (= 6.12.3-surface-1).

dpkg: error processing package linux-headers-6.12.3-surface-1 (--remove):
 dependency problems - not removing
Errors were encountered while processing:
 linux-image-6.12.3-surface-1
 linux-headers-6.12.3-surface-1

```

**Comment by technosf** [comment]
And the make.log
```

DKMS make.log for ipu6-drivers-0~git202406240945.aecec2aa-0ubuntu2~24.04.2 for kernel 6.12.3-surface-1 (x86_64)
Wed Dec 11 01:05:51 PM PST 2024
make -C /lib/modules/6.12.3-surface-1/build M=/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.12.3-surface-1'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
  You are using:           gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/hm11b1.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a1s.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a10.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02c10.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02e10.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08a10.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08x40.o
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a10.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/hm11b1.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a1s.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a10.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov01a1s.o] Error 1
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/hm11b1.o] Error 1
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02e10.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02c10.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02e10.o] Error 1
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08a10.c:4:10: fatal error: asm/unaligned.h: No such file or directory
    4 | #include <asm/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov02c10.o] Error 1
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08a10.o] Error 1
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08x40.c:4:10: fatal error: asm-generic/unaligned.h: No such file or directory
    4 | #include <asm-generic/unaligned.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c/ov08x40.o] Error 1
make[3]: *** [scripts/Makefile.build:478: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/i2c] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-bus.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-dma.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-mmu.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-buttress.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-trace.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-cpd.o
  CC [M]  /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/ipu6.o
/var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-trace.c:520:19: error: ‘no_llseek’ undeclared here (not in a function); did you mean ‘noop_llseek’?
  520 |         .llseek = no_llseek,
      |                   ^~~~~~~~~
      |                   noop_llseek
make[5]: *** [scripts/Makefile.build:229: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6/../ipu-trace.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [scripts/Makefile.build:478: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel/ipu6] Error 2
make[3]: *** [scripts/Makefile.build:478: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build/drivers/media/pci/intel] Error 2
make[2]: *** [/usr/src/linux-headers-6.12.3-surface-1/Makefile:1942: /var/lib/dkms/ipu6-drivers/0~git202406240945.aecec2aa-0ubuntu2~24.04.2/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.3-surface-1'
make: *** [Makefile:82: all] Error 2

```

**Comment by UStuej** [comment]
Hardware model: Surface Book 2 (2018)
Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1
Distribution: Debian 12.8 (bookworm)

Same problem

**Comment by qzed** [comment]
> I have built a 6.12.4 kernel for testing. With this the system starts normal. @qzed maybe you could create a new one?
> 
> ```
> Hardware model: Surface 10
> Kernel version: 6.12.4
> Distribution: Ubuntu 24.02
> ```

@lala-rob Unfortunately it looks like 6.12.4 isn't on the Ubuntu mainline repo yet (https://git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack/refs/ is missing `cod/mainline/v6.12.4`). But I'm not sure it's an issue between 6.12.3 and 6.12.4. I'm trying to figure out what broke...

**Comment by qzed** [comment]
> Also cannot uninstall:
> 
> ```
> dpkg -r linux-image-6.12.3-surface-1 linux-headers-6.12.3-surface-1
> dpkg: dependency problems prevent removal of linux-image-6.12.3-surface-1:
>  linux-image-surface depends on linux-image-6.12.3-surface-1 (= 6.12.3-surface-1).
> 
> dpkg: error processing package linux-image-6.12.3-surface-1 (--remove):
>  dependency problems - not removing
> dpkg: dependency problems prevent removal of linux-headers-6.12.3-surface-1:
>  linux-headers-surface depends on linux-headers-6.12.3-surface-1 (= 6.12.3-surface-1).
> 
> dpkg: error processing package linux-headers-6.12.3-surface-1 (--remove):
>  dependency problems - not removing
> Errors were encountered while processing:
>  linux-image-6.12.3-surface-1
>  linux-headers-6.12.3-surface-1
> ```

@technosf Try uninstalling `linux-image-surface` and `linux-headers-surface` as well. It likely fails because those meta-packages depend on the actual versioned packages.

**Comment by qzed** [comment]
@lala-rob Can you post the config of your working kernel?

**Comment by qzed** [comment]
NVM I think I might have found the problem... At some point we force-disabled module compression for Ubuntu because some Ubuntu/Debian versions don't seem to support that. Previously, that meant setting `CONFIG_MODULE_COMPRESS_NONE=y`. Somewhere from 6.11 to 6.12 this changed and we now have to set `CONFIG_MODULE_COMPRESS=n`. I've started a new build, hopefully that fixes this issue.

**Comment by hisoka3gm** [comment]
Can someone help how to install the previous kernel that is working
I am new to linux i only use the lines on this page to  copy and past

![Screenshot_20241212-054332.png](https://github.com/user-attachments/assets/aa36b19c-72b6-4cd8-b556-8fd14989c3ae)

**Comment by hisoka3gm** [comment]
> Hardware model: Surface Book 2 (2018)
> Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1
> Distribution: Debian 12.8 (bookworm)
> 
> Same problem.
> 
> Kernel 6.10.10-surface-1 boots fine.

My friend i have the same surface book 2, can you please tell me how i can install the previous version that is working ?

**Comment by Kosciany** [comment]
@hisoka3gm 
if after boot you have this grub selection:
![20241212_065907](https://github.com/user-attachments/assets/2336cb2a-0c0e-4ff4-946e-cb8abc5c7431)
you should be able to select 'Advanced options for Ubuntu'. If you did not remove old kernel, you should be able to select if from the list (6.10.10 in my case)
![20241212_065927](https://github.com/user-attachments/assets/932fb7fe-d8a1-4f91-a364-8d05e723edb0)
If the grub OS selection window is not displayed, try to press shift when booting (see https://askubuntu.com/questions/668049/grub-menu-at-boot-time-holding-shift-not-working).
Then set default boot header to the last one, according to second answer in this post (in `/etc/default/grub` file after booting): https://askubuntu.com/questions/216398/set-older-kernel-as-default-grub-entry
```
GRUB_DEFAULT=saved
GRUB_SAVEDEFAULT=true
```

**Comment by h2dden** [comment]
same issue on S7Pro with Debian12
As mentioned above, previous kernel can be booted succeasfully until a solution is worked out

**Comment by Moryason** [comment]
> > Hardware model: Surface Book 2 (2018)
> > Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1
> > Distribution: Debian 12.8 (bookworm)
> > Same problem.
> > Kernel 6.10.10-surface-1 boots fine.
> 
> My friend i have the same surface book 2, can you please tell me how i can install the previous version that is working ?

I think the meta package is not compliant anymore with 6.10.10 version. When you intend to install the meta package, it forces you to install the latest kernel.

**Comment by kwai-chang** [comment]
Surface Pro 9, Debian 12 
![2024-12-12_08-05-22](https://github.com/user-attachments/assets/0dfac604-ea98-4985-80e7-3a97f528e2c3)

**Comment by kwai-chang** [comment]
Same here Surface Pro 9, Debian 12, Mint XFCE
![2024-12-12_08-11-50_Surface](https://github.com/user-attachments/assets/b805ccb2-85b7-413f-9b36-d04fbd3e788f)

**Comment by che-wf** [comment]
The same thing happened to me. Here's my system info:

```
  System:
    OS: Linux 6.10 Ubuntu 24.10 24.10 (Oracular Oriole) 
    Host: Surface Pro 6
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
```

I ran into the same issue, but I also noticed that the during the installation (and reinstallation process in my case), there was a long list of messages saying "failed to find module...". Here's the tail end of it:

```
dracut-install: Failed to find module 'intel_uncore_frequency_tpmi' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/uncore-frequency/intel-uncore-frequency-tpmi.ko.gz
dracut-install: Failed to find module 'intel_vsec_tpmi' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/intel_vsec_tpmi.ko.gz
dracut-install: Failed to find module 'intel_punit_ipc' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/intel_punit_ipc.ko.gz
dracut-install: Failed to find module 'intel_chtwc_int33fe' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/intel_chtwc_int33fe.ko.gz
dracut-install: Failed to find module 'intel_sdsi' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/intel_sdsi.ko.gz
dracut-install: Failed to find module 'isst_tpmi' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_tpmi.ko.gz
dracut-install: Failed to find module 'isst_if_mbox_pci' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_if_mbox_pci.ko.gz
dracut-install: Failed to find module 'isst_if_mbox_msr' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_if_mbox_msr.ko.gz
dracut-install: Failed to find module 'isst_tpmi_core' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_tpmi_core.ko.gz
dracut-install: Failed to find module 'isst_if_mmio' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_if_mmio.ko.gz
dracut-install: Failed to find module 'isst_if_common' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/speed_select_if/isst_if_common.ko.gz
dracut-install: Failed to find module 'ishtp_eclite' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/ishtp_eclite.ko.gz
dracut-install: Failed to find module 'intel_skl_int3472_common' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/int3472/intel_skl_int3472_common.ko.gz
dracut-install: Failed to find module 'intel_skl_int3472_discrete' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/int3472/intel_skl_int3472_discrete.ko.gz
dracut-install: Failed to find module 'intel_skl_int3472_tps68470' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/int3472/intel_skl_int3472_tps68470.ko.gz
dracut-install: Failed to find module 'pmt_telemetry' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/pmt/pmt_telemetry.ko.gz
dracut-install: Failed to find module 'pmt_class' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/pmt/pmt_class.ko.gz
dracut-install: Failed to find module 'pmt_crashlog' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/pmt/pmt_crashlog.ko.gz
dracut-install: Failed to find module 'intel_smartconnect' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/intel-smartconnect.ko.gz
dracut-install: Failed to find module 'intel_ifs' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/intel/ifs/intel_ifs.ko.gz
dracut-install: Failed to find module 'quickstart' /lib/modules/6.12.3-surface-1/kernel/drivers/platform/x86/quickstart.ko.gz
dracut-install: Failed to find module 'ili9341' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/ili9341.ko.gz
dracut-install: Failed to find module 'st7735r' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/st7735r.ko.gz
dracut-install: Failed to find module 'bochs' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/bochs.ko.gz
dracut-install: Failed to find module 'gm12u320' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/gm12u320.ko.gz
dracut-install: Failed to find module 'repaper' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/repaper.ko.gz
dracut-install: Failed to find module 'hx8357d' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/hx8357d.ko.gz
dracut-install: Failed to find module 'panel_mipi_dbi' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/panel-mipi-dbi.ko.gz
dracut-install: Failed to find module 'ili9163' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/ili9163.ko.gz
dracut-install: Failed to find module 'st7586' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/st7586.ko.gz
dracut-install: Failed to find module 'cirrus' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/cirrus.ko.gz
dracut-install: Failed to find module 'ili9225' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/ili9225.ko.gz
dracut-install: Failed to find module 'ili9486' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/ili9486.ko.gz
dracut-install: Failed to find module 'mi0283qt' /lib/modules/6.12.3-surface-1/kernel/drivers/gpu/drm/tiny/mi0283qt.ko.gz
```

**Comment by fvojtech** [comment]
> NVM I think I might have found the problem... At some point we force-disabled module compression for Ubuntu because some Ubuntu/Debian versions don't seem to support that. Previously, that meant setting `CONFIG_MODULE_COMPRESS_NONE=y`. Somewhere from 6.11 to 6.12 this changed and we now have to set `CONFIG_MODULE_COMPRESS=n`. I've started a new build, hopefully that fixes this issue.

I can confirm, it works with the new build.
Thanks for that.

**Comment by 2v2m2x** [comment]
> Hardware model: Surface Pro 5 i5 (2017) Kernel version: 6.10.10-surface-1 to 6.12.3-surface-1 Distribution: Debian 12.8 (bookworm)
> 
> Same problem

confirming it now works with new build #2

**Comment by arielDeKlerk** [comment]
Not it works with **6.12.3-surface-2**, thank you.

Device: Surface Laptop 1
OS: Ubuntu 24.04.1

**Comment by h2dden** [comment]
S7Pro, Debian12
I can boot 6.12.3-surface-2, but it fails to detect the wifi card: wifi not working

**Comment by JeffBezsos** [comment]
the fix worked for logging in, great job! 
now however I experience a **new issue**
(I'm on **Pop_OS!** 22.04 using surface book 2) 
after logging in with the new kernel my **NVIDIA GPU** (GTX 1050) doesn't work 
by default the kernel loads with Integrated Graphics... 
when I try to switch to **Hybrid Graphics** I get a message it will require restart to initialize the changes 
my CPU maxes out for over a minute 
I restart as required & am still on Integrated Graphics...  
It works on the old kernel version though!

**Comment by schimmi68** [comment]
"Alles bestens"  - greetings from germany.
The new kernel boots now perfectly on a surfacebook2 with PeppermintOs Devuan, i think daedalus. Everything is working.
Have a good time!

**Comment by Kmschr** [comment]
Now working after upgrading to version `6.12.3-surface-2`

**Comment by Moryason** [comment]
Working now on surface pro 6
LinuxMint 22.
To prevent a next fail, I modified grub 
A grub menu now appears so that I can select a kernel to load.
I use grub customizer to easily proceed.

**Comment by zhuguangxiang** [comment]
> > > NVM I think I might have found the problem... At some point we force-disabled module compression for Ubuntu because some Ubuntu/Debian versions don't seem to support that. Previously, that meant setting `CONFIG_MODULE_COMPRESS_NONE=y`. Somewhere from 6.11 to 6.12 this changed and we now have to set `CONFIG_MODULE_COMPRESS=n`. I've started a new build, hopefully that fixes this issue.
> > 
> > 
> > I can confirm, it works with the new build. https://github.com/linux-surface/linux-surface/releases/tag/debian-6.12.3-2 Thanks for that.
> 
> This doesnt work for me. i still get that dpkg: error processing package linux-image-6.12.3-surface-2 (--configure): installed linux-image-6.12.3-surface-2 package post-installation script subprocess returned error exit status 11 dpkg: dependency problems prevent configuration of linux-image-surface: linux-image-surface depends on linux-image-6.12.3-surface-2 (= 6.12.3-surface-2); however: Package linux-image-6.12.3-surface-2 is not configured yet.
> 
> dpkg: error processing package linux-image-surface (--configure): dependency problems - leaving unconfigured Errors were encountered while processing: linux-image-6.12.3-surface-2 linux-image-surface E: Sub-process /usr/bin/dpkg returned an error code (1)
> 
> does anyone have any idea whats needed? i can boot just fine on previous kernel

how to solve it? i have the same problem and cannot update

**Comment by technosf** [comment]
I have 6.12.3-surface-2 installed and working, even though the install did complain:
```
E: linux-image-6.12.3-surface-2: installed linux-image-6.12.3-surface-2 package post-installation script subprocess returned error exit status 11
E: linux-image-surface: dependency problems - leaving unconfigured
```

I did try purging 6.12.3-surface-2 and the metadata packages and reinstalling after the issues with 6.12.3-surface-1, but the install error is the same - startup to 6.12.3-2 is fine however. 

The above error now occurs on every package install and update.

**Comment by BrianCArnold** [comment]
> I have 6.12.3-surface-2 installed and working, even though the install did complain:
> 
> ```
> E: linux-image-6.12.3-surface-2: installed linux-image-6.12.3-surface-2 package post-installation script subprocess returned error exit status 11
> E: linux-image-surface: dependency problems - leaving unconfigured
> ```
> 
> I did try purging 6.12.3-surface-2 and the metadata packages and reinstalling after the issues with 6.12.3-surface-1, but the install error is the same - startup to 6.12.3-2 is fine however.
> 
> The above error now occurs on every package install and update.

I think I also ran into this, I ended up having to go into /lib/modules and delete the kernel directories that I no longer had installed?

Or it might have had something to do with DKMS, where it was trying to clear out an old version of a DKMS package that wasn't there anymore, something like that. I use ZFS with linux-surface, so my environment is exceedingly complicated, I have to do a lot of things that most people don't. See if you can get the logs for that post-installation script, should help sort out what's happening.
