### ISSUE TITLE
[S7Pro] 6.12.3-surface-2 fails to detect wifi card

### ISSUE THREAD

**Issue by h2dden** [linux-surface/linux-surface#1629]
S7Pro running Debian 12
I can boot 6.12.3-surface-2 but the wifi card is not detected
Wifi is not working

**Comment by maremike** [comment]
Same issue for me. I tried Debian 12 with the same kernel as you. My wifi is not working. My screen also changes brightness periodically (going lower for a few seconds and back to normal). The battery indicator for me shows 50% when the surface battery is full. However on the OG debian kernel, the wifi is working.

With arch none of this happened for me with the same kernel.

**Comment by maremike** [comment]
I tried installing kernels from the newest version all the way down till everything seemed to work for debian. I have no issues with 6.10.10-1 so far with debian 12.

**Comment by xoorath** [comment]
> I tried installing kernels from the newest version all the way down till everything seemed to work for debian. I have no issues with 6.10.10-1 so far with debian 12.

Same. I am also experiencing this issue with Debian 12 on Surface Laptop 2 and also have no issues with 6.10.10-1, just as another data point.

**Comment by RalphBariz** [comment]
Same here SP9 and SG3. Both fail to find firmware with 6.12.3-surface-2. Both work with 6.10.10-1.

**Comment by h2dden** [comment]
for my S7Pro iwlwifi-Qu-c0-hr-b0-77.ucode did the trick
Thank you @groengpx 
for all other with the same problem, check 
sudo dmesg | grep wifi

**Comment by greysonofusa** [comment]
Same issue on surface Pro 8 with debian 12 6.12.3 nmtui/nmcli reflects no wireless hardware.

**Comment by greysonofusa** [comment]
> Those using Debian might have luck with the backport version of [firmware-iwlwifi](https://packages.debian.org/bookworm-backports/firmware-iwlwifi), since it seems to include the right firmware: https://packages.debian.org/search?suite=bookworm-backports&arch=any&searchon=contents&keywords=iwlwifi-QuZ-a0-hr-b0-77.ucode
> 
> I am no expert on Debian, so please consult the Debian manuals on installing backports.

Debian 12 with Surface 8 iwlwifi was already installed for me. Good suggestion though.

**Comment by greysonofusa** [comment]
Uninstalled existing reinstalled with back ports. Still not working in the
kernel update for surface pro 8.

**Comment by greysonofusa** [comment]
> > Uninstalled existing reinstalled with back ports. Still not working in the kernel update for surface pro 8.
> 
> Can you post the output of `sudo dmesg | grep iwlwifi`, `dpkg -L firmware-iwlwifi` and `apt show -a firmware-iwlwifi`? As for the output of dmesg, you might want to redact your MAC address before posting the output.


gjones  ~  09:30  sudo dmesg | grep iwlwifi
[sudo] password for gjones: 
[    5.223313] iwlwifi 0000:00:14.3: enabling device (0000 -> 0002)
[    5.228192] iwlwifi 0000:00:14.3: Detected crf-id 0x3617, cnv-id 0x20000302 wfpm id 0x80000000
[    5.228256] iwlwifi 0000:00:14.3: PCI dev a0f0/0074, rev=0x351, rfid=0x10a100
[    5.228259] iwlwifi 0000:00:14.3: Detected Intel(R) Wi-Fi 6 AX201 160MHz
[    5.229058] iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-77.ucode failed with error -2
[    5.229068] iwlwifi 0000:00:14.3: no suitable firmware found!
[    5.229069] iwlwifi 0000:00:14.3: iwlwifi-QuZ-a0-hr-b0-77 is required
[    5.229070] iwlwifi 0000:00:14.3: check git://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git

gjones  ~  09:31  sudo dpkg -L firmware-iwlwifi
/.
/lib
/lib/firmware
/lib/firmware/intel
/lib/firmware/intel/ibt-0040-0041.ddc
/lib/firmware/intel/ibt-0040-0041.sfi
/lib/firmware/intel/ibt-0040-4150.ddc
/lib/firmware/intel/ibt-0040-4150.sfi
/lib/firmware/intel/ibt-0041-0041.ddc
/lib/firmware/intel/ibt-0041-0041.sfi
/lib/firmware/intel/ibt-1040-0041.ddc
/lib/firmware/intel/ibt-1040-0041.sfi
/lib/firmware/intel/ibt-1040-4150.ddc
/lib/firmware/intel/ibt-1040-4150.sfi
/lib/firmware/intel/ibt-11-5.ddc
/lib/firmware/intel/ibt-11-5.sfi
/lib/firmware/intel/ibt-12-16.ddc
/lib/firmware/intel/ibt-12-16.sfi
/lib/firmware/intel/ibt-17-0-1.ddc
/lib/firmware/intel/ibt-17-0-1.sfi
/lib/firmware/intel/ibt-17-16-1.ddc
/lib/firmware/intel/ibt-17-16-1.sfi
/lib/firmware/intel/ibt-18-0-1.ddc
/lib/firmware/intel/ibt-18-0-1.sfi
/lib/firmware/intel/ibt-18-16-1.ddc
/lib/firmware/intel/ibt-18-16-1.sfi
/lib/firmware/intel/ibt-19-0-0.ddc
/lib/firmware/intel/ibt-19-0-0.sfi
/lib/firmware/intel/ibt-19-0-1.ddc
/lib/firmware/intel/ibt-19-0-1.sfi
/lib/firmware/intel/ibt-19-0-4.ddc
/lib/firmware/intel/ibt-19-0-4.sfi
/lib/firmware/intel/ibt-19-16-4.ddc
/lib/firmware/intel/ibt-19-16-4.sfi
/lib/firmware/intel/ibt-19-240-1.ddc
/lib/firmware/intel/ibt-19-240-1.sfi
/lib/firmware/intel/ibt-19-240-4.ddc
/lib/firmware/intel/ibt-19-240-4.sfi
/lib/firmware/intel/ibt-19-32-0.ddc
/lib/firmware/intel/ibt-19-32-0.sfi
/lib/firmware/intel/ibt-19-32-1.ddc
/lib/firmware/intel/ibt-19-32-1.sfi
/lib/firmware/intel/ibt-19-32-4.ddc
/lib/firmware/intel/ibt-19-32-4.sfi
/lib/firmware/intel/ibt-20-0-3.ddc
/lib/firmware/intel/ibt-20-0-3.sfi
/lib/firmware/intel/ibt-20-1-3.ddc
/lib/firmware/intel/ibt-20-1-3.sfi
/lib/firmware/intel/ibt-20-1-4.ddc
/lib/firmware/intel/ibt-20-1-4.sfi
/lib/firmware/intel/ibt-hw-37.7.10-fw-1.0.1.2d.d.bseq
/lib/firmware/intel/ibt-hw-37.7.10-fw-1.0.2.3.d.bseq
/lib/firmware/intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq
/lib/firmware/intel/ibt-hw-37.7.10-fw-1.80.2.3.d.bseq
/lib/firmware/intel/ibt-hw-37.7.bseq
/lib/firmware/intel/ibt-hw-37.8.10-fw-1.10.2.27.d.bseq
/lib/firmware/intel/ibt-hw-37.8.10-fw-1.10.3.11.e.bseq
/lib/firmware/intel/ibt-hw-37.8.10-fw-22.50.19.14.f.bseq
/lib/firmware/intel/ibt-hw-37.8.bseq
/lib/firmware/iwlwifi-100-5.ucode
/lib/firmware/iwlwifi-1000-5.ucode
/lib/firmware/iwlwifi-105-6.ucode
/lib/firmware/iwlwifi-135-6.ucode
/lib/firmware/iwlwifi-2000-6.ucode
/lib/firmware/iwlwifi-2030-6.ucode
/lib/firmware/iwlwifi-3160-17.ucode
/lib/firmware/iwlwifi-3168-29.ucode
/lib/firmware/iwlwifi-3945-2.ucode
/lib/firmware/iwlwifi-4965-2.ucode
/lib/firmware/iwlwifi-5000-5.ucode
/lib/firmware/iwlwifi-5150-2.ucode
/lib/firmware/iwlwifi-6000-4.ucode
/lib/firmware/iwlwifi-6000g2a-6.ucode
/lib/firmware/iwlwifi-6000g2b-6.ucode
/lib/firmware/iwlwifi-6050-5.ucode
/lib/firmware/iwlwifi-7260-17.ucode
/lib/firmware/iwlwifi-7265-17.ucode
/lib/firmware/iwlwifi-7265D-29.ucode
/lib/firmware/iwlwifi-8000C-36.ucode
/lib/firmware/iwlwifi-8265-36.ucode
/lib/firmware/iwlwifi-9000-pu-b0-jf-b0-34.ucode
/lib/firmware/iwlwifi-9000-pu-b0-jf-b0-38.ucode
/lib/firmware/iwlwifi-9000-pu-b0-jf-b0-46.ucode
/lib/firmware/iwlwifi-9260-th-b0-jf-b0-34.ucode
/lib/firmware/iwlwifi-9260-th-b0-jf-b0-38.ucode
/lib/firmware/iwlwifi-9260-th-b0-jf-b0-46.ucode
/lib/firmware/iwlwifi-Qu-b0-hr-b0-50.ucode
/lib/firmware/iwlwifi-Qu-b0-hr-b0-59.ucode
/lib/firmware/iwlwifi-Qu-b0-hr-b0-72.ucode
/lib/firmware/iwlwifi-Qu-b0-jf-b0-50.ucode
/lib/firmware/iwlwifi-Qu-b0-jf-b0-59.ucode
/lib/firmware/iwlwifi-Qu-b0-jf-b0-72.ucode
/lib/firmware/iwlwifi-Qu-c0-hr-b0-50.ucode
/lib/firmware/iwlwifi-Qu-c0-hr-b0-59.ucode
/lib/firmware/iwlwifi-Qu-c0-hr-b0-72.ucode
/lib/firmware/iwlwifi-Qu-c0-jf-b0-50.ucode
/lib/firmware/iwlwifi-Qu-c0-jf-b0-59.ucode
/lib/firmware/iwlwifi-Qu-c0-jf-b0-72.ucode
/lib/firmware/iwlwifi-QuZ-a0-hr-b0-50.ucode
/lib/firmware/iwlwifi-QuZ-a0-hr-b0-59.ucode
/lib/firmware/iwlwifi-QuZ-a0-hr-b0-72.ucode
/lib/firmware/iwlwifi-QuZ-a0-jf-b0-50.ucode
/lib/firmware/iwlwifi-QuZ-a0-jf-b0-59.ucode
/lib/firmware/iwlwifi-QuZ-a0-jf-b0-72.ucode
/lib/firmware/iwlwifi-cc-a0-50.ucode
/lib/firmware/iwlwifi-cc-a0-59.ucode
/lib/firmware/iwlwifi-cc-a0-72.ucode
/lib/firmware/iwlwifi-so-a0-gf-a0-72.ucode
/lib/firmware/iwlwifi-so-a0-gf-a0.pnvm
/lib/firmware/iwlwifi-so-a0-gf4-a0-72.ucode
/lib/firmware/iwlwifi-so-a0-gf4-a0.pnvm
/lib/firmware/iwlwifi-so-a0-hr-b0-72.ucode
/lib/firmware/iwlwifi-so-a0-jf-b0-72.ucode
/lib/firmware/iwlwifi-ty-a0-gf-a0-59.ucode
/lib/firmware/iwlwifi-ty-a0-gf-a0-66.ucode
/lib/firmware/iwlwifi-ty-a0-gf-a0-72.ucode
/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm
/usr
/usr/share
/usr/share/bug
/usr/share/bug/firmware-iwlwifi
/usr/share/bug/firmware-iwlwifi/presubj
/usr/share/doc
/usr/share/doc/firmware-iwlwifi
/usr/share/doc/firmware-iwlwifi/changelog.Debian.gz
/usr/share/doc/firmware-iwlwifi/copyright
/usr/share/metainfo
/usr/share/metainfo/firmware-iwlwifi.metainfo.xml

gjones  ~  09:32  sudo apt show -a firmware-iwlwifi
Package: firmware-iwlwifi
Version: 20230210-5
Priority: optional
Section: non-free-firmware/kernel
Source: firmware-nonfree
Maintainer: Debian Kernel Team <debian-kernel@lists.debian.org>
Installed-Size: 84.3 MB
Suggests: initramfs-tools
Homepage: https://git.kernel.org/cgit/linux/kernel/git/firmware/linux-firmware.git
Download-Size: 9,336 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bookworm/non-free-firmware amd64 Packages
Description: Binary firmware for Intel Wireless cards
 This package contains the binary firmware for Intel Wireless cards
 supported by the iwl3945, iwl4965, and iwlwifi drivers.
 .
 Contents:
  * Intel Wireless 8260 Bluetooth configuration, version 20.10.0.8
    (intel/ibt-11-5.ddc)
  * Intel Wireless 8260 Bluetooth firmware, version 20.100.0.3
    (intel/ibt-11-5.sfi)
  * Intel Wireless 8265 Bluetooth configuration, version 20.30.0.1
    (intel/ibt-12-16.ddc)
  * Intel Wireless 8265 Bluetooth firmware, version 21.10.0.6
    (intel/ibt-12-16.sfi)
  * Intel Wireless 9460/9650 (var 0 rev 1) Bluetooth configuration,
    version 20.10 (intel/ibt-17-0-1.ddc)
  * Intel Wireless 9460/9650 (var 0 rev 1) Bluetooth firmware, version
    20.30.0.1 (intel/ibt-17-0-1.sfi)
  * Intel Wireless 9460/9650 (var 16 rev 1) Bluetooth configuration,
    version 20.60.0.2 (intel/ibt-17-16-1.ddc)
  * Intel Wireless 9460/9650 (var 16 rev 1) Bluetooth firmware, version
    22.200.0.2 (intel/ibt-17-16-1.sfi)
  * Intel Wireless 9160/9260 (var 0 rev 1) Bluetooth configuration,
    version 20.10 (intel/ibt-18-0-1.ddc)
  * Intel Wireless 9160/9260 (var 0 rev 1) Bluetooth firmware, version
    20.30.0.1 (intel/ibt-18-0-1.sfi)
  * Intel Wireless 9160/9260 (var 16 rev 1) Bluetooth configuration,
    version 20.60.0.2 (intel/ibt-18-16-1.ddc)
  * Intel Wireless 9160/9260 (var 16 rev 1) Bluetooth firmware, version
    22.200.0.2 (intel/ibt-18-16-1.sfi)
  * Intel Bluetooth AX201 (var 0 rev 0) configuration, version 21.20.0.4
    (intel/ibt-19-0-0.ddc)
  * Intel Bluetooth AX201 (var 0 rev 0) firmware, version 22.200.0.2
    (intel/ibt-19-0-0.sfi)
  * Intel Bluetooth AX201 (var 0 rev 1) configuration, version
    22.200.0.2 (intel/ibt-19-0-1.ddc)
  * Intel Bluetooth AX201 (var 0 rev 1) firmware, version 22.180.0.2
    (intel/ibt-19-0-1.sfi)
  * Intel Bluetooth AX201 (var 0 rev 4) configuration, version 21.20.0.4
    (intel/ibt-19-0-4.ddc)
  * Intel Bluetooth AX201 (var 0 rev 4) firmware, version 22.200.0.2
    (intel/ibt-19-0-4.sfi)
  * Intel Bluetooth AX201 (var 16 rev 4) configuration, version
    21.20.0.4 (intel/ibt-19-16-4.ddc)
  * Intel Bluetooth AX201 (var 16 rev 4) firmware, version 22.200.0.2
    (intel/ibt-19-16-4.sfi)
  * Intel Bluetooth AX201 firmware, version 21.110.0.3
    (intel/ibt-19-240-1.ddc)
  * Intel Bluetooth AX201 firmware, version 22.200.0.2
    (intel/ibt-19-240-1.sfi)
  * Intel Bluetooth AX201 firmware, version 21.90.0.3
    (intel/ibt-19-240-4.ddc)
  * Intel Bluetooth AX201 firmware, version 22.200.0.2
    (intel/ibt-19-240-4.sfi)
  * Intel Bluetooth AX201 (var 32 rev 0) configuration
    (intel/ibt-19-32-0.ddc)
  * Intel Bluetooth AX201 (var 32 rev 0) firmware, version 22.200.0.2
    (intel/ibt-19-32-0.sfi)
  * Intel Bluetooth AX201 (var 32 rev 1) configuration, version
    21.20.0.4 (intel/ibt-19-32-1.ddc)
  * Intel Bluetooth AX201 (var 32 rev 1) firmware, version 22.200.0.2
    (intel/ibt-19-32-1.sfi)
  * Intel Bluetooth AX201 (var 32 rev 4) configuration, version
    21.90.0.3 (intel/ibt-19-32-4.ddc)
  * Intel Bluetooth AX201 (var 32 rev 4) firmware, version 22.200.0.2
    (intel/ibt-19-32-4.sfi)
  * Intel Wireless 22161 (var 0 rev 3) Bluetooth configuration, version
    22.200.0.2 (intel/ibt-20-0-3.ddc)
  * Intel Wireless 22161 (var 0 rev 3) Bluetooth firmware, version
    22.180.0.2 (intel/ibt-20-0-3.sfi)
  * Intel Wireless 22161 (var 1 rev 3) Bluetooth configuration, version
    21.0.0.4 (intel/ibt-20-1-3.ddc)
  * Intel Wireless 22161 (var 1 rev 3) Bluetooth firmware, version
    22.200.0.2 (intel/ibt-20-1-3.sfi)
  * Intel Wireless 22161 (var 1 rev 4) Bluetooth configuration
    (intel/ibt-20-1-4.ddc)
  * Intel Wireless 22161 (var 1 rev 4) Bluetooth firmware, version
    22.200.0.2 (intel/ibt-20-1-4.sfi)
  * Intel Wireless AX211 Bluethooth configuration, version 22.80.0.4
    (intel/ibt-0040-0041.ddc)
  * Intel Wireless AX211 Bluethooth firmware, version 22.200.0.2
    (intel/ibt-0040-0041.sfi)
  * intel/ibt-1040-0041.ddc
  * intel/ibt-1040-0041.sfi
  * Intel Wireless AX2100 Bluethooth configuration, version 22.00.0.0
    (intel/ibt-0041-0041.ddc)
  * Intel Wireless AX2100 Bluethooth firmware, version 22.200.0.2
    (intel/ibt-0041-0041.sfi)
  * Intel Wireless Bluetooth AX201 configuration, version 22.80.0.4
    (intel/ibt-0040-4150.ddc)
  * Intel Wireless Bluetooth AX201 firmware, version 22.200.0.2
    (intel/ibt-0040-4150.sfi)
  * Intel Wireless Bluetooth AX201 configuration, version 22.80.0.4
    (intel/ibt-1040-4150.ddc)
  * Intel Wireless Bluetooth AX201 firmware, version 22.200.0.2
    (intel/ibt-1040-4150.sfi)
  * Intel Wireless 3160 (B6) Bluetooth firmware patch, version 19.30
    (intel/ibt-hw-37.7.10-fw-1.0.1.2d.d.bseq)
  * Intel Wireless 3160 (B4) Bluetooth firmware patch, version 19.01
    (intel/ibt-hw-37.7.10-fw-1.0.2.3.d.bseq)
  * Intel Wireless 7260 (B5) Bluetooth firmware patch, version 20.60.0.2
    (intel/ibt-hw-37.7.10-fw-1.80.1.2d.d.bseq)
  * Intel Wireless 7260 (B3) Bluetooth firmware patch, version 20.60.0.2
    (intel/ibt-hw-37.7.10-fw-1.80.2.3.d.bseq)
  * Intel Wireless 7260 Bluetooth firmware generic patch
    (intel/ibt-hw-37.7.bseq)
  * Intel Wireless 7265 (C0) Bluetooth firmware patch, version 19.30
    (intel/ibt-hw-37.8.10-fw-1.10.2.27.d.bseq)
  * Intel Wireless 7265 (D0) Bluetooth firmware patch, version 20.60.0.2
    (intel/ibt-hw-37.8.10-fw-1.10.3.11.e.bseq)
  * Intel Wireless 7265 (D1) Bluetooth firmware patch, version 20.70.0.4
    (intel/ibt-hw-37.8.10-fw-22.50.19.14.f.bseq)
  * Intel Wireless 7265 Bluetooth firmware generic patch
    (intel/ibt-hw-37.8.bseq)
  * Intel Wireless 100 firmware, version 39.31.5.1 (iwlwifi-100-5.ucode)
  * Intel Wireless 105 firmware, version 18.168.6.1
    (iwlwifi-105-6.ucode)
  * Intel Wireless 135 firmware, version 18.168.6.1
    (iwlwifi-135-6.ucode)
  * Intel Wireless 1000 firmware, version 39.31.5.1
    (iwlwifi-1000-5.ucode)
  * Intel Wireless 2200 firmware, version 18.168.6.1
    (iwlwifi-2000-6.ucode)
  * Intel Wireless 2230 firmware, version 18.168.6.1
    (iwlwifi-2030-6.ucode)
  * Intel Wireless 3160 firmware, version 17.bfb58538.0
    (iwlwifi-3160-17.ucode)
  * Intel Wireless 3168 firmware, version 29.0bd893f3.0
    (iwlwifi-3168-29.ucode)
  * Intel Wireless 3945 firmware, version 15.32.2.9
    (iwlwifi-3945-2.ucode)
  * Intel Wireless 4965 firmware, version 228.61.2.24
    (iwlwifi-4965-2.ucode)
  * Intel Wireless 5100, 5300 and 5350 firmware, version 8.83.5.1
    (iwlwifi-5000-5.ucode)
  * Intel Wireless 5150 firmware, version 8.24.2.2
    (iwlwifi-5150-2.ucode)
  * Intel Wireless 6000 firmware, version 9.221.4.1
    (iwlwifi-6000-4.ucode)
  * Intel Wireless 6005/6205 firmware, version 18.168.6.1
    (iwlwifi-6000g2a-6.ucode)
  * Intel Wireless 6030 firmware, version 18.168.6.1
    (iwlwifi-6000g2b-6.ucode)
  * Intel Wireless 6250 firmware, version 41.28.5.1
    (iwlwifi-6050-5.ucode)
  * Intel Wireless 7260 firmware, version 17.bfb58538.0
    (iwlwifi-7260-17.ucode)
  * Intel Wireless 7265 firmware, version 17.bfb58538.0
    (iwlwifi-7265-17.ucode)
  * Intel Wireless 7265D firmware, version 29.0bd893f3.0
    (iwlwifi-7265D-29.ucode)
  * Intel Wireless 8000C firmware, version 36.ca7b901d.0
    (iwlwifi-8000C-36.ucode)
  * Intel Wireless 8265 firmware, version 36.ca7b901.0
    (iwlwifi-8265-36.ucode)
  * Intel Wireless 9000 firmware, version 34.ba501b11.0
    (iwlwifi-9000-pu-b0-jf-b0-34.ucode)
  * Intel Wireless 9000 firmware, version 38.755cfdd8.0
    (iwlwifi-9000-pu-b0-jf-b0-38.ucode)
  * Intel Wireless 9000 firmware, version 46.ea3728ee.0
    (iwlwifi-9000-pu-b0-jf-b0-46.ucode)
  * Intel Wireless 9260 firmware, version 34.ba501b11.0
    (iwlwifi-9260-th-b0-jf-b0-34.ucode)
  * Intel Wireless 9260 firmware, version 38.755cfdd8.0
    (iwlwifi-9260-th-b0-jf-b0-38.ucode)
  * Intel Wireless 9260 firmware, version 46.ea3728ee.0
    (iwlwifi-9260-th-b0-jf-b0-46.ucode)
  * Intel Wireless 22000 series (QU-B-HR-B) firmware, version
    50.3e391d3e.0 (iwlwifi-Qu-b0-hr-b0-50.ucode)
  * Intel Wireless 22000 series (QU-B-HR-B) firmware, version
    59.601f3a66.0 (iwlwifi-Qu-b0-hr-b0-59.ucode)
  * Intel Wireless 22000 series (QU-B-HR-B) firmware, version
    72.daa05125.0 (iwlwifi-Qu-b0-hr-b0-72.ucode)
  * Intel Wireless 22000 series (QU-B-JF-B) firmware, version
    50.3e391d3e.0 (iwlwifi-Qu-b0-jf-b0-50.ucode)
  * Intel Wireless 22000 series (QU-B-JF-B) firmware, version
    59.601f3a66.0 (iwlwifi-Qu-b0-jf-b0-59.ucode)
  * Intel Wireless 22000 series (QU-B-JF-B) firmware, version
    72.daa05125.0 (iwlwifi-Qu-b0-jf-b0-72.ucode)
  * Intel Wireless 22000 series (QU-C-HR-B) firmware, version
    50.3e391d3e.0 (iwlwifi-Qu-c0-hr-b0-50.ucode)
  * Intel Wireless 22000 series (QU-C-HR-B) firmware, version
    59.601f3a66.0 (iwlwifi-Qu-c0-hr-b0-59.ucode)
  * Intel Wireless 22000 series (QU-C-HR-B) firmware, version
    72.daa05125.0 (iwlwifi-Qu-c0-hr-b0-72.ucode)
  * Intel Wireless 22000 series (QU-C-JF-B) firmware, version
    50.3e391d3e.0 (iwlwifi-Qu-c0-jf-b0-50.ucode)
  * Intel Wireless 22000 series (QU-C-JF-B) firmware, version
    59.601f3a66.0 (iwlwifi-Qu-c0-jf-b0-59.ucode)
  * Intel Wireless 22000 series (QU-C-JF-B) firmware, version
    72.daa05125.0 (iwlwifi-Qu-c0-jf-b0-72.ucode)
  * Intel Wireless 22000 series (QUZ-A-HR-B) firmware, version
    50.3e391d3e.0 (iwlwifi-QuZ-a0-hr-b0-50.ucode)
  * Intel Wireless 22000 series (QUZ-A-HR-B) firmware, version
    59.601f3a66.0 (iwlwifi-QuZ-a0-hr-b0-59.ucode)
  * Intel Wireless 22000 series (QUZ-A-HR-B) firmware, version
    72.daa05125.0 (iwlwifi-QuZ-a0-hr-b0-72.ucode)
  * Intel Wireless 22000 series (QUZ-A-JF-B) firmware, version
    50.3e391d3e.0 (iwlwifi-QuZ-a0-jf-b0-50.ucode)
  * Intel Wireless 22000 series (QUZ-A-JF-B) firmware, version
    59.601f3a66.0 (iwlwifi-QuZ-a0-jf-b0-59.ucode)
  * Intel Wireless 22000 series (QUZ-A-JF-B) firmware, version
    72.daa05125.0 (iwlwifi-QuZ-a0-jf-b0-72.ucode)
  * Intel Wireless series (CC-A0) firmware, version 50.3e391d3e.0
    (iwlwifi-cc-a0-50.ucode)
  * Intel Wireless series (CC-A0) firmware, version 59.601f3a66.0
    (iwlwifi-cc-a0-59.ucode)
  * Intel Wireless series (CC-A0) firmware, version 72.daa05125.0
    (iwlwifi-cc-a0-72.ucode)
  * Intel Wireless (TY-A0-GF-A0) firmware, version 59.601f3a66.0
    (iwlwifi-ty-a0-gf-a0-59.ucode)
  * Intel Wireless (TY-A0-GF-A0) firmware, version 66.55c64978.0
    (iwlwifi-ty-a0-gf-a0-66.ucode)
  * Intel Wireless (TY-A0-GF-A0) firmware, version 72.daa05125.0
    (iwlwifi-ty-a0-gf-a0-72.ucode)
  * Intel Wireless (TY-A0-GF-A0) PNVM firmware, version 76.27f1c37b.0
    (iwlwifi-ty-a0-gf-a0.pnvm)
  * Intel Wireless (SO-A0-GF-A0) firmware, version 72.daa05125.0
    (iwlwifi-so-a0-gf-a0-72.ucode)
  * Intel Wireless (SO-A0-GF-A0) PNVM firmware, version 76.27f1c37b.0
    (iwlwifi-so-a0-gf-a0.pnvm)
  * iwlwifi-so-a0-gf4-a0-72.ucode
  * Intel Wireless (SO-A0-GF4-A0) PNVM firmware, version 76.27f1c37b.0
    (iwlwifi-so-a0-gf4-a0.pnvm)
  * Intel Wireless (SO-A0-HR-B0) firmware, version 72.daa05125.0
    (iwlwifi-so-a0-hr-b0-72.ucode)
  * Intel Wireless (SO-A0-JF-B0) firmware, version 72.daa05125.0
    (iwlwifi-so-a0-jf-b0-72.ucode)

**Comment by maremike** [comment]
Worked for me as well.

**Comment by qzed** [comment]
@groengpx Could you find any reason for why the required version was bumped?

**Comment by qzed** [comment]
Also according to github it's there since v6.11-rc1, so should v6.11 not also be affected and not just v6.12?

Apart from that, I'm kind of hesitant to just drop it because there are other min version bumps around/after that as well, and a couple of other changes where (from a very quick look) I can't tell whether they could require newer firmware. So I can't tell whether that will fix things or create new problems. Can anyone check whether reverting that commit does help?

**Comment by qzed** [comment]
@groengpx The problem is that I can't really tell whether changes are related or not without looking into it in more detail (and I'm unfortunately missing the time for that right now). For example on the surface just looking for API yields a bunch of commits that seem to do some changes potentially related to firmware APIs.

```
9715246ca0bf wifi: iwlwifi: mvm: Use the sync timepoint API in suspend
4d8ff1f7df43 wifi: iwlwifi: mvm: add API for EML OMN frame failure
ec6ba5367eaa wifi: iwlwifi: mvm: add the new API for the missed beacons notification
c4fe1c84b2b3 wifi: iwlwifi: update the BA notification API
```

Could likely be that things work out just fine by reverting it and there is really no reason. I'd just need someone to verify that it doesn't break anything and then I'd consider adding it.
