### ISSUE TITLE
SB1: Touchscreen only works for a split-second - 4.19 LTS Kernel

### ISSUE THREAD

**Issue by xabotage** [linux-surface/linux-surface#163]
Touchscreen not working on my Surface Book 1. If I tap and drag my finger on the screen (e.g. highlighting text), it works for a split second them immediately stops working.

Reloading the kernel module with `sudo modprobe -r ipts-surface && sudo modprobe ipts-surface` only "resets" the same behavior, meaning after the module is reloaded the touchscreen will again only work for a split second after I try to use it. **(Details provided in dmesg output at end of post)**

Is there some kind of input buffer getting filled up somewhere and causing the touchscreen to stop responding? Does anyone know how I can find more logs/messages relating to the status of the touchscreen driver, since dmesg isn't showing anything?

### Environment

- Hardware model: Surface Book 1
- Kernel version: Linux myusername 4.19.114-surface-lts #1 SMP Thu Apr 2 22:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 18.04

<details><summary>`dmesg` results</summary>

`dmesg` output when running `sudo modprobe -r ipts-surface`:
```
[ 1088.045395] IPTS ipts_mei_cl_exit() is called
[ 1088.046833] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: 0x80000007 failed status = 19
[ 1088.141484] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: error in reading m2h msg
[ 1088.141497] IPTS removed
```

`dmesg` output when running `sudo modprobe ipts-surface`:

```
[  252.689401] IPTS ipts_mei_cl_init() is called
[  252.705800] probing Intel Precise Touch & Stylus
[  252.705804] IPTS using DMA_BIT_MASK(64)
[  252.722939] input: ipts 1B96:005E Pen as /devices/pci0000:00/0000:00:16.4/0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04/0044:1B96:005E.0004/input/input35
[  252.723254] input: ipts 1B96:005E as /devices/pci0000:00/0000:00:16.4/0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04/0044:1B96:005E.0004/input/input36
[  252.725018] input: ipts 1B96:005E UNKNOWN as /devices/pci0000:00/0000:00:16.4/0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04/0044:1B96:005E.0004/input/input40
[  252.725291] hid-multitouch 0044:1B96:005E.0004: input,hidraw1: <UNKNOWN> HID v13300.fa Mouse [ipts 1B96:005E] on heci3
```

No messages of any kind appear in dmesg when the touchscreen fails. I'm not sure where to look for additional logs/errors for the ipts driver.

</details>

**Comment by qzed** [comment]
This could be related to the `no_feedback` quirk (https://github.com/linux-surface/linux-surface/wiki/Known-Issues#v419-ipts-touchscreen-driver-stops-working-sp4-and-sb1). Try re-loading `intel_ipts` with `no_feedback=0` (you need to unload `ipts_surface` before and re-load it after, as described in the wiki).

**Comment by xabotage** [comment]
Thank you, that seems to have done the trick!

For posterity, the above link instructs the following to disable the `no_feedback` parameter of intel_ipts:

```
sudo modprobe -r ipts_surface
sudo modprobe -r intel_ipts
sudo modprobe intel_ipts no_feedback=0
sudo modprobe ipts_surface
```

For a permanent solution, I added the file: `/etc/modprobe.d/intel-ipts.conf` with the following line:
```
options intel_ipts no_feedback=0
```
Closing this issue for now.
