### ISSUE TITLE
KConfig Missing?

### ISSUE THREAD

**Issue by wd5gnr** [linux-surface/linux-surface#170]
I've had the display link driver working with an older version of the kernel (5.1.15). However, with 5.6.5 I can't get it to build. The installer fails because it can't find Kconfig. I did install the headers but there is only a .config in there. It is odd, too, that I have:

/usr/src/linux-headers-surface

However,

I do not have /usr/src/linux-headers-5.6.5-surface

I do have /lib/modules/5.6.5-surface

OS is Neon and I installed using the Debian repo.

Any ideas?

### Environment

- Hardware model: Surface Book
- Kernel version: 5.6.5-surface
- Distribution: Neon

**Comment by archseer** [comment]
Dittoing the response from reddit:

Did you install the header package (linux-headers-surface for ubuntu) as per https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup ?

Did you reboot after updating the kernel? It keeps looking for the old revision for me until I reboot into the new kernel version.

**Comment by wd5gnr** [comment]
Yes, the header package is installed and yes, the system has been rebooted
numerous times.

**Comment by qzed** [comment]
I've looked into the latest `linux-headers-surface` package and there indeed seems to be quite a lot missing from `/usr/src/linux-headers-<version>`, compared to what I have on Arch. I'll try to figure out why that is.

**Comment by wd5gnr** [comment]
Thank you. I wonder if I could pull the arch package and replace the missing files in the source tree? I may experiment with that.

**Comment by qzed** [comment]
As there are Kconfig files in there, I wouldn't recommend that.

**Comment by qzed** [comment]
Here's the relevant part in the upstream packaging scripts (which we're using in a slightly modified version): https://github.com/torvalds/linux/blob/f66ed1ebbfde37631fba289f7c399eaa70632abf/scripts/package/builddeb#L54-L60. Note how they don't include the `Kconfig` files. This change was apparently made for 5.6 and 5.5 versions still include the `Kconfig` files. I'll try to track down the mailing list entry for that change, maybe there's some reason behind that.

**Comment by qzed** [comment]
Found it: https://lkml.org/lkml/2020/1/4/25 / https://github.com/torvalds/linux/commit/9945722afdc3443eab826b2da1122509a13a50a5. I have reverted it in our modified version.

**Comment by qzed** [comment]
A new build is on its way.

**Comment by wd5gnr** [comment]
Awesome! Thank you.

**Comment by wd5gnr** [comment]
Just to follow up, worked great. I was able to build the drivers and once again have two screens. Big thanks.

**Comment by niklas-simon** [comment]
I'm now running into the same Issue. Upon navigating to /usr/src/linux-headers-6.8.1-surface-1`, running `make config` as root yields the error `can't find file Kconfig`. Am I doing something wrong?

### Environment

    Hardware model: Surface Pro 8
    Kernel version: 6.8.1-surface
    Distribution: Vanilla OS (Debian-based)
