### ISSUE TITLE
Surface Book 2 - Cannot Shutdown Due to dGPU

### ISSUE THREAD

**Issue by starvsion** [linux-surface/linux-surface#173]
Fedora won't shutdown, it just hangs at the line `setting dGPU direct power to 'off'` 

### Environment

> I did not install dGPU driver, so it is still using nouveau

- Hardware model: Surface Book 2 15" 1793 (i7, nv 1060)
- Kernel version: 5.6.7-1.surface.fc31.x86_64
- Distribution: Fedora 31

<details><summary>surface_dgpu_hps MSHW0153:00: setting dGPU direct power to 'off'</summary>

```
[    6.477181] ttyS4 - failed to request DMA
[    6.481177] input: Microsoft Surface Base 2 Integration Device as /devices/platform/MSHW0133:00/input/input29
[    6.496520] battery: ACPI: Battery Slot [BAT1] (battery present)
[    6.504168] battery: ACPI: Battery Slot [BAT2] (battery present)
[    6.506209] surface_dgpu_hps MSHW0153:00: setting dGPU power state to 'off'
[    6.506246] surface_dgpu_hps MSHW0153:00: setting dGPU direct power to 'off'
[    6.506250] ACPI Warning: \_SB.SHPS._DSM: Argument #4 type mismatch - Found [Integer], ACPI requires [Package] (20200110/nsarguments-59)
[    6.531718] pcieport 0000:00:1c.4: pciehp: Slot(4): Link Down
[    6.531721] pcieport 0000:00:1c.4: pciehp: Slot(4): Card not present

```

</details>

**Comment by ghostplant** [comment]
Also have this issue using Linux 5.5+, but this issue doesn't happen on Linux 4.9 (but Linux 4.9 has too many other issues.)

I'm not sure whether it is related to dGPU, because there are many other logs no closed successfully as well:
```
[XX.XXXXXXX] sd-umount: Failed to umount /oldroot: Device or resource busy
[XX.XXXXXXX] shutdown: All filesystems umounted.
[XX.XXXXXXX] shutdown: Deactivation swaps.
[XX.XXXXXXX] shutdown: All swaps deactivated.
..
[XX.XXXXXXX] shutdown: Rebooting.
[XX.XXXXXXX] kvm: existing hardware virtualization.
[XX.XXXXXXX] surface_dgpu_hps MSHW0153:00: setting dGPU power state to 'on'.
(..hang forever..)
```

**Comment by ghostplant** [comment]
I am using Ubuntu instead of Fedora. And the issue happens in not only shutdown but also reboot.

**Comment by ghostplant** [comment]
@StollD Can you feature out what's wrong with the kernel logs?

**Comment by ghostplant** [comment]
I actually solved this by disabling dGPU features in Surface BIOS. When dGPU is not enabled, the shutdown will be performed back to normal.

**Comment by StollD** [comment]
> @StollD Can you feature out what's wrong with the kernel logs?

Sadly I have no experience with the dGPU since I dont own a model with one. @qzed has one and wrote the driver code for it, so he will probably know more than I.

**Comment by qzed** [comment]
I suspect that there might be some hick-up in the PCIe core. Basically, when you shut down the device, the dGPU driver turns the device on. This is done to avoid some issues when shutting down the PCIe core, specifically some core drivers trying to disable the device while it's already disabled (i.e. turned off). I've never had any issue with it blocking shutdown completely though.

As a workaround, you could try to (automatically) unload the `surface_sam_hps` module before you shut down. This will turn-on the dGPU before the kernel starts the shutdown procedure, so should avoid any hick-ups with the PCIe core.

**Comment by ghostplant** [comment]
@qzed I tried your suggestion of blacklist surface_sam_hps module, which seems to work when dGPU is re-enabled. What is the impact if I always blacklist this module?

**Comment by qzed** [comment]
By default (without the module), the dGPU is powered on, so that may cause higher battery drain. In the past, the dGPU also got quite a bit warm if it wasn't powered off (or put into some suspended mode after some time by the system). For now I'd recommend you look for some sort of shutdown hook (e.g. systemd) where you can put a script to unload the module before shutdown, as a workaround. I'll try adding a module parameter to disable power-on on shutdown, but I'll need to test that again.

**Comment by ghostplant** [comment]
OK, and now I think disabling dGPU in BIOS satisfies me more since I don't have any requirement to use the secondary GPU at the moment.

**Comment by qzed** [comment]
If you don't need it, that's probably the better workaround.

**Comment by Holmgren825** [comment]
I have the same problem with the surface book 2 13 with the gtx 1050, running pop os with the custom kernel. Turning the dpgu on with the surface utility before shutdown/restart seems to solve the issue.

**Comment by qzed** [comment]
This should be fixed with the next release. Please also have a look at the announcement issues for details as some things regarding the dGPU have changed.
