### ISSUE TITLE
Unsure why Compiling Failed

### ISSUE THREAD

**Issue by condemnedmeat** [linux-surface/linux-surface#179]
I'm just trying to compile the repository with the 5.4 lts kernel on a Pro 6 but I'm a little confused with step 5 and wouldn't mind a little advice please.

I initially installed 4.19-lts but while the buttons etc worked the touchscreen didn't. The os was installed with 5.3, perhaps it's that there is such a numerical difference between the two. Searching dmesg for ipts found this:

[    5.311676] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Direct firmware load for intel/ipts/MSHW0102/intel_desc.bin failed with error -2
[    5.311686] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Direct firmware load for intel/ipts/intel_desc.bin failed with error -2
[    5.311688] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: can't add hid device: -5

I hadn't expected the live usb to come with such a recent kernel, it was installed in place of the very same os which was on 4.15 and regularly updating.

I've gone to compile the 5.4 kernel but it failed for reasons unknown. I suspect I made mistakes in steps 4 & 5. I have compiled before but it never included that step five.

I just would like to understand the instructions better...
In step four, you could download and extract the zip or you could paste this command into terminal?: "git clone --depth 1 https://github.com/linux-surface/linux-surface.git ~/linux-surface"
I really didn't understand step five. The instruction uses the term "check out", is that used to mean have a look at, or is it a technical term similar to the way "checkout" is used earlier in the instructions? It also says "If you choose one of the configurations from the repo, copy it to .config, e.g. via". Is this sentence incomplete? Nonetheless there isn't a brief explanation why I would choose the repo configuration over another one, unless I'm missing something.
Lastly, I couldn't find a folder called "linux-surface-kernel-configs" to copy from which is the path given in the example! Am I missing something?
This is what I put in terminal in the end:
cp ~/kernel-configs-master/5.4/generated/ubuntu-surface-5.4-x86_64.config .config
Is that right?

Thank you!

**Comment by archseer** [comment]
`Direct firmware load for intel/ipts/MSHW0102/intel_desc.bin failed with error -2`

Looks like you didn't install `surface-ipts-firmware` as per the install guide. Make sure to install all the packages listed.

I don't recommend running 5.4 since multitouch will be broken there just like on 5.6. Either run the latest version or run 4.19.
