### ISSUE TITLE
Touchscreen does not rotate

### ISSUE THREAD

**Issue by sphh** [linux-surface/linux-surface#185]
[Description of the bug or feature]

This is probably just a configuration problem, but I could not find any solution on this or other sites, so any help would be appreciated.

The screen rotation works without any problem, but unfortunately the touch screen (pen) is not rotated at all. I could not find any settings in Cinnamon's settings menu... Can anybody help and point me in the right direction. Thanks.

BTW I should mention, that I had Jakeday's kernel installed with his script, before you jumped in (and you are doing a tremendous work! Thanks!!) I tried to remove all his direct modifications of configuration files, which were numerous, but I might have missed on.

### Environment

- Hardware model:  Surface Pro 5 (2017)
- Kernel version:  Linux Surface-Pro-5 5.6.11-surface #1 SMP Fri May 8 09:21:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Linux Mint 19.3 Cinnamon

<details><summary>`dmesg` output</summary>

```
$ dmesg | grep -i ipts
[    4.865324] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Probing IPTS
[    4.865327] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: IPTS using DMA_BIT_MASK(64)
[    4.868050] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting receive loop
[    4.873553] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting data loop
[    4.878958] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:001F found
[    4.879004] input: IPTS Stylus as /devices/virtual/input/input13
[    4.879099] input: IPTS Singletouch as /devices/virtual/input/input14
[    4.922143] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: IPTS enabled
```

</details>

**Comment by SamLukeYes** [comment]
Same issue in Manjaro Cinnamon, Surface Pro 6.

**Comment by sphh** [comment]
It looks like it's a problem with Cinnamon: https://github.com/linuxmint/cinnamon-settings-daemon/issues/188 It would be nice, if rotation could be configured in Cinnamon: Automatic/Manual rotation and which devices are included when the computer changes orientation.

I close it for now, but if you figured out a solution, feel free to post it here.

(BTW that little word "Cinnamon" gave the idea to include it in my search string ...)

**Comment by sphh** [comment]
I updated some information in Cinnamon's bug report https://github.com/linuxmint/cinnamon-settings-daemon/issues/188. Everybody who has more information, please feel free to provide it to the Cinnamon maintainer(s).
