### ISSUE TITLE
surface-ipts-firmware don't find in arch repo

### ISSUE THREAD

**Issue by koyado** [linux-surface/linux-surface#187]
The Surface-ipts-firmware don't find in arch repo, don't have touchscreen in Arch distro.

### Environment

- Hardware model: Surface Pro 2017 
- Kernel version:  Arch LTS
- Distribution:  Arch 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by qzed** [comment]
We've had some issues with the Arch repo yesterday. Should work now and the file should be there. Can you try again?

**Comment by archseer** [comment]
Closing, let us know if the problem still exists.
