### ISSUE TITLE
SP6 touch not working. 

### ISSUE THREAD

**Issue by k-dannemand** [linux-surface/linux-surface#189]
i have libwacom-surface on the machine.

~~~
➜  ~ uname -a
Linux kd-Surface-Pro-6 5.6.11-surface #1 SMP Fri May 8 09:21:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~~~

~~~
➜  ~ libwacom-list-local-devices
# Device node: /dev/input/event15
[Device]
Name=Microsoft Surface Pro 6
ModelName=
DeviceMatch=mei:045e:001f;
Class=ISDV4
Width=10
Height=6
IntegratedIn=Display;System;
Styli=0xffffe;0xfffff;

[Features]
Reversible=false
Stylus=true
Ring=false
Ring2=false
Touch=true
TouchSwitch=false
# StatusLEDs=
NumStrips=0
Buttons=0
~~~

**Comment by StollD** [comment]
The touchscreen driver as of kernel 5.5 upwards only supports either stylus input or singletouch input. The default is stylus mode, so only the stylus will work - touching the screen won't. 

You can find more information about this, including how to switch modes on the wiki: https://github.com/linux-surface/linux-surface/wiki/Known-Issues-and-FAQ#v56-only-single-touch-or-stylus-works

**Comment by k-dannemand** [comment]
Oh didden see that. and i even looked at the wiki : |

but thanks !
