### ISSUE TITLE
SP6 Pen/Touch recognition

### ISSUE THREAD

**Issue by lbayerlein** [linux-surface/linux-surface#190]
Hi,

I am using Xournal++ (with Wayland) and take notes with the microsoft pen. When taking notes, the lines are kind of curly and not straight. Created a screenshot, where you can see it on the "T" of "The" clearly.

![](https://cloud.bayerlein-networks.com/index.php/apps/files_sharing/publicpreview/87GodQZ5R4YTBZF?x=2542&y=911&a=true&file=Screenshot%2520from%25202020-05-12%252011-08-17.png&scalingup=0)

Maybe you have an advice, for solving this behaviour.

### Environment

- Hardware model: Surface 6 Pro (Intel)
- Kernel version: Linux surface6 5.6.11-arch1-1-surface #1 SMP PREEMPT Fri, 08 May 2020 09:19:25 +0000 x86_64 GNU/Linux
- Distribution: Manjaro Linux

If you need further informations, tell me, please.

Thanks very much

**Comment by sphh** [comment]
Is this the same issue as in #145?

**Comment by lbayerlein** [comment]
Ah yes, see that it is the same issue - sorry.

**Comment by qzed** [comment]
Closed as duplicate.
