### ISSUE TITLE
Network manager disconnects periodically (with "radio killswitch" in logs)

### ISSUE THREAD

**Issue by kujma10** [linux-surface/linux-surface#192]
Hello, 

I have a problem with my wifi periodically (~ at least once in day or two) that it suddenly disconnects. Sometimes this happens after waking up the laptop from hibernate. The result is that wifi icon disappears in the system tray and the adapter cannot be found in the settings as well. Restarting network manager from terminal also does not help. Only way I've got currently to get wifi back is to restart the laptop. Also I noticed that every time I restart laptop after this it gets stuck displaying the message like "task kworker blocked for more than X" and then i have to manually turn it off with the power button.

When I checked the network adapter logs, the main message related to this is I think "radio killswitch", see logs below for more details.

After research I did not find any way to fix this problem. I am not sure if this is `linux-surface` problem or the linux kernel itself. Anyway I am posting this here hoping that someone is aware of this issue.  I will be happy to provide more information.
Thanks

### Environment

- Hardware model:  Surface Laptop 2
- Kernel version: Linux kote-surface-laptop-2 5.4.6-surface
- Distribution: Debian, Ubuntu 19.10

<details><summary>network manager logs</summary>

```
May 16 13:29:20 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589628560.1492] device (p2p-dev-wlp2s0): supplicant management interface state: associating -> completed
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0085] device (wlp2s0): state change: activated -> unmanaged (reason 'removed', sys-iface-state: 'removed')
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0086] dhcp4 (wlp2s0): canceled DHCP transaction
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0087] dhcp4 (wlp2s0): state changed bound -> done
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0090] dhcp6 (wlp2s0): canceled DHCP transaction
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0090] dhcp6 (wlp2s0): state changed bound -> done
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0197] manager: NetworkManager state is now CONNECTED_LOCAL
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0201] device (p2p-dev-wlp2s0): state change: disconnected -> unmanaged (reason 'removed', sys-iface-state: 'removed')
May 16 14:12:54 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631174.0487] radio killswitch /sys/devices/pci0000:00/0000:00:1d.0/0000:02:00.0/ieee80211/phy0/rfkill1 disappeared
May 16 14:18:46 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631526.8566] modem-manager: ModemManager no longer available
May 16 14:18:47 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631527.2135] bluez5: NAP: removed interface 28:16:A8:50:B7:58
May 16 14:18:47 kote-surface-laptop-2 systemd[1]: Stopping Network Manager...
May 16 14:18:47 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631527.6042] caught SIGTERM, shutting down normally.
May 16 14:18:47 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631527.6076] device (virbr0-nic): released from master device virbr0
May 16 14:18:47 kote-surface-laptop-2 NetworkManager[800]: <info>  [1589631527.6180] exiting (success)
May 16 14:18:47 kote-surface-laptop-2 systemd[1]: NetworkManager.service: Succeeded.
May 16 14:18:47 kote-surface-laptop-2 systemd[1]: Stopped Network Manager.
-- Reboot --

```

</details>

**Comment by hanyiabc** [comment]
I'm having the same issue. On the latest 5.6.14 surface linux kernel with Ubuntu 18.04 on a new Surface Pro (SP5)

**Comment by guywilsonjr** [comment]
I'm having it on 5.6.14 on SB2 LinuxMint 19.3. But mine drops after 1 hour

**Comment by GankousKhan** [comment]
Same on Surface Pro 3 Pop!_OS Default kernel and Surface Linux kernel 5.6.14

**Comment by kachapman** [comment]
Same on SB2 with Pop!_OS 20.04 and surface-linux 5.7.7

**Comment by jonas2515** [comment]
This looks very much like firmware crashes of the Marvell card (the device gets removed. This should be fixed with the newest kernel, so closing this issue. If the issue persists please reopen and share a `dmesg` log after a disconnect happened.

**Comment by hanyiabc** [comment]
> This looks very much like firmware crashes of the Marvell card (the device gets removed. This should be fixed with the newest kernel, so closing this issue. If the issue persists please reopen and share a `dmesg` log after a disconnect happened.

I actually haven't seen the issue for a while. Maybe it's magically fixed...
