### ISSUE TITLE
SP5: Very high power usage for Bluetooth and Wireless

### ISSUE THREAD

**Issue by sphh** [linux-surface/linux-surface#196]
My Surface Pro 5 never lasted very long on battery, but after one of the last kernel updates (and installation of `laptop-mode-tools`), it is as short as 2 hours. It also shows 30-40% of battery left, just to cease working. When plugged in, I have to wait a bit for the battery to recover for the computer to make it through the boot process. Firstly I thought it's the batteries' fault, because the Surface was mostly plugged in, but then I looked at the `powertop` and noticed, that the WiFi and Bluetooth adapters draw a lot of power. Here are the top lines from the `Device stats` of `powertop` (the display backlight here is set to 100% as a reference):
```
The battery reports a discharge rate of 34.2 W
The power consumed was 200 J
System baseline power is estimated at 41.9 W

Power est.    Usage     Device name
  15.0 W    100.0%        USB device: Bluetooth and Wireless LAN Composite Device (Marvell)
  9.99 W    100.0%        Display backlight
  8.46 W    100.0%        Radio device: mwifiex_pcie
  3.10 W     33.7%        CPU core
  2.59 W      1.6 pkts/s  Network interface: wlp1s0 (mwifiex_pcie)
  1.42 W    100.0%        Radio device: btusb
  957 mW     33.7%        DRAM
  408 mW     33.7%        CPU misc
    0 mW    100.0%        USB device: xHCI Host Controller
    0 mW    100.0%        Audio codec hwC0D0: Realtek (pulseaudio )
    0 mW    100.0%        Audio codec hwC0D2: Intel
```
and here a screenshot of the `Power Statistics`:
![Screenshot from 2020-05-18 21-53-30](https://user-images.githubusercontent.com/4856462/82253960-81555a80-9941-11ea-8bc5-2cc2c124444f.png)

Any ideas, what is going wrong here? Any help is highly appreciated. Thanks.

BTW: The very same kernel and set-up works perfectly on a SP3!

### Environment

- Hardware model:  Surface Pro 5 (2017)
- Kernel version: Linux Surface-Pro-5 5.6.13-surface #1 SMP Sun May 17 01:54:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Linux Mint 19.3 Cinnamon
- Firmware package: linux-firmware 1.173.18 bionic-security, Thu, 16 Apr 2020 07:41:28 +0200
- laptop-mode-tools: 1.71-2ubuntu1, Mon, 22 May 2017 14:51:49 +0530
- /etc/NetworkManager/conf.d/99-surface.conf (but I believe, that's not relevant anymore):
```
[connection]
wifi.powersave = 2

[device]
wifi.scan-rand-mac-address=false
```

<details><summary>`dmesg` output</summary>

`$ dmesg | grep -Ei "(mwi|blue|bt)"`
```
[    3.399567] Btrfs loaded, crc32c=crc32c-intel
[    4.354320] mwifiex_pcie 0000:01:00.0: enabling device (0000 -> 0002)
[    4.356879] mwifiex_pcie: PCI memory map Virt0: ffffbd8b80d00000 PCI memory map Virt2: ffffbd8b81900000
[    5.881725] mwifiex_pcie 0000:01:00.0: info: FW download over, size 843828 bytes
[    6.776570] usb 1-5: Product: Bluetooth and Wireless LAN Composite Device
[    6.851701] mwifiex_pcie 0000:01:00.0: WLAN FW is active
[    6.917913] mwifiex_pcie 0000:01:00.0: Unknown api_id: 4
[    6.938398] mwifiex_pcie 0000:01:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.7.p154) 
[    6.938401] mwifiex_pcie 0000:01:00.0: driver_version = mwifiex 1.0 (15.68.7.p154) 
[    6.945609] mwifiex_pcie 0000:01:00.0 wlp1s0: renamed from mlan0
[    6.970836] mwifiex_pcie 0000:01:00.0: Request to enable ps_mode received but it's disallowed by module parameter. Rejecting the request.
[    9.545689] Bluetooth: Core ver 2.22
[    9.545711] Bluetooth: HCI device and connection manager initialized
[    9.545714] Bluetooth: HCI socket layer initialized
[    9.545716] Bluetooth: L2CAP socket layer initialized
[    9.545719] Bluetooth: SCO socket layer initialized
[    9.551667] Bluetooth: hci0: unexpected event for opcode 0x0000
[    9.552004] usbcore: registered new interface driver btusb
[    9.554296] Bluetooth: hci0: unexpected event for opcode 0x0000
[   10.582854] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   10.582857] Bluetooth: BNEP filters: protocol multicast
[   10.582865] Bluetooth: BNEP socket layer initialized
[   11.257529] mwifiex_pcie 0000:01:00.0: info: trying to associate to 'BLABLA' bssid b4:86:55:8d:14:56
[   11.292780] mwifiex_pcie 0000:01:00.0: info: associated to bssid b4:86:55:8d:14:56 successfully
[   13.593292] Bluetooth: RFCOMM TTY layer initialized
[   13.593297] Bluetooth: RFCOMM socket layer initialized
[   13.593301] Bluetooth: RFCOMM ver 1.11

```

</details>

**Comment by tarmack** [comment]
The power draw in your data does not make sense, but not to worry, the hardware simply doesn't measure it and the values that you see are essentially random. This also makes any software that uses that data to estimate the leftover runtime useless.

You mention that your tablet stops working at 30-40% battery. Do you mean that at that moment the tablet just goes out suddenly (emergency shutdown)? Because if that is the case there may be some power daemon running that shuts the tablet down when the remaining runtime is very short. This type of software generally uses the above mentioned (bogus on the SP5, and maybe others?) and as such triggers way too soon.

The last option that I can think of is that your battery is old and on its last legs. In that case there is not much you can do except replace it.

**Comment by jonas2515** [comment]
Yes, the power data "measured" by powertop is completely guessed, they should have removed that table long ago.

Regarding the power drain of wifi+bluetooth: When connected to a bluetooth device where a stream of data is sent, like a headphone, the system can't go into deeper power states that PC2, so higher battery usage would be expected. If bluetooth is disconnected though, the kernel a bug right now that also doesn't let it go into states higher than PC2, so that might be what you're seeing.

**Comment by sphh** [comment]
Now I get ½h max out of the Surface Pro running on battery. But at least I can go down to a couple of percent before it shuts itself off. You remember, that the computer shut of at about 30%. Better battery stats in newer kernels? Or "reconditioning" of the battery by running more often on battery (it spent most of it's life directly plugged into main – which is never good for batteries, so I was told).

If you feel thus inclined, this issue can be be closed.

**Comment by jonas2515** [comment]
Tbh it sounds like your battery is just severely damaged, when my battery was healthy I got at least 5 hours out of it. As you mentioned it's a bad idea to run it plugged in for such a long time without limiting the charge-level to 80%, so I don't think there's anything we can do here.

**Comment by sphh** [comment]
During this discussion, I very much got the same impression that the battery is dying …

I just found out that the latest firmware(s) is (are) able to restrict the load limit. Looks like I am not the only one having this problem and M$ finally added this feature as an after thought. But unfortunately this is too late for my battery.
