### ISSUE TITLE
SB2 disable touchpad while typing not working

### ISSUE THREAD

**Issue by AltamimiYasser** [linux-surface/linux-surface#197]
[Description of the bug or feature]

### Environment

Archlinux with i3
Initially I installed Gnome Then I installed i3 on top of it

- Hardware model: 
Surface Book 2

- Kernel version: 
Linux surface 5.6.13-arch1-1-surface

- Distribution: 
Archlinux

I was using Ubuntu at first and I did change the settings in gnome tweaks and gnome dconf editor 'disable touchpad while typing' and that had no effect on it at all.

Then I changed to Linux Mint and tried changing the settings in the settings GUI application but that also didn't work

Now I'm using Archlinux and at first I installed Gnome and tried changing the settings again in  gnome tweaks and the dconf editor but it didn't work.
Then I installed i3 on top of Gnome and tried changing the settings in `libinput`  by setting disable touchpad while typing to 1 (which was the default)but that also didn't work, so I went to the libinput website and tried the debugging steps which is to run `libinput measure touchpad-pressure` and that gave me this:

```
Using Microsoft Surface Keyboard Touchpad: /dev/input/event19

This device does not have the capabilities for pressure-based touch detection.
Details: Device does not have ABS_PRESSURE or ABS_MT_PRESSURE
``` 
So I thought it doesn't support the pressure-based touch detection so let's try the size detection as they suggested in their website.

So I did `libinput measure touch-size` and that gave me:

```
Using Microsoft Surface Keyboard Touchpad: /dev/input/event19

This device does not have the capabilities for size-based touch detection.
Details: Device does not have ABS_MT_TOUCH_MAJOR


```
so I thought maybe it is  a driver problem of some sort.
don't judge me on that as I'm not an expert on these things.
Finally, thanks for the great effort I really appreciate it.

**Comment by AltamimiYasser** [comment]
any update on this one?
thanks a lot and I appreciate all the work in this repo.

**Comment by qzed** [comment]
Sorry for the delay.

The touchpad on the SB2 is a normal HID device (via USB). I don't think it supports pressure or touch size detection (at least that's not apparent to me in its HID descriptor). AFAIK this is an MS Precision Touchpad, which is a bit special but should be supported by the upstream kernel. Might be possible to configure some things for that specifically, but I really don't know.

As it's not that Surface specific, you'll probably have more luck on more general forums.

**Comment by AltamimiYasser** [comment]
Thanks a lot for your replay. I will try to search more and find a solution as it is very frustrating. The weird thing is that it works just fine in Windows. Maybe it's a configuration problem which I have to look more into.
Thanks for the effort
