### ISSUE TITLE
setup.sh fails because curl isn't set to follow redirects

### ISSUE THREAD

**Issue by danielzfranklin** [linux-surface/linux-surface#20]
setup.sh calls `curl --silent "https://api.github.com/repos/qzed/libwacom-surface-deb/releases/latest"` which outputs

```json
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/211578378/releases/latest",
  "documentation_url": "https://developer.github.com/v3/#http-redirects"
}
```

Replacing `curl` with `curl -L` fixes the issue. Would you accept a PR that makes that change?

**Comment by qzed** [comment]
This should already have been fixed with https://github.com/linux-surface/linux-surface/commit/289f9d67e36573cd5fe79936850e8a24ff482195. Can you update and check again?

**Comment by danielzfranklin** [comment]
You're right. I'd tried updating to the second-latest tag because I'd seen that the latest tag broke touchscreen, but I realized a lot of stuff didn't work in that release and just upgraded to latest.
