### ISSUE TITLE
which ubuntu to use for surface rt?

### ISSUE THREAD

**Issue by wajahat57** [linux-surface/linux-surface#228]

**Comment by archseer** [comment]
Surface RT is not supported because there's no available bootloader:

https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features

> Surface RT 1 (UEFI Secure Boot can be disabled, but so far, only a partially functional GRUB package has been ported to this specific NVidia Tegra 3 SoC. I wouldn't expect anything coming for it soon.)
