### ISSUE TITLE
[SP2017] Disable keyboard backlights when suspending

### ISSUE THREAD

**Issue by jonas2515** [linux-surface/linux-surface#236]
On the Surface Pro 2017 the keyboard/type-cover backlight, FN-Key light etc. are not turned off on suspend. Since the backlight also can't be turned off by unbinding the USB device, it seems like the EC is able to turn off those LEDs.

**Comment by jonas2515** [comment]
Finally got to this one, see https://github.com/linux-surface/kernel/pull/69.

**Comment by qzed** [comment]
Thanks!

**Comment by archseer** [comment]
Should be solved by the above PR.
