### ISSUE TITLE
Question:Does this project support Android-x86?

### ISSUE THREAD

**Issue by izwb003** [linux-surface/linux-surface#238]
Question:Does this project support Android-x86?

Just a simple question here... And if I did something wrong, just close it and ignore me, thanks!

Well, Surface devices have a powerful touchscreen and mobile-friendly design, and I think it is a great idea to run Android on it. However, after I just install android-x86 on it, I found there are many problems like I can't sleep the device or speakers not working... etc. I found this project while I was searching the Internet. And as I see, Android is based on linux and I wonder if I could use this project on Android-x86 to fix these problems, and how to do that? I'm sorry I'm a newcomer to linux and GitHub but I really want to know... And thanks for your hard work!

**Comment by Sparticuz** [comment]
I run Android x86 with these patches. Still get the same issues, but it works fine. For now, you'll need to build from source, but the Android Generic project will be making a surface build soonish.

**Comment by izwb003** [comment]
> I run Android x86 with these patches. Still get the same issues, but it works fine. For now, you'll need to build from source, but the Android Generic project will be making a surface build soonish.

I'm sorry, but what do you mean "soonish"?
and also, as Android is a popular operating system, I think there are many people using Android-x86 on there Surface devices. so I think it will be helpful if we can compile a version for Android-x86 and it will help more people.

**Comment by Sparticuz** [comment]
Unfortunately, there is not an easy way to just publish the kernel for Android. If linux-surface wanted to do this, it would require building a full Android rom. See: https://www.android-x86.org/documentation/customize_kernel.html

The Android Generic project has just started work on a vendor/surface-drivers build target. Probably be available in the next few weeks. https://gitlab.com/android-generic/vendor_android-generic

**Comment by qzed** [comment]
Unfortunately this is not something we're currently supporting or looking to support in the near future. I can't speak for the others, but I personally do not have any experience in building Android roms and/or kernels, which is one reason for this (testing and maintenance, as @Sparticuz mentioned, are others). I do, however, encourage anyone who wants to take this up to do so, and for those to feel free to ask questions if they have any.

**Comment by izwb003** [comment]
> 
> 
> Unfortunately, there is not an easy way to just publish the kernel for Android. If linux-surface wanted to do this, it would require building a full Android rom. See: https://www.android-x86.org/documentation/customize_kernel.html
> 
> Edit: What I mean is that there are a lot of Android specific patches on top of the mainline Linux kernel, and I'm not sure linux-surface would want to maintain that, especially due to the difficulty is changing the kernel in Android x86.
> 
> The Android Generic project has just started work on a vendor/surface-drivers build target. Probably be available in the next few weeks. https://gitlab.com/android-generic/vendor_android-generic



> 
> 
> Unfortunately this is not something we're currently supporting or looking to support in the near future. I can't speak for the others, but I personally do not have any experience in building Android roms and/or kernels, which is one reason for this (testing and maintenance, as @Sparticuz mentioned, are others). I do, however, encourage anyone who wants to take this up to do so, and for those to feel free to ask questions if they have any.

All right I see it. Thank you for your reply.
