### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by lx07** [linux-surface/linux-surface#241]
Could you add a BTC Wallet and turn on Github Sponsoring for this project / update the wiki on how to do so? 

I would like to give back.

**Comment by archseer** [comment]
There's already #26, but we haven't reached any consensus. Since @qzed and @StollD do majority of the work it's up to them to decide; I'd be open to signing up for Github Sponsors but would probably abstain from receiving anything because it would complicate tax reporting on my end.

**Comment by qzed** [comment]
We've decided to set up a [liberapay team](https://liberapay.com/linux-surface/) as that seems to be the easiest solution for us at the moment. Unfortunately they don't support BTC yet and I'm not sure if there's an easy way to support that for us while keeping it all on the legal side (wrt. tax etc.).

**Comment by hapm** [comment]
First little thank you is on its way.

**Comment by qzed** [comment]
Thank you!
