### ISSUE TITLE
I can't open Microsoft surface book 2 laptop cam in ubuntu

### ISSUE THREAD

**Issue by o920130130** [linux-surface/linux-surface#266]
Hi Author :
my email:o920130130@gmail.com 
my name is Paul
My laptop is Microsoft surface book 2 and have setuped dual system (win10+ubuntu18.04).
I cann't open laptop cam in ubuntu but I can open one in win10.
I capture this photo and describe the detail :
Left battom is the process of ubuntu, cann't open camera so top side the python process cann't open camera,too.
I have enter dpkg --get-selections|grep linux and look up core but I can't found out camera device and drive.
I have enter :(base) paul@paul-Surface-Book-2:~$ sudo apt-get install webcam
camera no work
Could you help me ? I don't know which command can setup drive of camera .

[Description of the bug or feature]

### Environment

- Hardware model: 
- Kernel version: 
- Distribution: 

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by o920130130** [comment]
Hi Author :
my email:o920130130@gmail.com
my name is Paul
My laptop is Microsoft surface book 2 and have setuped dual system (win10+ubuntu18.04).
I cann't open laptop cam in ubuntu but I can open one in win10.
I capture this photo and describe the detail :
Left battom is the process of ubuntu, cann't open camera so top side the python process cann't open camera,too.
I have enter dpkg --get-selections|grep linux and look up core but I can't found out camera device and drive.
I have enter :(base) paul@paul-Surface-Book-2:~$ sudo apt-get install webcam
camera no work
Could you help me ? I don't know which command can setup drive of camera .

[Description of the bug or feature]

**Comment by hapm** [comment]
The camera isn't supported yet, as described in the [feature matrix](Supported-Devices-and-Features#feature-matrix). You can subscribe to issue #91 to be informed over the current process for that. This should be closed as duplicate.

**Comment by qzed** [comment]
As @hapm said. Closing this in favor of #91.
