### ISSUE TITLE
Kernel 5.8.3-arch1-1-surface breaks wifi connection.

### ISSUE THREAD

**Issue by fal23** [linux-surface/linux-surface#267]
Thank you for your invaluable work in maintaining of the surface kernel!

After latest update of kernel to 5.8.3-arch1-1-surface my SB2-13 lost connection to my home wifi. 
So I revert to previous which is ok.

There is repeated set of lines in dmesg:
[   28.231299] mwifiex_pcie 0000:01:00.0: info: trying to associate to 'xxxxxx' bssid 68:ff:7b:8b:44:82
[   28.276055] mwifiex_pcie 0000:01:00.0: info: associated to bssid 68:ff:7b:8b:44:82 successfully
[   28.301362] mwifiex_pcie 0000:01:00.0: crypto keys added
[   29.479295] mwifiex_pcie 0000:01:00.0: info: successfully disconnected from 68:ff:7b:8b:44:82: reason code 3

Notification about crypto keys: "mwifiex_pcie 0000:01:00.0: crypto keys added"
was not in previous kernel.

full dmesg output attached.

Thank You,
Alex Frolov

[dmesg.log](https://github.com/linux-surface/linux-surface/files/5118504/dmesg.log)

</details>

**Comment by qzed** [comment]
There's an open issue for this on the kernel repo: https://github.com/linux-surface/kernel/issues/54. There haven't been any changes regarding wifi from our side between v5.8.1 and v5.8.3, so must have likely be caused by an upstream change.

Interesting to note is also that all reports I've seen so far are from Manjaro.

**Comment by elChupaCambra** [comment]
Have been having this issue since last night. WiFi works out of the box after installation of a distro, but fails to authenticate with password-protected networks after installing the Linux-Surface kernel. Simply keeps asking to introduce the password. Occurs on Ubuntu 20.04 (and derivatives Pop_OS and KDE Neon) as well as Manjaro.

Connects to my phone hotspot fine but not to my home WiFi network. WiFi works perfectly on Windows, but no surprises there.

**Comment by Demonstrandum** [comment]
Same problem here, authentication just suddenly started always failing after upgrading, both on LTS and latest! [Surface Book 2]

I use LTS, downgraded it and works again.

**Comment by qzed** [comment]
Upstream discussion is taking place [here](http://patchwork.ozlabs.org/project/netdev/patch/20200825153829.38043-1-luzmaximilian@gmail.com/). It's not included in upstream v5.8.4 yet, but I'll add it to our patches for now. So our next release should fix this.

**Comment by johentsch** [comment]
I got the same problem, also on Manjaro, since the last update. 

Hardware: Surface Pro 3
Kernel: 5.8.3-arch1-1-surface
OS: Manjaro 20.1

Output of `lspci -k`:

    Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
    	Subsystem: SafeNet (wrong ID) Device 045e
    	Kernel driver in use: mwifiex_pcie
    	Kernel modules: mwifiex_pcie

`journalctl -b` from trying to connect to SSID `warumnicht?`:

    info: trying to associate to 'warumnicht?' bssid 34:81:c4:e7:05:0d
    [1598521328.1410] device (wlp1s0): supplicant interface state: scanning -> associating
    info: associated to bssid 34:81:c4:e7:05:0d successfully
    [1598521328.1411] device (p2p-dev-wlp1s0): supplicant management interface state: scanning -> associating
    wlp1s0: Associated with 34:81:c4:e7:05:0d
    wlp1s0: CTRL-EVENT-SUBNET-STATUS-UPDATE status=0
    nl80211: kernel reports: key addition failed
    wlp1s0: WPA: Failed to set GTK to the driver (alg=2 keylen=32 keyidx=1)
    wlp1s0: RSN: Failed to configure GTK
    [1598521328.1497] device (wlp1s0): supplicant interface state: associating -> 4way_handshake
    [1598521328.1497] device (p2p-dev-wlp1s0): supplicant management interface state: associating -> 4way_handshake
    crypto keys added
    wlp1s0: CTRL-EVENT-DISCONNECTED bssid=34:81:c4:e7:05:0d reason=1 locally_generated=1
    info: successfully disconnected from 34:81:c4:e7:05:0d: reason code 3

**Comment by qzed** [comment]
New releases with the fix are currently building.

**Comment by qzed** [comment]
New releases should be live in a couple of minutes.
