### ISSUE TITLE
surface and wpa3

### ISSUE THREAD

**Issue by supertomi** [linux-surface/linux-surface#276]
hi folks,

I tried to use wpa3 with my surface 6, the surface-kernel, wpa_supplicant/iwd and networkmanager, but I could not get it running. Is wpa3 a matter of the device driver or hardware based? Is it possible to use wpa3 with the surface kernel/wifi-driver? 

Thanks for help/info!

### Environment

- Hardware model: Surface Pro 6
- Kernel version: 4.19.186
- Distribution: Gentoo

**Comment by archseer** [comment]
I don't think WPA3 is supported on Surface Pro 6 at all, likely the new models (using Intel® Wi-Fi 6 AX200) are the only ones that support it.

**Comment by jonas2515** [comment]
Yes, sadly the 88W8897 wifi firmware doesn't support WPA3, and that won't change unless Marvell releases a new firmware, which is unlikely to say the least.
