### ISSUE TITLE
Save choices for setup.sh

### ISSUE THREAD

**Issue by danielzfranklin** [linux-surface/linux-surface#28]
# Feature Request: Save choices for setup.sh

## Problem
I have to carefully read through every question when I want to upgrade even though I want the same things as last time for all the questions that haven't changed.

## Proposed solution
I propose that `setup.sh` saves the response to everything it `ask`s to a standard location. On future runs by default any question with a saved response isn't asked again.

If a question requires new thought, the phrasing should change. As responses are indexed under question phrasing the question will be asked anew. (This should be the case anyhow because people skimming through the questions should be alerted if they require new thought.)

Outdated responses are left in the config file for simplicity. Users shouldn't need to edit the config file directly, so a few bytes of clutter won't matter. If setup.sh drastically changes the config file can be deleted.

The config file can be deleted by running `setup.sh --fresh-start`. (Poorly named I think, suggestions?).

### Technicalities
- If config file doesn't yet exist standard location is `$XDG_CONFIG_HOME/.linux_surface/config` if `$XDG_CONFIG_HOME` is defined, `~/.config/linux_surface/config` if directory `~/.config` exists, else `~/.linux_surface.conf`. Order of priorities is reversed for existing files so that if a user has `~/.linux_surface.conf` already that would be used even if they have a config directory.
- Config format is INI so that it can [be parsed](https://github.com/albfan/bash-ini-parser) with pure bash
- Answers are indexed under their URL slug form as that [can be done](https://stackoverflow.com/a/49035906/8334056) with bash and coreutils

**Comment by danielzfranklin** [comment]
I want this, and know enough bash to do it. Would a PR be accepted?

**Comment by qzed** [comment]
We're currently discussing how to best restructure the setup and installation process, see #32. I think this should wait until we've resolved that. However, I do like the idea.
