### ISSUE TITLE
Question : kernel 4.19 and iptsd

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#283]
Hello,

Can I use the iptsd service with the kernel branch `v4.19-surface` ?

If I understand well the new ipts kernel module cannot handle both the stylus and multitouch in the same time,
is it possible to change from stylus to multitouch and conversely without having to reboot or restart the X11 server ?

Regards

**Comment by SamLukeYes** [comment]
As I tested before, on 4.19-surface kernel, iptsd.service can be enabled, but the service itself doesn't work. Touchscreen and stylus work as expected with the old driver.

**Comment by StollD** [comment]
4.19 still supports and uses the old driver that was published by Intel, and supports full multitouch + stylus with the touch processing binaries extracted from windows (https://github.com/linux-surface/surface-ipts-firmware). You don't need iptsd on 4.19 to get full touch support, you only need it on 5.8.

**Comment by deb75** [comment]
Thanks for your answer,

My underlying question is what is best for daily use ?
- 4.19 lets you use multitouch and stylus seamlessly, however when I hibernate / suspend, I quite oftenly
  lose both on resuming with a message from the i915 driver looking like "unable to reacquire the IPTS
  doorbell" (not 100%  sure of it).
- latest 5.X kernel, for which I hope my suspend-hibernate/resume issue would be solved, I still can use the
  touchscreen (hand) and the stylus, but not in the same time, if I understand well. I can bear it provided it is not
  too annoying to switch from one to another. To do so, I guess I have to unload the `ipts` kernel module and
  load it again with the suitable parameter. Then, does unloading/reloading this module compels to restart the
  X session ? or reboot the computer itself ?

Regards

**Comment by StollD** [comment]
> I still can use the touchscreen (hand) and the stylus, but not in the same time,

With 5.8 + iptsd you can.

> My underlying question is what is best for daily use ?

4.19 has more fleshed out touch processing (the same as windows), but the driver is more complex, unmaintained and has bugs. The 5.8 setup with iptsd is simpler, but lacks some things (touch pressure calculation) and the touch processing isn't as good as 4.19.

If you are not sure what you want to use, try both and use what works better for you.

**Comment by deb75** [comment]
Hi,

I installed linux-surface 5.8.14 and the pen works very well. I tested it on xournalpp and styluslab, I see no difference with 4.19 kernel, even pressure works.

Regards
