### ISSUE TITLE
Display auto-rotate when applicatiion set in fullscreen

### ISSUE THREAD

**Issue by seblemaguer** [linux-surface/linux-surface#284]
Hello,

I am not sure if that is the correct repository to ask this question. If it is not the case, I apologize.

Nonetheless, I am facing the following undesired issue: when I set some apps in fullscreen (using the f11 key) the display rotate automatically. This happens even when the autorotation is locked. This is happening only for a subset of applications (emacs, mpv but not firefox).

I don't really know where to start to look for the issue so if someone as an idea that would be great.

Thanks a lot

### Environment

- Hardware model: Surface Pro 6 (AMD)
- Kernel version: Linux lemagues-surface 5.8.10-surface #3 SMP Sat Sep 19 21:35:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 20.04.1 LTS
- Gnome Shell: 3.36.3
- Windowing system: X11

**Comment by qzed** [comment]
If that only works on some applications, I think this should be an issue with the desktop environment. Unfortunately I don't really have any idea how to figure out what's going wrong. Maybe test Wayland instead of X11.

**Comment by seblemaguer** [comment]
Thanks a lot. Wayland seems to work. I have no idea why though :D
