### ISSUE TITLE
Cannot make Nvidia card run

### ISSUE THREAD

**Issue by mmalmeida** [linux-surface/linux-surface#293]
Hi,
- Hardware model: Surface Book 2
- Kernel version: 5.3.18-surface
- Distribution: Ubuntu 18.04

**Trying to make Nvidia card run**
1. Followed the steps described in https://github.com/linux-surface/surface-aggregator-module/wiki/Discrete-GPU

**Expected:**
8. Run your desired application on the dGPU with optirun <application>. To verify the Nvidia GPU is actually used, you can run optirun glxgears -v.

I expect to run glxgears.

**Actual:**

[   84.410594] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)
[   84.410628] [ERROR]Aborting because fallback start is disabled.

**Relevant dmesg log**

[sex out  2 11:13:53 2020] surface_dgpu_hps MSHW0153:00: setting dGPU power state to 'on'
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4: pciehp: Slot(4): Card present
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4: pciehp: Slot(4): Link Up
[sex out  2 11:13:53 2020] pci 0000:02:00.0: [10de:1c20] type 00 class 0x030200
[sex out  2 11:13:53 2020] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x00ffffff]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: reg 0x14: [mem 0x00000000-0x0fffffff 64bit pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: reg 0x1c: [mem 0x00000000-0x01ffffff 64bit pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: reg 0x24: [io  0x0000-0x007f]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: reg 0x30: [mem 0x00000000-0x0007ffff pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: Max Payload Size set to 256 (was 128, max 256)
[sex out  2 11:13:53 2020] pci 0000:02:00.0: 31.504 Gb/s available PCIe bandwidth, limited by 8 GT/s x4 link at 0000:00:1c.4 (capable of 126.016 Gb/s with 8 GT/s x16 link)
[sex out  2 11:13:53 2020] pci 0000:02:00.0: BAR 1: assigned [mem 0x90000000-0x9fffffff 64bit pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: BAR 3: assigned [mem 0xa0000000-0xa1ffffff 64bit pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: BAR 0: assigned [mem 0xc0000000-0xc0ffffff]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: BAR 6: assigned [mem 0xc1000000-0xc107ffff pref]
[sex out  2 11:13:53 2020] pci 0000:02:00.0: BAR 5: assigned [io  0x3000-0x307f]
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4: PCI bridge to [bus 02]
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4:   bridge window [io  0x3000-0x3fff]
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4:   bridge window [mem 0xc0000000-0xd2ffffff]
[sex out  2 11:13:53 2020] pcieport 0000:00:1c.4:   bridge window [mem 0x90000000-0xa1ffffff 64bit pref]
[sex out  2 11:13:53 2020] nvidia-nvlink: Nvlink Core is being initialized, major device number 242
[sex out  2 11:13:53 2020] nvidia 0000:02:00.0: enabling device (0000 -> 0003)
[sex out  2 11:13:53 2020] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  450.66  Wed Aug 12 19:42:48 UTC 2020
[sex out  2 11:13:53 2020] nvidia-modeset: Loading NVIDIA Kernel Mode Setting Driver for UNIX platforms  450.66  Wed Aug 12 19:37:58 UTC 2020
[sex out  2 11:13:53 2020] [drm] [nvidia-drm] [GPU ID 0x00000200] Loading driver
[sex out  2 11:13:53 2020] ACPI Warning: \_SB.PCI0.RP05.PXSX._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20190703/nsarguments-66)
[sex out  2 11:13:55 2020] [drm] Supports vblank timestamp caching Rev 2 (21.10.2013).
[sex out  2 11:13:55 2020] [drm] No driver support for vblank timestamp query.
[sex out  2 11:13:55 2020] [drm] Initialized nvidia-drm 0.0.0 20160202 for 0000:02:00.0 on minor 1
[sex out  2 11:13:55 2020] nvidia-uvm: Loaded the UVM driver, major device number 240.
[sex out  2 11:14:05 2020] bbswitch: version 0.8
[sex out  2 11:14:05 2020] bbswitch: Found integrated VGA device 0000:00:02.0: \_SB_.PCI0.GFX0
[sex out  2 11:14:05 2020] bbswitch: Found discrete VGA device 0000:02:00.0: \_SB_.PCI0.RP05.PXSX
[sex out  2 11:14:05 2020] ACPI Warning: \_SB.PCI0.GFX0._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20190703/nsarguments-66)
[sex out  2 11:14:05 2020] bbswitch: No suitable _DSM call found.
[sex out  2 11:14:45 2020] surface_sam_ssh serial0-0: recv: invalid start of message
[sex out  2 11:14:45 2020] surface_sam_ssh serial0-0: recv: invalid start of message

**Commands ran:**

malmeida@itclaptop001:~$ sudo surface dgpu get
dGPU power is 'on'
malmeida@itclaptop001:~$ sudo service bumblebeed status
● bumblebeed.service - Bumblebee C Daemon
   Loaded: loaded (/lib/systemd/system/bumblebeed.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2020-10-02 11:12:22 WEST; 1min 35s ago
  Process: 696 ExecStart=/usr/sbin/bumblebeed (code=exited, status=1/FAILURE)
 Main PID: 696 (code=exited, status=1/FAILURE)
malmeida@itclaptop001:~$ sudo service bumblebeed start
malmeida@itclaptop001:~$ sudo prime-select nvidia
Info: the nvidia profile is already set
malmeida@itclaptop001:~$ optirun glxgears -v
[   84.410594] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[   84.410628] [ERROR]Aborting because fallback start is disabled.
malmeida@itclaptop001:~$ sudo nvidia-modprobe
sudo: nvidia-modprobe: command not found
malmeida@itclaptop001:~$ sudo apt install nvidia-dkms-450
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nvidia-dkms-450 is already the newest version (450.66-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Could you help me pinpoint what is wrong? I haven't been able to run nvidia since I bought the laptop and I wanted to finally resolve this.

Thanks!

**Comment by qzed** [comment]
Can you check that the `nvidia` driver has been successfully installed for the kernel? You can do that by running `dkms status`.

**Comment by mmalmeida** [comment]
Hi @qzed 
 dkms status:
bbswitch, 0.8, 4.15.0-118-generic, x86_64: installed
bbswitch, 0.8, 5.3.18-surface, x86_64: installed
nvidia, 450.66, 4.15.0-118-generic, x86_64: installed
nvidia, 450.66, 5.3.18-surface, x86_64: installed


So I would say it is (not sure why I see two instances of each though)

**Comment by qzed** [comment]
v5.8.3 is really outdated at this point... you should either go with v4.19 or v5.8.

**Comment by mmalmeida** [comment]
I took the opportunity to update the kernel to 5.8.x (thought this was automatic with apt update). Am now struggling with boot (90% of the time it stops at "gpu has fallen off the bus" on startup and hangs on trying to disconnect network manager on shutdown).
Will continue once I overcome these issues (any help on these appreciated. I removed and installed the packages Linux-firmware, nvidia-dkms-450 and bumblebee)

**Comment by mmalmeida** [comment]
![Uploading IMG_20201004_150824.jpg…]()

**Comment by mmalmeida** [comment]
Update: seems the boot problems are with kernel 5.8.12-surface
If I run 5.3.18 it boots and powers off normally.

Installed kernels:
linux-image-5.3.18-surface                 5.3.18-surface-1                                 amd64        Linux kernel, version 5.3.18-surface
ii  linux-image-5.8.12-surface                 5.8.12-surface-2                                 amd64        Linux kernel, version 5.8.12-surface

@qzed is there an existing issue number for these 5.3.18 kernel problems (or should I create one)?

**Comment by mmalmeida** [comment]
I've opened #295  to deal with the 5.8.12 boot problems.

**Comment by Holmgren825** [comment]
Hey, I had similar issues on 20.04 and it turns out bumblebee is looking for the drivers in the wrong directory. Solved  by following [this reply](https://github.com/Bumblebee-Project/Bumblebee/issues/951#issue-307891832). With this drivers are loaded automatically (by gnome maybe??) as soon as I run `sudo surface dgpu set on` and optirun works as expected. No need to run `nvidia-modprobe`. This seems to cause some issues though, since it is not possible to unload the drivers and restart/shutdown is also not working properly.

**Comment by qzed** [comment]
@Holmgren825 Neat!
