### ISSUE TITLE
Cannot boot kernel 5.8.12

### ISSUE THREAD

**Issue by mmalmeida** [linux-surface/linux-surface#295]
Following description in #293 , I've been running issues upgrading to kernel 5.8.12 on Ubuntu 18.04:
Boot fails (almost) every time, with error messages like:
-  "gpu has fallen off the bus" 
- bluetooth hci0: unexpected event for opocode 0x0000
- and other messages.
and while shutting down it hangs on trying to disconnect network manager 

See images attached for error details

**Comment by mmalmeida** [comment]
![IMG_20201004_165137](https://user-images.githubusercontent.com/1058575/95020622-227c4d80-0664-11eb-865a-9b6bc1406754.jpg)
![Uploading IMG_20201004_150824.jpg…]()

**Comment by qzed** [comment]
Can you try blacklisting nouveau? Specifically by specifying the following options (e.g. in `/etc/modprobe.d/blacklist.conf`):
```
blacklist nouveau
blacklist lbm-nouveau
options nouveau modeset=0
alias nouveau off
alias lbm-nouveau off
```

**Comment by mmalmeida** [comment]
edit: I managed to overcome this by removing all nvidia drivers and then adding version 435. Will further explore to see if it's an issue with 450.

**Comment by mmalmeida** [comment]
update @qzed :+1:
With or without:
blacklist nouveau
blacklist lbm-nouveau
options nouveau modeset=0
alias nouveau off
alias lbm-nouveau off
blacklist nvidia

1. nvidia-dkms-450 and nvidia-dkms-440 do not work: system hangs indefinitely at startup waiting for dgpu. Strangly enough, when I try to install 440 it also installs 450.

2. With nvidia-dkms-435 it boots normally.

**Comment by mmalmeida** [comment]
/var/lib/dkms/nvidia/435.21/build/make.log
[make.log](https://github.com/linux-surface/linux-surface/files/5324013/make.log)

**Comment by qzed** [comment]
v435 doesn't support newer kernels, so that's expected.

Can you try adding `blacklist nvidia-modeset`, `blacklist nvidia-drm`, and `blacklist nvidia-uvm` to the blacklist (in addition to `blacklist nvidia` and the nouveau stuff)?

**Comment by mmalmeida** [comment]
Well not to bother you with the details, but I've tried booting on Windows to update the bios... Windows updates went OK but after restarting its stuck on a boot loop and nothing loads. Tried accessing bios with volume down and power, but no luck. Cannot boot from usb. Microsoft says there is no other way and that they will probably replace the unit. And I have no way of getting the data...
What a nightmare

**Comment by qzed** [comment]
> Tried accessing bios with volume down and power, but no luck.

I assume you mean volume up?

Based on your comment, I guess you've already tried a device reset (holding both power and volume-up)? Best do that while it's running as it should restart the device. If you have a Surface Dock connected, also try disconnecting that.

Unfortunately I have no other tricks. Best of luck to you.

**Comment by cedricfung** [comment]
My surface pro 7 boots with 5.8.12, but the booting is very slow, more than 1 minute. Previous versions boot much faster.

**Comment by qzed** [comment]
@cedricfung This looks like a different issue. Can you open a new one and provide a dmesg log?

**Comment by cedricfung** [comment]
@qzed after some reboots, this issue disappeared.

**Comment by qzed** [comment]
Hmm, interesting. Feel free to open a new issue if this happens again.

I'm going to close this one for now.
