### ISSUE TITLE
Kernel hang during apt upgrade

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/linux-surface#298]
I was `apt upgrade`ing my tablet when it froze.

I did the update inside Konsole. Only the mouse moved, and caps lock didn't work. After the mouse stopped moving, I held down the power button. There were corrupt inode messages on the next startup, so I decided to rerun the update. I ran `apt install --reinstall google-chrome-stable:amd64 libpulse-dev:amd64 pulseaudio-utils:amd64 pulseaudio-module-bluetooth:amd64 pulseaudio:amd64 libpulsedsp:amd64 libpulse-mainloop-glib0:amd64 libpulse0:amd64 libpulse0:i386 zlib1g-dev:amd64 zlib1g:amd64 zlib1g:i386 bolt:amd64 libbrotli1:amd64 libbrotli1:i386 libfprint-2-2:amd64 mdadm:amd64 python3-pip:all python-pip-whl:all python3-urllib3:all thermald:amd64`. This command froze in Konsole again. Force rebooting and retrying still led to the same error. I then decided to do the update on the TTY. After it froze there too, I retried it, and I attached a photo of the error at the bottom of this issue. After each TTY freeze, the caret stopped blinking but I only see the kernel stack trace after I switch to another TTY and back.

Interestingly, `dpkg --configure -a` succeeds without error, but the `apt install --reinstall` leads to kernel problems every time. The problems occur around the same point in the `apt` progress. I was on battery, with a USB-C hub and the type cover connected.

### Environment

- Hardware model: `Surface Pro 7 i7 512GB`
- Kernel version: `Linux daniel-tablet1 5.8.12-surface #2 SMP Thu Oct 1 19:58:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: `Ubuntu 20.04.1 LTS`

dmesg is unavailable because I needed to hold down the power button every time to recover the system.

I did manage to take a photo though:

![IMG_20201007_000314](https://user-images.githubusercontent.com/25646384/95435840-17a21100-0921-11eb-8bfc-da01f1f181a5.jpg)

**Comment by qzed** [comment]
This seems to be the same error as #299.
