### ISSUE TITLE
Kernel oops during shutdown

### ISSUE THREAD

**Issue by danielzgtg** [linux-surface/linux-surface#299]
Occasionally, a kernel oops happens to my tablet during shutdown.

I encountered each of these after clicking a button in the GUI. I got this one in particular after finishing writing #298. Every time this happens, a stack trace is printed near the end of the boot process, and the shutdown process lasts at least a minute longer than usual so I hold down the power button. The stack trace is never completely printed, and two lines of the stack trace text are displayed on a single line with the top half of one and the bottom half of another. That's why I didn't bother reporting this bug despite it affecting me for quite a long time.

Today, having #298 fresh on my mind, I remembered to try switching to another TTY and back. This got the complete stack trace to be displayed properly. Additionally, I saw that there were 3 shutdown jobs stuck for at least 3 minutes before I used REISUB (which didn't work in the one time I tried it in previous encounters). I am using the same environment, except with the battery full and the charger plugged in.

### Environment

- Hardware model: `Surface Pro 7 i7 512GB`
- Kernel version: `Linux daniel-tablet1 5.8.12-surface #2 SMP Thu Oct 1 19:58:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: `Ubuntu 20.04.1 LTS`

There is no dmesg because this occurred during shutdown. On next reboot, there was dmesg data in journalctl but the logs weren't as complete as the photo.

A photo of the kernel oops:

![IMG_20201008_052033](https://user-images.githubusercontent.com/25646384/95440795-589d2400-0927-11eb-84b6-f41014a5a915.jpg)

**Comment by qzed** [comment]
Thanks! I think I've tracked down the issue and fixed it in https://github.com/linux-surface/surface-aggregator-module/commit/9ed043e01ebefac406f10cd6b3b1055a1572306b. I'll probably update the kernel and schedule a new build later today.

**Comment by qzed** [comment]
Okay, should be fixed with the latest kernel. Can you confirm this?

**Comment by danielzgtg** [comment]
I haven't encountered this problem on the latest kernel (`linux-image-5.8.14-surface`).

But then, this bug doesn't happen all the time, so traditional testing methods can't know for sure.

I'll close this issue now, and I'll just say so if the problem pops up again

**Comment by qzed** [comment]
Perfect, thanks!
