### ISSUE TITLE
Nvidia X server settings missing

### ISSUE THREAD

**Issue by jonkatz6** [linux-surface/linux-surface#304]
All but the prime setting in the nvidia x server settings control panel have disappeared and I've lost ability to right click on app to run with dedicated graphics. This was oddly not an issue in the Jakeday recent release if anyone knows why/can help me regain those menus it would be greatly appreciated. 

- Hardware model: SB2 13in nvidia1050
- Kernel version: 5.8.14-surface
- Distribution: Debian, ubuntu

**Comment by qzed** [comment]
The nvidia settings panel must be run on an x-server running on the nvidia dGPU. By default, the dGPU is powered down to save battery, so the x-server will start on the integrated GPU. This means, you'll have to turn on the dGPU and run the nivdia control panel via optirun.

See https://github.com/linux-surface/surface-aggregator-module/wiki/Discrete-GPU on a rough overview of how to turn on the dGPU and use optirun.

**Comment by mynameisjeffe** [comment]
Hi @qzed ! I'm using Fedora 32 on SB2. I'm able to use Nvidia on the default kernel. It shows up using the command nvidia-smi
But when I use the linux-surface kernel, somehow Nvidia won't load even when I type
sudo surface dgpu set on. 

This is the error when I type nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

When I type DKMS, it can detect that the Nvidia is installed.

Do you have any advice on this?

**Comment by qzed** [comment]
What's the exact output of `dkms status`? Does running `nvidia-modprobe` work?

**Comment by mynameisjeffe** [comment]
`dkms status
nvidia, 455.23.04, 5.8.14-300.fc33.x86_64, x86_64: installed
`
nvidia-modprobe doesn't work :/

`nvidia-installer -v |grep version
nvidia-installer:  version 455.23.04
`

It's odd because when I use manjaro, I'm able to load nvidia up!

**Comment by jonkatz6** [comment]
sudo surface status
```
       Device-Mode: Laptop
  Performance-Mode: Best Performance (4)
        dGPU-Power: on
```

sudo prime-select query
`nvidia`


dkms status
```
bbswitch, 0.8, 5.1.15-surface-linux-surface, x86_64: installed
bbswitch, 0.8, 5.4.0-51-generic, x86_64: installed
bbswitch, 0.8, 5.8.14-surface, x86_64: installed
nvidia, 450.80.02, 5.4.0-51-generic, x86_64: installed
nvidia, 450.80.02, 5.8.14-surface, x86_64: installed

```
nvidia-modprobe
no output

sudo nvidia-modprobe
no output

lspci
`02:00.0 3D controller: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile] (rev a1)`
(this is the only instance of nvidia in the lspci output)


```
sudo optirun nvidia-settings
[20751.332807] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[20751.332829] [ERROR]Aborting because fallback start is disabled.
```

**Comment by qzed** [comment]
@mynameisjeffe 

> `dkms status`
> `nvidia, 455.23.04, 5.8.14-300.fc33.x86_64, x86_64: installed`

That only indicates that the driver is installed for the stock Fedora kernel. If there is no line with the `-surface` kernel, then it's not installed for the surface kernel. Also the dGPU is visible in `lspci` after running `surface dgpu set on`?

**Comment by qzed** [comment]
@jonkatz6 

Does `nvidia-smi` work? If that works, make sure that the paths to the driver in the bumblebee config are correct (see https://github.com/linux-surface/linux-surface/issues/293#issuecomment-706554007 and the link in that for details).

**Comment by jonkatz6** [comment]
```
jonathan@JKSB:~$ sudo surface dgpu set on
dGPU power already set to 'on', not changing
```

```
jonathan@JKSB:~$ nvidia-smi
Fri Oct 16 17:29:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   34C    P8     8W /  N/A |      0MiB /  2002MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
jonathan@JKSB:~$ ^C

```

I had already changed config file at etc/bumblebee/bumblebee.conf as suggested.

**Comment by qzed** [comment]
Unfortunately I don't have much experience with nvidia-settings, so I have no idea what's going wrong there. You could try to start a complete X session on the dGPU by turning it on, logging out, and then starting an X-server with it. I have never tried this so I can't really help you out there either.

**Comment by jonkatz6** [comment]
Ok thank you @qzed, I will investigate the jakeday kernal further when I get a chance. 
I appreciate the work you and the team have done. Keep up the great work!

**Comment by qzed** [comment]
What options are missing specifically?

Also: I just tried to run `nvidia-settings` and remembered that you'll have to specify the X-server display for this to work. Without specifying the display I also get the `ERROR: Unable to load info from any available system`.

This means you'll have to run `optirun nvidia-settings -c :8`, where the `:8` indicates the display. You can list all displays by running `(cd /tmp/.X11-unix && for x in X*; do echo ":${x#X}"; done)`. As `optirun` opens a new display, you'll have to 1) run this command, 2) run something via optirun, e.g. `optirun glxgears` and 3) in parallel with 2) run the command to list the displays again. Then look at the difference and the display that's new in the second run is the one you need.

I'll update the instructions with that info.
