### ISSUE TITLE
WARNING: Possibly missing firmware for module: xhci_pci

### ISSUE THREAD

**Issue by 1900011604** [linux-surface/linux-surface#306]
But `sudo pacman -S xhci_pci` or `yay -S xhci_pci` doesn't work.

How to solve this?

**Comment by qzed** [comment]
What device does this occur on?

Do you experience any issues related to USB? If not you can safely ignore this warning. For more details on this see https://bbs.archlinux.org/viewtopic.php?id=258184.

**Comment by 1900011604** [comment]
SP6 

No I use Manjaro and I installed linux-surface after installing Manjaro which do not require a USB.

**Comment by qzed** [comment]
The link applies regardless of the distribution you're using: If you have some renesas USB controller, you _might_ need additional firmware. If not, you don't, and if USB works, you probably don't either. As far as I can tell by looking at [this](https://linux-hardware.org/index.php?probe=90e927020f), the SP6 doesn't have such a controller, so you can ignore this warning.
