### ISSUE TITLE
PopOS 20.04, having graphics card issues

### ISSUE THREAD

**Issue by DamienTehDemon** [linux-surface/linux-surface#309]
nvidia-modprobe doesnt return anything.

nvidia-smi 
```
/usr/bin/nvidia-modprobe: unrecognized option: "-s"

ERROR: Invalid commandline, please run `/usr/bin/nvidia-modprobe --help` for usage information.

/usr/bin/nvidia-modprobe: unrecognized option: "-s"

ERROR: Invalid commandline, please run `/usr/bin/nvidia-modprobe --help` for usage information.

Sat Oct 17 08:41:36 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.28       Driver Version: 455.28       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   40C    P8    10W /  N/A |      0MiB /  6080MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+`
```
optirun glxgears -v
```
optirun glxgears -v
[ 1807.312115] [ERROR]Cannot access secondary GPU - error: [XORG] (EE) Failed to load module "nvidia" (module does not exist, 0)

[ 1807.312160] [ERROR]Aborting because fallback start is disabled.
```

**Comment by qzed** [comment]
Since `nvidia-smi` works, the drivers seem to be present and working. It's a bit weird that it complains about the `-s` option though. Do you have conflicting versions of some nvidia packages? E.g. `nvidia-utils`?

As far as I can tell, the optirun issue is, either a bumblebee config issue or some things for the nvidia driver to work under X are missing. I think you can try to figure out what's going wrong by looking at the Xorg log (`/var/log/Xorg.8.log`, replace 8 with the display number optirun is using).

**Comment by DamienTehDemon** [comment]
`damien@damiens-laptop:~$ sudo surface dgpu set on
No face model known
[sudo] password for damien: 
dGPU power set to 'on'
damien@damiens-laptop:~$ nvidia-smi
Mon Oct 26 19:42:38 2020       
+-----------------------------------------------------------------------------+





| NVIDIA-SMI 455.28       Driver Version: 455.28       CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1060    Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   30C    P0    24W /  N/A |      0MiB /  6080MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
damien@damiens-laptop:~$ 
`
