### ISSUE TITLE
Surface Book 2 touch screen and pen not working after last update.

### ISSUE THREAD

**Issue by engageintellect** [linux-surface/linux-surface#315]
systemd wont start iptsd immediately after rebooting post update just now.

$ sudo ./iptsd output:
operation not permitted
main.(*Epoll).Listen
        /home/r3dux/iptsd/epoll.go:34
main.(*IptsControl).Start
        /home/r3dux/iptsd/control.go:50
main.main
        /home/r3dux/iptsd/main.go:24
runtime.main
        /usr/lib/go/src/runtime/proc.go:204
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1374

I don't think this is a linux 5.9 issue as everything has been running fine the last few days. It wasn't until I ran an update from "linux-surface" and rebooted that the problem came up.

- Hardware model:  Surface Book 2
- Kernel version:  Linux SB2 5.9.1-arch1-1-surface #1 SMP PREEMPT Thu, 22 Oct 2020 16:57:47 +0000 x86_64 GNU/Linux

- Distribution:  Arch

<details><summary>`dmesg` output</summary>

https://termbin.com/88xf

</details>

**Comment by StollD** [comment]
What iptsd version do you have installed? For 5.9.1 you need iptsd 0.2.1, otherwise it wont work (iptsd 0.2 had a broken systemd service config).

**Comment by baconducttape** [comment]
I got touch partially working by running `sudo iptsd`. It does not persist through a reboot, though.

SB2, Pop! 20.04, 5.9.10

**Comment by StollD** [comment]
You need to enable the service: `sudo systemctl enable iptsd`

Then it will start automatically on boot.
