### ISSUE TITLE
SP5 - ipts not working

### ISSUE THREAD

**Issue by tihoulas** [linux-surface/linux-surface#320]
Hi,
I am runing kubuntu groovy on a Surface Pro 5. Using the latest surface kernel (5.9.1-surface), I cannot get iptsd working :
`oct. 27 18:43:15 krabardaf iptsd[677]: open /dev/ipts/0: not a directory`

`dmesg | grep ipts`
```
[    4.224558] ipts: loading out-of-tree module taints kernel.
[    4.224598] ipts: module verification failed: signature and/or required key missing - tainting kernel
[    4.224804] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Probing IPTS
[    4.224806] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: IPTS using DMA_BIT_MASK(64)
[    4.240910] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:001F found
[    4.247431] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: IPTS enabled
```
There is a /dev/ipts file, but it's not a directory, hence /dev/ipts/0 cannot exist. 
Am I missing something ?

**Comment by StollD** [comment]
You have an old version of the kernel module installed, either through DKMS or loading it manually. The iptsd version you have requires a newer module, so please either update it or use the module that comes with the kernel (which is up to date).

**Comment by tihoulas** [comment]
That did it, thanks a lot.
