### ISSUE TITLE
SB3 last kernel stopped working

### ISSUE THREAD

**Issue by introlinux** [linux-surface/linux-surface#330]
I use linux-surface kernel in 20.04 from 5.7.10. With this kernel everything seems to work (except the camera). Then the system automatically updated to 5.8.1, and the touchscreen stopped working. In the latest update with kernel 5.9.3, I don't have touchscreen neither touchpad, I can't do anything other than turn off the computer.

But I am very surprised, because in other threads I have seen users like [aarow12](https://github.com/linux-surface/linux-surface/issues/326#issuecomment-722117125) reporting datas without problems (although I don't know if he has the same problems and he is using an external keyboard or mouse).

[dmesg-sb3-5.9.3-surface.txt](https://github.com/linux-surface/linux-surface/files/5506169/dmesg-sb3-5.9.3-surface.txt)

**Comment by qzed** [comment]
There's currently a bug on the SP7 that might affect the SB3 too (#329). Can you post the output of `ls -al /sys/bus/serial/devices` and `ls -al /sys/bus/pci/drivers/intel-lpss`? This could be responsible for touchpad and keyboard. You should be able to manually install v5.9.1 from our releases section to avoid that issue for now.

Regarding touchscreen, the way the input is handled has been changed with v5.8. You'll need to install `iptsd` and enable/start the corresponding service. See https://github.com/linux-surface/linux-surface/issues/96#issuecomment-674440883 for details.

**Comment by qzed** [comment]
#329 has been fixed. Can you check if updating to v5.9.6 works?

**Comment by n-davis** [comment]
I'm having the same problem on a Surface Laptop 3. Worked beautifully before.

**Comment by qzed** [comment]
@n-davis What kernel version are you on? Can you try upgrading to 5.9.6 (or 5.8.18-2 for Fedora)?

**Comment by introlinux** [comment]
With kernel 5.9.6 it works perfectly.
Thanks a lot.
