### ISSUE TITLE
Surface Laptop 3 keyboard and trackpad not working, Ubuntu 20.10

### ISSUE THREAD

**Issue by iamrobdavies** [linux-surface/linux-surface#331]
Hey folks,  Thanks for all the amazing work in this community!

Running Ubuntu 20.10 clean install on Intel Surface Laptop 3.  Trackpad and built in keyboard do not work (aside from power button).  Touchscreen does work.  Any tips on what is happening?

Sharing info for reference.  Let me know if anything else would be of use. 

**Hardware**
Microsoft Corporation Surface Laptop 3/Surface Laptop 3, BIOS 7.124.140
Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

**kernel params**
Updated with reboot=pci

**uname -a**
    Linux compname 5.9.3-surface #1 SMP Wed Nov 4 03:03:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**lsmod**
    surface_aggregator    118784  3 surface_acpi_notify,surface_hid,surface_aggregator_registry

I updated **/etc/initramfs-tools/modules** adding the following modules:
 surface_aggregator
 surface_aggregator_registry
 surface_hid
 intel_lpss
 intel_lpss_pci
 8250_dw

Had to update the compression in **/etc/initramfs-tools/initramfs.conf** to:
    COMPRESS=gzip

Then ran **sudo update-initramfs -c -k $(uname -r) -v**

I attempted the steps [here](https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3#iwlwifi-direct-firmware-load-for-iwlwifi-quqnj-b0-hr-b0-50ucode-failed-with-error--2) to add the firmware, but this fails with: 

`sudo ln -s iwlwifi-Qu-c0-hr-b0-50.ucode iwlwifi-Qu-b0-hr-b0-50.ucode
ln: failed to create symbolic link 'iwlwifi-Qu-b0-hr-b0-50.ucode': File exists`

**acpidump**
acpidump log is [here](https://rodaviesgithubsharetemp.blob.core.windows.net/logshare/acpidump.out)

**lsinput**
lsinput output is [here](https://rodaviesgithubsharetemp.blob.core.windows.net/logshare/lsinput.txt)

Thank you!

**Comment by qzed** [comment]
Can you run `ls -al /sys/bus/serial/devices` and `ls -al /sys/bus/pci/drivers/intel-lpss`? Could be related to #329.

**Comment by iamrobdavies** [comment]
Sure, here's the output.

`ls -al /sys/bus/serial/devices`
total 0
drwxr-xr-x 2 root root 0 Nov  8 10:02 .
drwxr-xr-x 4 root root 0 Nov  8 10:02 ..

`ls -al /sys/bus/pci/drivers/intel-lpss`
total 0
drwxr-xr-x  2 root root    0 Nov  8 10:02 .
drwxr-xr-x 32 root root    0 Nov  8 10:02 ..
--w-------  1 root root 4096 Nov  8 18:03 bind
lrwxrwxrwx  1 root root    0 Nov  8 18:03 module -> ../../../../module/intel_lpss_pci
--w-------  1 root root 4096 Nov  8 18:03 new_id
--w-------  1 root root 4096 Nov  8 18:03 remove_id
--w-------  1 root root 4096 Nov  8 10:02 uevent
--w-------  1 root root 4096 Nov  8 18:03 unbind

**Comment by qzed** [comment]
Okay, this looks like it's #329. I'll try to push new kernels with a fix for that today.

**Comment by qzed** [comment]
Forgot to mention it earlier: In the mean time you can downgrade to v5.9.1 via our github releases. That version should still work.

**Comment by pinophyta** [comment]
Can confirm the same for `linux-surface-5.9.3.arch1-1`

**Comment by qzed** [comment]
#329 has been fixed with the latest release. Can you check if it's working now?

**Comment by iamrobdavies** [comment]
confirmed - this fixed it. Thanks so much!

**Comment by qzed** [comment]
Thanks for confirming!

**Comment by Revorg** [comment]
to tengo el mismo problema, Surface Pro 3 Kernel 6.15, pero el teclado no funciona, la pantalla tactil tampoco... SOS
