### ISSUE TITLE
dgpu_power can't be found

### ISSUE THREAD

**Issue by mynameisjeffe** [linux-surface/linux-surface#332]
[Description of the bug or feature]
dgpu_power file missing. 

Thus when I type "surface status", I only see 
`Performance-Mode: Normal (2)`

When I type sudo surface gpu set off, the result is 
`Error: Cannot access device.
       No such file or directory (os error 2).
`
When I go to cd /sys/bus/acpi/devices/MSHW0153\:00/physical_node, I don't see dgpu_power file

Can anyone advice what should be done?

### Environment

- Hardware model: Surface Book 2 15' 
- Kernel version: 5.9.3-arch1-1-surface
- Distribution: Manjaro

**Comment by qzed** [comment]
The way the dGPU power is controlled has been changed. See our [announcement](https://github.com/linux-surface/linux-surface/issues/96#issuecomment-721475056) for details. Basically, now the dGPU isn't controlled explicitly, but rather automatically by the kernel via runtime PM (e.g. it's turned off if not in use and automatically turned on if it is). There is a bit of configuration necessary to enable auto-suspend and to make sure it works the way you want it to work. See the updated [wiki page](https://github.com/linux-surface/surface-aggregator-module/wiki/Discrete-GPU) for that.

**Comment by Aphoh** [comment]
@qzed The wiki page you link to has been removed. Any updated docs on how to configure this properly?

**Comment by qzed** [comment]
Right, sorry. I've moved the module and thus the wiki to https://github.com/linux-surface/surface-hotplug/wiki.
