### ISSUE TITLE
Running iptsd on startup

### ISSUE THREAD

**Issue by David-OConnor** [linux-surface/linux-surface#334]
Hi. I'm running Manjaro linux. I installed linux-surface per the instructions. Touchscreen and pen didn't work initially. After troubleshooting, discovered I need a terminal running `sudo iptsd`. As soon as I stop this program, touch and pen stop.

Is there a way to make `iptsd` run on startup, and always in the background? What is the officially-recommended way? I recommend adding this to the instructions. Thank you.

**Comment by qzed** [comment]
The package should come with a systemd service, so running `systemctl enable --now iptsd.service` should start it automatically on boot.

**Comment by David-OConnor** [comment]
Thank you - that did it!

**Comment by David-OConnor** [comment]
It looks like that will do it without leaving a terminal window, but not on boot. Any ideas? Presumably there's a text file I can add that line to.

**Comment by qzed** [comment]
That should normally start it on boot too. Can you post the output of `systemctl status iptsd.service` after a fresh boot?

**Comment by David-OConnor** [comment]
It appears to be working now after reboot. Thanks for the help, and sorry for the trouble. Great installation instructions btw, right up through getting it to work with FF. If it weren't for this lovely lib and its instructions, I would have uninstalled Linux and gone back to Windows.
