### ISSUE TITLE
README.md incorrect hibernation link

### ISSUE THREAD

**Issue by EvoEvz** [linux-surface/linux-surface#34]
The line "If you chose to use hibernate over suspend, please follow the instructions here."

seems to have an incorrect link. Is
https://github.com/linux-surface/linux-surface/wiki/Secure-Boot

but supposed to be
https://fitzcarraldoblog.wordpress.com/2018/07/14/configuring-lubuntu-18-04-to-enable-hibernation-using-a-swap-file/

**Comment by qzed** [comment]
You're right, thanks! Fixed.
