### ISSUE TITLE
Tounchreen won't work on SP4

### ISSUE THREAD

**Issue by 3elDU** [linux-surface/linux-surface#347]
I've installed everything as in the tutorial.

### Environment

- Hardware model: Surface Pro 4
- Kernel version: Linux zakhar-Surface-Pro-4 5.9.11-surface #1 SMP Sat Nov 28 03:12:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Linux Mint 20 Cinnamon

If i touch my touchscreen, nothing happens. I can touch it with one finger, or many, it doesn't matter, it just won't react to my actions.

<details><summary>`dmesg` output</summary>

dmesg output: https://pastebin.com/eH0gfN3x

</details>

I'm fairly new to linux, especially to this thing with modifying kernel, so sorry for any unconvenience.

**Comment by StollD** [comment]
How are you running iptsd? Did you enable the service with systemd? The devices are registered with quite a delay in the dmesg log, which leads me to believe that you are starting iptsd manually.

**Comment by 3elDU** [comment]
> How are you running iptsd? Did you enable the service with systemd? The devices are registered with quite a delay in the dmesg log, which leads me to believe that you are starting iptsd manually.

Thanks, i just typed "sudo service iptsd start" and it will work.
