### ISSUE TITLE
typecover hotswapping doesn't work on the 4.19 lts kernel. typecover only works again after reboot

### ISSUE THREAD

**Issue by ultimo2002** [linux-surface/linux-surface#350]
running on manjaro on a surface pro 4

**Comment by ultimo2002** [comment]
hello?
anyone there?

**Comment by qzed** [comment]
Yes, we're here. Can you provide a dmesg log after detaching and re-attaching the typecover? Does this issue also persist on the non-lts kernel?

**Comment by ultimo2002** [comment]
> Yes, we're here. Can you provide a dmesg log after detaching and re-attaching the typecover? Does this issue also persist on the non-lts kernel?

I have tried other versions of the kernel too, and the problem didn't occur there. I will get a dmesg log tomorrow

**Comment by ultimo2002** [comment]
Maybe im doing it wrong, but sudo dmesg doesn't show anything when reconnecting the typecover. I installed other versions of the kernel to check again and the issue is not present there

**Comment by qzed** [comment]
It's entirely possible that there isn't any relevant information in dmesg. Is there anything that gets printed when you remove the typecover for the first time? Also can you try to figure out how the typecover is handled (I'd assume via USB) and if the corresponding input device gets removed properly?

**Comment by ultimo2002** [comment]
> It's entirely possible that there isn't any relevant information in dmesg. Is there anything that gets printed when you remove the typecover for the first time? Also can you try to figure out how the typecover is handled (I'd assume via USB) and if the corresponding input device gets removed properly?

My surface pro 4 died after i attempted a repair so i guess we will never know☹️

**Comment by qzed** [comment]
Oh, sorry to hear that.

I'm closing this issue for now. If someone else has this issue, feel free to comment and request a re-open.
