### ISSUE TITLE
Brave/Chromium works with touch

### ISSUE THREAD

**Issue by SwannSchilling** [linux-surface/linux-surface#352]
Until the Firefox touch issues are resolved...
Brave and Chromium are working well with touch and the latest kernel!
Brave is build on Chromium and is a good privacy based browser anyways!

**Comment by StollD** [comment]
There are no touch issues with firefox. You just need to enable an option if you are on X11 (`MOZ_USE_XINPUT2=1`). You dont need to do anything on wayland (you can set `apz.allow_zooming` in about:config for better zooming).

And is there a reason why you open an issue, close it, and then open the same issue again?

**Comment by SwannSchilling** [comment]
Hey, sorry for the mess...I kind of just wanted to share this!
Thanks for taking the time to answer and thanks for making this all possible!!

If I am trying to scroll in Firefox on Wayland, it just marks the text!
So I thought it is still an issue!

Do you want to close this, or should I?
Sorry for the double post!

**Comment by StollD** [comment]
> If I am trying to scroll in Firefox on Wayland, it just marks the text!

You need to enable the firefox wayland backend, otherwise it will still use X11. Some distros default to the wayland backend, others still use X11. Put this into your `~/.bashrc` to force the wayland backend: `export MOZ_ENABLE_WAYLAND=1`

**Comment by SwannSchilling** [comment]
I just did this, but it does not change anything...it still just marks text!
I can also try X11 just to confirm!

The pen and touch is also not working on boot, it starts working once i suspend...that kind of wakes it up!
Also just single touch in working on my SP4, but that is the correct way it should work, right?
I followed this setup
https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup

But I am very happy the way this all works, thank to your effort!!!
So if I cannot get Firefox to scroll, I can totally live with that!

**Comment by SwannSchilling** [comment]
Could this be because I did nor manually install Firefox? It came packaged with my distro...

**Comment by Panja0** [comment]
@SwannSchilling do you use Wayland or X11?
I have Ubuntu running and I've got touch enabled for Firefox.

**Comment by SwannSchilling** [comment]
OK, cool...I will close it down, thanks a lot for that info!!
