### ISSUE TITLE
A little problem while adding the Key

### ISSUE THREAD

**Issue by hypghzy** [linux-surface/linux-surface#355]
### Environment

- Hardware model: Surface pro 3
- Kernel version: Linux 5.9.12-surface x86_64
- Distribution: Deepin (build on ubuntu)

wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg

it shows that 
gpg: cannot find valid OpenPGP data.
i translate that line from another language, there might be some difference from the original line.

**Comment by SamLukeYes** [comment]
I guess you're in China. If so, please note that raw.githubusercontent.com is blocked by GFW. I've set up a [mirror](https://gitee.com/SamLukeYes/linux-surface) of this git repo on Gitee (without binary releases), and you can replace the URL in the command with [this one](https://gitee.com/SamLukeYes/linux-surface/raw/master/pkg/keys/surface.asc). Alternatively, you can simply copy the text of [this file](https://github.com/linux-surface/linux-surface/blob/master/pkg/keys/surface.asc), save it as a file, and run `cat /path/to/file | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg`

**Comment by hypghzy** [comment]
> I guess you're in China. If so, please note that raw.githubusercontent.com is blocked by GFW. I've set up a [mirror](https://gitee.com/SamLukeYes/linux-surface) of this git repo on Gitee (without binary releases), and you can replace the URL in the command with [this one](https://gitee.com/SamLukeYes/linux-surface/raw/master/pkg/keys/surface.asc). Alternatively, you can simply copy the text of [this file](https://github.com/linux-surface/linux-surface/blob/master/pkg/keys/surface.asc), save it as a file, and run `cat /path/to/file | gpg --dearmor | sudo dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg`

Thank you !! It works.
