### ISSUE TITLE
SB3 stuck on power down/reboot

### ISSUE THREAD

**Issue by blueskull** [linux-surface/linux-surface#359]
Hi community, 

I installed Ubuntu 20.04 on my SB3 15", and for the most part I'm happy, but it just refuses to power down, which annoys me a bit.

The symptom is simple, I can initiate a shutdown sequence, and using "journalctl -b -1 | tail" I can see the previous shutdown process has completed, at least on the software side, but the hardware will not cut off power.

This is what I got:

> Dec 13 15:02:50 bo-surface systemd[1]: Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
> Dec 13 15:02:50 bo-surface systemd[1]: Reached target Shutdown.
> Dec 13 15:02:50 bo-surface systemd[1]: Reached target Final Step.
> Dec 13 15:02:50 bo-surface systemd[1]: systemd-reboot.service: Succeeded.
> Dec 13 15:02:50 bo-surface systemd[1]: Finished Reboot.
> Dec 13 15:02:50 bo-surface systemd[1]: Reached target Reboot.
> Dec 13 15:02:50 bo-surface systemd[1]: Shutting down.
> Dec 13 15:02:51 bo-surface systemd-shutdown[1]: Syncing filesystems and block devices.
> Dec 13 15:02:51 bo-surface systemd-shutdown[1]: Sending SIGTERM to remaining processes...
> Dec 13 15:02:51 bo-surface systemd-journald[303]: Journal stopped

But the hardware will remain powered, despite the screen being off. Overtime, the computer will overheat if shoved in a bag, and the fan will kick in rabidly. I need to press the power button for a few secs to force powering it down more often than not, though the bug doesn't trigger 100% of the time.

Sometimes the bug doesn't trigger after hours of use and a few suspends, sometimes it triggers just an hour after boot, but generally the chance it triggers increases with time it has been booted.

BTW, I had the same issue with non-Surface kernel on my Acer Swift 5 2020 (same CPU, dGPU disabled), but the frequency it triggers is much, much lower, enough that I see it only probably once or twice a week.

I tried "reboot=pci" in /etc/default/grub and updated grub, with no help. I tried the kernel purge trick documented on Reddit before, with no help. In fact, I never had any Linux 4.x kernel installed, ever.

System information:

HW: Surface Book 3 15", i7-1065G7, 32GB, 1TB, GTX1660Ti Mobile
OS: Ubuntu 20.04, Linux 5.9.13-surface, X11, Gnome 3.36, dGPU disabled per SAM wiki, Secure Boot
Alt OS: Windows 10 20H2, stock installation, upgraded to Pro

Dmesg printout:

https://drive.google.com/file/d/1UbanLVrzuLwgH6b0wJsPed54vmLu7Wtd/view?usp=sharing

Regards, 

Bo Gao

**Comment by blueskull** [comment]
Problem still persists with Linux 5.9.14, with and without pci=noaer. Option pci=nomsi prevents iwlwifi from loading, so I turned it off without exhaustive testing.

**Comment by nullobsi** [comment]
I get this same issue on my SB2. The laptop will power off, but the backlight will still be on.

**Comment by blueskull** [comment]
> I get this same issue on my SB2. The laptop will power off, but the backlight will still be on.

I no longer have this since some version of 5.10. Also I didn't have stuck BL, just the fan wouldn't come off and the CPU would still dissipate power and get toasted if placed in a bag.
