### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#36]
Hello,

I currently have my SB2 with latest jakeday's kernel and I would like to update with this repository.

Should I install the `linux-surface/kernel` or retrieve the linux kernel from `kernel.org` and apply patches of this repository ?

Also, for a SB2 which kernel version to use ? 5.3 or 5.4 ?

Last question, there seem to be several versions of the ipts firmware ? Which one should I use ?

Regards

**Comment by qzed** [comment]
Depends on what you want:
- Choose `linux-surface/kernel` with one of the `-surface` branches if you want to get a tested set of sources that represents the current releases provided in this repo. Don't use the `surface-devel` branch unless you want to do development, as that's only there to keep a somewhat sane git history.
- Choose the kernel.org sources if you're not afraid of fixing some stuff manually (e.g. I think in 5.4.8 you'll need to drop the HID patch) and want the latest upstream source version.

As to kernel version: 5.4 doesn't have support for IPTS yet, so you'll probably want to go with 5.3.

For IPTS firmware, the easiest way is to just install everything (copy the whole `firmawre/intel/ipts` directory), the driver will select the correct one for you. If you really only want to install the correct one, then only copy the `MSHW0137` subdirectory. Basically, the target location should be `/lib/firmware/intel/ipts/<model>/<file>.bin`)

**Comment by deb75** [comment]
Thanks for your answeer,

I have cloned the v5.3-surface branch of the `linux-surface/kernel` repository. If I understand well, it is not necessary to patch it.

**Comment by qzed** [comment]
The `-surface` branches are actually what I use to generate the patches. Meaning you're correct and the patches don't need to be applied on that branch.

**Comment by deb75** [comment]
Another question, from the jakeday's repository I used to modify some files in `/etc` and `/lib`,  mainly for loading/unloading modules when hibernating and adjusting `systemd` and `udev`.

In this repository, nearly all modifications have disappeared, at least there is no more anything applicable to the SB2. Does it mean that with `linux-surface/kernel` I do not need anymore to unload some modules (touchscreen, wifi) prior to hibernating ? Do I still need some udev rules to dock/undock ? Also, does it mean that `suspend` is now working ? It was an unsupported sleeping mode a few month ago.

I had a look at the wifi page for the SB2. The discrete GPU is said to work, does it mean the bug whic h was causing the GPU to slow down is fixed ?

Regards

**Comment by qzed** [comment]
As far as we can tell, the removed modifications are not needed any more. You shouldn't need to unload any modules any more prior to suspend. Also suspend is now recommended over hibernate. If you want to do specific things before undocking (e.g. unloading the nvidia driver), you should have a look at the DTX daemon, the udev rules should not be used for that as they trigger only after actually removing the clipboard and thus trigger too late.

The only issue remaining with the dGPU is the sub-par performance when not connected to AC. Still haven't figured that one out. When connected to AC everything works as it should.

**Comment by deb75** [comment]
Hi,

I installed the 5.3.18 surface kernel and updated the libwacom package from your repository, plus `surface-control` and `surface-dtx-daemon`.

When I run `acpi -V` I get the output :
```
Battery 0: Discharging, 100%, 07:10:50 remaining
Battery 0: design capacity 4561 mAh, last full capacity 3734 mAh = 81%
Battery 1: Discharging, 100%, 07:32:02 remaining
Battery 1: design capacity 2138 mAh, last full capacity 1665 mAh = 77%
Adapter 0: off-line
Cooling 0: Processor 0 of 10
Cooling 1: GEN7 no state information available
Cooling 2: Processor 0 of 10
Cooling 3: GEN9 no state information available
Cooling 4: Processor 0 of 10
Cooling 5: B0D4 no state information available
Cooling 6: Processor 0 of 10
Cooling 7: GEN1 no state information available
Cooling 8: Processor 0 of 10
Cooling 9: GEN6 no state information available
Cooling 10: Processor 0 of 10
Cooling 11: GEN8 no state information available
Cooling 12: Processor 0 of 10
Cooling 13: pch_skylake no state information available
Cooling 14: intel_powerclamp no state information available
Cooling 15: x86_pkg_temp no state information available
Cooling 16: INT3400 Thermal no state information available
Cooling 17: Processor 0 of 10
Cooling 18: GEN5 no state information available
```
There are plenty of `no state available`, I wonder if it is normal ?

Also, touchcscreen works but I noticed it does not appear in `xinput` : 
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Consumer Control	id=8	[slave  pointer  (2)]
⎜   ↳ Microsoft Surface Keyboard Touchpad     	id=9	[slave  pointer  (2)]
⎜   ↳ ipts 045E:0021                          	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard              	id=7	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=12	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=13	[slave  keyboard (3)]
    ↳ Microsoft Surface Keyboard Consumer Control	id=14	[slave  keyboard (3)]
    ↳ ipts 045E:0021                          	id=11	[slave  keyboard (3)]
```
The consequence is just that when I rotate the screen, the touchscreen does not. Am I missing something ?

**Comment by qzed** [comment]
> There are plenty of `no state available`, I wonder if it is normal ?

To be honest, I have no idea, but I have the same results.

> Also, touchcscreen works but I noticed it does not appear in `xinput`

The touchscreen should be the `ipts 045E:0021` devices.

> The consequence is just that when I rotate the screen, the touchscreen does not. Am I missing something ?

What desktop environment are you running? As far as I know, automatic rotation only works with Gnome in combination with libwacom. If you're running any other DE, you may have to configure something.

**Comment by deb75** [comment]
I am running `awesome` and I use this lua module to manage rotation :
```
#!/usr/bin/lua5.3

local dbus = require "dbus_proxy"
local awful = require("awful")
local gears = require("gears")
local naughty = require("naughty")


local config = {
   devices = {
      "ipts 045E:0021",
      "ipts 045E:0021 Pen (0)",
      "ipts 045E:0021 Eraser (0)"
   }
}


local proxy = dbus.Proxy:new(
   {
      bus = dbus.Bus.SYSTEM,
      name = "net.hadess.SensorProxy",
      interface = "org.freedesktop.DBus.Properties",
      path = "/net/hadess/SensorProxy"
   }
)

proxy:ClaimAccelerometer()

local XinputMatrices = {
   normal = "1 0 0 0 1 0 0 0 1",
   inverted = "-1 0 1 0 -1 1 0 0 1",
   left = "0 -1 1 1 0 0 0 0 1",
   right = "0 1 0 -1 0 1 0 0 1",
}


local active = nil

local function callback(proxy_obj, interface, chprop)
   if active == false then return end

   local devices = {}

   if interface == "net.hadess.SensorProxy" then
      local orientation = chprop["AccelerometerOrientation"]
      if orientation ~= nil then
         local p = io.popen("xinput --list --name-only")
         local output = p:read("*a")
         p:close()

         local rows = gears.string.split(output, "\n")
         for _, device in ipairs(rows) do
            for _, devname in ipairs(config.devices)
            do
               if device == devname then
                  table.insert(devices, device)
                  break
               end
            end
         end

         if orientation == "left-up" then
            orientation = "left"
         elseif orientation == "right-up" then
            orientation = "right"
         elseif orientation == "bottom-up" then
            orientation = "inverted"
         end

         for _, v in ipairs(devices)
         do
            local cmd = "xinput set-prop '" .. v
               .. "' --type=float 'Coordinate Transformation Matrix' "
               .. XinputMatrices[orientation]

            awful.spawn(cmd, false)
         end

         awful.spawn("xrandr -o " .. orientation, false)
      end
   end
end


local function init()
   awful.spawn.easy_async("xinput --list --name-only", function(stdout)
                             if string.find(stdout, "Microsoft Surface Keyboard") then
                                active = false
                             else
                                active = true
                             end
   end)
   proxy:connect_signal(callback, "PropertiesChanged", nil)
end


local function toggle()
   active = not active
   naughty.notify({
         font = "Monospace 16", timeout = 5,
         text = "<span weight = \"bold\">Toggle</span> screen rotation <span weight = \"bold\">[" .. (active and "<span color = \"magenta\">ON</span>" or "<span color = \"cyan\">OFF</span>") .. "]</span>" })
end

local function is_active()
   return active
end

return {init = init, toggle = toggle, is_active = is_active}
```

It works with the pen and the erasor but no more with the touchscreen although I told the module which device is the touchscreen, as you said. It is possible there is as bug in the module, but it was working fine before.

Regards

**Comment by qzed** [comment]
Glad you got it working! I was just about to ask what happens when two devices are named the same. This is a (bit unfortunate) consequence of us dropping the modifications to the HID core drivers.
