### ISSUE TITLE
Log message of `libbpf: failed to find kernel BTF` upon upgrading to the latest Arch Linux package

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [linux-surface/linux-surface#375]
Log message of `libbpf: failed to find kernel BTF` upon upgrading to the latest Arch Linux package

### Environment

- Hardware model: Surface Laptop 3 (Intel)
- Kernel version: `Linux 5.10.5-arch1-1-surface #1 SMP PREEMPT Fri, 08 Jan 2021 00:10:23 +0000 x86_64 GNU/Linux`
- Distribution: Arch

**Comment by k4ever** [comment]
I have the exact same issue. I was going to file a report myself until I saw this one.

Environment

Hardware model: Surface Pro 4 (Intel)
Kernel version: 5.10.5-arch1-1-surface #1 SMP PREEMPT Fri, 08 Jan 2021 00:10:23 +0000 x86_64 GNU/Linux
Distribution: Manjaro KDE 20.2

**Comment by qzed** [comment]
I believe this is because `CONFIG_DEBUG_INFO_BTF` is not enabled. Unfortunately, I don't think that we can fix that. This option depends on `CONFIG_DEBUG_INFO`, which we've specifically disabled to save memory (and time) during kernel compilation. Without that, we've been running into the memory limit on GitHub Actions (see 06d6fbbe8248f893aaeaadcb9cb4ded39844205a).

I think you'll unfortunately have to build the kernel yourselves if you need `CONFIG_DEBUG_INFO_BTF`.

**Comment by 1900011604** [comment]
Is there a way to keep the message hidden when booting or enable `CONFIG_DEBUG_INFO_BTF` after installing?

**Comment by markgeejw** [comment]
hi! is it possible to disable CONFIG_BPF_PRELOAD in compilations as well, to remove the warnings

**Comment by qzed** [comment]
Thanks for that hint! I assume this shouldn't have any big drawbacks?

**Comment by qzed** [comment]
This change is included in the upcoming v5.11.10 kernel.

**Comment by unikzforce** [comment]
> I believe this is because `CONFIG_DEBUG_INFO_BTF` is not enabled. Unfortunately, I don't think that we can fix that. This option depends on `CONFIG_DEBUG_INFO`, which we've specifically disabled to save memory (and time) during kernel compilation. Without that, we've been running into the memory limit on GitHub Actions (see [06d6fbb](https://github.com/linux-surface/linux-surface/commit/06d6fbbe8248f893aaeaadcb9cb4ded39844205a)).
> 
> I think you'll unfortunately have to build the kernel yourselves if you need `CONFIG_DEBUG_INFO_BTF`.

Hi  @qzed  Thanks for all the efforts.

is the github action memory still a blocker for adding BTF information?

**Comment by qzed** [comment]
@unikzforce I have not checked if anything has changed regarding that recently. For now, we've just kept it disabled, but at some point I can try again.
