### ISSUE TITLE
Surface Laptop (1st Gen) Keyboard doesn’t work out of the box.

### ISSUE THREAD

**Issue by Parinz** [linux-surface/linux-surface#385]
[Description of the bug or feature]
The Surface Laptop 1st gen’s keyboard doesn’t actually work out of the box and requires the Surface-Linux  kernel to work, contrary to the feature matrix.

Tested on: Fedora, Arch, Ubuntu, and Debian

- Hardware model: Surface Laptop 1st Gen

**Comment by qzed** [comment]
Right, that is correct. I've fixed the feature matrix.
