### ISSUE TITLE
How to install surface-control, surface-dtx-daemon, and libwacom-surface

### ISSUE THREAD

**Issue by jonkatz6** [linux-surface/linux-surface#388]
How can I install `surface-control`, `surface-dtx-daemon`, and `libwacom-surface` on surface book 2 on Manjaro?
 I was able to use the surface-control utility in ubuntu but have not been able to install on Manjaro Arch. 

`sudo pacman -Syu surface-control`, `sudo pacman -Syu surface-dtx-daemon`, and `sudo pacman -Syu libwacom-surface` all show `target not found

### Environment
- Surface Book 2 13
- Linux JKSB 5.10.8-arch1-1-surface #1 SMP PREEMPT Mon, 18 Jan 2021 05:46:05 +0000 x86_64 GNU/Linux
- Manjaro Arch

**Comment by StollD** [comment]
On Arch they are packaged in the AUR, not in our repository.

**Comment by SamLukeYes** [comment]
Enable the AUR support of Add/Remove Software (disable "software mode" if enabled), and then you can search and install these packages using the GUI, or use the command `pamac build surface-control surface-dtx-daemon libwacom-surface`.

BTW, *Manjaro is not Arch*.

**Comment by SamLukeYes** [comment]
Enable the AUR support of Add/Remove Software (disable "software mode" if enabled), and then you can search and install these packages using the GUI, or use the command `pamac build surface-control surface-dtx-daemon libwacom-surface`.

BTW, *Manjaro is not Arch*.

**Comment by SamLukeYes** [comment]
Enable the AUR support of Add/Remove Software (disable "software mode" if enabled), and then you can search and install these packages using the GUI, or use the command `pamac build surface-control surface-dtx-daemon libwacom-surface`.

BTW, *Manjaro is not Arch*.
