### ISSUE TITLE
Surface Laptop 1: Speaker noise when headphones are plugged in.

### ISSUE THREAD

**Issue by VisibleReality** [linux-surface/linux-surface#401]
When headphones are plugged in and audio is playing, white noise comes out of the speakers. The noise starts as soon as audio starts playing and stops a few seconds after it stops playing. Adjusting the volume of the audio device has no effect on the volume of the noise. The noise doesn't happen when headphones are unplugged, even if the speakers have a low volume or are muted. The audio is playing perfectly fine through the headphones. I've recorded a video of this happening, you will probably have to turn your volume up to hear it though as its pretty quiet. https://youtu.be/Q6aCL-c0D7c

### Environment

- Hardware model: Surface Laptop 1 (i7, 8GB RAM, 256GB SSD)
- Kernel version: Linux alexander-Surface-Laptop 5.10.8-surface #1 SMP Mon Jan 18 05:51:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Kubuntu 20.04

<details><summary>`dmesg` output</summary>

[dmesg.log](https://github.com/linux-surface/linux-surface/files/5996705/dmesg.log)

</details>

**Comment by DrMaxNix** [comment]
Same thing happening on `Surface Pro 7` with `Ubuntu 20.04` and kernel `5.10.16-surface`

**Comment by DrMaxNix** [comment]
I just randomly found out the noise goes away when you disable 'auto-mute mode' with `sudo amixer sset "Auto-Mute Mode" Disabled`

**Comment by archseer** [comment]
I had this denoted on the SL3 page, I guess it should be moved to the main wiki entry: https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-3#hiss-sound-through-speakers-when-headphones-plugged-in

**Comment by DrMaxNix** [comment]
Yep, seems like this is device-independent. But isn't this a bug in the surface-kernel then? And where in the wiki should the note about the 'workaround' get added? New page under 'Device Independent Information'?

**Comment by qzed** [comment]
Looks like a fairly small fix/entry, so "Known Issues" is probably better. Although that page could probably use some cleanup/updates.

**Comment by DrMaxNix** [comment]
I added a section to the 'Known Issues' Page [here](https://github.com/linux-surface/linux-surface/wiki/Known-Issues-and-FAQ#speaker-noise-when-headphones-plugged-in).
The device specific info for Surface Laptop 3 still contains a notice about this fix.. should this be removed or replaced by a link to the 'Known Issues' Page?

**Comment by qzed** [comment]
I think a link to the "Known Issues" page would be best.

**Comment by DrMaxNix** [comment]
No problem, I linked the 'Known Issues'-page

**Comment by archseer** [comment]
Thanks! Closing this now, since it's properly documented.
