### ISSUE TITLE
Unable to pair my pen with surface go

### ISSUE THREAD

**Issue by paju1986** [linux-surface/linux-surface#405]
Using KDE NEON with plasma mobile I'm unable to pair my stylus via bluetooth with the surface go, when I tried to pair it says the assistant has a problem and crashes, my pen is the 2 buttons on the side and clip one, it works without pairing minus the buttons 

- Hardware model: Surface Go
- Kernel version: 5.10.17-surface
- Distribution: KDE Neon

**Comment by afalout** [comment]
Works on Ubuntu Groovy. Also 2 button pen with purple eraser/cap.
I note that I had to try pairing several times before it finally worked.
Andrej

**Comment by jonas2515** [comment]
If the assistant crashes this is most likely a KDE bug. Can you check if it also happens on GNOME based distributions like Fedora? I'm closing this issue for now, please reopen and attach system logs and `dmesg` output if you're confident it's a kernel bug.
