### ISSUE TITLE
Upstreaming the ath10k board file

### ISSUE THREAD

**Issue by archseer** [linux-surface/linux-surface#41]
We would like to upstream http://www.killernetworking.com/support/K1535_Debian/board.bin so that the manual patching is no longer required (since it breaks on every linux-firmware update) for the ath10k based wifi chips.

Upstreaming process: https://wireless.wiki.kernel.org/en/users/drivers/ath10k/boardfiles

Open PR, might include the right files: https://github.com/kvalo/ath10k-firmware/pull/2#issuecomment-232317668

I think the project doesn't merge PRs and we'd need to correctly send the board files via the mailing list.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1383184/comments/351

Sorry to ping you directly @PandorasFox, but would you be interested in doing this? The rest of us don't really have the right hardware to test the firmware.

**Comment by archseer** [comment]
(Also, please feel free to join us on matrix/freenode https://github.com/linux-surface/linux-surface#support to discuss this and other AMD related bugs)

**Comment by PandorasFox** [comment]
Sounds good to me. I'll be a bit busy for the next ~two weeks, then I'll mail the board files and get on that.

**Comment by archseer** [comment]
Hey @thebitstick after seeing [your workaround](https://github.com/thebitstick/surfacego-touchscreen), thought I'd CC you here as well. We probably just need to literally send that board.bin file with some extra information.

(Would you mind [adding yourself to the testers list too?](https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing) We don't have any Surface Go users yet.)

**Comment by thebitstick** [comment]
I think you meant to link [this one](https://github.com/thebitstick/surfacego-wifi).
I'd be willing to add myself to the list.

**Comment by PandorasFox** [comment]
Sorry - I forgot to mention; I ended up passing my SL3 on to a friend who needed it, so I never got around to mailing this off since I didn't have a way to verify the bin file anymore.

**Comment by thebitstick** [comment]
Update: Due to classes going online-only, I've had to install Windows on my Surface; which I'm fine with since I just received my Pinebook Pro.
I'll keep myself on the testers list since I'm hoping that I can re-install Manjaro/Fedora for the summer.

**Comment by archseer** [comment]
@thebitstick You can always dual boot! :)

@fxgsell Can you give me the output of `dmesg | grep ath10k` before replacing the wifi firmware files, and after? I have the required data for Surface Go so I'm going to do the upstreaming, I just need to double check if the SL3AMD output matches.

**Comment by archseer** [comment]
I've submitted the board for upstreaming: http://lists.infradead.org/pipermail/ath10k/2020-April/014817.html

**Comment by archseer** [comment]
Didn't get a follow up to my bump: http://lists.infradead.org/pipermail/ath10k/2020-August/011758.html

**Comment by keplersj** [comment]
I have both a 1st Gen Surface Go and an AMD Surface Laptop 3, what needs to be done to upstream the binary needed for this?

**Comment by qzed** [comment]
There's a new push for upstreaming the (this time correct) board file (at least for the Surface Go), see #542. Maybe someone with a Surface Laptop 3 could check if the board file provided by Windows is the same on that device?

**Comment by keplersj** [comment]
I'm more than happy to check this out on both of my devices! I'll check later tonight and write back here.

**Comment by jwrdegoede** [comment]
> There's a new push for upstreaming the (this time correct) board file (at least for the Surface Go), see #542. Maybe someone with a Surface Laptop 3 could check if the board file provided by Windows is the same on that device?

As I tried to explain in #542 the way this stuff works is that we need to add a board.bin file (the proper board.bin file) to boards-2.bin for each pci subsys vendor-id:product-id pair. The `Windows\System32\driverstore\netath10k` dir on my Surface Go has a ton of eeprom files and the netath10k.inf allows mapping the pci subsys vendor-id:product-id pairs to those files.

So if people can provide me with the pci subsys vendor-id:product-id pairs for their wifi,see the `PCI 168c:003e subsys: xxxx:xxxx` line in dmesg, then I can dig up the board.bin for that subsys vendor-id:product-id pair and once tested also submit those board.bin-s for the other subsys vendor-id:product-id pairs upstream.

For starters I wonder what the subsys vendor-id:product-id pair is on the Surface Go LTE, the netath10k.inf file suggests that the LTE version might have a different subsys vendor-id:product-id pair (and uses a different board.bin).

**Comment by mexisme** [comment]
> Hey @thebitstick after seeing [your workaround](https://github.com/thebitstick/surfacego-touchscreen), thought I'd CC you here as well. We probably just need to literally send that board.bin file with some extra information.
> 
> (Would you mind [adding yourself to the testers list too?](https://github.com/linux-surface/linux-surface/wiki/Testers-and-Contributing) We don't have any Surface Go users yet.)

I'm also an (intermittant) Surface Go v.1 user, and happy to help test.

But I'm using NixOS so perhaps have more flexibility in getting this going — see https://github.com/NixOS/nixos-hardware/tree/master/microsoft/surface/firmware/surface-go/ath10k for how I implemented it.

FYI: this uses a `board.bin` from https://github.com/mexisme/linux-surface_ath10k-firmware which is much easier to use from NixOS.

**Comment by keplersj** [comment]
Hi @jwrdegoede, sorry for the delay! I've attached some of the output from my Surface Laptop 3 AMD about the network adapter. Below is the output from `lspci`:

```
02:00.0 Network controller: Qualcomm Atheros QCA6174 802.11ac Wireless Network Adapter (rev 32)
	Subsystem: Device 045e:0001
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0
	Interrupt: pin A routed to IRQ 60
	IOMMU group: 0
	Region 0: Memory at fa000000 (64-bit, non-prefetchable) [size=2M]
	Capabilities: [40] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0+,D1-,D2-,D3hot+,D3cold+)
		Status: D0 NoSoftRst- PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [50] MSI: Enable+ Count=1/8 Maskable+ 64bit-
		Address: fee00000  Data: 0000
		Masking: 000000fe  Pending: 00000000
	Capabilities: [70] Express (v2) Endpoint, MSI 00
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 <64us
			ExtTag- AttnBtn- AttnInd- PwrInd- RBE+ FLReset- SlotPowerLimit 0.000W
		DevCtl:	CorrErr- NonFatalErr- FatalErr- UnsupReq-
			RlxdOrd+ ExtTag- PhantFunc- AuxPwr- NoSnoop-
			MaxPayload 128 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr+ NonFatalErr- FatalErr- UnsupReq- AuxPwr+ TransPend-
		LnkCap:	Port #0, Speed 2.5GT/s, Width x1, ASPM L0s L1, Exit Latency L0s <4us, L1 <64us
			ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, Disabled- CommClk+
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
		LnkSta:	Speed 2.5GT/s (ok), Width x1 (ok)
			TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Not Supported, TimeoutDis+ NROPrPrP- LTR+
			 10BitTagComp- 10BitTagReq- OBFF Via message, ExtFmt- EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS- TPHComp- ExtTPHComp-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR+ OBFF Disabled,
			 AtomicOpsCtl: ReqEn-
		LnkCap2: Supported Link Speeds: 2.5GT/s, Crosslink- Retimer- 2Retimers- DRS-
		LnkCtl2: Target Link Speed: 2.5GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance De-emphasis: -6dB
		LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete- EqualizationPhase1-
			 EqualizationPhase2- EqualizationPhase3- LinkEqualizationRequest-
			 Retimer- 2Retimers- CrosslinkRes: unsupported
	Kernel driver in use: ath10k_pci
	Kernel modules: ath10k_pci
```

As well, the output from `dmesg` related to the adapted:

```
[    0.159185] pci 0000:02:00.0: [168c:003e] type 00 class 0x028000
[    0.159885] pci 0000:02:00.0: reg 0x10: [mem 0xfa000000-0xfa1fffff 64bit]
[    0.163212] pci 0000:02:00.0: PME# supported from D0 D3hot D3cold
[    0.192075] pci 0000:02:00.0: Adding to iommu group 0
[    6.584117] ath10k_pci 0000:02:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[    6.846571] ath10k_pci 0000:02:00.0: qca6174 hw3.2 target 0x05030000 chip_id 0x00340aff sub 045e:0001
[    6.846577] ath10k_pci 0000:02:00.0: kconfig debug 1 debugfs 1 tracing 1 dfs 0 testmode 0
[    6.846972] ath10k_pci 0000:02:00.0: firmware ver WLAN.RM.4.4.1-00157-QCARMSWPZ-1 api 6 features wowlan,ignore-otp,mfp crc32 90eebefb
[    6.909827] ath10k_pci 0000:02:00.0: firmware override: pretending 'board-2.bin' does not exist
[    6.909833] ath10k_pci 0000:02:00.0: firmware override: replacing 'board.bin' with 'board-override.bin'
[    6.910054] ath10k_pci 0000:02:00.0: board_file api 1 bmi_id N/A crc32 70c38a29
[    7.002286] ath10k_pci 0000:02:00.0: htt-ver 3.60 wmi-op 4 htt-op 3 cal otp max-sta 32 raw 0 hwcrypto 1
[    7.088897] ath10k_pci 0000:02:00.0 wlp2s0: renamed from wlan0
```

I apologize if this is more than is needed, just wanted to provide anything that could be helpful here.

**Comment by jwrdegoede** [comment]
@keplersj do you still have Windows on your Surface? To find the right / official board.bin for the wifi in your model Surface I need the contents of the Windows\System32\DriverStore\FileRepository\netathr10x.inf* directory or directories.

If you can create a zip with the contents of that dir, or those directories if there are multiple and attach that here or provide a link to it that would be great.

**Comment by keplersj** [comment]
I do, I dual boot Windows at work and Linux at home. Happy to dig in and share what I have. I'll share when I get a moment in the next couple days

**Comment by keplersj** [comment]
Hi @jwrdegoede my laptop containing two directories matching for netathr10x in the Driver Store File Repository. I've zipped them, uploaded them to IPFS, and pinned them: [IPFS object](ipfs://bafybeienoohsqj4hdfrcmoahih3ltafohnd326zq35piypq7r7pamlsme4) / [link to pinned copy](https://storageapi.fleek.co/keplersj-team-bucket/Surface Laptop 3 Model 1873  WiFi Driver Extract.zip)

**Comment by jwrdegoede** [comment]
> Hi @jwrdegoede my laptop containing two directories matching for netathr10x in the Driver Store File Repository. I've zipped them, uploaded them to IPFS, and pinned them: [IPFS object](https://ipfs.io/ipfs/bafybeienoohsqj4hdfrcmoahih3ltafohnd326zq35piypq7r7pamlsme4?filename=bafybeienoohsqj4hdfrcmoahih3ltafohnd326zq35piypq7r7pamlsme4) / [link to pinned copy](https://storageapi.fleek.co/keplersj-team-bucket/Surface%20Laptop%203%20Model%201873%20%20WiFi%20Driver%20Extract.zip)

@keplersj, thank you. I've extracted the correct eeprom file for your Surface (subsys ids 045e:0001) and put it here: https://fedorapeople.org/~jwrdegoede/eeprom_ar6320_3p0_Parsberg_clpc.bin

Can you please replace `/usr/lib/firmware/ath10k/QCA6174/hw3.0/board.bin` with this file and then see if things still work (or maybe even work better) ?

Also, if this works can you please move `/etc/modprobe.d/ath10k.conf` to your homedir and then after a reboot do `cat /sys/module/ath10k_core/parameters/skip_otp` this should now say `N`; if that indeed says `N`, then please check your wifi again, it should still work. At least for me the setting of this option to `Y` as advertised on the wiki is not necessary.

**Comment by keplersj** [comment]
Hey @jwrdegoede, thanks for all of your help on this! I've followed your instructions on my Surface Laptop and everything is working great! I took a speed test at every step to try and capture any performance changes that may have occurred, but I think all I captured was the normal fluctuations of my network at this time of night :laughing:

I copied the notes I took between reboots below:

# Before

Fast.com Down: 60 Mbps

Fast.com Up: 5.2 Mbps

`cat /etc/modprobe.d/ath10k.conf`:

```
# Board override and quirks for Microsoft Surface devices with ATK10K WiFi chip
options ath10k_core skip_otp=y override_board=board-override.bin override_board2=none
```

`cat /sys/module/ath10k_core/parameters/skip_otp`:

```
Y
```

# After board.bin Swap and Restart

Fast.com Down: 57 Mbps

Fast.com Up: 4.5 Mbps

# After `/etc/modprobe.d/ath10k.conf` and Restart:

Fast.com Down: 52 Mbps

Fast.com Up: 5.0 Mbps

`cat /etc/modprobe.d/ath10k.conf`:

```
cat: /etc/modprobe.d/ath10k.conf: No such file or directory
```

`cat /sys/module/ath10k_core/parameters/skip_otp`:

```
N
```
---

Let me know if there is anything else I can help check out!

**Comment by jwrdegoede** [comment]
Thank you for testing on your  Surface Laptop 3 AMD. I have email the ath10k (firmware) maintainer asking him if it is ok if I take care of updating the upstream board-2.bin file with the extra board.bin files for the Surface Go + Surface Laptop 3. I'm waiting for a reply on this now.

**Comment by jwrdegoede** [comment]
@keplersj, Hi, I've prepared an updated board-2.bin which contains the correct board.bin for both the Surface Go and for your Surface Laptop 3 AMD. I've already tested this on the Surface Go, if you can test this on your Surface Laptop 3 AMD, then I can submit it upstream once I've your (positive) testing results.

To test this do `mv /lib/firmware/ath10k/QCA6174/hw3.0/board.bin ~` (move it to a place where the kernel cannot find it) and then replace `/lib/firmware/ath10k/QCA6174/hw3.0/board-2.bin` with https://fedorapeople.org/~jwrdegoede/board-2.bin .

After this the `failed to fetch board data for bus=pci,vendor=168c,device=003e,subsystem-vendor=045e,subsystem-device=0001` message should be gone from your dmesg and otherwise everything should work as before.

**Comment by keplersj** [comment]
I am very happy to confirm the new board-2.bin is working on my Surface Laptop 3!

**Comment by jwrdegoede** [comment]
Good news, the updated board-2.bin file has landed in the official linux-firmware repo:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=4d74f4dec175363fa24c95702dd86f477cef232c

So this issue can be closed now.

**Comment by qzed** [comment]
@jwrdegoede Thanks for your work!
