### ISSUE TITLE
SB2 Trackpad drivers on Debian 10

### ISSUE THREAD

**Issue by lx07** [linux-surface/linux-surface#410]
Hey, quick question and fast close, which package contains the trackpad drivers for the SB2 on Debian 10? Is it somewhere in firmware-linux-nonfree, or is it installed with your linux-surface pack?

Thanks and keep rocking

**Comment by qzed** [comment]
The SB2 uses a standard USB HID device for the touchpad. It should work out of the box on any kernel. Do you mean touchscreen?

**Comment by lx07** [comment]
Hey, no meant the Trackpad, weird it's not being detected in Debian 10 at iso-boot-start, during install (with Debian 10 firmware iso) while it is with Ubuntu. I did not proceeed the installation though, just decided to ask here first.

**Comment by qzed** [comment]
That's very odd indeed. What's the kernel version of the Debian ISO?

**Comment by lx07** [comment]
Indeed weird @qzed , but seems to only be within the installer.

**Solution**: Select Non-Graphical Install, finish Install, enjoy full Trackpad Support
Closing.
