### ISSUE TITLE
Surface Book 2 No Nvidia GPU detected

### ISSUE THREAD

**Issue by comrade-skeleton** [linux-surface/linux-surface#412]
I don't seem to have any Nvidia GPU detected on a 15" SB2, however I have the performance base. I've installed the linux-surface kernel, and attempted to find the device through lspci, but it's not showing at all, though the nvidia drivers do install successfully.

**Comment by qzed** [comment]
Can you post a dmesg log and lspci output?

**Comment by comrade-skeleton** [comment]
I think there may be a hardware issue now, as it doesn't show in Windows anymore, either. I even tried downgrading the firmware manually, via the tool here, and upgrading it again via Windows update, but it still doesn't appear, nor does it show when connecting/disconnecting. I've attached full logs though I'm not sure how much they'll help, I couldn't even see the GPU there.

[dmesg_log.txt](https://github.com/linux-surface/linux-surface/files/6102472/dmesg_log.txt)
[lspci_log.txt](https://github.com/linux-surface/linux-surface/files/6102473/lspci_log.txt)

**Comment by qzed** [comment]
I think this might be related:

```
[    0.421903] pci 0000:00:02.0: can't claim BAR 4 [io  0x3080-0x30bf]: address conflict with PCI Bus 0000:02 [io  0x3000-0x3fff]
```

and

```
[    0.447140] pci_bus 0000:02: resource 0 [io  0x3000-0x3fff]
[    0.447142] pci_bus 0000:02: resource 1 [mem 0xc1000000-0xc1ffffff]
[    0.447144] pci_bus 0000:02: resource 2 [mem 0x90000000-0xa1ffffff 64bit pref]
```

The first one specifically could indicate a problem with the PCIe device. Maybe try cleaning the contacts and a two-button reset?

**Comment by comrade-skeleton** [comment]
I've tried cleaning the contacts a few times, and doing the "disconnect, power down, UEFI, then reconnect" thing, with the base disconnected from power. It may have just failed on me. Weird that power works fine though, along with the keyboard and everything else.

**Comment by qzed** [comment]
Give the two-button reset a try (turn on, hold power and volume up, i.e. the volume button next to power, until you get into uefi), that should reset any firmware state. If this also happens in Windows this might be a hardware issue, or at the very least a firmware issue.

**Comment by comrade-skeleton** [comment]
It does also now happen in Windows, though it wasn't previously. Is there a particular firmware package I should try to install?linux-surface/linux-surface wrote:
Give the two-button reset a try (turn on, hold power and volume up, i.e. the volume button next to power, until you get into uefi), that should reset any firmware state. If this also happens in Windows this might be a hardware issue, or at the very least a firmware issue.

**Comment by qzed** [comment]
> Is there a particular firmware package I should try to install?

I can't think of any. This shouldn't really be a problem caused by any type of firmware that Linux can load. If it's a firmware problem then UEFI or ACPI.

**Comment by comrade-skeleton** [comment]
I mean via the Surface firmware packages provided by Microsoft.

**Comment by qzed** [comment]
Ah, well you could try re-flashing the UEFI firmware (see e.g. https://github.com/linux-surface/surface-uefi-firmware), but I'd do that as a last resort only.

**Comment by comrade-skeleton** [comment]
I'm at that point, so I may as well try it, even the factory firmware
doesn't show anything. Thanks for the help, this doesn't appear
surface-linux related, so if need be, we may as well close the issue.

**Comment by qzed** [comment]
Good luck!
