### ISSUE TITLE
[SL3] Latest update breaks Hibernate to disk

### ISSUE THREAD

**Issue by bguta** [linux-surface/linux-surface#420]
[Description of the bug or feature]

### Environment
- Hardware model: Surface Laptop 3 (AMD)
- Kernel version: 5.11.10-arch1-1-surface
- Distribution: Arch Linux

After updating to the latest update, hibernate to disk is not working anymore. It enters a hibernation state (systemctl hibernate) but immediately reboots without restoring the previous state. I downgraded my version back to 5.10.8 and this fixed the issue for me

**Comment by avanishsubbiah** [comment]
I'm having the exact same issue.

- Surface Laptop 3 (Intel)
- Kernel version: 5.11.16-arch1-1-surface #1
- Distro: Arch Linux

**Comment by bguta** [comment]
Fixed with new update
