### ISSUE TITLE
Failed to boot after updating packages

### ISSUE THREAD

**Issue by aflyingpumpkin** [linux-surface/linux-surface#421]
I was running pacman -Syu, and half way through my Surface 2 powered off completely.  After booting back up I was unable to boot with the Surface Linux Kernel.  How can I fix this?

When trying to boot with the Surface Linux Kernel I get the folloiwng bessage in grub:

```Loading Linux Linux-surface ...
error: file /boot/vmlinuz/linux-surface not found.
loading initial ram disk ...
error: you need to load the kernel first.

press any key to continue ...```

**Comment by SamLukeYes** [comment]
Boot into an Arch Linux live image, [mount your filesystems](https://wiki.archlinux.org/index.php/Installation_guide#Mount_the_file_systems) (do the same as how you installed), `arch-chroot` into your Arch installation, and `pacman -S linux-surface`.

**Comment by aflyingpumpkin** [comment]
This worked, thank you.
