### ISSUE TITLE
Gentoo Linux Overlay

### ISSUE THREAD

**Issue by Parinz** [linux-surface/linux-surface#426]
Hello! This is actually **NOT** an issue. However, I am currently creating some ebuilds for the Linux-surface kernel and the iptsd utility. I will also be maintaining this overlay once it is finished. I am asking here to see if anyone would be interested in this and if it may be added to the Linux-surface wiki when I am done. I would appreciate any kind of response! Thank you!

- [X] Creating a local overlay
- [X] Creating a usable surface-sources ebuild
- [X] Creating a usable iptsd ebuild
- [X] Hosting the [overlay](https://github.com/Parinz/linux-surface-overlay) 
- [ ] Maybe adding other utilities
- [ ] Provide a binary? surface-sources-bin?

Sincerely,
Parin

**Comment by StollD** [comment]
Feel free to add it to the wiki once you have something thats ready for others to use.

**Comment by supertomi** [comment]
Jepp, highly appreciated!!!

**Comment by Parinz** [comment]
Thank you for your responses!

**Comment by Parinz** [comment]
UPDATE: I've got those two ebuilds working on my machine, I would appreciate it if anyone that has a gentoo device could test it as well. Please contact me if you've got anything!

**Comment by supertomi** [comment]
Please, can you attach these ebuilds or make it available f0r download? 

Thanks!

**Comment by Parinz** [comment]
@supertomi You can install the overlay under the name of "linux-surface". Or if you wish to see the repo it is [here](https://github.com/Parinz/linux-surface-overlay). 

Sincerely,
Parin

**Comment by supertomi** [comment]
Did you include the gentoo patchset into the kernel sources?

**Comment by Parinz** [comment]
Yes, the kernel was the normal gentoo-sources with linux-surface patches on top of them.

**Comment by Parinz** [comment]
I'll add a full installation guide to the wiki as soon as most packages get's ported into ebuilds.

**Comment by StollD** [comment]
> I'll add a full installation guide to the wiki as soon as most packages get's ported into ebuilds.

Please add the guide to your repository, and only link to it from the linux-surface wiki. I think the setup guide on the wiki should only have the distributions that we "officially" support. Its already a bit too messy for my taste (coverying 3 / 4 distros).

**Comment by Parinz** [comment]
@StollD Sure!

**Comment by CanuteTheGreat** [comment]
I do not wish to steal anyone's thunder, but this overlay looks a bit outdated and possibly inactive. As a result I created another overlay (gentoo-linux-surface-overlay) on at https://github.com/CanuteTheGreat/gentoo-linux-surface-overlay that has Gentoo kernel patchset sources + surface patch set, iptsd, libwacom-surface, surface-control, and libcamera. Most things are in a working state, but not all and some need improvement still. I welcome assistance/contributors!

**Comment by Parinz** [comment]
@CanuteTheGreat Amazing work! The overlay has actually been updated yesterday. I put an automated system in place to update the kernel patches as well and a few other things. I also am finishing up my installation guide and making a YouTube video as well. Since our ebuilds are quite similar would you mind diverting the work over to this repo to streamline the effort (maybe pull requests or something)?

**Comment by Parinz** [comment]
Right, another update. I have created a complete guide on installing Gentoo. So I would consider this project is at a usable state. I will now submit a pull request to edit the wiki and add the Gentoo guide. The url for the project is: [right here](https://github.com/Parinz/linux-surface-overlay).

All contributions are very welcome!
