### ISSUE TITLE
Bluetooth "no adapters available" after upgrade to 5.11.18-surface

### ISSUE THREAD

**Issue by afalout** [linux-surface/linux-surface#434]
SP4, 5.11.18-surface, Ubuntu 20.10

After last kernel upgrade, KDE shows "no adapters available" for Bluetooth

[   22.933039] usb 1-5: Product: Bluetooth and Wireless LAN Composite Device
[   22.933042] usb 1-5: Manufacturer: Marvell
[   22.933043] usb 1-5: SerialNumber: 0000000000000000
[   22.971914] Bluetooth: Core ver 2.22
[   22.971941] NET: Registered protocol family 31
[   22.971942] Bluetooth: HCI device and connection manager initialized
[   22.971946] Bluetooth: HCI socket layer initialized
[   22.971948] Bluetooth: L2CAP socket layer initialized
[   22.971950] Bluetooth: SCO socket layer initialized
[   22.982221] usbcore: registered new interface driver btusb
[   22.985134] Bluetooth: hci0: unexpected event for opcode 0x0000
[   22.985142] Bluetooth: hci0: unexpected event for opcode 0x0000
...
[   24.585978] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   24.585983] Bluetooth: BNEP filters: protocol multicast
[   24.585987] Bluetooth: BNEP socket layer initialized

"bluetoothctl list" and "hciconfig" return nothing. So does "rfkill list"

Any clues?

Thanks,
Andrej

**Comment by afalout** [comment]
Please ignore - did not work after three reboots - but after full shutdown it started working again. 
Got the clue here: https://askubuntu.com/questions/1178512/ubuntu-18-04-lts-no-bluetooth-found-plug-in-a-dongle-to-use-bluetooth
Is this perhaps related to loading new firmware?

In any case, please close.

Cheer
Andrej

**Comment by qzed** [comment]
> Is this perhaps related to loading new firmware?

That is possible, I guess.
