### ISSUE TITLE
Very high cpu temps in 5.12

### ISSUE THREAD

**Issue by atropos112** [linux-surface/linux-surface#438]
Hi,

Ever since the new update 5.12 I have been having very weird temperature issues (initially i thought it was because i cant set performance but then Qzed kindly pointed out the existence of profiles so I don't think its that) . Previously in power-saving mode when I did nothing (with ~1% CPU utilization due to background apps) my temperature (without fans being on) was about 40 degrees, should I watch a video on YouTube this would go up to 50's, sometimes even 60's. Now however when in low power profile I hit 67 degrees on idle (sub 1% CPU), watching a YouTube video (fans are not turning on, I assume it is  because I am in low power mode?) I hit 100 degrees on some cores while the other cores are in high 80's or low 90's, as a matter of fact writing this post causes the CPU temp to go to 85 degrees.

- Hardware model: Surface Book 2 (15 inch)
- Kernel version: 5.12.2-arch1-3-surface
- Distribution: Arch Linux

**Comment by qzed** [comment]
I can't reproduce this on my SB2 (13"). Barely gets over 45°C when watching youtube. You might want to check if you've got anything else running in the background and make sure that you're using video acceleration.

**Comment by atropos112** [comment]
I believe I have just figured it out.

Using `cpupower` it showed that even though I was in low power mode, my CPU frequencies were very high (hitting the 4000 Hz frequently), the Power setting governeor policy claimed i was in "Performance" mode. This is strange though as I never set anything of this sort (as a matter of fact didnt know it was an option). Changing from Performance to power-mode made the temperature go back down to where I saw it previously.

**Comment by qzed** [comment]
Yeah, that would explain temperatures like that. Could be the power-profiles-daemon is messing with that.

**Comment by atropos112** [comment]
> Yeah, that would explain temperatures like that. Could be the power-profiles-daemon is messing with that.

God damnit, that makes sense. I recall yesterday when you mentioned power-profiles-daemon i installed it to give it a try, that must have done it. Thank you for your time !
