### ISSUE TITLE
Package linux-libc-dev-5.3.18-surface unavailable in Debian Repository

### ISSUE THREAD

**Issue by mmalmeida** [linux-surface/linux-surface#45]
Currently following the guide to get Ubuntu 18.04 working on my brand new SB2.

On item 4 (Download and install the required packages), it mentions 3 kernel packages to install, one of them being: linux-libc-dev-[VERSION].deb

I installed the debian repository as per [https://github.com/linux-surface/linux-surface/wiki/Package-Repositories](url). Trying to install 5.3.18 as I want touch support.

However, no package matches linux-libc-dev_5.3.18* . an apt-cache search 5.3.18 only yields:
- linux-headers-5.3.18-surface
- linux-image-5.3.18-surface

Could you help me understand:
1. why the -dev package is not there. Should it be?
2. Do I need to install it? I can manually download it and install via dpkg, but that defeats the purpose of installing everything via the repository.

Thanks for the help!

**Comment by archseer** [comment]
Hmm I can see `linux-libc-dev_5.3.18-surface-1_amd64.deb` on the repository https://tmsp.io/fs/repos/debian/linux-surface/pool/main/l/linux-surface/

**Comment by qzed** [comment]
This is a problem with versioning. The package names of the kernel are `linux-headers-<version>-surface` and `linux-image-<version>-surface`, whereas for the libc it's just `linux-libc-dev`. Thus it's possible to have two different kernel versions in the same repo, but not two different libc versions. This is a drawback of the linux `[bin]deb-pkg` make target (one reason why I'm pushing for using the actual debian build files for the automation).

I think it should be possible to install a specific version, e.g. by `apt-get install linux-libc-dev=5.3.18-surface-1`.

**Comment by mmalmeida** [comment]
Follow-up:
> I think it should be possible to install a specific version, e.g. by apt-get install linux-libc-dev=5.3.18-surface-1.

Indeed, but that version does not exist (apt-cache showpkg linux-libc-dev only shows 5.4.6-surface-1 from the above mentioned repository, and a 4.15.0-74.84 from the bionic-updates repo. 
Should the 5.3.18-surface-1 be there?


> Edit: Also I don't think you'll need that unless you want to develop/compile stuff interfacing with libc.
Will proceed with installing without the -dev package for now.

**Comment by qzed** [comment]
That's probably an error in how I added it to the repo then. I hope that we can fix that with the packaging stuff we're currently working on. Until then, if you need this package you'll unfortunately have to install it from github releases.
