### ISSUE TITLE
Patches don't work on Xanmod

### ISSUE THREAD

**Issue by cantenna** [linux-surface/linux-surface#48]
5.4 and 5.3 apply fine but touch screen doesn't work; coming from a a previous xanmod kernel ver supported by last made available Jakeday patches where touch screen functioned fine. 

I have added;
MODULES=(intel_ipts hid hid_sensor_hub i2c_hid hid_generic usbhid hid_multitouch)
to /etc/mkinitcpio.conf

After applying 5.3 patches to 5.3 Xanmod source, lsmod returns ;
ipts_surface           16384  0
intel_ipts             45056  1 ipts_surface
i915                 2265088  20 intel_ipts
mei                   122880  3 intel_ipts,mei_me
hid                   143360  7 i2c_hid,usbhid,hid_multitouch,hid_sensor_hub,intel_ipts,hid_generic,uhid

Have followed advise here;
https://github.com/dmhacker/arch-linux-surface/issues/22

UPDATE: Fixed; had to replace my Jakeday Intel IPTS firmware as well to MSHW0103

**Comment by archseer** [comment]
Please fill out [the issue template](https://raw.githubusercontent.com/linux-surface/linux-surface/master/.github/ISSUE_TEMPLATE.md). Choice of your OS usually doesn't matter as much as the hardware you're running, since it's all using the same hardware.

Currently 5.4 doesn't support IPTS because Intel removed a bunch of stuff we need from their i915 driver. 5.3 should work however.

**Comment by cantenna** [comment]
> Please fill out [the issue template](https://raw.githubusercontent.com/linux-surface/linux-surface/master/.github/ISSUE_TEMPLATE.md). Choice of your OS usually doesn't matter as much as the hardware you're running, since it's all using the same hardware.
> 
> Currently 5.4 doesn't support IPTS because Intel removed a bunch of stuff we need from their i915 driver. 5.3 should work however.

Thank you, here is more info;
[    2.114921] ipts: initializing ipts
[    2.115008] ipts: Intel iTouch framework initialized
[    2.191732] IPTS ipts_mei_cl_init() is called
[    3.394998] IPTS using DMA_BIT_MASK(64)
[    3.394998] IPTS using DMA_BIT_MASK(64)
[    3.406739] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/intel_desc.bin failed with error -2
[    3.407253] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/vendor_desc.bin failed with error -2
[    3.411168] input: ipts 1B96:0021 as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:0021.0002/input/input15
[    3.411260] input: ipts 1B96:0021 as /devices/pci0000:00/0000:00:16.4/mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F/0044:1B96:0021.0002/input/input16
[    3.411360] hid-multitouch 0044:1B96:0021.0002: input,hidraw1: <UNKNOWN> HID v16b00.03 Mouse [ipts 1B96:0021] on heci3
[    3.413517] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/vendor_kernel.bin failed with error -2
[    3.415628] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.415841] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.415875] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.415908] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.415938] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.415975] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416008] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416039] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416073] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416104] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416135] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416178] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416215] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416249] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416286] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.416327] ipts mei::3e8d0870-271a-4208-8eb5-9acb9402ae04:0F: Direct firmware load for intel/ipts/MSHW0103/config.bin failed with error -2
[    3.447410] intel-lpss 0000:00:15.1: enabling device (0000 -> 0002)
[    3.447729] idma64 idma64.1: Found Intel integrated DMA 64-bit
[    3.454639] intel-lpss 0000:00:15.2: enabling device (0000 -> 0002)
[    3.454874] idma64 idma64.2: Found Intel integrated DMA 64-bit

**Comment by cantenna** [comment]
I'm using the same firmware that worked with Jakeday patches, perhaps I should try updating the firmware as well?

**Comment by kitakar5525** [comment]
By the way, your hardware is SP4 but uses unknown hardware ID (`MSHW0103`)
https://github.com/linux-surface/linux-surface/blob/3ca250a015f1096efc4e99d51ea382439bb30134/patches/5.3/0008-ipts.patch#L1716-L1720

I wonder if there are two different SP4 in the world?

**Comment by kitakar5525** [comment]
Looks so, there are two different IDs on SP4: `MSHW0078` and `MSHW0103`)
https://github.com/linux-surface/acpidumps/blob/9e5706ab2409139b16eda97b49f03af0c3a1da00/surface_pro_4/dsdt.dsl#L16669-L16683

Anyway, There should be no impact on functionality if you install firmware from https://github.com/linux-surface/linux-surface/tree/master/firmware/intel/ipts or just run setup.sh

**Comment by qzed** [comment]
This seems to be fixed. Please feel free to re-open if I'm mistaken.
