### ISSUE TITLE
PGP error for the linux surface key - no update possible

### ISSUE THREAD

**Issue by satansbraten330** [linux-surface/linux-surface#483]
I am having this issue since a couple of days.
Running Manjaro on my SP6 with linux-surface and it worked buttersmooth for like the past 6 months.
But now I get an errormessage when trying to sudo pacman -Syu:

```
>>> sudo pacman -Syu                                                                                                       [1]
[sudo] Passwort für loki-sp6: 
Fehler: linux-surface: Schlüssel "87DEFA4AB94A99A4C8C3112556C464BAAC421453" ist unbekannt
:: PGP Schlüssel 87DEFA4AB94A99A4C8C3112556C464BAAC421453 importieren? [J/n] J
Fehler: Schlüssel "87DEFA4AB94A99A4C8C3112556C464BAAC421453" konnte nicht entfernt abgerufen werden
:: Synchronisiere Paketdatenbanken...
 core ist aktuell
 extra ist aktuell
 community ist aktuell
 multilib ist aktuell
 linux-surface                                      6,6 KiB  0,00   B/s 00:00 [############################################] 100%
 linux-surface.sig                                566,0   B  0,00   B/s 00:00 [############################################] 100%
Fehler: linux-surface: Schlüssel "87DEFA4AB94A99A4C8C3112556C464BAAC421453" ist unbekannt
:: PGP Schlüssel 87DEFA4AB94A99A4C8C3112556C464BAAC421453 importieren? [J/n] j
Fehler: Schlüssel "87DEFA4AB94A99A4C8C3112556C464BAAC421453" konnte nicht entfernt abgerufen werden
Fehler: Konnte linux-surface nicht aktualisieren (Ungültige oder beschädigte Datenbank (PGP-Signatur))
Fehler: Fehler beim synchronisieren aller Datenbanken
```
also `sudo pacman-key --refresh-keys` does not work

Anyone with the same issue?
Any int how to fix this?
`~ >>> uname -a                                                                                                             [130]
Linux manjaro 5.12.9-arch1-1-surface #1 SMP PREEMPT Thu, 03 Jun 2021 18:17:21 +0000 x86_64 GNU/Linux
~ >>>`

**Comment by qzed** [comment]
Could be an issue with the key server used in manjaro. See https://github.com/linux-surface/linux-surface/issues/468. You could try changing the server (see e.g. https://wiki.archlinux.org/title/Pacman/Package_signing#Change_keyserver) or add the key manually as described in the wiki (https://github.com/linux-surface/linux-surface/wiki/Package-Repositories#arch-linux-repository).

**Comment by satansbraten330** [comment]
@qzed  - thanks a lot for the quick turnaround.
manually adding and signing the key again fixed my issue, update was successful yesterday

**Comment by qzed** [comment]
I'm closing this then. As far as I can tell, using `hkps://keyserver.ubuntu.com` as keyserver should work.
