### ISSUE TITLE
mwifiex bug - surface book 2

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#49]
[Description of the bug or feature]

Wifi was working well when it suddenly stopped with the below dmesg. Bluetooth is disabled in bios.
I upgraded the mwifiex firmware to the latest.

### Environment

- Hardware model: Surface Book 2
- Kernel version: 5.3.18-custom+
- Distribution: Debian buster

<details><summary>`dmesg` output</summary>

```
Jan 17 22:20:59 paquerette kernel: [ 1965.449489] mwifiex_pcie 0000:01:00.0: Firmware wakeup failed
Jan 17 22:20:59 paquerette kernel: [ 1965.449540] mwifiex_pcie 0000:01:00.0: PREP_CMD: FW in reset state
Jan 17 22:20:59 paquerette kernel: [ 1965.449618] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449623] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449627] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449631] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449635] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449639] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449643] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449647] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449650] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449660] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449664] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.449667] mwifiex_pcie 0000:01:00.0: deleting the crypto keys
Jan 17 22:20:59 paquerette kernel: [ 1965.449718] mwifiex_pcie 0000:01:00.0: info: shutdown mwifiex...
Jan 17 22:20:59 paquerette kernel: [ 1965.450592] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette kernel: [ 1965.450598] mwifiex_pcie 0000:01:00.0: PREP_CMD: card is removed
Jan 17 22:20:59 paquerette avahi-daemon[791]: Interface wlp1s0.IPv6 no longer relevant for mDNS.
Jan 17 22:20:59 paquerette avahi-daemon[791]: Leaving mDNS multicast group on interface wlp1s0.IPv6 with address fe80::c69d:edff:fe23:e310.
Jan 17 22:20:59 paquerette dhclient[2633]: receive_packet failed on wlp1s0: Network is down
```

</details>

**Comment by deb75** [comment]
Might be related to the fact that powsersave was on

**Comment by archseer** [comment]
Yeah from what I understand you need to turn off powersave via an udev rule or in the NetworkManager config that's in the repo:

https://github.com/linux-surface/linux-surface/wiki/Known-Issues#mwifiex-you-may-need-to-disable-wifi-power_save-manually-if-you-dont-use-networkmanager

https://github.com/linux-surface/linux-surface/blob/master/root/etc/NetworkManager/conf.d/99-surface.conf

**Comment by archseer** [comment]
More info also here: https://github.com/linux-surface/kernel/issues/20

**Comment by qzed** [comment]
What @archseer said is correct. If this happens with powersave off, feel free to re-open this issue or drop a comment on https://github.com/linux-surface/kernel/issues/20.

**Comment by deb75** [comment]
I wrote a udev rule which set powersave `off`. I checked that powersave is indeed `off` right after connecting to my home wifi. However, the funny thing is that I sometimes found powersave to be `on` after a while. I wonder whether an application changes this setting in the background.

**Comment by qzed** [comment]
If you're using NetworkManager (or something like it), that could be the culprit.

**Comment by deb75** [comment]
I do not use `NetworkManager`, the culprit is very likely to be `pm-utils`.

The script `/usr/lib/pm-utils/power.d/wireless` indeed set powersave `on`

Creating an empty script `/etc/pm-utils/power.d/wireless` seems to fix the issue.

Regards
