### ISSUE TITLE
Potential macos port

### ISSUE THREAD

**Issue by JChamberlain28** [linux-surface/linux-surface#493]
May be a silly question, but the surface aggregator module does not work in macos, and this project supports the SAM on linux. How challenging would a macos port of at least the keyboard drivers be, and its it something that would be considered by contributors?

**Comment by qzed** [comment]
It shouldn't be too difficult to get something basic working for someone experienced in developing drivers for MacOS. Documentation of the protocol is available [here](https://www.kernel.org/doc/html/latest/driver-api/surface_aggregator/ssh.html). Individual request definitions can be found in the code (some basic info can also be found [here](https://github.com/linux-surface/surface-aggregator-module/blob/master/doc/requests.txt)).

If anyone wants to have a go at that, feel free to do so. I personally (and I think the same probably holds for other core contributers) don't have any interest in MacOS and also don't have the time (there are a ton of other issues still to address, e.g. touch, and time for this project is sparse on my end at the moment).
