### ISSUE TITLE
Can't boot using secure boot after update

### ISSUE THREAD

**Issue by headkaze** [linux-surface/linux-surface#512]
I just performed an update and rebooted and now I get:

```
Failed to open \EFI\UBUNTU\grubx64.efi - Not found 
Failed to load image \EFI\UBUNTU\grubx64.efi: Not found 
start_image() returned Not found
```
I tried running boot-repair from a live CD but it didn't work. Here's the output https://paste.ubuntu.com/p/hvG64yvJ3z/

I can only boot now by turning off secure boot.

- Hardware model: Surface Pro 4
- Kernel version: Linux Nova 5.13.4-surface #1 SMP Wed Jul 21 02:26:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 21.04

**Comment by headkaze** [comment]
I managed to get it to boot in secure boot mode but now it boots directly into the GRUB command line and I can boot into it by running:
```
grub> ls
(proc) (hd0) (hd0,gpt2) (hd0,gpt1)
grub> set prefix=(hd0,gpt1)/efi/ubuntu (fails)
grub> set prefix=(hd0,gpt1)/efi/grub (succeeds)
grub> set prefix=(hd0,gpt1)/efi/boot (succeeds)
grub> set root=(hd0,gpt1)
grub> insmod linux
grub> insmod normal
grub> normal
```
After successfully booting in I try running 'sudo update-grub' but it still boots into GRUB command line.

I also have a bunch of different grub versions now (not doubt from trying to repair it incorrectly). I'm not sure which is the one I should keep and which one I should remove? Can someone please show me a list of directories from their /boot and /boot/EFI?
```
$ ls /boot/efi/EFI/BOOT
bkpbootx64.efi  bootx64.efi  fbx64.efi  grub.cfg  grubx64.efi  mmx64.efi
$ ls /boot/efi/EFI/grub
grub.cfg  grubx64.efi
$ ls /boot/efi/EFI/ubuntu
BOOTX64.CSV  grub.cfg  grubx64.efi  mmx64.efi  shimx64.efi
$ ls /boot/grub
fonts  grub.cfg  grubenv  x86_64-efi
```

**Comment by headkaze** [comment]
Hey guys running the following command appears to have fixed it for me
`sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=ubuntu --recheck --debug /dev/nvme0n1 --no-nvram --removable`

**Comment by qzed** [comment]
Any chance you have multiple bootloaders/GRUBs installed? You might also want to check the EFI entries and see if there are any outdated ones that could cause this behavior (e.g. with `efibootmgr`).

**Comment by headkaze** [comment]
Here's the output of `efibootmgr`:
```
BootCurrent: 0005
Timeout: 0 seconds
BootOrder: 0005,0001,0004,0000,0002
Boot0000* Internal Storage
Boot0001* USB Storage
Boot0002* PXE Network
Boot0003* SurfaceFrontPage
Boot0004* Windows Boot Manager
Boot0005* ubuntu
```

I believe the key to fixing the problem for me was the -`-bootloader-id=ubuntu` command line option for `grub-install`. This was probably caused by accidentally re-installing GRUB to the wrong location. I ended up finding a version of GRUB located at /boot/efi/EFI/grub that was fine to delete.

The only folders required are:
- /boot/efi/EFI/BOOT
- /boot/efi/EFI/ubuntu
- /boot/grub

**Comment by qzed** [comment]
Yeah, that looks correct. I think the `ubuntu` entry may have pointed to an invalid location before, and running that command fixed that.
