### ISSUE TITLE
[SP6] Touchscreen does not work. iptsd: No such device

### ISSUE THREAD

**Issue by alien2003** [linux-surface/linux-surface#517]
### Environment
- Hardware model: Surface Pro 6
- Kernel version: Linux surface 5.13.4-arch1-1-surface #1 SMP PREEMPT Wed, 21 Jul 2021 00:34:25 +0000 x86_64 GNU/Linux
- Distribution: [Garuda Linux](https://garudalinux.org/) (Arch)

Touchscreen doesn't work at all, `/dev/ipts/*` is missing. I noticed that `ipts` module was not loaded at all.

I tried to manually run iptsd:
```
ERROR: ../src/control.c:139: Failed to open /dev/ipts/0: No such file or directory
ERROR: ../src/main.c:106: Failed to start IPTS: No such file or directory
```
I tried to load module using `modprobe` and `MODULES()` section in `mkinitcpio.conf`. After that devices in `/dev/ipts/` appeared:
```
╭─alien@surface in ~ took 16ms
╰─λ ls /dev/ipts
crw-------  252,0 root 28 июл 23:58  0
crw-------  252,1 root 28 июл 23:58  1
crw-------  252,2 root 28 июл 23:58  2
crw-------  252,3 root 28 июл 23:58  3
crw-------  252,4 root 28 июл 23:58  4
crw-------  252,5 root 28 июл 23:58  5
crw-------  252,6 root 28 июл 23:58  6
crw-------  252,7 root 28 июл 23:58  7
crw-------  252,8 root 28 июл 23:58  8
crw-------  252,9 root 28 июл 23:58  9
crw------- 252,10 root 28 июл 23:58  10
crw------- 252,11 root 28 июл 23:58  11
crw------- 252,12 root 28 июл 23:58  12
crw------- 252,13 root 28 июл 23:58  13
crw------- 252,14 root 28 июл 23:58  14
crw------- 252,15 root 28 июл 23:58  15
```
iptsd now tells:
```
ERROR: ../src/control.c:51: Failed to send feedback: No such device
ERROR: ../src/control.c:74: Failed to flush buffers: No such device
ERROR: ../src/main.c:106: Failed to start IPTS: No such device
```

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/6896449/dmesg.txt)

Kernel options:
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet cryptdevice=UUID=68f80254-8b6c-46be-b121-92c1162e6e49:luks-68f80254-8b6c-46be-b121-92c1162e6e49 root=/dev/mapper/luk
s-68f80254-8b6c-46be-b121-92c1162e6e49 splash rd.udev.log_priority=3 vt.global_cursor_default=0 systemd.unified_cgroup_hierarchy=1 resume=/dev/mapper/
luks-5dc2e774-23e5-44e1-b597-ccc03ce284e2 loglevel=3 mitigations=off"
GRUB_CMDLINE_LINUX=""
```

some `mkinitcpio` lines:
```
MODULES=(ipts)
HOOKS="base udev autodetect modconf block keyboard keymap consolefont plymouth encrypt openswap resume filesystems"
```

**Comment by StollD** [comment]
Do you have a file `/etc/modprobe.d/noime.conf` that contains `blacklist mei`? If yes, delete that file and reboot. And then complain to your distro to stop blacklisting random drivers. :P

**Comment by alien2003** [comment]
> Do you have a file `/etc/modprobe.d/noime.conf` that contains `blacklist mei`? If yes, delete that file and reboot. And then complain to your distro to stop blacklisting random drivers. :P

Yes! I commented out all lines in that file and now touchscreen works perfectly! Thank you very much
