### ISSUE TITLE
Error when building nvidia kernel

### ISSUE THREAD

**Issue by deb75** [linux-surface/linux-surface#52]
I try to install the nvidia drivers on my surface book 2.

All what I did is :
```
surface dgpu set on
aptitude install nvidia-kernel-dkms
```
as root.

I googled the error, it seems known. Did anyone experience the same error ?

[Description of the bug or feature]

### Environment

- Hardware model: Surface Book 2
- Kernel version: 5.3.18-surface
- Distribution: Debian buster

<details><summary>`/var/lib/dkms/nvidia-current/418.74/build/make.log` output</summary>

```

/var/lib/dkms/nvidia-current/418.74/build/common/inc/nv-linux.h:733:21: error: void value not ignored as it ought to be
         int __ret = on_each_cpu(func, info, 1);        \
                     ^~~~~~~~~~~
```

</details>

**Comment by qzed** [comment]
The 418.74 driver is likely too old for the 5.3 kernel. You can check if there is a newer kernel (there seems to be 430.64 in [backports](https://packages.debian.org/buster-backports/nvidia-kernel-dkms)) or if that doesn't work you may need to switch to the LTS (4.19) kernel.

**Comment by deb75** [comment]
Hi,


Thanks for your reply.

What do you think is best to do ? Stick to the 5.3.18 kernel and try the backport ? or revert to the 4.19 ?

Can you confirm me that in both cases, the dGPU bug is gone (low performances) and that it does not change anything for the surface devices (battery, ...)

Regards

**Comment by qzed** [comment]
At the moment I'd try the backport first. We're currently back-porting IPTS changes to 4.19, but apart from that 5.3 and 4.19 shouldn't be much different (meaning with the next release, those should essentially be the same apart from the changes in upstream). Battery status etc. should work with both.

The dGPU "low-performance without AC power" problem is still present, regardless of what kernel you choose.

**Comment by deb75** [comment]
The backport compiled successfully with 5.3.18.

I have not tried yet however the nvidia card.
