### ISSUE TITLE
Remove Linux-surface kenrel and packages

### ISSUE THREAD

**Issue by chaaridev** [linux-surface/linux-surface#523]
Hi,
I had the Linux-surface kernel and package installed on my surface pro , Now I'm using a lenovo laptop and I tried to move my packages to my new Ubuntu installation and I mistakenly restored linux-surface packages to my lenovo laptop and now I get this error every time tried to use apt command  

```
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up linux-surface-secureboot-mok (20210319-1) ...

The secure-boot certificate has been installed to

    /usr/share/linux-surface-secureboot/surface.cer

It will now be automatically enrolled for you and guarded with the password

    surface

EFI variables are not supported on this system
dpkg: error processing package linux-surface-secureboot-mok (--configure):
 installed linux-surface-secureboot-mok package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-surface-secureboot-mok
E: Sub-process /usr/bin/dpkg returned an error code (1)

```

and I can't remove Remove Linux-surface kenrel and packages on my lenovo laptop using
`sudo apt-get remove surface-ipts-firmware`
I get the same error that's mentioned above

**Comment by qzed** [comment]
I think you can modify the `prerm` script of the package and simply add an `exit 0` below the `#!/bin/bash` and `set -e` lines. Should be located at `/var/lib/dpkg/info/linux-surface-secureboot-mok.prerm`, I think. After that you should be able to uninstall it.

**Comment by chaaridev** [comment]
it worked !
thank you @qzed
