### ISSUE TITLE
Cannot boot after MOK

### ISSUE THREAD

**Issue by IntelligentDisaster** [linux-surface/linux-surface#527]
SL4 - I Ubuntu 21.04 + Win11 dual boot frozen on GRUB menu, auto boot timer also frozen

**Comment by Anon0ne** [comment]
Shit.. I always check issues before updating but this time I didn't.  Same issue for me.. updated everything and installed MOK. Now the PC freeze at loading initial ramdisk every time I boot, no matter the kernel.

**Comment by IntelligentDisaster** [comment]
Disabled secure boot, make sure to pick the right kernel in GRUB. Works with a bit of screen tearing

**Comment by Anon0ne** [comment]
> @Anon0ne Disabled secure boot, make sure to pick the right kernel in GRUB. Works with a bit of screen tearing

No that did not fix it. Freezing at loading initial ramdisk every time.
