### ISSUE TITLE
Touchscreen randomly activates on SB2

### ISSUE THREAD

**Issue by MaxTretikov** [linux-surface/linux-surface#528]
It seems that my touchscreen is experiencing phantom inputs in a very specific location at random intervals, near the top left of the screen (in fact, it keeps pushing me to the Discussions page of this repo.) This did not happen when I had Windows installed, nor did it happen when I had the regular linux kernel installed, and even more interestingly, it didn't happen immediately after I installed the linux-surface kernel either. 

The only thing I can think of coinciding with this bug is making the camera work through libcamera, but I don't see how that's relevant. This bug happens whether or not the stylus is attached to the side of the screen.

I know it's a touchscreen input as whenever the phantom input hits an input, it pulls up the on-screen keyboard, which only happens with touchscreen inputs.

### Environment

- Hardware model: SB2 w/ GTX 1050
- Kernel version: Linux REBORN 5.13.4-surface #1 SMP Wed Jul 21 02:26:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 20.04

``xinput_calibrator`` did not fix it, this is a very annoying bug and I'm out of ideas.

**Comment by JustinCardona** [comment]
I have had the same problem on the surface pro 2017. I was running Arch 5.11-5.12. This problem occurred on both on Gnome and i3 so I am also inclined to believe that this is a linux-surface kernel issue.

**Comment by MaxTretikov** [comment]
The issue seems to be resolved (on my machine) by using proprietary Nvidia drivers instead of Noveau drivers.

**Comment by JustinCardona** [comment]
Thanks, I’ll try it out :)

**Comment by MaxTretikov** [comment]
Ok, my apologies for this very wrong answer. It took me about a month of passive observation to figure it out. If your machine is having this problem, it's *likely* a hardware issue and will be fixed by a reboot.

Now, on my machine (SB2), thanks to Microsoft brilliance, there's a battery behind my screen since it needs to detach from the main unit. Thanks to about 2-3 years of consistent use, the battery has expanded significantly, providing me with a lovely orange-blue discoloration on the top-right edge of my screen. What I didn't realize is that the battery expanding is pushing on the screen - the most probable cause of the phantom touches. You might be saying: wait! The touchscreen is capacitive, it doesn't use membranes! I don't know if this is true, but if it is, my best guess is that the battery is close enough to discharge the capacitors and trigger a touch.

Big disclaimer on the next section: I'm no physicist and I haven't researched touchscreens at all, so take this next part with a large grain of salt.

So, why should a reboot fix this? Well, during the touchscreen initialization step, it should re-calibrate, which should automatically identify any capacitors that aren't charging or any other problems like that and adjust accordingly. You might notice that even if you reboot, the problem comes back after a couple days in the same general area. My guess is that the battery is expanding ever so slightly further and discharging different capacitors that are quite close. Another reboot will fix this.

My initial answer was a shot in the dark, but it *did* fix the issue on first glance, since changing the driver requires a reboot. ¯\\\_(ツ)_/¯.

And of course, the ``xinput`` calibrator just messes with your transformation matrix, it isn't doing anything near complex enough to fix this issue, so afaik a reboot is basically necessary.

Sorry for the novel. I wanted to fully document the issue in case anyone else stumbles upon it. Oh, and distribute the following tone indicators after any sentence in which I inadvertently praise Microsoft: /s /s /s /s /s

**Comment by JustinCardona** [comment]
The issue certainly has several symptoms of battery expansion: consistency of the phantom touch location as well as increased frequency of phantom touches as the usage time increases (to the point where there is about 1 touch per second in the case of the SP2017). However, this issue does not appear when using windows 10/11. I wonder if this is consistent with the battery theory. If so, I suspect that it might be able to be resolved by using a different palm rejection technique for the touch screen?

**Comment by Boffice** [comment]
This was creepy, cursor started moving and tabs got switched, At first i thought that i was hacked, then i disabled network and cursor kept moving, i thought it was my Bluetooth mouth and after disabling it issue was still in place. 

I can't identify any hardware issues.

SB2
Kernel 5.15.6-surface
Ubuntu 20.04 / Zorin 16

**Comment by JustinCardona** [comment]
I would like to add that battery inflation seems unlikely to be the cause of these touches since the phantom touches tend to happen on the top left of the screen but the battery is not there (https://www.ifixit.com/Teardown/Microsoft+Surface+Book+2+Teardown/100364). Although I suppose it’s possible that it pushes other components that then push on the screen. But it would be quite the coincidence that this happens on both a surface book 2 and a surface pro 2017.

I find that as MaxTretikov said, rebooting temporarily fixes it but the problem comes back a few hours later(sometimes less for me). Whether or not the battery is an issue, the fact that this problem is not encountered on windows suggests that this can be solved with software. Also, I don’t think is a screen hardware issue either because it happens on different models of surface.
