### ISSUE TITLE
surface-ath10k-firmware-override should depend on firmware-atheros

### ISSUE THREAD

**Issue by iandonnelly** [linux-surface/linux-surface#550]
surface-ath10k-firmware-override does not fix Wi-Fi on the Surface Go if the firmware-atheros package isn't already installed

### Environment

- Hardware model: Surface Go
- Kernel version: 5.13.12-surface
- Distribution: Debian 11 - Bullseye

journalctl output

```
~> sudo journalctl | grep ath10k
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/pre-cal-pci-0000:01:00.0.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/cal-pci-0000:01:00.0.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/QCA6174/hw3.0/firmware-6.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/QCA6174/hw3.0/firmware-5.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/QCA6174/hw3.0/firmware-4.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/QCA6174/hw3.0/firmware-3.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: firmware: failed to load ath10k/QCA6174/hw3.0/firmware-2.bin (-2)
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: Failed to find firmware-N.bin (N between 2 and 6) from ath10k/QCA6174/hw3.0: -2
Sep 01 08:24:02 kernel: ath10k_pci 0000:01:00.0: could not fetch firmware files (-2)
Sep 01 08:24:02 ikernel: ath10k_pci 0000:01:00.0: could not probe fw (-2)

```
After installing firmware-atheros and reinstalling surface-ath10k-firmware-override wifi works as expected.

**Comment by qzed** [comment]
Unfortunately it seems that Ubuntu doesn't provide that package, so I assume adding it as normal dependency will break the package for Ubuntu. I'm not sure if there's a way to specify it as optional dependency maybe?

**Comment by qzed** [comment]
@StollD any idea?

**Comment by StollD** [comment]
We could add it as an optional dependency / recommended package. Depending on how debian has setup their apt (if it installs them by default), it might work, but it isnt really a nice solution.

We could maybe add a note to the wiki that you need to install the non-free firmware on Debian (or install from the non-free iso).

**Comment by qzed** [comment]
Right, I think adding a note to the wiki is probably better. I've done that now.
