### ISSUE TITLE
[SP7] OSK not popping up automatically on Pop!_OS (21.04) Wayland

### ISSUE THREAD

**Issue by Panja0** [linux-surface/linux-surface#551]
Just installed Pop!_OS 21.04 on my Surface Pro 7.
When using X11 and touching a text input field the On Screen Keyboard (OSK) automatically pops up and you can begin to type.
This works the same in Ubuntu (20.04.3 and 21.04) on X11 and Wayland. But when using Wayland (for better touch support on our Surface) on the latest Pop!_OS it does not pop up the OSK. You need to swipe up from the bottom of the screen to enable the OSK. Is there a way to revert it to the "default" behaviour of automatically popping up?

- Hardware model: Surface Pro 7 - Intel
- Kernel version: 5.13.12-1
- Distribution: Pop!_OS 21.04

**Comment by yatli** [comment]
This is not really much can be done from this repo, I guess.
I've got the stock gnome on screen keyboard only working with gdm and gnome-shell, but not popping up at all for other windows (Ubuntu 20.04) -- my workaround is to install `onboard`, which also provides a more customizable keyboard, automatic window movement/resizing etc.

**Comment by StollD** [comment]
As far as I know GNOME disables the OSK if it detects a keyboard. Do you have a keyboard attached? If yes, can you try with it detached?

**Comment by Panja0** [comment]
@yatli 
I will give onboard a try.

@StollD 
I've got a typecover, but got it detached when trying. I was aware about the typecover and OSK.

**Comment by StollD** [comment]
What apps were you trying with? Firefox for example has made problems with the OSK for me in the past. If you didnt try with a GNOME / GTK app, could you do that?

**Comment by Panja0** [comment]
I've tried with Firefox and Terminal. A few others but don't recall which one.
On Ubuntu 21.04 Firefox OSK works with popping up.

**Comment by Panja0** [comment]
Just did a fresh re-install of Pop!_OS 21.04, removed all partitions before starting so I know for 100% sure I'm starting from scratch.

Same problem. When using Wayland the OSK does not pop up automatically when touching a text input field, tried Firefox, Terminal, Textedit.
Using ONBOARD gives me others problems. When using onboard on Wayland the ONBOARD keyboard "flickers".
It pops up, goes away, pops up, goes away etc etc.

**Comment by yatli** [comment]
> Using ONBOARD gives me others problems. When using onboard on Wayland the ONBOARD keyboard "flickers".
> It pops up, goes away, pops up, goes away etc etc.

Sounds classical and I encounter this today too. Could be worked around by turning off the automatic positioning -- I'll see if I can do something when I have time.

That said, I still prefer onboard than the stock OSK -- GNOME does not like to give user control and knobs these days.

**Comment by Panja0** [comment]
I just settled with "Improved OSK":
https://extensions.gnome.org/extension/4413/improved-osk/

I can enable my OSK with the menu bar icon, which imo is more convenient than swiping up.
I'll close this issue now. Thanks all for the help!
