### ISSUE TITLE
Does it run for ubuntu 18.10?

### ISSUE THREAD

**Issue by edyedy46** [linux-surface/linux-surface#57]
Hi team,
Does it work for the latest version of ubuntu?
I just tried installing it and it doesn't work.
Regards.

**Comment by qzed** [comment]
I don't see any reason why it shouldn't. What device do you have? What kernel version did you install? What's the output of `uname -a`? What specifically doesn't work (touch, battery, ...)?

**Comment by archseer** [comment]
Please fill out [the issue template](https://raw.githubusercontent.com/linux-surface/linux-surface/master/.github/ISSUE_TEMPLATE.md). It's there so we can help you diagnose the problem :)

**Comment by archseer** [comment]
Closing the issue as it doesn't provide any details. If you fill out the template, let me know and I'll reopen it.
