### ISSUE TITLE
Upgrading to 5.4.13 required `--force-overwrite`

### ISSUE THREAD

**Issue by pbnelson** [linux-surface/linux-surface#58]
Updating from 5.4.6 to 5.4.13 I got this error:

```
sudo dpkg -i linux-headers-surface_5.4.13-surface-1_amd64.deb linux-image-surface_5.4.13-surface-1_amd64.deb linux-libc-dev-surface_5.4.13-surface-1_amd64.deb
...results in...

dpkg: error processing archive linux-libc-dev-surface_5.4.13-surface-1_amd64.deb (--install):
 trying to overwrite '/usr/include/asm-generic/auxvec.h', which is also in package linux-libc-dev:amd64 5.4.6-surface-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```
The solution was to use the --force-overwrite option in dpkg -i, like this:

```
sudo dpkg --force-overwrite -i linux-headers-surface_5.4.13-surface-1_amd64.deb linux-image-surface_5.4.13-surface-1_amd64.deb linux-libc-dev-surface_5.4.13-surface-1_amd64.deb
```

**Comment by qzed** [comment]
Please note that the last couple of releases here are marked as test and come from us trying to set up an automated build system. That being said, they should work just fine, apart from some details we've yet to fix, like this one.

Regarding this issue: The `linux-libc-dev-surface` is not intended to be installed alongside `linux-libc-dev`, rather replace it. I'll try to fix this in the package metadata. Until it is fixed I recommend uninstalling `linux-libc-dev` before installing `linux-libc-dev-surface`.

**Comment by pbnelson** [comment]
Fair enough. I want to stress that I am only reporting this for the benefit of y'all maintainers and other users. My `--force-overwrite` workaround seems to have worked just fine for me. Thanks for all your hard work.

Having said that, I did just now issue a trial `sudo apt remove linux-libc-dev` and the resulting list of packages to be removed was long and shocking, including among many other things, `gfortran-9`, `libpython3-dev`, `r-base-dev` and `rstudio`. 

Ergo, I won't be proceeding with removing linux-libc-dev unless you tell me it is essential for system stability???

**Comment by qzed** [comment]
It isn't essential for system stability. You should actually be fine with either package in almost all cases. The `linux-libc-dev` package provides header-files for the Linux uapi, so if you don't have a `linux-libc-dev` installed with newer version than the kernel you should be fine. In case you've not, you should also be fine as long as nothing is using newly added features and even then system stability should not be affected, just the program in question using them. All in all I'd say there's a _very_ slim chance of anything breaking, so for now go with `linux-libc-dev` if the other option breaks dependencies.

I think this should be fixed by providing appropriate `Provides`, `Conflicts` and `Replaces` fields in the package metadata, I'll look into that.

**Comment by qzed** [comment]
Build is currently running, I will notify you here when it finishes so that you can try if this is fixed.

**Comment by qzed** [comment]
Alright, if you want to try, a new set of packages is available at https://github.com/linux-surface/linux-surface/suites/417017369/artifacts/1305877.

**Comment by pbnelson** [comment]
Looks good! The key lines being: 
```
dpkg: considering removing linux-libc-dev:amd64 in favour of linux-libc-dev-surface:amd64 ...
dpkg: yes, will remove linux-libc-dev:amd64 in favour of linux-libc-dev-surface:amd64
```

Full log:
```
15:28 mssb2 ~/Downloads/debian-latest$ sudo dpkg -i linux-headers-surface_5.4.13-surface-1_amd64.deb linux-image-surface_5.4.13-surface-1_amd64.deb linux-libc-dev-surface_5.4.13-surface-1_amd64.deb
[sudo] password for pbnelson: 
(Reading database ... 380483 files and directories currently installed.)
Preparing to unpack linux-headers-surface_5.4.13-surface-1_amd64.deb ...
Unpacking linux-headers-surface (5.4.13-surface-1) over (5.4.13-surface-1) ...
Preparing to unpack linux-image-surface_5.4.13-surface-1_amd64.deb ...
Unpacking linux-image-surface (5.4.13-surface-1) over (5.4.13-surface-1) ...
dpkg: considering removing linux-libc-dev:amd64 in favour of linux-libc-dev-surface:amd64 ...
dpkg: yes, will remove linux-libc-dev:amd64 in favour of linux-libc-dev-surface:amd64
Preparing to unpack linux-libc-dev-surface_5.4.13-surface-1_amd64.deb ...
Unpacking linux-libc-dev-surface:amd64 (5.4.13-surface-1) over (5.4.13-surface-1) ...
Setting up linux-headers-surface (5.4.13-surface-1) ...
Setting up linux-image-surface (5.4.13-surface-1) ...
update-initramfs: Generating /boot/initrd.img-5.4.13-surface
Sourcing file `/etc/default/grub'
Sourcing file `/etc/default/grub.d/init-select.cfg'
Generating grub configuration file ...
Found background image: splash1.png
Found linux image: /boot/vmlinuz-5.4.13-surface
Found initrd image: /boot/initrd.img-5.4.13-surface
Found linux image: /boot/vmlinuz-5.4.6-surface
Found initrd image: /boot/initrd.img-5.4.6-surface
Found linux image: /boot/vmlinuz-5.3.18-surface
Found initrd image: /boot/initrd.img-5.3.18-surface
Found Windows Boot Manager on /dev/nvme0n1p1@/EFI/Microsoft/Boot/bootmgfw.efi
Adding boot menu entry for EFI firmware configuration
done
Setting up linux-libc-dev-surface:amd64 (5.4.13-surface-1) ...
15:30 mssb2 ~/Downloads/debian-latest$ 
```

**Comment by qzed** [comment]
Nice, thanks for reporting and testing!
