### ISSUE TITLE
SP6 Invalid Signature

### ISSUE THREAD

**Issue by Brunochris13** [linux-surface/linux-surface#586]
When I reboot my SP6 and try to boot into the new surface kernel I get this message.

Loading Linux 5.14.8-surface
error: /boot/vmlinuz-5.14.8-surface has invalid signature.
Loading initial ramdisk ...

### Environment

- Hardware model:  Surface Pro 6
- Kernel version:  Linux Christos-Surface-Pro-6 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Debian/Ubuntu

**Comment by qzed** [comment]
Looks like a secureboot problem. Did you install the `linux-surface-secureboot-mok` package and follow the instructions printed during installation? If not, you can boot into the distro kernel and install the package from there. If you've already installed the package but did not follow the instructions, you can uninstall and then re-install it (you have to actually uninstall it to trigger the install script again).

**Comment by Brunochris13** [comment]
I had Secure Boot ON, but after I turned it OFF it worked. Thank you.

**Comment by qzed** [comment]
If you change your mind, you can still set up secureboot following the instructions above on the wiki any time you want. Secureboot should work with the Surface kernel once you've installed the keys.
