### ISSUE TITLE
Can't install v4l2loopback, "make[1]: *** /lib/modules/5.14.7-1.surface.fc34.x86_64/build: No such file or directory."

### ISSUE THREAD

**Issue by CoralCunt** [linux-surface/linux-surface#588]
I've been trying to get my camera working through making a GStreamer Loopback Device. It's been a bit difficult since the guide is written for Ubuntu-/Debian-based distros and I run Fedora, but I think I got there most of the way.

I get stuck during the step of installing v4l2loopback. I tried downloading it from the [v4l2loopback github page](https://github.com/umlaeute/v4l2loopback) using `make`.

Doing so gives this result: 
```
v4l2loopback-main]$ make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/andrew/Downloads/v4l2loopback-main modules
make[1]: *** /lib/modules/5.14.7-1.surface.fc34.x86_64/build: No such file or directory.  Stop.
make: *** [Makefile:46: v4l2loopback.ko] Error 2
```

Apparently /lib/modules/5.14.7-1.surface.fc34.x86_64/build is missing. I go there using the file explorer and it looks like a text file. I click on it and get this error. 
![image](https://user-images.githubusercontent.com/87242503/135757669-1427259d-6b78-46e5-b85b-cb1d29249f1a.png)

Just out of curiosity I checked the same location of the generic kernel, and it's a folder there with several files and folders in it. That seems to be as it should be.

So as far as I understand something is missing here. I figured this was an issue with the kernel overall, which is why I posted it here and not in the camera thread.

If someone could help me here, I would really appreciate it, because I don't know how to get the camera working at this point. 

### Environment

- Hardware model: Surface Pro 6
- Kernel version: `Linux fedora 5.14.7-1.surface.fc34.x86_64 #1 SMP Mon Sep 27 18:10:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: Fedora 34

</details>

**Comment by qzed** [comment]
Did you install the `kernel-surface-devel` package? And is there any chance you've updated the kernel and did not reboot before trying to build the loopback module?

**Comment by CoralCunt** [comment]
Wow. Thank you, that package was the one thing that was missing. I wish this package had been listed somewhere, because this entire endeavor has been really tedious due to nothing being explained for Fedora. I've been spending half of my day just trying to get the camera working, the other half being installing the kernel and everything else, and now it works. 

> And is there any chance you've updated the kernel and did not reboot before trying to build the loopback module?

No, I was definitely running on the newest kernel the entire time. 

(As a side note for future people finding this: I had to use v4l2sink device=/dev/video14 because v4l2sink device=/dev/video42 did not exist for me.)

**Comment by qzed** [comment]
> I wish this package had been listed somewhere, because this entire endeavor has been really tedious due to nothing being explained for Fedora.

I've added a line about this to the installation/setup page on the wiki.
