### ISSUE TITLE
No audio devices/battery status

### ISSUE THREAD

**Issue by ttichler** [linux-surface/linux-surface#60]
No audio devices or battery status is shown after installation and boot of 5.3.18 kernel

- Hardware model: Surface 3 (non pro)
- Kernel version: uname -a output: Linux TSurface3 5.3.18-surface #1 SMP Fri Dec 27 23:37:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Debian/Ubuntu 18.04

dmesg output: [dmesgOutput.txt](https://github.com/linux-surface/linux-surface/files/4105028/dmesgOutput.txt)

**Comment by kitakar5525** [comment]
I can' t find a direct cause, but generally speaking:
- Try 5.4 kernels (Surface 3 does not use IPTS)


Regarding battery status:
Try updating firmware if Windows is still available (via Windows Update)
> `[    0.000000] DMI: Microsoft Corporation Surface 3/Surface 3, BIOS 1.51116.178 03/09/2015`

1.51116.178 was released on 8/8/2016
The latest UEFI firmware is `1.51116.238.0` (released on July 11, 2019)
You can also update firmware on Linux: https://github.com/linux-surface/surface-firmware

Regarding audio:
what will happen when you restart pulseaudio?
```bash
pulseaudio -k
pulseaudio -D
```

**Comment by ttichler** [comment]
Results of pulseaudio -k: <nothing>
Results of pulseaudio -D: E: [pulseaudio] main.c: Daemon startup failed.
Windows isn't an option atm so I'll take a crack at 5.4. If that issue persists I'll go get windows back on it for the firmware update.

**Comment by ttichler** [comment]
Looks like 5.4.6 has both the same issues. I'll try updating firmware once I get windows back on this thing.

uname -a output: Linux TSurface3 5.4.6-surface #1 SMP Fri Dec 27 22:27:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

new dmesg output: 
[dmesgOutput.txt](https://github.com/linux-surface/linux-surface/files/4109877/dmesgOutput.txt)

**Comment by ttichler** [comment]
Booting into windows with that link to download and install the firmware updates has helped get battery status indicator into 5.4 but there is still no detectable sound devices outside of the login screen.

Login screen has the hardware buttons able to control the volume and play sound but upon logging in it all stops. Not sure where to go or what to do to fix this issue

**Comment by qzed** [comment]
The buttons and sound working on the login screen indicates that this is probably a setup/config issue. Apart from that I don't have any clue though.

**Comment by kitakar5525** [comment]
Regarding battery status:
It's interesting that updating firmware is needed for surface3-power driver (battery status reading driver) to work.

Regarding audio:
What is the output sink?
```bash
# https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_default_output_sink
# To list the output sinks available, type the following command:
pacmd list-sinks | grep -e 'name:' -e 'index:'
```

For example, on my Surface 3:
```bash
$ pacmd list-sinks | grep -e 'name:' -e 'index:'
  * index: 0
	name: <alsa_output.platform-cht-bsw-rt5645.HiFi__hw_chtrt5645__sink>
```

**Comment by ttichler** [comment]
Initially that pacmd said there was no pulseaudio daemon running but after launching and closing pavucontrol, I was able to get it get an output. Still no volume control from buttons and sound doesn't play from speakers but hey, babysteps.

[pacmdOutput.txt](https://github.com/linux-surface/linux-surface/files/4118340/pacmdOutput.txt)

**Comment by ttichler** [comment]
For what it's worth I've only been able to get windows to detect and play sound through the speakers without issue. Ubuntu doesn't and the 9.0 build of Android x86 doesn't either. Not sure if that's helpful here

**Comment by kitakar5525** [comment]
Hmm…

>  Ubuntu doesn't and the 9.0 build of Android x86 doesn't either

Did sound work before on any distros?

What's the output of pulseaudio service on journal log:
```bash
journalctl --user -u pulseaudio.service -b 0 --no-pager
```

**Comment by kitakar5525** [comment]
Also, try starting pulseaudio without daemonize to see logs on terminal:
```bash
pulseaudio -k
pulseaudio
```

You may get more useful info with verbose output… :
```bash
pulseaudio -k
pulseaudio -v
```

**Comment by ttichler** [comment]
>Did sound work before on any distros?

Nope. Only Windows natively recognizes and plays sound without issue.

>What's the output of pulseaudio service on journal log:

tyler@TSurface3:~$ journalctl --user -u pulseaudio.service -b 0 --no-pager
-- Logs begin at Fri 2020-01-24 02:51:21 CST, end at Tue 2020-01-28 12:33:23 CST. --
-- No entries --

>Also, try starting pulseaudio without daemonize to see logs on terminal

tyler@TSurface3:~$ pulseaudio -k
E: [pulseaudio] main.c: Failed to kill daemon: No such file or directory

tyler@TSurface3:~$ pulseaudio
W: [pulseaudio] pid.c: Stale PID file, overwriting.
N: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
N: [pulseaudio] alsa-util.c: Disabling timer-based scheduling because running inside a VM.
Killed

Here's the verbose output. Not to keep giving anyone a big thing to read through but there's a lot there and I don't really know much about what I'm looking at.
[pulseaudioVerbose.txt](https://github.com/linux-surface/linux-surface/files/4124022/pulseaudioVerbose.txt)

Also, thanks for trying to help with this. I really appreciate it.

**Comment by kitakar5525** [comment]
When searching with "[alsa-sink-HdmiLpeAudio] alsa-sink.c: Starting playback.", hit old results. Especially, this: [[pulseaudio-discuss] pulseaudio fails to start with kernel 4.11, caused by new snd_hdmi_lpe_audio module)](https://lists.freedesktop.org/archives/pulseaudio-discuss/2017-March/027858.html)

I thought this was fixed by the kernel side, but if you don't have a strong reason to use Ubuntu LTS release, try Ubuntu 19.10 to update pulseaudio.

But then, I'm not sure why the sound doesn't work on Android-x86, if I assume the cause of this issue is old pulseaudio.

**Comment by kitakar5525** [comment]
Yes, many things regarding this issue (snd_hdmi_lpe_audio driver makes internal sound card unusable after kernel 4.11) has been fixed on pulseaudio v11.99.1 
BugLink: https://bugs.freedesktop.org/show_bug.cgi?id=100488

So, updating PulseAudio to at least v11.99.1 is required (and to do so, upgrading Ubuntu to the latest stable version may be the best option)

**Comment by ttichler** [comment]
Sorry for the delayed response. I'll give Ubuntu 19.10 a try sometime in the next week and get back to you about it. Again, thanks for your patience

**Comment by ttichler** [comment]
Upgrading to Ubuntu 19.10 fixed the issue. After installing the 5.4.6 kernel I have full battery recognition and volume control through the OS and the hardware buttons on the surface. Thanks again to everyone who helped me out!

**Comment by kitakar5525** [comment]
I'm glad to hear that!

**Comment by kitakar5525** [comment]
@ttichler By the way, Can I ask you a favor?
My Surface 3 is affected by another bug that DMI table is broken and I want to know the correct table infomation.

Please post the output of the following commands:
```bash
grep . /sys/devices/virtual/dmi/id/{bios_vendor,board_name,board_vendor,chassis_vendor,product_name,sys_vendor}
```

For reference, the output from my Surface 3 that has broken DMI table:
```bash
$ grep . /sys/devices/virtual/dmi/id/{bios_vendor,board_name,board_vendor,chassis_vendor,product_name,sys_vendor}
/sys/devices/virtual/dmi/id/bios_vendor:American Megatrends Inc.
/sys/devices/virtual/dmi/id/board_name:OEMB
/sys/devices/virtual/dmi/id/board_vendor:OEMB
/sys/devices/virtual/dmi/id/chassis_vendor:OEMB
/sys/devices/virtual/dmi/id/product_name:OEMB
/sys/devices/virtual/dmi/id/sys_vendor:OEMB
```

**Comment by ttichler** [comment]
>Please post the output of the following commands:

Sure, sorry it took so late for me to get back to you. Here's the output:
```
grep . /sys/devices/virtual/dmi/id/{bios_vendor,board_name,board_vendor,chassis_vendor,product_name,sys_vendor}
/sys/devices/virtual/dmi/id/bios_vendor:American Megatrends Inc.
/sys/devices/virtual/dmi/id/board_name:Surface 3
/sys/devices/virtual/dmi/id/board_vendor:Microsoft Corporation
/sys/devices/virtual/dmi/id/chassis_vendor:Microsoft Corporation
/sys/devices/virtual/dmi/id/product_name:Surface 3
/sys/devices/virtual/dmi/id/sys_vendor:Microsoft Corporation
 ```

**Comment by kitakar5525** [comment]
@ttichler Thanks!
