### ISSUE TITLE
Surface Pro 8 - Surface Pro Signature Keyboard and touchscreen don't work with Ubuntu 20.04.3

### ISSUE THREAD

**Issue by xG33Kx** [linux-surface/linux-surface#616]
Came with Windows 11.  Secure boot disabled.  A fresh install of Ubuntu 20.04.03 and subsequently updating, then installing and booting into the 5.14.14-surface kernel doesn't have a working Surface Pro Signature Keyboard, touchscreen, or webcams.  Other tested functions including WiFi, Bluetooth, USB, volume buttons, and speakers appear to work.

### Environment

- Hardware model: Surface Pro 8 
- Kernel version:  Linux surface8-ubuntu 5.14.14-surface #1 SMP Sat Oct 23 18:01:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
- Distribution: Ubuntu Desktop 20.04.03

<details><summary>`dmesg` output from unplugging and replugging the keyboard</summary>

```
[Tue Oct 26 16:35:14 2021] surface_serial_hub serialo-0: event: unhandled event (rqid: 0x0e, tc: 0x0e, tid: 0x01, ctd: 0x26, tid: 0x00) 
[Tue Oct 26 16:35:14 2021] surface_serial_hub sertal0-0: event: unhandled event (rqid: 0x0e, tc: 0x0e, tid: 0x01, ctd: 0x2c, tid: 0x00) 
[Tue Oct 26 16:35:17 2021] surface_serial_hub serialo-0: event: unhandled event (rqid: 0x0e, tc: 0x0e, tid: 0x01, cid: 0x26, tid: 0x00) 
[Tue Oct 26 16:35:17 2021] surface_serial_hub serialo-0: event: unhandled event (rqid: 0x0e, tc: 0x0e, tid: 0x01, cid: 0x2c, tid: 0x00) 
[Tue Oct 26 16:35:17 2021] surface_serial_hub sertalo-0: event: unhandled event (rqid: 0x0e, tc: 0x0e, tid: 0x01, cid: 0x26, tid: 0x00) 
[Tue Oct 26 16:35:17 2021] surface_serial_hub serialo-0: event: unhandled event (rgid: 0x0e, tc: 0x0e, tid: 0x01, cid: 0x2c, tid: 0x00) 
[Tue Oct 26 16:35:18 2021] surface_serial_hub sertal0-0: event: unhandled event (rgid: 0x0e, tc: 0x0e, tid: 0x01, cid: 0x1d, tid: 0x00)

```

</details>

**Comment by qzed** [comment]
I've cleaned up the patches for the latest release (v5.14.15, should be available in the next hour). This also contains the hot-remove fix to prevent/fix timeouts. With that, the Surface Aggregator Module support for the Surface Pro 8 should be complete. I'll submit the patches upstream after some more testing in the Surface kernel.

The touchscreen/pen discussion is handled at https://github.com/linux-surface/intel-precise-touch/issues/8. So I'm going to close this issue. If you experience any problems, please feel free to open up a new issue for that.
