### ISSUE TITLE
SB1: 5.14.14 breaks hibernate in Ubuntu

### ISSUE THREAD

**Issue by OliverUrbann** [linux-surface/linux-surface#617]
After installing the 5.14.14 for Ubuntu 20.04 LTS my Surface Book 1 goes into hibernate, wakes-up, I can still enter the luks password, but afterwards in X11 (or at the login screen) my keyboard and touchpad does not work anymore. Touchscreen still works (with finger and pen). 5.14.13 works as expected.

Dmesg and lsusb:
```
[   87.179376] PM: hibernation: hibernation exit
[   87.442808] usb 1-6: USB disconnect, device number 4
[   90.885856] mwifiex_pcie 0000:03:00.0: info: trying to associate to bssid 18:83:bf:66:bd:25
[   90.984125] mwifiex_pcie 0000:03:00.0: info: associated to bssid 18:83:bf:66:bd:25 successfully
[   90.993832] IPv6: ADDRCONF(NETDEV_CHANGE): wlp3s0: link becomes ready
┌─[civic@ciVicSurface] - [~] - [2021-10-29 07:59:14]
└─[0] lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
lsusb on a working system (5.14.13):
```
lsusb
Bus 002 Device 002: ID 045e:090b Microsoft Corp. Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 1286:204c Marvell Semiconductor, Inc. Bluetooth and Wireless LAN Composite Device
Bus 001 Device 003: ID 045e:07cd Microsoft Corp. Surface Keyboard
Bus 001 Device 002: ID 045e:091a Microsoft Corp. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Probably caused by 36e910cf4215b4a418dab5201b91d204f943aca5?

**Comment by DrBrad** [comment]
I think its become almost unusable. If I flip the lid of my laptop there is a 100% chance of it going into the no wake mode.
It all depends upon whether or not it plugged in.. If its plugged in it will never go in to the no wake.
If its unplugged it might go into it when the screen times out, however it takes about 20 minutes.

No keys will turn it on even external keyboard and mouse. The display is just off.

**Comment by DrBrad** [comment]
Update, v5.14.15 still has the hibernation / suspend problem.

**Comment by DrBrad** [comment]
I have tried using `nouveau.modeset=0` with no changes. Seems that after forcing the laptop into suspend, I have found that the keyboard FN light will toggle, however CAP-LOCK wont work (light toggle).

**Comment by DrBrad** [comment]
It also looks like having it plugged in doesn't change anything.

**Comment by DrBrad** [comment]
I have allocated more swap space (9GB for 8GB of RAM) and the problem persists.

**Comment by OliverUrbann** [comment]
@DrBrad I guess the source of your issue is different to mine. You have an AMD device (instead of Intel) from another product line and your issue is also different: a full freeze instead of disconnected keyboard/touchpad after hibernate (note that everything else works in my case), right? Probably in another thread you can already find a solution?

**Comment by imlinstress** [comment]
I just installed the latest kernel and latest ubuntu lts on my SB2 and i'm experiencing similar issues with suspend. Display goes black, cursor blinks for a while. The only way to wake up the surface is through power button and restart. Somewhere i saw that files named Nvidia-suspend, Nvidia-hibernate were 0 bytes.

**Comment by DrBrad** [comment]
That seems very similar to the issue i was having with the surface laptop, except i dont even get a cursor. Check out my thread - link in comment above.

**Comment by OliverUrbann** [comment]
Ok got it:

```
[0] git bisect good
e54abefe703ab7c4e5983e889babd1447738ca42 is the first bad commit
commit e54abefe703ab7c4e5983e889babd1447738ca42
Author: Pavankumar Kondeti <pkondeti@codeaurora.org>
Date:   Fri Oct 8 12:25:46 2021 +0300

    xhci: Fix command ring pointer corruption while aborting a command

    commit ff0e50d3564f33b7f4b35cadeabd951d66cfc570 upstream.

    The command ring pointer is located at [6:63] bits of the command
    ring control register (CRCR). All the control bits like command stop,
    abort are located at [0:3] bits. While aborting a command, we read the
    CRCR and set the abort bit and write to the CRCR. The read will always
    give command ring pointer as all zeros. So we essentially write only
    the control bits. Since we split the 64 bit write into two 32 bit writes,
    there is a possibility of xHC command ring stopped before the upper
    dword (all zeros) is written. If that happens, xHC updates the upper
    dword of its internal command ring pointer with all zeros. Next time,
    when the command ring is restarted, we see xHC memory access failures.
    Fix this issue by only writing to the lower dword of CRCR where all
    control bits are located.

    Cc: stable@vger.kernel.org
    Signed-off-by: Pavankumar Kondeti <pkondeti@codeaurora.org>
    Signed-off-by: Mathias Nyman <mathias.nyman@linux.intel.com>
    Link: https://lore.kernel.org/r/20211008092547.3996295-5-mathias.nyman@linux.intel.com
    Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

:040000 040000 25ba4e9d3f359c8c28f52c50e79ad3ece482f6aa 129ea69a7b35cc18c2c0ffd47ec70148512821eb M      drivers

```

**Comment by qzed** [comment]
Doesn't look like the fix is in the USB tree yet, I'll apply it to our sources for now. So hopefully the next release should work again.

**Comment by imlinstress** [comment]
Guys, it's the network manager, most of the times at least in my case. 

Hibernate works fine after shutting downs the wifi-scanning.
After connecting to wifi, i use **sudo killall -STOP NetworkManager** to stop wifi-scanning that is used for location tracking.
_https://ubuntuforums.org/showthread.php?t=2163994_.  
To renable wifi scanning again:  **sudo killall -CONT NetworkManager**

Amasingly  the hibernate and the wakeup (pressing enter) actions reacts with no delay.
 It's not one hundred  percent bulletproof though.

**Comment by OliverUrbann** [comment]
Thx for sharing your experience. However, as I wrote in my last post, I'm pretty sure I've found the reason for the described issue. I intended to wait till I was able to test the fix but I think I should close this issue to make clear that a solution already seems to exist.

**Comment by qzed** [comment]
New kernels with the fix above are building now.
