### ISSUE TITLE
Package for Fedora Linux 35

### ISSUE THREAD

**Issue by FlyinPancake** [linux-surface/linux-surface#619]
Fedora 35 is about to be released, the beta has been out for a while as well, so the fedora repo should support it.

**Comment by qzed** [comment]
We're currently running into an issue with Fedora 35 builds and GitHub Actions, specifically the `checkout@v2` action:

```
Run actions/checkout@v2
  with:
    repository: linux-surface/libwacom-surface
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
/usr/bin/docker exec  721d0b583303f1f296a30166275dc3244e3cb88f0c8d2e28dc90266cca8680fd sh -c "cat /etc/*release | grep ^ID"
/__e/node12/bin/node[17]: ../src/node_platform.cc:63:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0x9da7c0 node::Abort() [/__e/node12/bin/node]
 2: 0x9da847  [/__e/node12/bin/node]
 3: 0xa49c8a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/__e/node12/bin/node]
 4: 0xa49d4b node::NodePlatform::NodePlatform(int, node::tracing::TracingController*) [/__e/node12/bin/node]
 5: 0x94e3da node::InitializeV8Platform(int) [/__e/node12/bin/node]
 6: 0x9ac4c1 node::InitializeOncePerProcess(int, char**) [/__e/node12/bin/node]
 7: 0x9ac6b3 node::Start(int, char**) [/__e/node12/bin/node]
 8: 0x7f8d61ca8560  [/lib64/libc.so.6]
 9: 0x7f8d61ca860c __libc_start_main [/lib64/libc.so.6]
10: 0x94a055  [/__e/node12/bin/node]
```

If we try to replace `checkout@v2` with `checkout@v1` it gets a bit further but then fails downloading dependencies with
```
Run dnf distro-sync -y
  dnf distro-sync -y
  dnf install -y make rpmdevtools rpm-sign 'dnf-command(builddep)'
  dnf builddep -y pkg/fedora/libwacom-surface.spec
  shell: sh -e {0}
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Fedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Process completed with exit code 1.
```

The underlying error is documented here: https://medium.com/nttlabs/ubuntu-21-10-and-fedora-35-do-not-work-on-docker-20-10-9-1cd439d9921 (credits to @StollD for tracking this down). At the moment, our best option seems to wait until docker on Ubuntu gets updated to version 20.10.10 (seems to be at version 20.10.7 right now).

**Comment by LawsOfScience** [comment]
Since Fedora 35 just released, is it safe to upgrade to that yet, or should I wait for this issue to get resolved?

**Comment by FlyinPancake** [comment]
To put it simple: you can, but that results in having 5.13.X surface 
kernel and 5.14.14 generic kernel. If you plan on a clean install, 
don't, since the f35 repo isn't up and we can't even download the 
outdated kernel. I have updated my SP6 with f35 but stayed with the 
surface kernel.

Hope this clears things up :smiley:

**Comment by Riezebos** [comment]
This software list was updated 8 hours ago and now contains docker 20.10.10:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md

I'm not sure whether this means the underlying error should now be fixed, but I thought I'd share the info here.

**Comment by StollD** [comment]
All our packages should have Fedora 35 builds now and the repo will update soon-ish.
