### ISSUE TITLE
[SLS] Request for Testing: KIP Subsystem on Surface Laptop Studio

### ISSUE THREAD

**Issue by qzed** [linux-surface/linux-surface#620]
Hi all,

the Surface Laptop Studio is currently missing a tablet-mode switch, i.e. a small input device that provides `SW_TABLET_MODE` events to user-space, letting it know when the keyboard and touchpad are available and when they are not. This event can, for example, help desktop environments (such as Gnome) to decide whether it should show the touchscreen keyboard.

On the Surface Pro 8 (and Surface Pro X), the detachable keyboard cover is managed via the "KIP" subsystem. This subsystem provides events via the Surface System Aggregator Module, including events when the keyboard is being folded back and detached/re-attached. I now want to figure out if similar events are sent on the Surface Laptop Studio.

To help test this, you can follow these steps:
1. Clone the Surface Aggregator Module repository and change into it:
   ```
   git clone https://github.com/linux-surface/surface-aggregator-module.git
   cd surface-aggregator-module
   ```
2. Load the debug interface for the Surface Aggregator Module:
    ```
    sudo modprobe surface_aggregator_cdev
    ```
3. Enable events of the KIP subsystem:
   ```
   sudo ./scripts/ssam/events.py enable 0x01 0x01 0x0b 0x0c 0x0e 0x00 0x01
   ```
   If that command fails, you don't need to continue.
4. Start listening to incoming KIP subsystem events:
   ```
   sudo ./scripts/ssam/events.py listen 0x0e
   ```
   Note: This command will run and log events until you terminate it with `ctrl-c`. Please keep it running for the next steps.
5. Move the screen around, e.g. switch from laptop mode to tablet mode and other modes (e.g. screen folded back). The order is not important (but you should be able to map the events, if some were emitted, to your actions). If there are any events emitted, please post them here.

During this, you should also have a look at the dmesg log, e.g. via `sudo dmesg -w` in a separate terminal and check if there are any errors.

CC @ukasuviok

**Comment by ukasuviok** [comment]
There was no output or error messages.

**Comment by qzed** [comment]
Thanks! Are there any `unhandled event` messages in the dmesg log or any warnings?

**Comment by ukasuviok** [comment]
Nothing there either.

**Comment by qzed** [comment]
Okay, so doesn't look like the SLS uses the KIP subsystem then. Thanks again!
