### ISSUE TITLE
Touchscreen does not work on Microsoft Surface 

### ISSUE THREAD

**Issue by dianaberlin** [linux-surface/linux-surface#633]
Touchscreen does not work

### Environment

- Hardware model:  Surface Laptop 4, Intel i5
- Kernel version: 5.14.16-surface #2 
- Distribution: Ubuntu 20.04

 `dmesg` 
Linux version 5.14.16-surface (root@37ef9163043b) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #2 SMP Tue Nov 9 00:20:10 UTC 2021
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-5.14.16-surface root=UUID=1661b1e0-dea5-4046-878a-3f40cde4136e ro quiet splash vt.handoff=7
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Hygon HygonGenuine
[    0.000000]   Centaur CentaurHauls
[    0.000000]   zhaoxin   Shanghai  
[    0.000000] x86/split lock detection: #AC: crashing the kernel on kernel split_locks and warning on user-space split_locks

**Comment by Vexored** [comment]
Hey ! Same, I need to downgrade to 5.14.15 on Fedora 35 with SP4

**Comment by qzed** [comment]
@dianaberlin See https://github.com/linux-surface/linux-surface/issues/532 and in particular https://github.com/linux-surface/intel-precise-touch/issues/4 and https://github.com/linux-surface/intel-precise-touch/issues/8.

**Comment by qzed** [comment]
@Vexored That's a different problem. Please open up a new issue for that and post a dmesg log.
