### ISSUE TITLE
[Question] How to create a dummay package for Silverblue?

### ISSUE THREAD

**Issue by thjderjktyrjkt** [linux-surface/linux-surface#637]
As [wiki](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#Fedora-Silverblue) mentioned:

> However, this can be solved with an ugly and dirty hack: You can build a kernel dummy package, with a version number thats so high that it will always override the default kernel package. This dummy package then pulls in the kernel-surface package from our Fedora package repository.
> 
> We already prepared a dummy package for you to use.

How did you create a dummy package that pulls another package? Is there a tutorial for that?

**Comment by thjderjktyrjkt** [comment]
```
Summary: Dummy Package
Name: kernel
Version: 20201215
Release: 1
Group: System Environment/Base
License: Freeware
BuildArch: x86_64
Provides: some-fresh-air
Requires: kernel-surface

%description

Some fresh air here.

This meta-package fools other packages to think you have certain packages installed.

%files
```

Is this the correct way?

If `Provides:` has `kernel` then `rpm-ostree` complains about:

```shell
error: Could not depsolve transaction; 1 problem detected:
 Problem: package quota-1:4.06-6.fc35.x86_64 conflicts with kernel < 2.4 provided by kernel-20201215-1.x86_64.rpm
  - conflicting requests
```

**Comment by StollD** [comment]
https://github.com/linux-surface/linux-surface/blob/master/pkg/fedora/kernel-surface-silverblue/kernel-surface-silverblue.spec

We also have a finished rpm that you can use, just run the script block from the wiki that comes after the part you quoted.

**Comment by thjderjktyrjkt** [comment]
@StollD Much appreciated for the file!

In fact I'm not installing surface linux kernel, but liquorix kernel. But I have a Surface device which had surface linux installed on Silverblue successfully, so I'm trying to reuse the same hack to install that kernel.
