### ISSUE TITLE
Touchscreen and Power Issues

### ISSUE THREAD

**Issue by chaoticode** [linux-surface/linux-surface#64]
[Description of the bug or feature]

I have the repositories added and have installed the dmhacker kernel previously but neither of them have the touchscreen working. The power issue I can get around and not be bothered by it but I cannot figure out the Touch Issue.

### Environment

- Hardware model: Surface Pro 4
- Kernel version: ARCH 5.4.14.a-1-hardened #1 
- Distribution: Arch Linux x86_64 GNU/Linux

<details><summary>`dmesg` output</summary>

dmesg attached to email
```
please provide a copy of `dmesg` here if possible

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/4113144/dmesg.txt)

```

</details>

**Comment by archseer** [comment]
You should install 5.3 for the time being because 5.4 doesn't support IPTS (touchscreen)

**Comment by qzed** [comment]
Also the kernel version looks like the Arch `linux-hardened` package and not a surface kernel.

**Comment by archseer** [comment]
Closing because it seems that the wrong kernel was loaded. Leave a comment if you need me to reopen.
