### ISSUE TITLE
Problem installing/booting

### ISSUE THREAD

**Issue by Mr-Brojobs** [linux-surface/linux-surface#65]
I'm trying to get v5.3.18 working on my Surface book 2(Ubuntu 18.04). I installed the three deb files and when I run the setup script I get the following error-
dpkg: error: cannot access archive 'tmp/*.deb': No such file or directory.
 
I cannot boot using the 5.3.18-surface linux version- it tells me that the version has an invalid signature and then, to load the kernel.

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/4113538/dmesg.txt)

**Comment by archseer** [comment]
You probably should update your local repo, the setup script doesn't really do any deb installation anymore.

For booting, that sounds like an issue with secure boot, did you set up the custom certificate as described here? https://github.com/linux-surface/linux-surface/wiki/Secure-Boot#using-the-provided-secure-boot-certificate
