### ISSUE TITLE
Question:Does it support Surface 3(Not Pro)?

### ISSUE THREAD

**Issue by IZWB-003** [linux-surface/linux-surface#68]
Just a question... If I did something wrong,just close it and I am sorry about that...
I'd like to try Linux on my Surface 3 device(Not Surface Pro 3),but as I see Surface 3 is not in the list. However,I found some issues said that someone else who uses Surface 3 are using this project,and everything goes well. So now I wonder whether this project supports Surface 3 or not? If it does, which firmware should I use and what should I do? Thanks.
(PS:I'm a newcomer in English and Github and please don't mind it... thanks.)

**Comment by archseer** [comment]
The wiki says "TODO: add Surface 3 (non-Pro) to matrix", we just haven't added it to the list yet. Everything should work fine with the patched kernel and I think you don't need to use IPTS for it. The kernel currently includes a few patches to add battery status and allow the the wifi to suspend, etc.

**Comment by IZWB-003** [comment]
@archseer All right I see it. I will try it by myself. Thanks!

**Comment by archseer** [comment]
Surface 3 has been added to the wiki.
