### ISSUE TITLE
Compiling issue in ipts module

### ISSUE THREAD

**Issue by Valerio1474** [linux-surface/linux-surface#69]
Hello,
I'm trying to compile your patched 5.3.18 kernel but excluding a lot of drivers and functions that I don't need on my Surface, so I'm using a laptop config (based on Intel) that I've tuned in the past as a starting point. I'm getting this error during compilation:

ERROR: "ipts_dbgfs_deregister" [drivers/misc/ipts/intel-ipts.ko] undefined!
ERROR: "ipts_dbgfs_register" [drivers/misc/ipts/intel-ipts.ko] undefined!
make[4]: *** [scripts/Makefile.modpost:103: modules-modpost] Error 1
make[3]: *** [Makefile:1304: modules] Error 2

Do you know what kind of feature/module should be enabled to fix this?

### Environment

- Hardware model: Surface Pro 2017
- Kernel version: 5.3.18
- Distribution: not relevant

<details><summary>`dmesg` output</summary>
 not relevant

please provide a copy of `dmesg` here if possible

 not relevant

</details>

**Comment by StollD** [comment]
Hmm, that seems like an issue with some of the #defines in the IPTS driver. You can either enable `CONFIG_DEBUG_FS`, or replace these [lines](https://github.com/linux-surface/kernel/blob/a93d778a611eadfa0ffa8dc3b6e252c418429f17/drivers/misc/ipts/ipts.h#L98-L99):
```C
static int ipts_dbgfs_register(struct ipts_info *ipts, const char *name);
static void ipts_dbgfs_deregister(struct ipts_info *ipts);
```
with
```C
static inline int ipts_dbgfs_register(struct ipts_info *ipts, const char *name) { return 0; }
static inline void ipts_dbgfs_deregister(struct ipts_info *ipts) { }
```

**Comment by Valerio1474** [comment]
> Hmm, that seems like an issue with some of the #defines in the IPTS driver. You can either enable `CONFIG_DEBUG_FS`, or replace these [lines](https://github.com/linux-surface/kernel/blob/a93d778a611eadfa0ffa8dc3b6e252c418429f17/drivers/misc/ipts/ipts.h#L98-L99):
> 
> ```c
> static int ipts_dbgfs_register(struct ipts_info *ipts, const char *name);
> static void ipts_dbgfs_deregister(struct ipts_info *ipts);
> ```
> 
> with
> 
> ```c
> static inline int ipts_dbgfs_register(struct ipts_info *ipts, const char *name) { return 0; }
> static inline void ipts_dbgfs_deregister(struct ipts_info *ipts) { }
> ```

Thank you! Now it compiles. I've tried the debug_fs=yes solution, but shouldn't it be mandatory in the driver if it is required to compile?

**Comment by StollD** [comment]
Because it shouldn't be mandatory. The driver is broken, simple as that.
