### ISSUE TITLE
Surface Kernel Has Invalid Signature

### ISSUE THREAD

**Issue by PythonOrC** [linux-surface/linux-surface#690]
When I try to boot up the surface kernel an error message popped up.

```
error: /boot/vmlinuz-5.15.6-surface has invalid signature.
Loading initial ramdisk ...
error: you need to load the kernel first.
```

I have manually installed the secureboot-mok.deb file but there are no instructions that popped up after I installed it. 
I would still like to keep secure-boot on.

### Environment

- Hardware model: Surface Laptop 1
- Kernel version: Linux 5.15.6-surface
- Distribution: Ubuntu

**Comment by jarchiepacheco** [comment]
Did you ever get this figured out? I'm having the same issue on my Surface Pro 6 right now.

**Comment by DictXiong** [comment]
this works for me: 
Invalid Signature Issue #605

**Comment by qzed** [comment]
Closing this as the steps are described in #605 and the wiki has been updated to be a bit clearer on the secure-boot/MOK topic.
