### ISSUE TITLE
Feedback of issues I encountered during my installation

### ISSUE THREAD

**Issue by alxnbl** [linux-surface/linux-surface#694]
### Environment

- Hardware model:  Surface 5
- Kernel version: Linux Surface-Pro 5.15.11-surface
- Distribution: Ubuntu 20.04.3

Hi all, 

First of all thank you all for you hard work on this project, I have been able to successfully install linux-surface kernel on my Surface 5 with Ubuntu.

You will find some feed back bellow about issues that I encountered during installation and that may be helpful for you to update the installation documentation :
- Step "sudo apt install linux-image-surface linux-headers-surface iptsd libwacom-surface"
  - This step failed because my CA certificates were no up-to-date. I needed to do an apt update && apt upgrade to get the last CA certificate
- I then needed to update apt as described in issue #625  (comment of sphh  7 Nov 2021) to solve 401 errors of GitHub servers
- I failed to import the key in the boot  loader during my first try : 
  - After installing linux-surface-secureboot-mok and rebooting, the key enrollment process is displayed only one time, and after rebooting I was not able to reopen it. I think some more instructions about this step would be useful. I finally manage to enroll the key manually by following these instructions : https://github-wiki-see.page/m/linux-surface/linux-surface/wiki/Secure-Boot
  - In the key enrollment process, I failed to enroll the key using the password "surface". After several tries, I finally understood that the issue came from my french keyboard (azerty) with A and Q keys reversed. I keyed the password using the provided virtual keyboard with success. Maybe it is obvious for some people, but It was not for me.

 
Thanks again to all contributors,
Alex

**Comment by avhaymart** [comment]
thank you for opening this, i ran into all of these issues as well and this helped!
