### ISSUE TITLE
Heating issues on SB3 while using Ubuntu

### ISSUE THREAD

**Issue by gaurav7019** [linux-surface/linux-surface#698]
Running dual boot(W11 and Ubuntu 18.04 LTS) on Surface Book 3. I observed that my machine heats up a lot more when I am using Ubuntu than Windows. Also, consequently, the battery drains faster on Ubuntu. Any help with this? Like, installing proper drivers or something?

**Comment by gaurav7019** [comment]
Also, in case there is no solution, is it okay to keep switching between these OSs. Will it harm my device hardware or battery health?

**Comment by ruslanbay** [comment]
Did you try to tune your thermald settings?
https://github.com/linux-surface/linux-surface/tree/master/contrib/thermald
https://github.com/linux-surface/linux-surface/issues/221

**Comment by pkerschbaum** [comment]
@gaurav7019 have you been able to fix the issue?  
I am currently considering installing Ubuntu on my SB3 like you, would like to know if it works (well) :slightly_smiling_face:

**Comment by gaurav7019** [comment]
Nope, moved to WSL

**Comment by qzed** [comment]
Thermald should normally help, but requires some configuration. Without that you have nothing actively throttling the CPU based on its temperature until the firmware limits kick in. Windows uses something similar (Intel DPTF via ACPI tables), which you can use as a base (dptfxtract) for Linux (but likely still needs manual configuration, see e.g. https://github.com/linux-surface/linux-surface/tree/master/contrib/thermald for examples).
