### ISSUE TITLE
[SB2] DKMS error when installing non-free nvidia drivers

### ISSUE THREAD

**Issue by CountOmega** [linux-surface/linux-surface#705]
- Hardware model:  Surfacae Book 2 15"
- Kernel version:  5.15.14-surface (x86_64)
- Distribution:  Debian testing

I want to install the non-free nividia drivers because nouveau runs into a bug. When I try to install nvidia-drivers, DKMS installations fails: 

```
Loading new nvidia-current-470.94 DKMS files...
Building for 5.15.14-surface
Building initial module for 5.15.14-surface
Error! Bad return status for module build on kernel: 5.15.14-surface (x86_64)
Consult /var/lib/dkms/nvidia-current/470.94/build/make.log for more information.

```

snippet from the build log:

```
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  You are using:           gcc (Debian 11.2.0-14) 11.2.0

```

**Comment by qzed** [comment]
Can you post the full log from `/var/lib/dkms/nvidia-current/470.94/build/make.log`? If it really fails due to the compiler version being different (not sure as it's just a warning), you could check if Debian provides gcc version 9 in some package and if DKMS picks that up (also not sure if that actually works though).

**Comment by CountOmega** [comment]
[loge.txt](https://github.com/linux-surface/linux-surface/files/7878234/loge.txt)
Here is the log. I suppose I could downgrade the gcc.

**Comment by qzed** [comment]
It should be possible to install multiple gcc versions in parallel.

Okay, so it really is caused by the gcc version:
```
It is recommended to set the CC environment variable
to the compiler that was used to compile the kernel.

The compiler version check can be disabled by setting
the IGNORE_CC_MISMATCH environment variable to "1".
However, mixing compiler versions between the kernel
and kernel modules can result in subtle bugs that are
difficult to diagnose.

*** Failed CC version check. Bailing out! ***
```

So you could try installing gcc-9 and then setting the `CC` environment variable. Not sure if there's an option to configure that for the package or DKMS specifically.

**Comment by CountOmega** [comment]
Thanks, resolved it by installing gcc 9 alongside gcc11 and changing the default compiler to gcc9.
