### ISSUE TITLE
SL1 Ubuntu 19.10 5.3.18-surface no touchscreen

### ISSUE THREAD

**Issue by alturismo** [linux-surface/linux-surface#71]
no touchscreen

### Environment

Surface Laptop 1- Kernel version
alturismo@AlsSurface:~$ uname -a
Linux AlsSurface 5.3.18-surface #1 SMP Fri Dec 27 23:37:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 19.10

hi, as i wanted to try the linux surface again, installed fresh with 5318 kernel as 5.4x is not supposed to support the touchscreen on my model, is there anything else to install besides the 3 kernel packages ?

also installed now libwacom-surface_1.2-2_amd64.deb with the same result.

i remember i once had to replace some files to get touchscreen working, but when i read here about it it should be all included.

for an tipp, thanks ahead

wifi suspend is looking good without doing any extras
kernel sign worked out of the box with the presign from dev

**Comment by alturismo** [comment]
update, as i readed back when i had the no touchscreen issue before

i downloaded now the sourcecode from kernel 5.3.18 and copied the /ipts into /lib/firmware/intel and now touchscreen is working.

i guess without the setup.sh script from the first version and a fresh install it missed to copy the files, or i missed somewhere howto add them manually.

**Comment by qzed** [comment]
This seems to be fixed. Please re-open if not.
