### ISSUE TITLE
Wifi and Bluetooth not working on latest kernel

### ISSUE THREAD

**Issue by RononDex** [linux-surface/linux-surface#723]
[Description of the bug or feature]
Since the latest surface-linux kernel update, the wifi and bluetooth adapter no longer work on my SurfaceBook

relevant dmesg output:
![signal-2022-01-26-164224_001](https://user-images.githubusercontent.com/2249071/151196474-5659f678-8094-4fac-95e5-5876ed9ee31e.png)

### Environment
Arch Linux

- Hardware model: Surface Book (the original)
- Kernel version: 5.16.0-arch1-1surface from 15. January
- Distribution: Arch Linux

<details><summary>`dmesg` output</summary>

![signal-2022-01-26-164224_001](https://user-images.githubusercontent.com/2249071/151196474-5659f678-8094-4fac-95e5-5876ed9ee31e.png)

</details>

**Comment by qzed** [comment]
See https://github.com/linux-surface/linux-surface/issues/721. Installing `linux-firmware-marvell` should fix this.

**Comment by RononDex** [comment]
well that is kind of hard without internet now ;)

Is there a way to download the precompiled package and install it offline?

**Comment by qzed** [comment]
Go to https://archlinux.org/packages/core/any/linux-firmware-marvell/ then select "download from mirror" (or [this direct link]( https://archlinux.org/packages/core/any/linux-firmware-marvell/download)). Install the downloaded package via `pacman -U <filename.pkg.tar.zst>`.

**Comment by RononDex** [comment]
Worked perfectly, thank you very much :)
