### ISSUE TITLE
Installing libwacom-surface disables all inputs after reboot

### ISSUE THREAD

**Issue by ftastisch** [linux-surface/linux-surface#724]
Installing libwacom-surface makes my Surface Go with Manjaro 21.2.2 (KDE) unusable. After rebooting neither touch, external keyboard nor type cover are recognized. This happened first after a larger system update a few days ago. As I was not able to login anymore, I did a fresh install. The system runs "well" (was not yet fully functional) until I install libwacom-surface, which removes libwacom. Each time, the behaviour reappears and I am unable to interact with the system after rebooting.

### Environment

- Hardware model: Surface Go
- Kernel version: n/a (login not possible)
- Distribution: Manjaro 21.2.2.

**Comment by qzed** [comment]
Manjaro still uses libwacom-1.x whereas Arch uses libwacom-2.x (and thus the AUR version is also libwacom-2.x). Those versions are incompatible and I think that this is caused by that. You could try downgrading to libwacom-surface-1.12 until Manjaro uses libwacom-2.x (see e.g. https://discover.manjaro.org/package/libwacom for the version Manjaro is currently using).

**Comment by ftastisch** [comment]
Thank you, that sounds very promising. The easiest way to do so would be to download the build here directly, correct?
https://aur.archlinux.org/cgit/aur.git/commit/?h=libwacom-surface&id=5ad933310df442ad567e6076d707bac90283e1c3

**Comment by qzed** [comment]
Yes, download those files (manually or by cloning the repo and checking out the commit you've linked) and then build the package via `makepkg -fsi` from inside that directory. That should automatically build and install the package.

**Comment by LakanBanwa** [comment]
Sorry to ask what probably amounts to a pretty beginner question, but I'm in the same situation on my surface book 2 where neither my touchscreen nor my keyboard works (hence I can't login) after an update and on manjaro.  So how would I install packages in this situation?  Via a live install usb that also contains the package files?

**Comment by CountOmega** [comment]
I have the same issue on my SB2 with debian testing and the latest kernel.  For some reason, I can't replace libwacom-common with libwacom-surface because of some dependencies. Also, libwacom-common is version 2.1.0, whereas libwacom-surface is version 1.12.2
