### ISSUE TITLE
SP 4: WiFi device not detected anymore on Arch Linux

### ISSUE THREAD

**Issue by luca-viggiani** [linux-surface/linux-surface#727]
After updating my Arch Linux system on MS SP4 (can't tell exactly which package as I got 391 updates in one go) the wifi device is not detected anymore.
Current kernel is linux-surface 5.16.0. I tried downgrading to 5.15.12 which was running before the 391 updates but it still doesn't detect the wifi device.
Can someone help me please?

**Comment by luca-viggiani** [comment]
not even bluetooth device is detected anymore. I've checked in BIOS and both are enabled

**Comment by qzed** [comment]
See https://github.com/linux-surface/linux-surface/issues/723 and  #721. Arch has split up their firmware package. Installing `linux-firmware-marvell` should fix this.

**Comment by luca-viggiani** [comment]
Thank'you so much, that worked! and sorry for the duplicate!
