### ISSUE TITLE
pkg.surfacelinux.com is not responding

### ISSUE THREAD

**Issue by neilzone** [linux-surface/linux-surface#728]
```
W: Failed to fetch https://pkg.surfacelinux.com/debian/dists/release/InRelease  Could not connect to pkg.surfacelinux.com:443 (37.120.189.81), connection timed out
```

### Environment

- Hardware model: Surface Book 2
- Kernel version: Linux surfacebook 5.15.14-surface #1 SMP Sat Jan 15 02:27:14 UTC 2022 x86_64 GNU/Linux
- Distribution: Debian Bullseye

**Comment by CountOmega** [comment]
Can confirm. 
Surface Book 2, debian testing, latest kernel

**Comment by StollD** [comment]
The whole server was kinda messed up and wouldnt even shut down properly, so I had to kill it from the control panel. Now its running some sort of storage optimization. Who knows how long that will take ...

**Comment by neilzone** [comment]
> Who knows how long that will take ...

Fingers crossed! 🤞

**Comment by StollD** [comment]
Everything should work again now
