### ISSUE TITLE
Wifi device not recognized since update

### ISSUE THREAD

**Issue by MeisterLLD** [linux-surface/linux-surface#729]
My Wifi device disappeared since the last update and reboot. It is as if the chipset disappeared. nmcli device gives nothing. I didn't update for a few weeks so I cannot say at what point exactly in the updates the change would have occured, but it is somewhere between two weeks (my next to last update) and yesterday (last update, worked fine until that update).

### Environment

- Hardware model: Surface Pro 2017
- Kernel version: Linux archsurface 5.16.0-arch1-1-surace 
- Distribution: Arch Linux

lspci -vvnn | grep Network returns nothing anymore. When I boot on Windows, Wifi works as intended.

**Comment by qzed** [comment]
Arch split their firmware package and the normal does not include marvell firmware any more. See https://github.com/linux-surface/linux-surface/issues/721 /and https://github.com/linux-surface/linux-surface/issues/723. Installing linux-firmware-marvell should fix this.

**Comment by MeisterLLD** [comment]
Thank you very much. Sorry for not seeing these threads, I tried but I guess I didn't research well enough.
