### ISSUE TITLE
Built-in Keyboard, Trackpad, touchscreen, and battery do not work/register

### ISSUE THREAD

**Issue by CaryRock** [linux-surface/linux-surface#731]
[Description of the bug or feature]
As in the title, the keyboard, the trackpad, and touchscreen capabilities are not responsive. In addition, there is no recognition of anything battery related under /sys/class/power_supply - it is an empty folder when it should not be.

The keyboard works for the GRUB bootloader (though it takes a second to work, but always does work), but I haven't tried the touchscreen capabilities, nor the trackpad, during the GRUB phase (though I don't think they'll work regardless).

### Environment
Hardware model: Surface Laptop Studio w/ Intel i7, 16 GB RAM, 512 GB SSD, w/ dedicated (nVidia 3050 Ti mobile) GPU
Kernel Version: 5.13.13-surface
Distribution: Gentoo (using parinzee's surface-sources for 5.13.13)

Parinzee's repo has sources and patches for the 5.15 and 5.16 kernels, but I am unable to install those (the emerge fails on the camera patch for 5.15 and the wifi patch for 5.16). I can also include a copy of my kernel's .config if that would be helpful.

I've attached a copy the dmesg output as well - hopefully it's something simple that I'm just not noticing.

[dmesg_out.txt](https://github.com/linux-surface/linux-surface/files/8008686/dmesg_out.txt)

Edit: External peripherals work: connecting an external keyboard and mouse work just fine, and libwacom is not installed.

**Comment by CaryRock** [comment]
Updating to 5.16.4 (meant to update to 5.16.8, but 5.16.4 is just as well) resolved the keyboard and the battery issues completely. To do so, all I had to do was delete the camera patch (which probably means the camera doesn't work) in the Gentoo .ebuild. As well, the haptic trackpad now "sort-of" works: it must be clicked down to work (which sends a "LMB click", unfortunately), and then the pointer can be moved around, but it does work (enough - I hear that there may be solutions to this matter related to Apple's trackpads. I will investigate). Perhaps 5.16.8 will actually fix that?

The touchscreen does not work, but I honestly never expected it to, so there's "no issues" there as far as I'm concered today. Marking as closed - thank you all for your patience.

**Comment by qzed** [comment]
> As well, the haptic trackpad now "sort-of" works: it must be clicked down to work (which sends a "LMB click", unfortunately), and then the pointer can be moved around, but it does work (enough - I hear that there may be solutions to this matter related to Apple's trackpads. I will investigate). Perhaps 5.16.8 will actually fix that?

It looks like the driver works since you get some reaction when you press down. So I think this could have to do with it being pressure sensitive, see https://wayland.freedesktop.org/libinput/doc/latest/touchpad-pressure-debugging.html#touchpad-pressure-hwdb on how to debug this.

There's been a discussion about this at https://github.com/linux-surface/linux-surface/issues/596. Not sure if the changes ever made it upstream (ideally libinput would detect the device and load appropriate defaults).

**Comment by CaryRock** [comment]
D'oh! I forgot that the quirks page was there. Thank you for reminding me!

**Comment by qzed** [comment]
> Is there a good way to learn how to even become helpful in maintaining something like this?

I think most of it is just learning by doing and looking at examples, e.g. other kernel code if you want to write a kernel driver or something like this (at least that's how I got into this). Pick something that you think you can/want to improve on and go from there. You only need to be willing to learn (and have the time for all of this, of course).

**Comment by mikebridge** [comment]
@CaryRock I am on an SB3, and after setting up the nvidia drivers I have the same issue where moving my finger on the trackpad doesn't move the mouse any longer, except if I press-and-move.  I can run `sudo libinput debug-gui` and I can see that my touchpad sees mouse movements just fine though.  Were you able to come up with a set of `local-overrides.quirks` that works for you?
