### ISSUE TITLE
 [Help needed] Cannot use wifi in SP3 with Manjaro

### ISSUE THREAD

**Issue by hypghzy** [linux-surface/linux-surface#736]
[Description of the bug or feature]

### Environment

- Hardware model: Surface pro 3
- Kernel version: Kernel 5.16.8-arch1-1-surface
- Distribution: Manjaro Linux 21.2.3 Qonos
- 
### Some outputs that I think could be relevent

[brucehou-surfacepro3 brucehou]# lspci -k
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 09)
        Subsystem: Microsoft Corporation Device 0a04
        Kernel driver in use: hsw_uncore
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
        Subsystem: Microsoft Corporation Device 0005
        Kernel driver in use: i915
        Kernel modules: i915
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 09)
        Subsystem: Intel Corporation Haswell-ULT HD Audio Controller
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
        Subsystem: Microsoft Corporation Device 9c31
        Kernel driver in use: xhci_hcd
        Kernel modules: xhci_pci
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
        Subsystem: Microsoft Corporation Device 9c3a
        Kernel driver in use: mei_me
        Kernel modules: mei_me
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
        Subsystem: Microsoft Corporation Device 9c20
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 3 (rev e4)
        Kernel driver in use: pcieport
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
        Subsystem: Microsoft Corporation Device 9c43
        Kernel driver in use: lpc_ich
        Kernel modules: lpc_ich
00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] (rev 04)
        Subsystem: Microsoft Corporation Device 9c03
        Kernel driver in use: ahci
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
        Subsystem: Microsoft Corporation Device 9c22
        Kernel driver in use: i801_smbus
        Kernel modules: i2c_i801
01:00.0 Ethernet controller: Marvell Technology Group Ltd. 88W8897 [AVASTAR] 802.11ac Wireless
        Subsystem: SafeNet (wrong ID) Device 045e
        Kernel driver in use: mwifiex_pcie
        Kernel modules: mwifiex_pcie
[brucehou-surfacepro3 Downloads]# dmesg | grep mwifiex
[    2.613130] mwifiex_pcie 0000:01:00.0: no quirks enabled
[    2.613232] mwifiex_pcie 0000:01:00.0: enabling device (0000 -> 0002)
[    2.613458] mwifiex_pcie: PCI memory map Virt0: 00000000ab88974e PCI memory map Virt2: 0000000024bb5c13
[    2.620543] mwifiex_pcie 0000:01:00.0: Direct firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
[    2.620551] mwifiex_pcie 0000:01:00.0: Failed to get firmware mrvl/pcie8897_uapsta.bin
[    2.620554] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device
[    2.631575] mwifiex_pcie 0000:01:00.0: performing cancel_work_sync()...
[    2.631580] mwifiex_pcie 0000:01:00.0: cancel_work_sync() done
[brucehou-surfacepro3 Downloads]# modprobe -r mwifiex_pcie
[brucehou-surfacepro3 Downloads]# dmesg | grep mwifiex
[    2.613130] mwifiex_pcie 0000:01:00.0: no quirks enabled
[    2.613232] mwifiex_pcie 0000:01:00.0: enabling device (0000 -> 0002)
[    2.613458] mwifiex_pcie: PCI memory map Virt0: 00000000ab88974e PCI memory map Virt2: 0000000024bb5c13
[    2.620543] mwifiex_pcie 0000:01:00.0: Direct firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
[    2.620551] mwifiex_pcie 0000:01:00.0: Failed to get firmware mrvl/pcie8897_uapsta.bin
[    2.620554] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device
[    2.631575] mwifiex_pcie 0000:01:00.0: performing cancel_work_sync()...
[    2.631580] mwifiex_pcie 0000:01:00.0: cancel_work_sync() done
[brucehou-surfacepro3 Downloads]# modprobe mwifiex_pcie
[brucehou-surfacepro3 Downloads]# dmesg | grep mwifiex
[    2.613130] mwifiex_pcie 0000:01:00.0: no quirks enabled
[    2.613232] mwifiex_pcie 0000:01:00.0: enabling device (0000 -> 0002)
[    2.613458] mwifiex_pcie: PCI memory map Virt0: 00000000ab88974e PCI memory map Virt2: 0000000024bb5c13
[    2.620543] mwifiex_pcie 0000:01:00.0: Direct firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
[    2.620551] mwifiex_pcie 0000:01:00.0: Failed to get firmware mrvl/pcie8897_uapsta.bin
[    2.620554] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device
[    2.631575] mwifiex_pcie 0000:01:00.0: performing cancel_work_sync()...
[    2.631580] mwifiex_pcie 0000:01:00.0: cancel_work_sync() done
[  158.990896] mwifiex_pcie 0000:01:00.0: no quirks enabled
[  158.991500] mwifiex_pcie: PCI memory map Virt0: 000000001ca862df PCI memory map Virt2: 000000001a7b9465
[  158.992551] mwifiex_pcie 0000:01:00.0: Direct firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
[  158.992563] mwifiex_pcie 0000:01:00.0: Failed to get firmware mrvl/pcie8897_uapsta.bin
[  158.992567] mwifiex_pcie 0000:01:00.0: info: _mwifiex_fw_dpc: unregister device
[  158.992905] mwifiex_pcie 0000:01:00.0: performing cancel_work_sync()...
[  158.992912] mwifiex_pcie 0000:01:00.0: cancel_work_sync() done

Appears to be network controller not working. 
The WiFi could work before I upgrade the kernel, and sorry about that I could not recall if it works while the system is freshly installed.
However, based on the outputs of the dmesg, it appears that the mwifie_pcie failed at some point. I tried to search the error message on google but could not find any result close to my situation. 
Any suggestions would be appreciated, thanks

**Comment by qzed** [comment]
I assume that's the same issue as #721 and #723. Arch (and now also Manjaro) split up their firmware package, so you now also have to install `linux-firmware-marvell`.

**Comment by hypghzy** [comment]
> I assume that's the same issue as #721 and #723. Arch (and now also Manjaro) split up their firmware package, so you now also have to install `linux-firmware-marvell`.

Thank you so much for the solution, and sorry for the duplicate asking, I thought I have done my searching, but it appears not  so well done.
 Anyway thanks again, I will close this issue now.
