### ISSUE TITLE
Since 5.16.7-surface resolution 1600x1024 doesn't work anymore on SP7

### ISSUE THREAD

**Issue by Corben78** [linux-surface/linux-surface#737]
Today I got the upgrade to kernel 5.16.7-surface-1. Booting seems normal, I get the login screen, but directly after I logged in, the display stays dark. My user is logged in, I can access the device remotely, even trigger `gnome-session-exit --logout --no-prompt` and see the login screen again.
No issue with the previous kernel 5.15.14-surface

### Environment

- Hardware model: Surface Pro 7
- Kernel version: 5.16.7-surface
- Distribution: Ubuntu 20.04.3 LTS

[dmesg-5.16.7-surface.txt](https://github.com/linux-surface/linux-surface/files/8032504/dmesg-5.16.7-surface.txt)
[dmesg-5.15.14-surface.txt](https://github.com/linux-surface/linux-surface/files/8032507/dmesg-5.15.14-surface.txt)

edit:
When I boot into recovery mode (`Ubuntu, mit Linux 5.16.7-surface (recovery mode)`) I can login, but changing resolution is not possible, and I run my SP7 normally at 1600x1024, so maybe the new kernel is not capable of changing to the configured resolution.
edit 2: confirmed. When I boot the old kernel, set the resolution to native 2736x1824, reboot to the new kernel, I can login normally. As soon as I try to change the resolution to 1600x1024 the screen goes black and I see a segfault in dmesg after a timeout (which reverts to the previous resolution):
```
[  872.012193] gnome-control-c[7950]: segfault at 7fff96f82f98 ip 00007fbfed64fa80 sp 00007fff96f82fa0 error 6 in libc-2.31.so[7fbfed5fb000+178000]
[  872.012203] Code: 89 fb 83 e3 02 0f 85 2f 04 00 00 f3 41 0f 6f 0e 49 8b 46 10 be 25 00 00 00 4c 89 ef 48 89 85 c8 fb ff ff 0f 11 8d b8 fb ff ff <e8> 0b b9 fa ff 41 81 e7 00 80 00 00 c7 85 44 fb ff ff 00 00 00 00
```
Looks like I can set other resolutions, but something is wrong with 1680x1050. My impression is, if I set it to 1680x1050 it is the previous 1600x1024. Maybe enumeration is wrong? All others seem to work like they should, only these two are wrong.

journalctrl shows this when trying to set 1600x1024 from e.g. native resolution:
```
Feb 09 13:42:01 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (EE) modeset(0): failed to set mode: Invalid argument
Feb 09 13:42:01 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Allocate new frame buffer 1600x1024 stride
Feb 09 13:42:01 surfacepro7 gnome-shell[2379]: JS ERROR: TypeError: mmPanelBox is undefined
                                               _popPanel@/home/krummen/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:247:3
                                               _monitorsChanged@/home/krummen/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:201:10
                                               _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:559:14
Feb 09 13:42:01 surfacepro7 gnome-shell[2379]: pi:-1
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): EDID vendor "LGD", prod id 1365
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Using hsync ranges from config file
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Using vrefresh ranges from config file
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Printing DDC gathered Modelines:
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Modeline "2736x1824"x0.0  325.75  2736 2784 2816 2896  1824 1827 1837 1876 -hsync -vsync (112.5 kHz eP)
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): EDID vendor "LGD", prod id 1365
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Using hsync ranges from config file
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Using vrefresh ranges from config file
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Printing DDC gathered Modelines:
Feb 09 13:42:02 surfacepro7 /usr/lib/gdm3/gdm-x-session[2236]: (II) modeset(0): Modeline "2736x1824"x0.0  325.75  2736 2784 2816 2896  1824 1827 1837 1876 -hsync -vsync (112.5 kHz eP)
Feb 09 13:42:02 surfacepro7 gnome-shell[2379]: JS ERROR: TypeError: mmPanelBox is undefined
                                               _popPanel@/home/krummen/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:247:3
                                               _monitorsChanged@/home/krummen/.local/share/gnome-shell/extensions/multi-monitors-add-on@spin83/mmlayout.js:201:10
                                               _monitorsChanged@resource:///org/gnome/shell/ui/layout.js:559:14
Feb 09 13:42:02 surfacepro7 gnome-shell[2379]: Error adding children to desktop: desktopGrid is undefined
Feb 09 13:42:02 surfacepro7 gnome-shell[2379]: Error adding children to desktop: desktopGrid is undefined
Feb 09 13:42:02 surfacepro7 gnome-shell[2379]: Error adding children to desktop: desktopGrid is undefined
Feb 09 13:42:19 surfacepro7 kernel: gnome-control-c[8689]: segfault at 7ffcbca0eff8 ip 00007f46c92b5142 sp 00007ffcbca0f000 error 6 in libc-2.31.so[7f46c9245000+178000]
Feb 09 13:42:19 surfacepro7 kernel: Code: b6 00 48 83 c4 08 5b 5d c3 0f 1f 80 00 00 00 00 e8 b3 bb ff ff eb d1 90 f3 0f 1e fa 48 85 d2 0f 84 63 01 00 00 41 57 49 89 ff <41> 56 49 89 d6 41 55 49 89 d5 41 54 4c 8d 25 4b 77 15 00 55 48 8d
Feb 09 13:42:19 surfacepro7 systemd[2132]: gnome-launched-gnome-control-center.desktop-8689.scope: Succeeded.
```

edit 3:
Today I am using the device at my docking station, and the configuration with 2 additional monitors was still set to 1600x1024 for the internal screen. The two external monitors worked, the internal one stayed dark, and isn't even detected. 1680x1050 is not the previous 1600x1024, it's just close enough not to see a difference at first glance.

**Comment by AlexBMacLeod** [comment]
I have the same problem, it froze after the update, and ever since as soon as I complete login the screen goes black. I'm currently using the computer in recovery mode which works although curiously I tried an older version of the kernel for boot and the screen also went black. I had been using it on recovery mode with the kernel 5.16 but eventually the wifi stopped detecting networks. I'm currently using kernel 5.15.14-surface

**Comment by Corben78** [comment]
No change with kernel 5.16.9-surface. When previously having the device running with a different resolution, 1600x1024 is in the dropdown, but when selecting and activating it, it doesn't work.
Also when it was working (with a different kernel before) and booting into 5.16.{7,9} the internet screen is not detected.

**Comment by enigmabbott** [comment]
i have same problem;
tried:
-rw-r--r--  1 root root  9029880 Feb 17 19:38 vmlinuz-5.16.10-surface
-rw-r--r--  1 root root  9029944 Feb  2 19:07 vmlinuz-5.16.5-surface

rolled back to:
cat /proc/version
Linux version 5.15.14-surface (root@ecefb1fb9e40) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1 SMP Sat Jan 15 02:27:14 UTC 2022

and working again.

**Comment by Corben78** [comment]
Same, when I want the 1600x1024 resolution, I'm back on 5.15.14-surface. For newer kernels 1680x1050 seems to be close enough to 1600x1024 to not make a too much difference. Maybe it's a general problem in 5.16 series kernel and the intel driver. Haven't tried installing a 5.16 kernel from a different source yet.

**Comment by enigmabbott** [comment]
I tried: 5.17.5-surface today; no luck

**Comment by enigmabbott** [comment]
i resolved this today;
5.18.5-surface (and probably earlier versions) is working
sequence:
boot to recovery; then fail safe graphics driver (normal boot) from recovery menu;
i noticed the resolution was different than my 5.15 version;
i booted to 5.15 and set it to the same resolution as the recovery session;
i then was able to boot 5.18.5

**Comment by Corben78** [comment]
Switched today to 5.19.13-surface (#834 seems solved) but still 1600x1024 (3:2) doesn't work. It's detected, it can be selected, but hitting apply turns the screen black and it's not detected anymore.

**Comment by Corben78** [comment]
After updating to Ubuntu 22.04 LTS and kernel 6.2.x I cannot select 1600x1024 from the list anymore. Running now at 1680x1050.
Closing this issue.
