### ISSUE TITLE
Wifi and Bluetooth down (latest kernel 5.16.9)

### ISSUE THREAD

**Issue by chris2052** [linux-surface/linux-surface#742]
`kernel: 5.16.9-arch-1-1-surface`

`DE: GNOME`

Hey all,
as mentioned in the title, I can't access wifi or Bluetooth. In the settings the device can't be found.

**Comment by qzed** [comment]
Arch split their firmware package, meaning you have to install `linux-firmware-marvell`. See https://github.com/linux-surface/linux-surface/issues/721 and https://github.com/linux-surface/linux-surface/issues/723.

**Comment by chris2052** [comment]
Works like a charm! 
Thx mate! <3
