### ISSUE TITLE
Color Profiles and Factory Display Calibration

### ISSUE THREAD

**Issue by perrinpagess** [linux-surface/linux-surface#744]
Would it be possible for factory calibration and color profiles to be supported? Microsoft supports the "Enhanced," "Vivid," and "sRGB" color profiles in windows on various devices with a custom driver called "surface color profile". How does Microsoft implement the factory display calibration? Could the display calibration be fine-tuned (like on the new MacBook pros with XDR display)?

### Environment

- Hardware model:  Surface Laptop 3 (Intel)
- Kernel version:  N/A
- Distribution:  Fedora

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by qzed** [comment]
Sorry for the delayed response. I'm honestly not sure how exactly this is implemented for the Surface or why there is a specific driver for this (probably to automate, but I can only guess). In the driver package for your device (or alternatively on the Windows installation of your device), Microsoft provides `.icm` files (e.g. `Surface_sRGB_Accurate_Template.icm` on the SB2). You should be able to load those on Linux as well. Manual calibration should also work. I'm not entirely sure what software you need user-space wise, but Gnome seems to have decent support for color profiles.

**Comment by qzed** [comment]
Huh, interesting. I did not know that. Thanks!

Yeah I have no idea what's going on on the Windows side with that.
