### ISSUE TITLE
[SGO3] USB-PD charging not possible

### ISSUE THREAD

**Issue by Biont** [linux-surface/linux-surface#751]
Prior to installing Linux, I know for a fact that I have been able to charge my Surface Go 3 via a USB-PD charger. On Linux this is no longer possible. I have a PinePower that tells me that 20volts are negotiated but no current is drawn at all. It just sits there.

### Environment

- Hardware model: Surface Go 3
- Kernel version: `Linux surface 5.16.9-arch1-1-surface #1 SMP PREEMPT Sat, 12 Feb 2022 07:29:08 +0000 x86_64 GNU/Linux`
- Distribution: Arch Linux

Note: I did clear the kernel messages prior to connecting my charger, so I no longer have the full dmesg log, but I can provide one if needed.  However, `dmesg` does not report anything at all when plugging my PinePower.
I'll also happily provide any further information you need to track this down

**Comment by mogorman** [comment]
on my surface go 3 with the https://github.com/linux-surface/linux-surface/blob/master/patches/5.16/0012-misc-fixes.patch I see 20v and a draw of 1amp but it never seems to charge either just maintains the battery when plugged over usb pd.

**Comment by a0193143** [comment]
It seems working now on 6.x kernels, at least it could charged from Xiaomi PD chager.

**Comment by Biont** [comment]
I also have not experienced any issues in recent weeks.
