### ISSUE TITLE
patches fail with plain linux kernel

### ISSUE THREAD

**Issue by supertomi** [linux-surface/linux-surface#755]
I try to use the resent patches with a plain linux-5.16.11 kernel from kernel.org. Since a few month, the camera.patch fails to apply. But today, nearly all pacthes fail.

### Environment

recent Gentoo Linux, but original kernel fom kernel.org without modifications/patches

- Hardware model: Surface Pro 6
- Kernel version: 5.16.11
- Distribution: Gentoo, original kernel from kernel.org

<details><summary>`dmesg` output</summary>

for i in /usr/src/linux-surface-fedora-35-5.16.11-1/patches/5.16/00*; do patch -p1 --dry-run < $i; done 2>&1 >  patchfehler

cat patchfehler

checking file sound/soc/intel/common/soc-acpi-intel-cht-match.c
checking file drivers/net/wireless/marvell/mwifiex/pcie.c
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
Hunk #1 succeeded at 87 with fuzz 2 (offset -19 lines).
checking file drivers/net/wireless/marvell/mwifiex/pcie.c
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
Hunk #1 succeeded at 27 (offset -11 lines).
Hunk #2 succeeded at 37 (offset -11 lines).
Hunk #3 succeeded at 47 (offset -11 lines).
Hunk #4 succeeded at 56 (offset -11 lines).
Hunk #5 succeeded at 65 (offset -11 lines).
Hunk #6 succeeded at 74 (offset -11 lines).
Hunk #7 succeeded at 83 (offset -11 lines).
Hunk #8 succeeded at 92 with fuzz 2 (offset -11 lines).
Hunk #9 FAILED at 142.
1 out of 9 hunks FAILED
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
Hunk #1 FAILED at 23.
1 out of 1 hunk FAILED
checking file drivers/net/wireless/marvell/mwifiex/pcie.c
Hunk #1 succeeded at 1774 (offset -7 lines).
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.c
Hunk #1 FAILED at 39.
Hunk #2 FAILED at 49.
Hunk #3 FAILED at 59.
Hunk #4 FAILED at 68.
Hunk #5 FAILED at 77.
Hunk #6 FAILED at 86.
Hunk #7 FAILED at 95.
Hunk #8 FAILED at 104.
Hunk #9 FAILED at 145.
9 out of 9 hunks FAILED
checking file drivers/net/wireless/marvell/mwifiex/pcie_quirks.h
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED
checking file drivers/bluetooth/btusb.c
Hunk #1 succeeded at 60 with fuzz 2 (offset -1 lines).
Hunk #2 succeeded at 357 (offset -19 lines).
Hunk #3 succeeded at 3864 (offset -46 lines).
checking file drivers/net/wireless/marvell/mwifiex/pcie.c
checking file drivers/net/wireless/marvell/mwifiex/main.c
checking file drivers/net/wireless/marvell/mwifiex/main.h
checking file drivers/net/wireless/marvell/mwifiex/sta_cmdresp.c
checking file drivers/net/wireless/marvell/mwifiex/sta_event.c
Hunk #1 succeeded at 1057 (offset -4 lines).
checking file drivers/net/wireless/ath/ath10k/core.c
Hunk #4 succeeded at 835 (offset -17 lines).
Hunk #5 succeeded at 885 (offset -17 lines).
checking file drivers/misc/mei/hw-me-regs.h
checking file drivers/misc/mei/pci-me.c
checking file drivers/misc/Kconfig
checking file drivers/misc/Makefile
checking file drivers/misc/ipts/Kconfig
checking file drivers/misc/ipts/Makefile
checking file drivers/misc/ipts/context.h
checking file drivers/misc/ipts/control.c
checking file drivers/misc/ipts/control.h
checking file drivers/misc/ipts/mei.c
checking file drivers/misc/ipts/protocol.h
checking file drivers/misc/ipts/receiver.c
checking file drivers/misc/ipts/receiver.h
checking file drivers/misc/ipts/resources.c
checking file drivers/misc/ipts/resources.h
checking file drivers/misc/ipts/uapi.c
checking file drivers/misc/ipts/uapi.h
checking file drivers/platform/surface/aggregator/bus.c
checking file drivers/platform/surface/aggregator/bus.h
checking file drivers/platform/surface/aggregator/core.c
checking file include/linux/surface_aggregator/device.h
checking file drivers/platform/surface/surface_aggregator_registry.c
checking file drivers/platform/surface/surface_aggregator_registry.c
Hunk #1 succeeded at 297 (offset 14 lines).
Hunk #2 succeeded at 412 with fuzz 2 (offset 14 lines).
Hunk #3 succeeded at 611 (offset 14 lines).
checking file drivers/platform/surface/aggregator/bus.c
Hunk #1 succeeded at 396 with fuzz 2 (offset 8 lines).
checking file include/linux/surface_aggregator/device.h
checking file Documentation/driver-api/surface_aggregator/client.rst
checking file drivers/platform/surface/aggregator/controller.c
checking file include/linux/surface_aggregator/controller.h
checking file include/linux/surface_aggregator/device.h
Hunk #1 succeeded at 421 (offset -51 lines).
checking file drivers/platform/surface/surface_aggregator_registry.c
Hunk #1 succeeded at 482 (offset 14 lines).
Hunk #2 succeeded at 494 with fuzz 2 (offset 14 lines).
Hunk #3 succeeded at 506 with fuzz 2 (offset 14 lines).
checking file drivers/power/supply/surface_charger.c
checking file drivers/power/supply/surface_battery.c
checking file drivers/hid/surface-hid/surface_hid_core.c
checking file include/linux/surface_aggregator/serial_hub.h
checking file drivers/platform/surface/surface_aggregator_registry.c
Hunk #1 succeeded at 528 (offset 14 lines).
Hunk #2 succeeded at 881 (offset 14 lines).
checking file drivers/platform/surface/surface_aggregator_registry.c
checking file MAINTAINERS
checking file drivers/platform/surface/Kconfig
checking file drivers/platform/surface/Makefile
checking file drivers/platform/surface/surface_kip_tablet_switch.c
checking file drivers/platform/surface/surface_aggregator_registry.c
Hunk #1 succeeded at 71 (offset -6 lines).
Hunk #2 FAILED at 270.
1 out of 2 hunks FAILED
checking file drivers/i2c/i2c-core-acpi.c
checking file drivers/platform/surface/Kconfig
checking file drivers/platform/surface/Makefile
checking file drivers/platform/surface/surfacebook1_dgpu_switch.c
checking file drivers/platform/surface/surface_gpe.c
checking file drivers/input/misc/soc_button_array.c
checking file drivers/platform/surface/surfacepro3_button.c
checking file drivers/hid/hid-multitouch.c
checking file drivers/media/pci/intel/ipu3/ipu3-cio2-main.c
checking file MAINTAINERS
Hunk #1 succeeded at 14111 (offset -6 lines).
checking file drivers/media/i2c/Kconfig
checking file drivers/media/i2c/Makefile
checking file drivers/media/i2c/ov5693.c
can't find file to patch at input line 1727
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.35.1
|
|From 5d5e9ba6d1129453c3167128789c67015e7cba29 Mon Sep 17 00:00:00 2001
|From: Daniel Scally <djrscally@gmail.com>
|Date: Thu, 20 May 2021 23:31:04 +0100
|Subject: [PATCH] media: i2c: Fix vertical flip in ov5693
|
|The pinkness experienced by users with rotated sensors in their laptops
|was due to an incorrect setting for the vertical flip function; the
|datasheet for the sensor gives the settings as bits 1&2 in one place and
|bits 1&6 in another.
|
|Switch to flipping bit 6 instead of bit 2 for 0x3820 in the vertical
|flip function to fix the pink hue.
|
|Signed-off-by: Daniel Scally <djrscally@gmail.com>
|Patchset: cameras
|---
| drivers/media/i2c/ov5693.c | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/drivers/media/i2c/ov5693.c b/drivers/media/i2c/ov5693.c
|index 9499ee10f56c..c558f9b48c83 100644
|--- a/drivers/media/i2c/ov5693.c
|+++ b/drivers/media/i2c/ov5693.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
checking file drivers/media/i2c/ov8865.c
Hunk #2 succeeded at 2947 (offset -4 lines).
Hunk #3 succeeded at 2963 (offset -4 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 712 (offset -1 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 2795 (offset -3 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 20 (offset -1 lines).
Hunk #2 succeeded at 562 (offset -1 lines).
Hunk #3 succeeded at 649 (offset -1 lines).
Hunk #4 succeeded at 677 (offset -1 lines).
Hunk #5 FAILED at 696.
Hunk #6 succeeded at 740 (offset -1 lines).
Hunk #7 succeeded at 966 (offset -1 lines).
Hunk #8 succeeded at 1020 (offset -1 lines).
Hunk #9 succeeded at 1078 (offset -1 lines).
Hunk #10 succeeded at 1142 (offset -1 lines).
Hunk #11 succeeded at 1537 (offset -1 lines).
Hunk #12 succeeded at 1575 (offset -1 lines).
Hunk #13 succeeded at 1647 (offset -1 lines).
Hunk #14 succeeded at 1686 (offset -1 lines).
Hunk #15 succeeded at 2081 (offset -1 lines).
Hunk #16 succeeded at 2813 (offset -3 lines).
Hunk #17 succeeded at 2891 (offset -1 lines).
1 out of 17 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 453 (offset 3 lines).
Hunk #2 succeeded at 2706 (offset -61 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 2082 (offset -68 lines).
Hunk #2 succeeded at 2392 (offset -70 lines).
Hunk #3 succeeded at 2438 (offset -70 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 186 (offset 3 lines).
Hunk #2 succeeded at 654 (offset -23 lines).
Hunk #3 succeeded at 2160 (offset -68 lines).
Hunk #4 succeeded at 2425 (offset -70 lines).
Hunk #5 succeeded at 2443 (offset -70 lines).
Hunk #6 succeeded at 2480 (offset -71 lines).
Hunk #7 succeeded at 2667 (offset -71 lines).
Hunk #8 succeeded at 2919 (offset -150 lines).
checking file drivers/media/i2c/ov8865.c
Hunk #1 FAILED at 677.
Hunk #2 FAILED at 2515.
Hunk #3 FAILED at 2552.
Hunk #4 succeeded at 2599 (offset -99 lines).
Hunk #5 succeeded at 2640 with fuzz 2 (offset -103 lines).
3 out of 5 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 FAILED at 659.
Hunk #2 succeeded at 890 (offset -74 lines).
Hunk #3 succeeded at 929 with fuzz 2 (offset -74 lines).
Hunk #4 succeeded at 943 (offset -72 lines).
Hunk #5 succeeded at 982 with fuzz 2 (offset -72 lines).
Hunk #6 succeeded at 1039 with fuzz 2 (offset -70 lines).
Hunk #7 succeeded at 1102 with fuzz 2 (offset -68 lines).
Hunk #8 succeeded at 2510 (offset -108 lines).
Hunk #9 FAILED at 2774.
Hunk #10 FAILED at 2867.
3 out of 10 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 FAILED at 677.
Hunk #2 succeeded at 2382 (offset -74 lines).
Hunk #3 succeeded at 2446 (offset -79 lines).
Hunk #4 succeeded at 2613 with fuzz 2 (offset -102 lines).
Hunk #5 succeeded at 2653 with fuzz 2 (offset -110 lines).
1 out of 5 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 FAILED at 2515.
Hunk #2 succeeded at 2470 (offset -108 lines).
1 out of 2 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 2066 (offset -59 lines).
Hunk #2 FAILED at 2530.
1 out of 2 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 2792 (offset -165 lines).
Hunk #2 succeeded at 2844 (offset -163 lines).
checking file drivers/media/pci/intel/ipu3/cio2-bridge.c
checking file drivers/acpi/scan.c
Hunk #2 succeeded at 1768 (offset -7 lines).
Hunk #3 succeeded at 1977 (offset -7 lines).
Hunk #4 succeeded at 1986 (offset -7 lines).
Hunk #5 succeeded at 2000 (offset -7 lines).
Hunk #6 succeeded at 2088 (offset -7 lines).
Hunk #7 succeeded at 2333 (offset -7 lines).
checking file include/acpi/acpi_bus.h
Hunk #3 succeeded at 695 (offset -1 lines).
checking file drivers/i2c/i2c-core-acpi.c
checking file include/linux/platform_data/tps68470.h
checking file drivers/regulator/Kconfig
checking file drivers/regulator/Makefile
checking file drivers/regulator/tps68470-regulator.c
checking file drivers/clk/Kconfig
checking file drivers/clk/Makefile
checking file drivers/clk/clk-tps68470.c
checking file include/linux/mfd/tps68470.h
checking file drivers/platform/x86/intel/int3472/intel_skl_int3472_tps68470.c
checking file drivers/platform/x86/intel/int3472/Makefile
checking file drivers/platform/x86/intel/int3472/clk_and_regulator.c (renamed from drivers/platform/x86/intel/int3472/intel_skl_int3472_clk_and_regulator.c)
checking file drivers/platform/x86/intel/int3472/common.c
checking file drivers/platform/x86/intel/int3472/common.h (renamed from drivers/platform/x86/intel/int3472/intel_skl_int3472_common.h)
checking file drivers/platform/x86/intel/int3472/discrete.c (renamed from drivers/platform/x86/intel/int3472/intel_skl_int3472_discrete.c)
checking file drivers/platform/x86/intel/int3472/tps68470.c (renamed from drivers/platform/x86/intel/int3472/intel_skl_int3472_tps68470.c)
Hunk #2 succeeded at 95 (offset -7 lines).
Hunk #3 succeeded at 135 (offset -7 lines).
can't find file to patch at input line 4257
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.35.1
|
|From 4b1748be137eb2ebc5233a292bf603834e5da499 Mon Sep 17 00:00:00 2001
|From: Hans de Goede <hdegoede@redhat.com>
|Date: Sun, 10 Oct 2021 20:57:04 +0200
|Subject: [PATCH] platform/x86: int3472: Add get_sensor_adev_and_name() helper
|
|The discrete.c code is not the only code which needs to lookup the
|acpi_device and device-name for the sensor for which the INT3472
|ACPI-device is a GPIO/clk/regulator provider.
|
|The tps68470.c code also needs this functionality, so factor this
|out into a new get_sensor_adev_and_name() helper.
|
|Signed-off-by: Hans de Goede <hdegoede@redhat.com>
|Patchset: cameras
|---
| drivers/platform/x86/intel/int3472/common.c   | 28 +++++++++++++++++++
| drivers/platform/x86/intel/int3472/common.h   |  3 ++
| drivers/platform/x86/intel/int3472/discrete.c | 22 +++------------
| 3 files changed, 35 insertions(+), 18 deletions(-)
|
|diff --git a/drivers/platform/x86/intel/int3472/common.c b/drivers/platform/x86/intel/int3472/common.c
|index 350655a9515b..77cf058e4168 100644
|--- a/drivers/platform/x86/intel/int3472/common.c
|+++ b/drivers/platform/x86/intel/int3472/common.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 4293
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/drivers/platform/x86/intel/int3472/common.h b/drivers/platform/x86/intel/int3472/common.h
|index d14944ee8586..53270d19c73a 100644
|--- a/drivers/platform/x86/intel/int3472/common.h
|+++ b/drivers/platform/x86/intel/int3472/common.h
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 4307
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/drivers/platform/x86/intel/int3472/discrete.c b/drivers/platform/x86/intel/int3472/discrete.c
|index a19a1f5dbdd7..efd31a0c7a88 100644
|--- a/drivers/platform/x86/intel/int3472/discrete.c
|+++ b/drivers/platform/x86/intel/int3472/discrete.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 4365
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.35.1
|
|From 7f3f98ee521fe6817bebe14ab6f8aace8b5175dd Mon Sep 17 00:00:00 2001
|From: Hans de Goede <hdegoede@redhat.com>
|Date: Sun, 10 Oct 2021 20:57:05 +0200
|Subject: [PATCH] platform/x86: int3472: Pass tps68470_clk_platform_data to the
| tps68470-regulator MFD-cell
|
|Pass tps68470_clk_platform_data to the tps68470-clk MFD-cell,
|so that sensors which use the TPS68470 can find their clock.
|
|Signed-off-by: Hans de Goede <hdegoede@redhat.com>
|Patchset: cameras
|---
| drivers/platform/x86/intel/int3472/tps68470.c | 33 ++++++++++++++-----
| 1 file changed, 25 insertions(+), 8 deletions(-)
|
|diff --git a/drivers/platform/x86/intel/int3472/tps68470.c b/drivers/platform/x86/intel/int3472/tps68470.c
|index b94cf66ab61f..78e34e7b6969 100644
|--- a/drivers/platform/x86/intel/int3472/tps68470.c
|+++ b/drivers/platform/x86/intel/int3472/tps68470.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
4 out of 4 hunks ignored
checking file drivers/platform/x86/intel/int3472/Makefile
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED
can't find file to patch at input line 4477
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/drivers/platform/x86/intel/int3472/tps68470.c b/drivers/platform/x86/intel/int3472/tps68470.c
|index 78e34e7b6969..aae24d228770 100644
|--- a/drivers/platform/x86/intel/int3472/tps68470.c
|+++ b/drivers/platform/x86/intel/int3472/tps68470.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
6 out of 6 hunks ignored
checking file drivers/platform/x86/intel/int3472/tps68470.h
checking file drivers/platform/x86/intel/int3472/tps68470_board_data.c
can't find file to patch at input line 4780
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.35.1
|
|From 971a45456d79b8ff8f7eddbb81852aed26ab3059 Mon Sep 17 00:00:00 2001
|From: Hans de Goede <hdegoede@redhat.com>
|Date: Sun, 10 Oct 2021 20:57:07 +0200
|Subject: [PATCH] platform/x86: int3472: Deal with probe ordering issues
|
|The clk and regulator frameworks expect clk/regulator consumer-devices
|to have info about the consumed clks/regulators described in the device's
|fw_node.
|
|To work around this info missing from the ACPI tables on devices where
|the int3472 driver is used, the int3472 MFD-cell drivers attach info about
|consumers to the clks/regulators when registering these.
|
|This causes problems with the probe ordering wrt drivers for consumers
|of these clks/regulators. Since the lookups are only registered when the
|provider-driver binds, trying to get these clks/regulators before then
|results in a -ENOENT error for clks and a dummy regulator for regulators.
|
|All the sensor ACPI fw-nodes have a _DEP dependency on the INT3472 ACPI
|fw-node, so to work around these probe ordering issues the ACPI core /
|i2c-code does not instantiate the I2C-clients for any ACPI devices
|which have a _DEP dependency on an INT3472 ACPI device until all
|_DEP-s are met.
|
|This relies on acpi_dev_clear_dependencies() getting called by the driver
|for the _DEP-s when they are ready, add a acpi_dev_clear_dependencies()
|call to the discrete.c probe code.
|
|In the tps68470 case calling acpi_dev_clear_dependencies() is already done
|by the acpi_gpiochip_add() call done by the driver for the GPIO MFD cell
|(The GPIO cell is deliberately the last cell created to make sure the
|clk + regulator cells are already instantiated when this happens).
|
|However for proper probe ordering, the clk/regulator cells must not just
|be instantiated the must be fully ready (the clks + regulators must be
|registered with their subsystems).
|
|Add MODULE_SOFTDEP dependencies for the clk and regulator drivers for
|the instantiated MFD-cells so that these are loaded before us and so
|that they bind immediately when the platform-devs are instantiated.
|
|Signed-off-by: Hans de Goede <hdegoede@redhat.com>
|Patchset: cameras
|---
| drivers/platform/x86/intel/int3472/discrete.c | 1 +
| drivers/platform/x86/intel/int3472/tps68470.c | 6 ++++++
| 2 files changed, 7 insertions(+)
|
|diff --git a/drivers/platform/x86/intel/int3472/discrete.c b/drivers/platform/x86/intel/int3472/discrete.c
|index efd31a0c7a88..18e6d51acc96 100644
|--- a/drivers/platform/x86/intel/int3472/discrete.c
|+++ b/drivers/platform/x86/intel/int3472/discrete.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 4792
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/drivers/platform/x86/intel/int3472/tps68470.c b/drivers/platform/x86/intel/int3472/tps68470.c
|index aae24d228770..21c6c1a6edfc 100644
|--- a/drivers/platform/x86/intel/int3472/tps68470.c
|+++ b/drivers/platform/x86/intel/int3472/tps68470.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored                                                                                                                                         10:50:50
checking file drivers/media/i2c/ov8865.c
Hunk #1 succeeded at 146 (offset 3 lines).
Hunk #2 FAILED at 2465.
1 out of 2 hunks FAILED
checking file drivers/media/i2c/ov8865.c
Hunk #1 FAILED at 2537.
1 out of 1 hunk FAILED
checking file drivers/mfd/intel-lpss-pci.c
checking file drivers/mfd/intel-lpss.c
checking file drivers/mfd/intel-lpss.h
can't find file to patch at input line 5010
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|-- 
|2.35.1
|
|From 0fb2088a6ba9d3e1faae7ac54a950780a9a81a88 Mon Sep 17 00:00:00 2001
|From: Daniel Scally <djrscally@gmail.com>
|Date: Thu, 6 Jan 2022 22:12:38 +0000
|Subject: [PATCH] platform/x86: int3472: Add board data for Surface Go 3
|
|The Surface Go 3 needs some board data in order to configure the
|TPS68470 PMIC - add entries to the tables in tps68470_board_data.c
|that define the configuration that's needed.
|
|Signed-off-by: Daniel Scally <djrscally@gmail.com>
|Patchset: cameras
|---
| .../x86/intel/int3472/tps68470_board_data.c         | 13 +++++++++++++
| 1 file changed, 13 insertions(+)
|
|diff --git a/drivers/platform/x86/intel/int3472/tps68470_board_data.c b/drivers/platform/x86/intel/int3472/tps68470_board_data.c
|index 96954a789bb8..2dcadfa62196 100644
|--- a/drivers/platform/x86/intel/int3472/tps68470_board_data.c
|+++ b/drivers/platform/x86/intel/int3472/tps68470_board_data.c
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
2 out of 2 hunks ignored
checking file arch/x86/kernel/acpi/boot.c
checking file arch/x86/kernel/acpi/boot.c
Hunk #1 FAILED at 1155.
1 out of 1 hunk FAILED
checking file drivers/acpi/battery.c
Hunk #1 succeeded at 59 (offset -1 lines).
Hunk #2 succeeded at 1159 with fuzz 1 (offset -22 lines).
checking file drivers/acpi/battery.c
Hunk #1 succeeded at 1146 with fuzz 2 (offset -35 lines).
checking file drivers/platform/surface/surface3_power.c

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by qzed** [comment]
All patches in `patches/v5.16` should apply cleanly to v5.16.11 via `git am` or similar commands.
