### ISSUE TITLE
linux-firmware package 20220119 update breaks WiFi support on Surfaces with Marvell network devices

### ISSUE THREAD

**Issue by mwallner** [linux-surface/linux-surface#759]
### Problem
After doing a `-Syyuu` WiFi and Bluetooth stopped working.

### Environment

- Hardware model: Surface Book 2
- Kernel version: 5.16.11-arch1-1-surface
- Distribution: Manjaro

### It is known...

see [this post on reddit](https://www.reddit.com/r/SurfaceLinux/comments/sakujr/sp3_arch_linuxfirmware_package_20220119_update/)
or [this arch news article](https://archlinux.org/news/linux-firmware-202201190c6a7b3-2-requires-kernel-53-and-package-splitting/)

you have this problem if you run `sudo dmesg | grep mwifiex` and see something like this:
```
[    4.752743] mwifiex_pcie 0000:01:00.0: Direct firmware load for mrvl/pcie8897_uapsta.bin failed with error -2
[    4.752749] mwifiex_pcie 0000:01:00.0: Failed to get firmware mrvl/pcie8897_uapsta.bin
```

### Solution

Install the `linux-firmware-marvell` package, reload the module
```
sudo pacman -S linux-firmware-marvell
sudo modprobe -r mwifiex_pcie && sudo modprobe mwifiex_pcie
```

**Comment by ProgrammerIn-wonderland** [comment]
+1 
I am using a Microsoft Surface Book OG, I have this issue, and can confirm the solution works

**Comment by qzed** [comment]
See also #742, #723, and 721.

**Comment by papersomeok** [comment]
the reload was the big one. I'm not sure why a reboot didn't count. but BT works again post reinstall
