### ISSUE TITLE
Surface Book 1 does not detect dedicated NVIDIA GPU 

### ISSUE THREAD

**Issue by beshad** [linux-surface/linux-surface#770]
hi all, 

it doesn't matter what i do i just can't get my SB1 to detect the dedicated GPU inside the keyboard base. i have installed: 
`sudo apt install nvidia-utils-470 nvidia-driver-470 nvidia-dkms-470`
as well as surface-control

`$ nvidia-smi`
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`
`$ sudo surface dgpu set on`
`Error: No discrete GPU found`

what am i missing here? kernel is 5.16.13-surface on Ubuntu 21.10

thanks

**Comment by qzed** [comment]
The dGPU on the SB1 unfortunately requires running some commands to be detected (or rather, power it on or off). Have a look at https://github.com/linux-surface/linux-surface/wiki/Surface-Book#controlling-dgpu-power-state. If you want to know more details, we have https://github.com/linux-surface/linux-surface/issues/93 as an issue for that.
