### ISSUE TITLE
Battery only charges to 50%

### ISSUE THREAD

**Issue by ZhiyuanChen** [linux-surface/linux-surface#772]
Battery only charges to 50%

### Environment

- Hardware model: Surface Book 3
- Kernel version: 5.16.13-surface #1 SMP PREEMPT Fri Mar 11 01:08:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Ubuntu 20.04

**Comment by qzed** [comment]
This sounds like you have the battery limit enabled in UEFI. Can you check that?

**Comment by ZhiyuanChen** [comment]
> This sounds like you have the battery limit enabled in UEFI. Can you check that?

I check UEFI twice and there doesn't seems to be a batter limit option :(

**Comment by ZhiyuanChen** [comment]
Sorry, apparently there is one options namely `enable battery limit` in the boot config of UEFI. It is a bit misleading and I trurned it on wrongly.
