### ISSUE TITLE
Temporary failure resolving 'pkg.surfacelinux.com'

### ISSUE THREAD

**Issue by curiosorwhat** [linux-surface/linux-surface#775]
trying to install surfacelinux on Tails 4.28 (Debian, buster) to run on a MS Surface Pro 4. Without it, the touchscreen and Bluethooth don't work but Tails does operate via external keyboard and a mouse.

Following the instructions here

echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" | sudo tee /etc/apt/sources.list.d/linux-surface.list
sudo apt update

then the following error will get me stuck:
Failed to fetch https://pkg.surfacelinux.com/debian/dists/release/InRelease  
Temporary failure resolving 'pkg.surfacelinux.com'

Any suggestion how to fix this?

thanks

**Comment by StollD** [comment]
Works for me. Can you resolve other servers? What happens if you run `ping tmsp.io`, does that work? (tmsp.io is the same server, but both domains run through different DNS)

**Comment by curiosorwhat** [comment]
Ok, thanks. That ping did not work either! So, me working with Tails I'm on the Tor network which generates those problems. I found I have to modify the command like this:

echo "deb [arch=amd64] tor+https://pkg.surfacelinux.com/debian release main" | sudo tee /etc/apt/sources.list.d/linux-surface.list

adding the "tor" before the https://. Then this works.

But now I get the next problem. When calling:

sudo apt install linux-image-surface linux-headers-surface iptsd libwacom-surface

I get a lot of 401 errors like this one here:

Err:1 tor+https://pkg.surfacelinux.com/debian release/main amd64 libwacom-surface amd64 1.12.1-3
  401  Unauthorized [IP: 127.0.0.1 9050]

I found issue # 625 talking about same problems but there are "endless" discussions. Any quick suggestion what I shoudl try? I assume its again because I'm coming from Tor. Is there a way to download these packages with a non Tor PC and then install them on my surface, running Tails in "offline" mode? Any link of how to do that?

Thanks

**Comment by qzed** [comment]
> I assume its again because I'm coming from Tor.

Nope, it's a bug in APT. See https://github.com/linux-surface/linux-surface/issues/625 for a workaround. Alternative is using a newer distro, where this bug has been fixed (anything based on Ubuntu 21.04 upwards I think, or comparable Debian versions). I should probably add this to the FAQ and install section...
