### ISSUE TITLE
Touchscreen don't work if hard touch it

### ISSUE THREAD

**Issue by zccrs** [linux-surface/linux-surface#781]
[Description of the bug or feature]

Does it work if you don't press the touchscreen hard, just lightly touch it with your finger? I had a similar problem, as long as I press the screen with a little force, I can't get touch events unless I reduce the pressure 

### Environment

- Hardware model: Surface Pro 6
- Kernel version: Linux zccrs 5.16.17-surface #1 SMP PREEMPT Thu Mar 24 20:44:13 UTC 2022 x86_64 GNU/Linux
- Distribution: Debian
- Iptsd version: 0.5-1

`dmesg` output: [dmesg.log](https://github.com/linux-surface/linux-surface/files/8357067/dmesg.log)

**Comment by yatli** [comment]
Similar problem on SB3, the workaround is to edit `/etc/ipts.conf` and enable advanced processing:

```
[Touch]
## Whether iptsd will ignore very fast moving touches.
# Stability = true

## The touch processor to use. Basic should give a good
## overall experience. Advanced might offer a bit better
## finger detection, but its palm detection is still rough.
Processing = advanced
```

I guess if we press too hard it thinks it's a palm not a finger.

**Comment by zccrs** [comment]
> Similar problem on SB3, the workaround is to edit `/etc/ipts.conf` and enable advanced processing:
> 
> ```
> [Touch]
> ## Whether iptsd will ignore very fast moving touches.
> # Stability = true
> 
> ## The touch processor to use. Basic should give a good
> ## overall experience. Advanced might offer a bit better
> ## finger detection, but its palm detection is still rough.
> Processing = advanced
> ```
> 
> I guess if we press too hard it thinks it's a palm not a finger. Wondering if there's a way to tweak it as different screens may have different "gain levels". On SB3 with basic processing, I had to very gently touch it or otherwise it doesn't register.

Thanks. I'am try it, but it's not any changes. Maybe the "Processing = advanced" is not supported the surface pro 6

**Comment by ChengduLittleA** [comment]
eh my case exactly https://github.com/linux-surface/linux-surface/issues/925

**Comment by zccrs** [comment]
I can't reproduction this issue on 6.2.2-surface
