### ISSUE TITLE
Provide a newer version of libwacom-surface for debian testing

### ISSUE THREAD

**Issue by quank123wip** [linux-surface/linux-surface#783]
### Environment

- Hardware model: Surface Pro 5
- Kernel version: ```Linux penguin 5.16.17-surface #1 SMP PREEMPT Thu Mar 24 20:44:13 UTC 2022 x86_64 GNU/Linux```
- Distribution: Debian Testing

The Debian testing channel is already using libwacom-2.1.0, installing libwacom-surface will break the dependency.

**Comment by berggggg** [comment]
seconding this, can't figure out how to get my pen to work on a SB3.

**Comment by qzed** [comment]
I'm a bit busy right now but I'll have a look at that once I got some more time on my hands.

**Comment by qzed** [comment]
Okay, I've updated libwacom. We now have several split packages (see https://github.com/linux-surface/libwacom-surface/releases/tag/v2.2.0). This includes packages for libwacom-1.x and libwacom-2.x libraries, so hopefully everything works now across all Debian/Ubuntu versions.

**Comment by therealdandecker** [comment]
Thanks - just to make sure I understand, is this package update in the kernel or does this need to be installed separately?

**Comment by qzed** [comment]
It's in the repo. Assuming you have the repo set up, running `sudo apt install libwacom-surface` should install it.

**Comment by mcmufffin** [comment]
Fedora 36 seem to also require libwacom2 now. Any chance we might see this happening? I replaced with default libwacom2 from fedora repo for now, upgrade from F35 to F36 is still in progress. Lets see how this works :)

**Comment by qzed** [comment]
F36 should already have version 2.2.0. See e.g. https://github.com/linux-surface/libwacom-surface/releases/tag/v2.2.0-2 for `fc36` packages.

**Comment by ruralTom** [comment]
Is libwacom only needed for certain devices? I don't see it on my sp3

May 5, 2022 12:14:38 PM Maximilian Luz ***@***.***>:

**Comment by qzed** [comment]
> Is libwacom only needed for certain devices? I don't see it on my sp3

libwacom tells desktop environments such as Gnome whether the display is built in or not. That then is used for rotation. So depending on the desktop env, it's required for any device that has a built-in touchscreen to correctly handle rotation of that.

**Comment by qzed** [comment]
Closing as this should be fixed.
