### ISSUE TITLE
Battery charging till 49%

### ISSUE THREAD

**Issue by LinuxNewbie101** [linux-surface/linux-surface#79]
Now i have the special kernel 5.3.18-surface. Everthing works fine, but there is one problem left: my battery is only charging till 49%(or at least only displays 49%). someone know something about that issue?
**Environment**
Hardware model: Surface Pro Laptop 6, Kernel version: 5.3.18-surface, Distribution: Linux Mint 19.3

**Comment by kitakar5525** [comment]
Check "Battery Limit Mode" setting on Surface UEFI: https://docs.microsoft.com/en-us/surface/battery-limit

**Comment by LinuxNewbie101** [comment]
Wow that worked 👍🏻 Thank you very much!!
