### ISSUE TITLE
keyboard battery warning with touch pen/stylus

### ISSUE THREAD

**Issue by dr-ni** [linux-surface/linux-surface#791]
Using the touch pen prompts a "keyboard battery is low" warning

- Hardware model: surface go2 + original surface keyboard
- Kernel version: 5.16.17-surface
- Distribution: ubuntu mate 21.10

```
uwe@go2:~$ upower --dump 
Device: /org/freedesktop/UPower/devices/line_power_ACAD
  native-path:          ACAD
  power supply:         yes
  updated:              Sa 16 Apr 2022 11:34:14 CEST (9526 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              no
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT1
  native-path:          BAT1
  vendor:               DYN
  model:                Uhu
  serial:               3
  power supply:         yes
  updated:              Sa 16 Apr 2022 14:12:15 CEST (45 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              18,2461 Wh
    energy-empty:        0 Wh
    energy-full:         26,0593 Wh
    energy-full-design:  26,81 Wh
    energy-rate:         1,915 W
    voltage:             7,906 V
    time to empty:       9,5 hours
    percentage:          71%
    capacity:            97,2%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
  History (rate):
    1650111135	1,915	discharging

Device: /org/freedesktop/UPower/devices/keyboard_hid_0018o04F3o2A1Cx0001_battery
  native-path:          hid-0018:04F3:2A1C.0001-battery
  model:                ELAN9038:00 04F3:2A1C
  power supply:         no
  updated:              Sa 16 Apr 2022 14:12:22 CEST (38 seconds ago)
  has history:          yes
  has statistics:       yes
  keyboard
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    percentage:          1%
    icon-name:          'battery-caution-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              Sa 16 Apr 2022 14:12:15 CEST (45 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               discharging
    warning-level:       none
    energy:              18,2461 Wh
    energy-full:         26,0593 Wh
    energy-rate:         1,915 W
    time to empty:       9,5 hours
    percentage:          71%
    icon-name:          'battery-full-symbolic'

Daemon:
  daemon-version:  0.99.5
  on-battery:      yes
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: HybridSleep
```

- Why is this warning triggered when using the pen/stylus?
- Why is upower reporting a keyboard battery discharge whithout an existing battery?

My workaround:
I've made an upower fork which is suppressing the warning since the keyboard has no battery
https://github.com/dr-ni/upower_no_keyboard_batt_warning.git

**Comment by JulianHeuser** [comment]
I'm having the same issue with the Surface Go 3, Ubuntu 21.10, same kernel version.

I'm not using bluetooth to connect it so it triggers when I first put the pen tip close enough to the screen for it to register.

**Comment by JulianHeuser** [comment]
Just to consolidate everything related to this, the same issue is mentioned in #771 
I have the same device name (ELAN9038:00 04F3:2A1C) listed for the standard surface pen.

**Comment by qzed** [comment]
> * Why is this warning triggered when using the pen/stylus?
> 
> * Why is upower reporting a keyboard battery discharge whithout an existing battery?

Good questions. From upower, it seems that it's a HID device that causes this problem. So I assume that the HID standard has a way of defining batteries and the HID descriptor sent by the device has, for some reason, a battery defined in it. I assume that's not the battery of the pen as that is normally (at least with the two pens that I have) handled via bluetooth.

Can you post the HID descriptor of that device (product/vendor ID seems to be `04F3:2A1C`)? You can use e.g. [`usbhid-dump`](https://www.systutorials.com/docs/linux/man/8-usbhid-dump/) to do that.

The proper fix would be for MS to fix the HID descriptor via a firmware update (I guess that's unlikely), so the next best thing is probably adding a [quirk](https://elixir.bootlin.com/linux/v5.18/source/drivers/hid/hid-input.c#L342) inside the kernel to just ignore it.

**Comment by dr-ni** [comment]
here the dump:
[usbhid-dump.txt](https://github.com/linux-surface/linux-surface/files/8766077/usbhid-dump.txt)

**Comment by qzed** [comment]
@dr-ni That seems to be the descriptor and things for the typecover. I think the device causing the issue is the touchscreen. This one in your UPower output:
```
Device: /org/freedesktop/UPower/devices/keyboard_hid_0018o04F3o2A1Cx0001_battery
  native-path:          hid-0018:04F3:2A1C.0001-battery
  model:                ELAN9038:00 04F3:2A1C
```

Not sure if usbhid just didn't pick that up. Might be because it (IIRC) is a i2c-hid device and not usb-hid. Could you try to use `hid-recorder` to get the descriptor? There should be a line starting with `R: ` followed by some hex values right after you selected the device.

**Comment by dr-ni** [comment]
```
uwe@go2:~$ sudo hid-recorder 
[sudo] Passwort für uwe: 
Available devices:
/dev/hidraw0:	ELAN9038:00 04F3:2A1C
/dev/hidraw1:	Microsoft Surface Keyboard
/dev/hidraw2:	Microsoft Surface Keyboard
/dev/hidraw3:	Microsoft Surface Keyboard
/dev/hidraw4:	Microsoft Surface Keyboard
Select the device event number [0-4]: 0
D: 0
R: 930 05 0d 09 04 a1 01 85 01 09 22 a1 02 09 42 15 00 25 01 75 01 95 01 81 02 75 01 81 03 75 06 09 51 25 3f 81 02 26 ff 00 75 08 09 48 81 02 09 49 81 02 95 01 05 01 a4 26 e0 0a 75 10 55 0f 65 11 09 30 35 00 46 de 00 95 02 81 02 26 20 07 46 94 00 09 31 81 02 b4 c0 05 0d 09 22 a1 02 05 0d 09 42 15 00 25 01 75 01 95 01 81 02 75 01 81 03 75 06 09 51 25 3f 81 02 26 ff 00 75 08 09 48 81 02 09 49 81 02 95 01 05 01 a4 26 e0 0a 75 10 55 0f 65 11 09 30 35 00 46 de 00 95 02 81 02 26 20 07 46 94 00 09 31 81 02 b4 c0 05 0d 09 22 a1 02 05 0d 09 42 15 00 25 01 75 01 95 01 81 02 75 01 81 03 75 06 09 51 25 3f 81 02 26 ff 00 75 08 09 48 81 02 09 49 81 02 95 01 05 01 a4 26 e0 0a 75 10 55 0f 65 11 09 30 35 00 46 de 00 95 02 81 02 26 20 07 46 94 00 09 31 81 02 b4 c0 05 0d 09 22 a1 02 05 0d 09 42 15 00 25 01 75 01 95 01 81 02 75 01 81 03 75 06 09 51 25 3f 81 02 26 ff 00 75 08 09 48 81 02 09 49 81 02 95 01 05 01 a4 26 e0 0a 75 10 55 0f 65 11 09 30 35 00 46 de 00 95 02 81 02 26 20 07 46 94 00 09 31 81 02 b4 c0 05 0d 09 22 a1 02 05 0d 09 42 15 00 25 01 75 01 95 01 81 02 75 01 81 03 75 06 09 51 25 3f 81 02 26 ff 00 75 08 09 48 81 02 09 49 81 02 95 01 05 01 a4 26 e0 0a 75 10 55 0f 65 11 09 30 35 00 46 de 00 95 02 81 02 26 20 07 46 94 00 09 31 81 02 b4 c0 05 0d 09 56 55 00 65 00 27 ff ff ff 7f 95 01 75 20 81 02 09 54 25 7f 95 01 75 08 81 02 85 0a 09 55 25 0a b1 02 c0 06 ff 01 09 01 a1 01 85 02 16 00 00 26 ff 00 75 08 95 40 09 00 81 02 c0 06 00 ff 09 01 a1 01 85 03 75 08 95 20 09 01 91 02 c0 06 00 ff 09 01 a1 01 85 06 09 03 75 08 95 12 91 02 09 04 75 08 95 03 b1 02 c0 06 01 ff 09 01 a1 01 85 04 15 00 26 ff 00 75 08 95 13 09 00 81 02 c0 05 0d 09 02 a1 01 85 07 35 00 09 20 a1 00 09 32 09 42 09 44 09 3c 09 45 15 00 25 01 75 01 95 05 81 02 95 03 81 03 05 01 09 30 75 10 95 01 a4 55 0f 65 11 46 de 00 26 00 3a 81 42 09 31 46 94 00 26 00 26 81 42 b4 05 0d 09 30 26 00 10 81 02 75 08 95 01 09 3b 25 64 81 42 75 10 95 01 09 3d a4 65 14 55 0e 36 d8 dc 46 28 23 16 d8 dc 26 28 23 81 02 09 3e 81 02 35 00 47 a0 8c 00 00 15 00 27 a0 8c 00 00 09 3f 81 02 b4 06 00 ff 75 08 95 02 09 01 81 02 c0 c0 06 00 ff 09 81 a1 01 85 17 75 08 95 40 09 05 81 02 c0 75 08 15 00 26 ff 00 06 0b ff 09 0b a1 01 95 02 09 48 85 48 b1 02 95 0f 09 29 85 29 b1 02 95 1f 09 2a 85 2a b1 02 95 3e 09 2b 85 2b b1 02 95 fe 09 2c 85 2c b1 02 96 fe 01 09 2d 85 2d b1 02 95 0f 09 2e 85 2e 81 02 95 1f 09 2f 85 2f 81 02 95 3e 09 30 85 30 81 02 95 fe 09 31 85 31 81 02 96 fe 01 09 32 85 32 81 02 96 fe 03 09 33 85 33 81 02 96 fe 07 09 34 85 34 81 02 96 fe 0f 09 35 85 35 81 02 96 3f 1d 09 36 85 36 81 02 c0 06 0f ff 09 60 a1 01 85 19 75 08 95 04 15 00 26 ff 00 09 00 91 02 85 19 75 08 95 04 15 00 26 ff 00 09 c6 81 02 c0 06 0f ff 09 50 a1 01 85 22 75 20 95 01 17 00 00 00 80 27 ff ff ff 7f 09 72 81 02 09 73 81 02 09 74 81 02 09 75 81 02 c0
N: ELAN9038:00 04F3:2A1C
P: i2c-ELAN9038:00
I: 18 04f3 2a1c
```

**Comment by dr-ni** [comment]
see also https://www.reddit.com/r/SurfaceLinux/comments/ah30w8/surface_go_remove_not_existing_battery_from_gnome/

**Comment by qzed** [comment]
@dr-ni Can you compile a kernel and test [0001-HID-hid-input-add-Surface-Go-battery-quirk.patch](https://github.com/linux-surface/linux-surface/files/8771067/0001-HID-hid-input-add-Surface-Go-battery-quirk.patch.txt)? Alternatively I'll add that to the next kernel and you can test it then.

**Comment by dr-ni** [comment]
>@dr-ni Can you compile a kernel and test 0001-HID-hid-input-add-Surface-Go-battery-quirk.patch? >Alternatively I'll add that to the next kernel and you can test it then.

I'll try that any short advice?

**Comment by qzed** [comment]
For ubuntu/debian it's mostly just cloning the repo (specifically you want the `v5.17-surface` branch), applying the config (via `./scripts/kconfig/merge_config.sh <path-to-base-ubuntu-config> <path-to-surface-config>` or you could just use the config of the current surface kernel which should be on your file system somehwere) and then finally building the kernel (via `make bindeb-pkg -j $(nproc)`.

I can also just add the patch and schedule some fresh builds later today.

**Comment by dr-ni** [comment]
>I can also just add the patch and schedule some fresh builds later today.

I think that's better - keep me informed when I can test it

**Comment by qzed** [comment]
I'll ping this issue.

**Comment by qzed** [comment]
@dr-ni New kernels with the patch should be available in the repo.

**Comment by dr-ni** [comment]
[upower-dump.txt](https://github.com/linux-surface/linux-surface/files/8774806/upower-dump.txt)

**Comment by qzed** [comment]
Neat! I've sent the patch upstream (will add link here once it shows up on patchwork).

**Comment by dr-ni** [comment]
ok perfect :)

**Comment by qzed** [comment]
Link: https://patchwork.kernel.org/project/linux-input/patch/20220525230827.1019662-1-luzmaximilian@gmail.com/

**Comment by dr-ni** [comment]
what about the go3?
is italso solved?
