### ISSUE TITLE
Hey Guys i currently face this prolem on Fedora 36 and 35

### ISSUE THREAD

**Issue by divtodiv** [linux-surface/linux-surface#794]
Error: Failed to download metadata for repo 'linux-surface': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: linux-surface
Last metadata expiration check: 0:42:39 ago on Tue 19 Apr 2022 01:17:45 PM EDT.
No match for argument: kernel-surface
No match for argument: iptsd
No match for argument: libwacom-surface

**Comment by StollD** [comment]
Sorry, I didnt build all the packages for Fedora 36 yet. So the repo not working is to be expected (because it doesnt exist)

**Comment by Kellegram** [comment]
Purely out of curiosity, how long does it generally take? What would be the best place to monitor this, just looking at the commits in this repo?

**Comment by Kellegram** [comment]
I just saw the commit so I guess I got my answer 😂

**Comment by qzed** [comment]
Ah, wanted to ping here. F36 is mostly ready, libwacom-surface should be the last package and that's building now.

**Comment by qzed** [comment]
Packages are built and the repo is updated, so should be available now or in the next 10 minutes or so.
