### ISSUE TITLE
Surface Laptop 4  AMD - Surface Kernel 22.04 - External monitor issues - High resolution (Ultrawide) do not work. 

### ISSUE THREAD

**Issue by RichardODonoghue** [linux-surface/linux-surface#800]
Hi Everyone, 

Is anyone else having issues with external monitors not working on SL4? 

I installed the surface kernel to get my touchpad / keyboard working and this is the only thing left I really need to tick off the list. 

Is there any work arounds I can implement? I may have missed something. 

Cheers :)

**Comment by jpgombas** [comment]
Hi,

I had this problem too. I run Ubuntu21 on SL4. I was able to get it working by decreasing the monitor resolution. So instead of 4k, I got 1440p working. Not optimal, but it got it working.

Best

**Comment by sphh** [comment]
I had a similar issue on a SP5. It was definitely a different set up (running the second monitor on a surface dock), but I got it eventually working with the very best cable I could lay my hands on (and OMG I tried many, many different cables!). It was not the software or computer set up, just an inferior cable not up to the task to deliver the high-resolution picture to the external screen. Which cable to you use to connect the screen to your SL4? Which connectors? Also have a look at the specifications of the monitor cable you use.

Well, that's just an idea, which might help you …

**Comment by RichardODonoghue** [comment]
thanks for the advice @sphh but I think that is highly unlikely given I only installed ubuntu yesterday and before that my monitors connected to my surface dock were working flawlessly.

**Comment by RichardODonoghue** [comment]
> Hi,
> 
> I had this problem too. I run Ubuntu21 on SL4. I was able to get it working by decreasing the monitor resolution. So instead of 4k, I got 1440p working. Not optimal, but it got it working.
> 
> Best

did your monitors show up in the display settings? Mine are not.

**Comment by RichardODonoghue** [comment]
update on this issue: 

I got the graphics somewhat working using the workarounds in my grub config. I am using amd_iommu=force_isolation

So I have two external displays. Ubuntu detects both of them when connecting my SL4 to the surface dock (which my displays are connected to) however the laptop screen automatically changes the resolution scale from 100% to 200%. For some reason this happens every time even if i save changes. 

While ubuntu detects both monitors just fine, only one of them will actually display an image. 

The external monitor which is working is an asus 1080p monitor. 
The not working one is a 34" curved titan army ultra wide with a native resolution of 3440x1440. 

Any ideas?

**Comment by sphh** [comment]
> > Hi,
> > I had this problem too. I run Ubuntu21 on SL4. I was able to get it working by decreasing the monitor resolution. So instead of 4k, I got 1440p working. Not optimal, but it got it working.
> > Best
> 
> did your monitors show up in the display settings? Mine are not.

@RichardODonoghue: That was ages ago. I cannot remember … I tried to unearth the discussion but could not find it.

Sorry, that I cannot help here further.

**Comment by jpgombas** [comment]
> update on this issue:
> 
> I got the graphics somewhat working using the workarounds in my grub config. I am using amd_iommu=force_isolation
> 
> So I have two external displays. Ubuntu detects both of them when connecting my SL4 to the surface dock (which my displays are connected to) however the laptop screen automatically changes the resolution scale from 100% to 200%. For some reason this happens every time even if i save changes.
> 
> While ubuntu detects both monitors just fine, only one of them will actually display an image.
> 
> The external monitor which is working is an asus 1080p monitor. The not working one is a 34" curved titan army ultra wide with a native resolution of 3440x1440.
> 
> Any ideas?

I'm glad both monitors are now showing up. Progress :)

My grub config is "amd_iommu=off iommu=off", and I am running with Wayland. I just have 1 external monitor, standard 3840 x 2160. I am using the Microsoft dock for my external monitor. 

When I initially connect, my 4k monitor does not show anything. I have to first set the resolution to 1440p, click apply. And then I can decrease the scale down to 100% (mine also defaults to 200% when I plug it in). If I reverse the order, I get a black screen on both the internal and external monitor. 

I hope this helps!

**Comment by RichardODonoghue** [comment]
@jpgombas thank you. I tried this. I managed to get the external display working once at low res & 200% scale... but as soon as my laptop went to sleep I lost it and I didn't get it back again. Frustrating but yeah an update on display management or at least something to get the drivers working properly would be epic.

**Comment by RichardODonoghue** [comment]
Update: I decided to try a different MDP to HDMI adapter to see if I could output to the display. To my surprise... it actually worked. Oddly enough there doesn't seem to be anything wrong with the adapter. I tried it on a couple of other devices, with the same cable and it worked just fine... just not under linux. 

I have all three displays working now. Only one flaw left to fix. The ultrawide display does not want to output at anything more than 1920x1080, even if I set the resolution to higher than that. I have tried a couple of things so far like creating a custom resolution mode with xrandr but have not had any success just yet. 

I am going to see if changing the scaling mode (use the GPU instead of the display / or vice versa) and see if that makes a difference. From there I am not sure where to next.

**Comment by RichardODonoghue** [comment]
Okay, after a variety of different tests... I chose to switch to a mini-DP to DP cable... and some how all of my problems are miraculously solved even though the previous mini-dp to HDMI adapter and hdmi cable I had was working fine on every other device I tried it on... Meh I can't complain at least its now working... and at full resolution too. YAY!
