### ISSUE TITLE
Surface Book 1 - No more cameras with kernel 5.17.4-arch

### ISSUE THREAD

**Issue by EinderJam** [linux-surface/linux-surface#801]
Since updating to kernel 5.17.4, `cam --list` does not detect any camera anymore. `ipu3-cio2` reports adding 2 cameras in dmesg, but they are nowhere to be found afterwards.

While writing this issue and reviewing requirements for camera support, I came across the IPU3 firmware section, stating that "/lib/firmware/intel/ipu3-fw.bin is required to be present at kernel boot time to support loading of the IPU3 IMGU device."
I only have /lib/firmware/intel/ipu3-fw.bin.xz, is that an issue ?

### Environment

- Hardware model: Surface Book 1
- Kernel version: `5.17.4-arch1-1-surface #1 SMP PREEMPT Tue, 26 Apr 2022 00:45:10 +0000 x86_64 GNU/Linux`
- Distribution: Arch Linux
- `libcamera-git` installed from AUR and up-to-date
- `linux-firmware` installed from repos

<details><summary>`dmesg` output</summary>

[dmesg_output.txt](https://github.com/linux-surface/linux-surface/files/8584367/dmesg_output.txt)

</details>

**Comment by qzed** [comment]
Thanks for the report, we've already discussed this on the IRC yesterday and @djrscally is on it.

> I only have /lib/firmware/intel/ipu3-fw.bin.xz, is that an issue ?

No, as far as I can tell that's not a problem.

**Comment by djrscally** [comment]
Should be fixed by https://github.com/linux-surface/kernel/pull/122 - sorry about that.

**Comment by qzed** [comment]
New releases with the fix are building now.

**Comment by EinderJam** [comment]
> Should be fixed by [linux-surface/kernel#122](https://github.com/linux-surface/kernel/pull/122) - sorry about that.

Awesome, thanks!

**Comment by qzed** [comment]
The new releases should be available in the repos now.

**Comment by JulianHeuser** [comment]
Confirmed that everything's working as it was - this issue can probably be closed now.

**Comment by qzed** [comment]
Thanks!
