### ISSUE TITLE
SP3 Temp spikes since upgrade to Ubuntu Jammy Jellish

### ISSUE THREAD

**Issue by ruralTom** [linux-surface/linux-surface#802]
My temps settled around 150 but would spike to 170 at the most and only under heavy load.

After upgrading I'm seeing temps of 180 on a regular basis and it's sustained far longer than I'd prefer. Unplugging the charger helps, but this device burns through battery like hell on Linux so I've mostly used it as a couch surfer.

Is anyone else seeing these issues? I don't know if this is even a surface kernel issue or a Ubuntu issue.

**Comment by headkaze** [comment]
Use System Monitor and sort by CPU usage to find out which process is causing the issue.
