### ISSUE TITLE
Nvidia-DKMS, vl412loop-DKMS wouldn't build when **kernel-surface** is installed #Fedora #dkms #nvidia #SB2

### ISSUE THREAD

**Issue by 2ndBillGates** [linux-surface/linux-surface#803]
**[Description of the bug or feature]**

Nvidia-DKMS, vl412loop-DKMS wouldn't build when **kernel-surface** is installed

I've already installed DKMS module ,**nvidia/510.68.02** & **v4l2loopback/0.12.5** for normal kernel **(5.17.4-200.fc35.x86_64)**,
before I tried to install kernel-surface.
<details><summary>`Try to build DKMS module` output </summary>

```
# dkms install nvidia/510.68.02

Building module:
cleaning build area...
'make' -j8 NV_EXCLUDE_BUILD_MODULES='' KERNEL_UNAME=5.17.4-2.surface.fc35.x86_64 IGNORE_CC_MISMATCH='' modules...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.17.4-2.surface.fc35.x86_64 (x86_64)
Consult /var/lib/dkms/nvidia/510.68.02/build/make.log for more information.
```
</details>

when DKMS try to automatically install those module for surface kernel, seems to be what kernel-surface different from the regular kernel name, that confuse DKMS installer. **kernel-surface** name is **5.17.4-2** where as regular version is **5.17.4-200.**

<details><summary> **make.log** output </summary>

```
DKMS make.log for nvidia-510.68.02 for kernel 5.17.4-2.surface.fc35.x86_64 (x86_64)
Fri 29 Apr 21:19:10 CST 2022
make[1]: Entering directory '/usr/src/kernels/5.17.4-2.surface.fc35.x86_64'
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `if [ "cc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)" != ""gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)"" ]; then \'
make[1]: *** [Makefile:1727: prepare] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.17.4-2.surface.fc35.x86_64'
make: *** [Makefile:82: modules] Error 2

```
</details>

[dmesg.log](https://github.com/linux-surface/linux-surface/files/8591086/dmesg.log)

**Comment by 2ndBillGates** [comment]
arr....... I remove the original kernel dkms module and kernel-surface, try to do it all over again

and, now I cannot use the same method to reinstall. similar error pops up.

**Comment by 2ndBillGates** [comment]
I'm frustrated now... it was working just fine..... 
[make.log](https://github.com/linux-surface/linux-surface/files/8592034/make.log)

**Comment by StollD** [comment]
You should really install the driver from a repository, preferably rpmfusion.

If you want to get it working with the nvidia installer, it seems you need to add `IGNORE_CC_MISMATCH=1` to the make command that is used to build the module. That command should be in `/etc/dkms/dkms-nvidia.conf` (or a slightly different filename). Check this out for reference: https://github.com/negativo17/dkms-nvidia/blob/master/dkms-nvidia.conf

**Comment by 2ndBillGates** [comment]
I tried akmod in the first time, no luck either

> Building and installing nvidia-kmod                        [FAILED]
Building rpms failed; see /var/cache/akmods/nvidia/510.60.02-1-for-5.17.4-2.surface.fc35.x86_64.failed.log for details

[510.60.02-1-for-5.17.4-200.fc35.x86_64.log](https://github.com/linux-surface/linux-surface/files/8592264/510.60.02-1-for-5.17.4-200.fc35.x86_64.log)

**Comment by StollD** [comment]
Ahh, ok, now I see. Fedora updated the compiler for 35 yesterday, so right after I built kernel 5.17.4 with the old compiler. So now they don't match anymore and the DKMS builds fail.

I built 5.17.5 earlier today, which used the new compiler. It should be available in the repo in a few hours. If you dont want to wait, you can download the rpms from github releases.

**Comment by 2ndBillGates** [comment]
unfortunately, it's still off to the same error

not just dkms has problems
I found  out that even i try to install the module in a normal way, it won't install to /lib/modules/5.17.5-2.surface.fc35.x86_64

I don' t understand why



<details><summary>'error code' output </summary>

``
[root@sb2-2022211-f35 v4l2loopback]# make
[root@surfacebook2-fedora v4l2loopback]# make
Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/tom/Downloads/.tmp/v4l2loopback KCPPFLAGS="-DSNAPSHOT_VERSION='"v0.12.5-253-gd01c20c"'" modules
make[1]: Entering directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `if [ "gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)" != ""gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)"" ]; then \'
make[1]: *** [Makefile:1727: prepare] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'
make: *** [Makefile:51: v4l2loopback.ko] Error 2
[root@surfacebook2-fedora v4l2loopback]# make install all
make -C /lib/modules/`uname -r`/build M=/home/tom/Downloads/.tmp/v4l2loopback modules_install
make[1]: Entering directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'
cat: /home/tom/Downloads/.tmp/v4l2loopback/modules.order: No such file or directory
  DEPMOD  /lib/modules/5.17.5-2.surface.fc35.x86_64
make[1]: Leaving directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'

SUCCESS (if you got 'SSL errors' above, you can safely ignore them)

Building v4l2-loopback driver...
make -C /lib/modules/`uname -r`/build M=/home/tom/Downloads/.tmp/v4l2loopback KCPPFLAGS="-DSNAPSHOT_VERSION='"v0.12.5-253-gd01c20c"'" modules
make[1]: Entering directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `if [ "gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)" != ""gcc (GCC) 11.3.1 20220421 (Red Hat 11.3.1-2)"" ]; then \'
make[1]: *** [Makefile:1727: prepare] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.17.5-2.surface.fc35.x86_64'
make: *** [Makefile:51: v4l2loopback.ko] Error 2
[root@surfacebook2-fedora v4l2loopback]# 

``
</details>

**Comment by ch3wt0ys** [comment]
Issue stems from bad quotes in /usr/src/kernels/5.17.5-2.surface.fc35.x86_64/Makefile between lines 1724 and 1731

```patch
 # now expand this into a simple variable to reduce the cost of shell evaluations
 prepare: CC_VERSION_TEXT := $(CC_VERSION_TEXT)
 prepare:
-	@if [ "$(CC_VERSION_TEXT)" != "$(CONFIG_CC_VERSION_TEXT)" ]; then \
+	@if [ "$(CC_VERSION_TEXT)" != $(CONFIG_CC_VERSION_TEXT) ]; then \
 		echo >&2 "warning: the compiler differs from the one used to build the kernel"; \
-		echo >&2 "  The kernel was built by: $(CONFIG_CC_VERSION_TEXT)"; \
+		echo >&2 "  The kernel was built by: "$(CONFIG_CC_VERSION_TEXT); \
 		echo >&2 "  You are using:           $(CC_VERSION_TEXT)"; \
 	fi
```

Fix the quotes and dkms will work correctly. Reference: https://github.com/QubesOS/qubes-issues/issues/7459

**Comment by 2ndBillGates** [comment]
> Issue stems from bad quotes in /usr/src/kernels/5.17.5-2.surface.fc35.x86_64/Makefile between lines 1724 and 1731
> 
> ```diff
>  # now expand this into a simple variable to reduce the cost of shell evaluations
>  prepare: CC_VERSION_TEXT := $(CC_VERSION_TEXT)
>  prepare:
> -	@if [ "$(CC_VERSION_TEXT)" != "$(CONFIG_CC_VERSION_TEXT)" ]; then \
> +	@if [ "$(CC_VERSION_TEXT)" != $(CONFIG_CC_VERSION_TEXT) ]; then \
>  		echo >&2 "warning: the compiler differs from the one used to build the kernel"; \
> -		echo >&2 "  The kernel was built by: $(CONFIG_CC_VERSION_TEXT)"; \
> +		echo >&2 "  The kernel was built by: "$(CONFIG_CC_VERSION_TEXT); \
>  		echo >&2 "  You are using:           $(CC_VERSION_TEXT)"; \
>  	fi
> ```
> 
> Fix the quotes and dkms will work correctly. Reference: [QubesOS/qubes-issues#7459](https://github.com/QubesOS/qubes-issues/issues/7459)

Agree, I find it weird 

here is the Makefile in "/usr/src/kernels/5.17.5-2.surface.fc35.x86_64/
[Makefile.txt](https://github.com/linux-surface/linux-surface/files/8614581/Makefile.txt)
"

**Comment by 2ndBillGates** [comment]
it's fixed now

many thanks to [ch3wt0ys](https://github.com/ch3wt0ys)

**Comment by 2ndBillGates** [comment]
$dkms status

nvidia/510.68.02, 5.17.5-200.fc35.x86_64, x86_64: installedDeprecated feature: REMAKE_INITRD
Deprecated feature: REMAKE_INITRD

nvidia/510.68.02, 5.17.5-2.surface.fc35.x86_64, x86_64: installed
v4l2loopback/0.12.5, 5.17.5-200.fc35.x86_64, x86_64: installedDeprecated feature: REMAKE_INITRD
 (original_module exists)
v4l2loopback/0.12.5, 5.17.5-2.surface.fc35.x86_64, x86_64: installedDeprecated feature: REMAKE_INITRD
 (original_module exists)
[curie@sb2-2022211-f35 ~]$

**Comment by 2ndBillGates** [comment]
Sorry to ask again
is there something I can do, to prevent that happens again?

whenever I try to install new kernel, the make file in /usr/src/kernels/..../ MAKEFILE
come with this double quote issue

I wonder how is that MAKEFILE generated.

**Comment by 2ndBillGates** [comment]
I look into this commit, doesn't seem to provide any permanent fix
[](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.17.4&id=129ab0d2d9f)

**Comment by 2ndBillGates** [comment]
[https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.17.4&id=129ab0d2d9f](url)
[https://lkml.org/lkml/2022/3/7/1896](url)
