### ISSUE TITLE
Linux Surface Kernel report incorrect resolution/Hz for SLS Screen

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/linux-surface#817]
Before I using Surface Linux  Kernel, Surface Laptop Studio Screen Panel have 2400x1600@60Hz option on normal Linux Kernel
But when switched to Surface Linux Kernel, only 120Hz exists for 2400x1600

For other resolution, refresh rate info is not same as generic kernel and not same as Windows
(UPDATE: generic not same as Windows)

Firmware update and Ubuntu update is done before and after Surface Kernel installation

### Environment
- Hardware model: Surface Laptop Studio CPU:i5 SSD:512GB without dGPU
- Kernel version: 

> Linux NP-chaonay-L1L 5.17.5-surface #_3 SMP PREEMPT Sat May 7 16:37:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux (underline between sharp and 3 because to prevent accident GitHub markdown interpretation)

- Distribution: Ubuntu 22.04 LTS

DMESG output is attached as file.
[dmesg.log](https://github.com/linux-surface/linux-surface/files/8666664/dmesg.log)

**Comment by NP-chaonay** [comment]
Have try on both X11 and Wayland
but there are interesting result from xrandr output when running on X11, I don't know if this techincal workaround or an bug
<details><summary>xrandr output</summary>

```
Screen 0: minimum 320 x 200, current 2400 x 1600, maximum 16384 x 16384
eDP-1 connected primary 2400x1600+0+0 (normal left inverted right x axis y axis) 303mm x 202mm
   2400x1600    120.00*+
   2048x1536     85.00    75.00    60.00  
   1920x1440     85.00    75.00    60.00  
   1856x1392     75.00    60.01  
   1792x1344     75.00    60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01    59.97    59.96    59.93  
   1600x1200     85.00    75.00    70.00    65.00    60.00  
   1680x1050     84.94    74.89    69.88    59.95    59.88  
   1600x1024     60.17  
   1400x1050     85.00    74.76    70.00    59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     85.02    75.02    60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      85.00    60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864     100.00    85.06    85.00    75.00    75.00    70.00    60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      85.00    75.05    60.04    85.00    75.03    70.07    60.00  
   1024x768i     86.96  
   960x720       85.00    75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600       85.00    75.00    70.00    65.00    60.00    85.14    72.19    75.00    60.32    56.25  
   840x525       85.02    74.96    69.88    60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       85.08    74.76    70.06    59.98  
   800x450       59.95    59.82  
   640x512       85.02    75.02    60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       85.09    60.00    85.01    72.81    75.00    59.94  
   720x405       59.51    58.99  
   720x400       85.04  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98    85.08  
   576x432      100.11    85.15    85.09    75.00    75.00    70.00    60.06  
   640x360       59.86    59.83    59.84    59.32  
   640x350       85.08  
   512x384       85.00    75.03    70.07    60.00  
   512x384i      87.06  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       85.27    72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       85.18    72.81    75.00    60.05  
   360x202       59.51    59.13  
   360x200       85.04  
   320x200       85.27  
   320x180       59.84    59.32  
   320x175       85.27  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)

```

</details>

**Comment by m1nicrusher** [comment]
I can confirm the same problem is happening here.
- Hardware: Surface Laptop Studio i7 3050Ti
- Kernel: 5.17.7-1-surface
- Distro: Fedora 36

Plus, the external monitor is stuck at 79.95Hz (says GNOME), or 75Hz (says my monitor) at most.
Before the kernel, my external monitor can run 120Hz or 144Hz.

**Comment by NP-chaonay** [comment]
Ok I have change title and desc to be more match the problem.
For generic kernel resolution list testing will be reported soon.

@m1nicrusher have you try on generic kernel?

**Comment by NP-chaonay** [comment]
<details><summary>On Windows side supported these resolution:
</summary>
- 2400x1600
- 640x480
- 800x600
- 1024x768
- 1152x864
- 1280x600
- 1280x720
- 1280x768
- 1280x800
- 1280x960
- 1280x1024
- 1360x768
- 1366x768
- 1400x1050
- 1440x900
- 1600x900
- 1600x1200
- 1680x1050
- 1792x1344
- 1856x1392
- 1920x1080
- 1920x1200
- 1920x1440
- 2048x1152
- 2048x1536
- 1830x1200
- 1648x1080
- 1220x800
</details>
Every of them has only 60hz and 120hz

**Comment by m1nicrusher** [comment]
On Kernel ```5.17.9-1.surface.fc36.x86_64```
GNOME settings is reporting to support 60Hz 90Hz 120Hz on all other resolutions (1440x1080, 1920x1200, etc.) except native resolution (2400x1600), which only have 120Hz one option. PS: for other resolutions, 60Hz 90Hz 120Hz are various decimals (59.81 89.89 119.85) depending on resolutions. I think it's normal but worth noting if somehow it helps...

**Comment by m1nicrusher** [comment]
> Ok I have change title and desc to be more match the problem. For generic kernel resolution list testing will be reported soon.
> 
> @m1nicrusher have you try on generic kernel?

I can confirm on Kernel ```5.17.8-300.fc36.x86_64```, it is behaving the same.
However I could remember during installation (livecd) I could actually change the refresh rate.

**Comment by StollD** [comment]
The default Ubuntu 22.04 kernel is 5.15 or so right? It seems there were some changes to the intel graphics driver regarding refresh rates in 5.16, so since our kernel is newer, that could be the difference. I dont think it is a config difference, at least for Fedora we use the upstream configs and sources, and just add our changes on top. And they don't touch the graphics stack.

My assumption would be that Intel locked the panel into its native refresh rate for some reason. This can make sense for 120Hz, because it can already display 60fps content smoothly. But without software that allows you to explicitly render at 60fps, you get locked into 120fps rendering.

**Comment by StollD** [comment]
Also, #825 seems related, but actually describes the opposite problem.

**Comment by NP-chaonay** [comment]
[StollD](https://github.com/StollD)
yes latest out-of-box kernel is 5.15, thx I forget that it possible that it is different because of upstream kernel tree.

so if that is true, then I think problem is about kernel bug in the tree / or technical issues. 

> My assumption would be that Intel locked the panel into its native refresh rate for some reason. This can make sense for 120Hz, because it can already display 60fps content smoothly. But without software that allows you to explicitly render at 60fps, you get locked into 120fps rendering.

I don't know if I misunderstanding, yes on native resolution only have 120hz while other have some non-120hz refresh rate, but all of them is incorrect based on EDID read on Windows (and may also on generic kernel, which I will test later); So I don't think Intel lock panel into native refresh rate, I think there's some technical thing about parsing EDID and other HW information.

But however I think kernel should display according to EDID which is resolution from Windows with only 60/120Hz, but the xrandr gives some random which idk if that is deep EDID/etc info, but finally it should be the EDID that used in Windows. However another resolution except native resolution.

**Comment by NP-chaonay** [comment]
So I think it is bug on kernel not relate to linux-surface.
<details><summary>xrandr output on generic kernel</summary>

```

np-chaonay@NP-chaonay-L1L:~$ xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 303mm x 202mm
   2400x1600    120.00 +  60.00  
   2048x1536     85.00    75.00    60.00  
   1920x1440     85.00    75.00    60.00  
   1856x1392     75.00    60.01  
   1792x1344     75.00    60.01  
   2048x1152     59.99    59.98    59.90    59.91  
   1920x1200     59.88    59.95  
   1920x1080     60.01*   59.97    59.96    59.93  
   1600x1200     85.00    75.00    70.00    65.00    60.00  
   1680x1050     84.94    74.89    69.88    59.95    59.88  
   1600x1024     60.17  
   1400x1050     85.00    74.76    70.00    59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     85.02    75.02    60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      85.00    60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864     100.00    85.06    85.00    75.00    75.00    70.00    60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      85.00    75.05    60.04    85.00    75.03    70.07    60.00  
   1024x768i     86.96  
   960x720       85.00    75.00    60.00  
   928x696       75.00    60.05  
   896x672       75.05    60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   832x624       74.55  
   960x540       59.96    59.99    59.63    59.82  
   800x600       85.00    75.00    70.00    65.00    60.00    85.14    72.19    75.00    60.32    56.25  
   840x525       85.02    74.96    69.88    60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       85.08    74.76    70.06    59.98  
   800x450       59.95    59.82  
   640x512       85.02    75.02    60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       85.09    60.00    85.01    72.81    75.00    59.94  
   720x405       59.51    58.99  
   720x400       85.04  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98    85.08  
   576x432      100.11    85.15    85.09    75.00    75.00    70.00    60.06  
   640x360       59.86    59.83    59.84    59.32  
   640x350       85.08  
   512x384       85.00    75.03    70.07    60.00  
   512x384i      87.06  
   512x288       60.00    59.92  
   416x312       74.66  
   480x270       59.63    59.82  
   400x300       85.27    72.19    75.12    60.32    56.34  
   432x243       59.92    59.57  
   320x240       85.18    72.81    75.00    60.05  
   360x202       59.51    59.13  
   360x200       85.04  
   320x200       85.27  
   320x180       59.84    59.32  
   320x175       85.27  
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
HDMI-1 disconnected (normal left inverted right x axis y axis)

```

</details>

**Comment by StollD** [comment]
Could you upload the EDID?

My theory about the native refresh rate is only for native resolution, because I don't really know a lot about the graphics stack, so I wasn't sure how trustworthy these Xorg refresh rates are. Most of them are weird decimals. Kinda like Xorg tried to calculate what it can safely interpolate or something like that.

**Comment by m1nicrusher** [comment]
Oh actually I didn't check which kernel is my livecd using, but I'm using Fedora, which could be using a different OOB kernel.

**Comment by NP-chaonay** [comment]
> Could you upload the EDID?
> 
> My theory about the native refresh rate is only for native resolution, because I don't really know a lot about the graphics stack, so I wasn't sure how trustworthy these Xorg refresh rates are. Most of them are weird decimals. Kinda like Xorg tried to calculate what it can safely interpolate or something like that.

Here below is EDID binary file but in txt extension.
[SurfacePanel_EDID.txt](https://github.com/linux-surface/linux-surface/files/8752456/SurfacePanel_EDID.txt)

**Comment by qzed** [comment]
Decoded timings from the above:
```
  Established Timings I & II: none
  Standard Timings: none
  Detailed Timing Descriptors:
    DTD 1:  2400x1600  120.000191 Hz   3:2    196.320 kHz    502.580000 MHz (303 mm x 202 mm)
                 Hfront   48 Hsync  32 Hback   80 Hpol N
                 Vfront    3 Vsync  10 Vback   23 Vpol N
    DTD 2:  2400x1600   60.000096 Hz   3:2    196.320 kHz    502.580000 MHz (303 mm x 202 mm)
                 Hfront   48 Hsync  32 Hback   80 Hpol N
                 Vfront    3 Vsync  10 Vback 1659 Vpol N

```

I wonder if the second entry gets dropped somewhere...

**Comment by NP-chaonay** [comment]
ok I have create new issue and let this old as reference
