### ISSUE TITLE
Bad shim signature on Fedora 36, SP7+.

### ISSUE THREAD

**Issue by Pairman** [linux-surface/linux-surface#821]
[Description of the bug or feature]

Can't boot into kernel-surface. Having gone through the Fedora part of your detailed installation guide and set up the secureboot by installing `surface-secureboot`. `shim` and `shim-signed` are already installed. 3rd-party signatures are enabled in the surface UEFI.
The message after opting to boot into kernel-surface:

```
error: ../../grub-core/kern/efi/sb.c:150:bad shim signature.
error: ../../grub-core/loader/i386/efi/linux.c:207:you need to load the kernel first.
Press any key to continue...
```

Thanks for your help in advance.

### Environment

- Hardware model: `Surface Pro 7+. 11th Gen Intel i5-1135G7 (8) @ 4. Memory 7787 MiB.
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/8697664/dmesg.txt)
`
- Kernel version: `kernel-surface-5.17.5-3.fc36.x86_64.rpm` (Installed, but currently using the official out-of-box kernel because I can't boot into the surface kernel.)
- Distribution: `Fedora Linux 36 (Workstation Edition)`

<details><summary>`dmesg` output</summary>

```
Attached in the file

```

</details>

**Comment by 2ndBillGates** [comment]
I use fedora as well.

are your "official out-of-box kernel“ has secure boot enable already?

**Comment by 2ndBillGates** [comment]
What I meant was, before you installed surface kernel, are you able to boot with secure boot enabled?

after you install surface-secure-boot from dnf, does it output any message to ask you to reboot and use mokutil to enroll the surface key?

**Comment by exSnake** [comment]
> What I meant was, before you installed surface kernel, are you able to boot with secure boot enabled?
> 
> after you install surface-secure-boot from dnf, does it output any message to ask you to reboot and use mokutil to enroll the surface key?

Same happened to me with Ubuntu, after installing linux-surface-secureboot-mok he asked to reboot and write 'surface' but i followed the instruction and did sudo update-grub before rebooting, now it's stuck there.

**Comment by Pairman** [comment]
> 

1) I'm able to boot finely with the original kernel with secure boot enabled.

2) I didn't see any message like this other than dnf messages. 

I gonna try installing again and see what happens.

**Comment by Pairman** [comment]
After reinstalling surface-secureboot even building by myself, finally it shows the mok window after reboot. Thanks for all your development and help! I can finally use the surface kernel.

**Comment by mik1656** [comment]
Hi there, I have the same identical issue on my SP7. I'm very basic with doing stuff on linux, can someone please explain very easy how to solve the problem? (step by step please)

**Comment by 2ndBillGates** [comment]
> Hi there, I have the same identical issue on my SP7. I'm very basic with doing stuff on linux, can someone please explain very easily how to solve the problem? (step by step please)

you gotta give us some details, like what distro that you're using, have you installed surface kernel already?

**Comment by Al3bad** [comment]
I've got the same problem with my SP5. I installed the surface kernel but whenever I try to boot into it, I get the same error mentioned in this issue. I still can boot into the default kernel that came with Fedora distro.

**Comment by qzed** [comment]
Did you install the `surface-secureboot-mok` package and follow the instructions printed during installation (i.e. enroll the secureboot key)?

**Comment by Al3bad** [comment]
I installed `surface-secureboot` package as mentioned in the instructions in the wiki but I couldn't find `surface-secureboot-mok` if that's the package that I meant to install. And yes, I enrolled the secureboot key during the installation.

**Comment by qzed** [comment]
Yes that's the right package, sorry for confusing the names. So you rebooted into MokManager and enrolled the key there? Can you check the output of `mokutil --list-enrolled` whether there's a certificate with `CN=linux-surface` in there?

**Comment by Al3bad** [comment]
I believe I did. I only see `CN=Fedora Secure Boot CA` when I ran the command ... I'm assuming that means the key is not enrolled right? If so, how can I bring up the MokManager again to enroll the key?

**Comment by qzed** [comment]
Right, the easiest way to do that is to uninstall the `surface-secureboot` package and then reinstall it (completely uninstall, not just reinstall). Rebooting should then bring up MokManager again. Enter `surface` as password, then continue with `yes`/`ok`.

**Comment by Al3bad** [comment]
That worked. Thanks!

**Comment by JoseBCN84** [comment]
Yay, I had the same issue with a SB1 And Fedora36, this solved. Thanks!

**Comment by pzinn** [comment]
Had the same problem, got it now. Maybe the install instructions should make it clearer that you have to actively do something during the next reboot (I didn't see the message at reboot and it disappears after a few seconds if you do nothing).

**Comment by mauriciabad** [comment]
I solved it by re installing `linux-surface-secureboot-mok` and creating a key after reboot.
Run:
```sh
sudo apt remove linux-surface-secureboot-mok
sudo apt install linux-surface-secureboot-mok
reboot
# And now follow the instructions, don't directly boot.
```

**Comment by qzed** [comment]
> Had the same problem, got it now. Maybe the install instructions should make it clearer that you have to actively do something during the next reboot (I didn't see the message at reboot and it disappears after a few seconds if you do nothing).

Thanks for the feedback. I've adapted the instructions in the setup guide. Please also feel free to edit that if you feel that something is unclear or have anything to add/improve.

**Comment by chemarito** [comment]
Sorry, but in my surface go 3 with Fedora 37, a blue screen appears (moko?) that I'm unable to manage properly due that little keyboard is blinking continuously. I don't know which option to select (...).
No option to enter "surface" key and problem continue.
Could you help?

PS: Sorry for my bad english.
