### ISSUE TITLE
surface-ath10k-firmware-override unavailable in repo

### ISSUE THREAD

**Issue by discord5000** [linux-surface/linux-surface#827]
surface-ath10k-firmware-override package is unavailable to install from surface linux repo in Fedora 36.

- Hardware model:  Surface Go
- Distribution: Fedora 36

**Comment by qzed** [comment]
It's no longer required on Fedora 36 as the fix has been included in the linux-firmware upstream repository.

**Comment by discord5000** [comment]
I still had to copy the firmware files manually after first install before I could get any updates.

**Comment by qzed** [comment]
May be related to https://github.com/linux-surface/ath10k-firmware-override/issues/3.

**Comment by kevin-fibich** [comment]
this should be reopened once https://github.com/linux-surface/ath10k-firmware-override/pull/4 is merged to support SGO 1 LTE, support for which is missing from linux-firmware.

**Comment by qzed** [comment]
The package has been updated and should now be available in the repository again.
