### ISSUE TITLE
Surface Go 2 - Fedora 36 - no camera detected

### ISSUE THREAD

**Issue by FlyingPC** [linux-surface/linux-surface#828]
Under Fedora 36 with kernel 5.17.9-1.surface, cam --list does not detect any camera.

In dmesg, there no mention of ipu3-cio2 (so no camera detected ?) while the module is available in lsmod.

### Environment

- Hardware model: Surface Go 2
- Kernel version: Linux fedora 5.17.9-1.surface.fc36.x86_64 #1 SMP PREEMPT Sat May 21 03:18:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Fedora 36
- libcamera-git build and install with ninja (everything build with no errors)
- linux-firmware installed from repos Fedora

### Output of dmesg:
[dmesg.txt](https://github.com/linux-surface/linux-surface/files/8749816/dmesg.txt)

**Comment by FlyingPC** [comment]
Maybe this issue should not be here. Should I post it in https://github.com/linux-surface/kernel bugtracher?

**Comment by djrscally** [comment]
Yeah sorry, I got this a bit screwed up and I'm just trying to figure out the best way to unravel  it all

**Comment by FlyingPC** [comment]
@djrscally That's not a problem. It's just the first time I write a new issue in linux surface bugtracker. And I just want to be sure I didn't make a mistake posting this issue here.

**Comment by hardwareadictos** [comment]
Just to confirm, i have the same issue on SGO1, Fedora 36 also. No cameras detected.

**Comment by FlyingPC** [comment]
Fix by kernel 5.18.
