### ISSUE TITLE
[SB2] Brightness "jumps" around

### ISSUE THREAD

**Issue by CountOmega** [linux-surface/linux-surface#829]
[Description of the bug or feature]
When waking the device up from sleep, the brightness I set before isn't saved.Also, every so often then brightness jumps around. E.g. when I press the key for increasing brightness once the brightness moves all the way to the highest setting on its own. 
Sometimes the brightness just randomly de-/increases despite there being no change in the environment. Automatic brightness is on in the setting
- Hardware model:  Surface Book 2 15"
- Kernel version: 5.17.7-surface
- Distribution: Debian testing
-DE: GNOME 42

**Comment by qzed** [comment]
I assume this does not happen if you turn off auto-brightness in Gnome (and maybe also GDM)? As far as I know, that adjustment is handled by some user-space program, the kernel just reports these values. So I assume that that goes crazy somehow. Alternatively the values reported by the kernel could be wrong, so I guess you could try to monitor/log those somehow.

**Comment by FlyingPC** [comment]
It s maybe a bad evaluation of the amount of energy in battery compare to energy consumption.

**Comment by m1nicrusher** [comment]
From my experience, GNOME's auto brightness is pretty much unusable. It's too sensitive and changes too fast but not smoothly. However the bright side is: turning off auto brightness certainly saves more battery if you can constantly adjust your brightness manually according to environment.

**Comment by flying-foss** [comment]
The auto brightness is very responsive at my surface go 3 with ubuntu and surface kernel too. Coming from an old iPad Pro it's really jumpy and not smooth. When i use my surface with the pen, the rotation is the key for not getting crazy. The hand with the pencil should not be over the cameras, because if you do so, the brightness is getting very jumpy.
