### ISSUE TITLE
SL3 locked at minimum clock speed and runs very slowly. 

### ISSUE THREAD

**Issue by hydrobeam** [linux-surface/linux-surface#833]
Hi! For the past few days my laptop has been running extrmely slowly. It started when after waking from boot, I noticed that the battery indicator in KDE read 0% and stated that the battery was missing. I immediately started charging the machine and rebooted. After rebooting, the battery indicator was back to normal (it was at 92% capacity); however, the system was running extremely slow. I later found out that this was because it was constantly running at its bare minimum cpu frequency. Now, no matter what I try to do i can't entice my machine to go back to normal.

The slowness also persists when booting into Windows, so it's not exclusively a linux problem. I've tried the following to fix it:

- reboot (many times)
- shut down
- sleep
- force shutdown (by holding down the power button)
- charge the battery to full
- drain the battery completely (until I saw the low battery indicator) 

I also installed [intel_ucode](https://archlinux.org/packages/?name=intel-ucode).

I'm not sure if the laptop arbitrarily reached the end of its life, or if there's something to be done. Thank you for any help!

(Please let me know if you'd like me to include more information about my system below.)

### Environment

output from `i7z` (every frame is extremely similar to this)
```
Cpu speed from cpuinfo 1497.00Mhz
cpuinfo might be wrong if cpufreq is enabled. To guess correctly try estimating via tsc
Linux's inbuilt cpu_khz code emulated now
True Frequency (without accounting Turbo) 1497 MHz
  CPU Multiplier 15x || Bus clock frequency (BCLK) 99.80 MHz

Socket [0] - [physical cores=4, logical cores=8, max online cores ever=4]
  TURBO ENABLED on 4 Cores, Hyper Threading ON
  Max Frequency without considering Turbo 1596.80 MHz (99.80 x [16])
  Max TURBO Multiplier (if Enabled) with 1/2/3/4 Cores is  37x/36x/33x/33x
  Real Current Frequency 201.16 MHz [99.80 x 2.02] (Max of below)
        Core [core-id]  :Actual Freq (Mult.)      C0%   Halt(C1)%  C3 %   C6 %   C7 %  Temp      VCore
        Core 1 [0]:       200.99 (2.01x)        44.6    85.4       0       0    8.63    39      0.6799
        Core 2 [1]:       200.71 (2.01x)        43.8    86.8       0       0     7.3    40      0.6675
        Core 3 [2]:       201.16 (2.02x)        45.3    80.4       0       0    13.5    39      0.6825
        Core 4 [3]:       200.81 (2.01x)        46.6      83       0       0    10.8    42      0.6675

```

output from `cpupower frequency-info`
```
analyzing CPU 0:
  driver: intel_pstate
  CPUs which run at the same hardware frequency: 0
  CPUs which need to have their frequency coordinated by software: 0
  maximum transition latency:  Cannot determine or is not supported.
  hardware limits: 400 MHz - 3.70 GHz
  available cpufreq governors: performance powersave
  current policy: frequency should be within 400 MHz and 3.70 GHz.
                  The governor "powersave" may decide which speed to use
                  within this range.
  current CPU frequency: Unable to call hardware
  current CPU frequency: 201 MHz (asserted by call to kernel)
  boost state support:
    Supported: yes
    Active: yes
```
sample output from `lscpu`
```
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-1035G7 CPU @ 1.20GHz
    CPU family:          6
    Model:               126
    Thread(s) per core:  2
    Core(s) per socket:  4
    Socket(s):           1
    Stepping:            5
    CPU(s) scaling MHz:  5%
    CPU max MHz:         3700.0000
    CPU min MHz:         400.0000
    BogoMIPS:            2996.00
```
- Hardware model: Surface Laptop 3 (Intel) 13.5"
- Kernel version: 5.17.9-arch1-1-surface
- Distribution: Arch Linux

Link to `dmesg` output: https://pastebin.com/UMyQBQ9j

**Comment by hydrobeam** [comment]
The issue resolved itself after leaving the laptop untouched for a long time, completely draining the battery (such that the low battery indicator doesn't show up) and turning it on again. My thinking is that the battery randomly had some bug, and it needed some kind of ""reset"" before the cpu would allow itself to draw more power from it. Not sure if it's logical but that's my head canon.


> Q1: Have your problem started after recent Windows upgrade or firmware upgrade?

Nope, I hadn't touched Windows for months at this point, and after booting into windows while bugfixing and installing all the relevant firmware and OS updates, the issue still wasn't resolved.

**Comment by danielzgtg** [comment]
Will continue this discussion at #706
