### ISSUE TITLE
No tablet mode for SGO1 when Type Cover is folded

### ISSUE THREAD

**Issue by krnhotwings** [linux-surface/linux-surface#837]
(Used https://github.com/linux-surface/linux-surface/issues/735 as a reference for this issue)

With the type cover _detached_, SGO1 will properly enter tablet mode where screen autorotation will work and the on-screen keyboard will display from touch/tap inputs on key input fields.

With the type cover _attached_ and folded back, SGO1 will _not_ enter tablet mode such that screen autorotation will not work and the on-screen keyboard will not appear from touch inputs.

Using the above issue as a reference, I was able to gather the following:

```
$ sudo libinput debug-events

-event15  DEVICE_ADDED            Video Bus                         seat0 default group1  cap:k
-event0   DEVICE_ADDED            Power Button                      seat0 default group2  cap:k
-event1   DEVICE_ADDED            Lid Switch                        seat0 default group3  cap:S
-event3   DEVICE_ADDED            Microsoft Surface Type Cover      seat0 default group4  cap:k
-event4   DEVICE_ADDED            Microsoft Surface Type Cover Consumer Control seat0 default group4  cap:kp scroll-nat
-event13  DEVICE_ADDED            Microsoft Surface Type Cover Mouse seat0 default group4  cap:p left scroll-nat scroll-button
-event14  DEVICE_ADDED            Microsoft Surface Type Cover Touchpad seat0 default group4  cap:pg  size 94x52mm tap(dl off) left scroll-nat scroll-2fg-edge click-buttonareas-clickfinger dwt-on
-event9   DEVICE_ADDED            ELAN9038:00 04F3:261A Stylus      seat0 default group5  cap:T  size 211x140mm calib
-event6   DEVICE_ADDED            ELAN9038:00 04F3:261A             seat0 default group5  cap:t  size 208x140mm ntouches 10 calib
-event16  DEVICE_ADDED            Intel HID events                  seat0 default group6  cap:k
-event17  DEVICE_ADDED            Intel HID 5 button array          seat0 default group7  cap:k
-event2   DEVICE_ADDED            AT Translated Set 2 keyboard      seat0 default group8  cap:k
```

When cover is folded, when tablet is rotated while cover is folded, or when cover is unfolded:
```
-event17  KEYBOARD_KEY            +17.311s	KEY_UNKNOWN (240) pressed
 event17  KEYBOARD_KEY            +17.311s	KEY_UNKNOWN (240) released
 event17  KEYBOARD_KEY            +17.311s	KEY_UNKNOWN (240) pressed
 event17  KEYBOARD_KEY            +17.311s	KEY_UNKNOWN (240) released
```

```
$ sudo evtest /dev/input/event17

Input driver version is 1.0.1
Input device ID: bus 0x19 vendor 0x0 product 0x0 version 0x0
Input device name: "Intel HID 5 button array"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 114 (KEY_VOLUMEDOWN)
    Event code 115 (KEY_VOLUMEUP)
    Event code 116 (KEY_POWER)
    Event code 125 (KEY_LEFTMETA)
    Event code 240 (KEY_UNKNOWN)
    Event code 561 (?)
  Event type 4 (EV_MSC)
    Event code 4 (MSC_SCAN)
Properties:
Testing ... (interrupt to exit)
```

When cover is folded:
```
Event: time 1653582428.829337, type 4 (EV_MSC), code 4 (MSC_SCAN), value cb
Event: time 1653582428.829337, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653582428.829337, -------------- SYN_REPORT ------------
Event: time 1653582428.829363, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653582428.829363, -------------- SYN_REPORT ------------
Event: time 1653582428.829477, type 4 (EV_MSC), code 4 (MSC_SCAN), value cc
Event: time 1653582428.829477, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653582428.829477, -------------- SYN_REPORT ------------
Event: time 1653582428.829492, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653582428.829492, -------------- SYN_REPORT ------------
```

When cover is unfolded:
```
Event: time 1653582440.485773, type 4 (EV_MSC), code 4 (MSC_SCAN), value ca
Event: time 1653582440.485773, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653582440.485773, -------------- SYN_REPORT ------------
Event: time 1653582440.485815, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653582440.485815, -------------- SYN_REPORT ------------
Event: time 1653582440.485828, type 4 (EV_MSC), code 4 (MSC_SCAN), value cd
Event: time 1653582440.485828, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653582440.485828, -------------- SYN_REPORT ------------
Event: time 1653582440.485833, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653582440.485833, -------------- SYN_REPORT ------------
```

When cover is folded and screen rotated in any orientation:
(Output appears to be the same as when the cover is folded back)
```
Event: time 1653585054.773887, type 4 (EV_MSC), code 4 (MSC_SCAN), value cb
Event: time 1653585054.773887, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653585054.773887, -------------- SYN_REPORT ------------
Event: time 1653585054.773929, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653585054.773929, -------------- SYN_REPORT ------------
Event: time 1653585054.773944, type 4 (EV_MSC), code 4 (MSC_SCAN), value cc
Event: time 1653585054.773944, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 1
Event: time 1653585054.773944, -------------- SYN_REPORT ------------
Event: time 1653585054.773948, type 1 (EV_KEY), code 240 (KEY_UNKNOWN), value 0
Event: time 1653585054.773948, -------------- SYN_REPORT ------------
```

It's at this point where I get stuck. I tried looking through the various `/dev/hidrawX` devices using `hid-recorder`, but none are related to the type cover's folding functionality. `dmesg` shows these lines, which might be related?

```
[    5.515416] hid-generic 001F:8087:0AC2.0006: hidraw5: <UNKNOWN> HID v2.00 Device [hid-ishtp 8087:0AC2] on 
[    5.520479] idma64 idma64.0: Found Intel integrated DMA 64-bit
[    5.520879] hid-generic 001F:8087:0AC3.0007: hidraw6: <UNKNOWN> HID v2.00 Device [hid-ishtp 8087:0AC3] on 
[    5.521591] idma64 idma64.1: Found Intel integrated DMA 64-bit
[    5.521918] idma64 idma64.2: Found Intel integrated DMA 64-bit
```

Beyond this, I'm not sure what else I can provide since this is above my head.

### Environment

- Hardware model: Surface Go 1 with Type Cover
- Kernel version: 5.17.9-2.surface.fc36.x86_64
- Distribution: Fedora Workstation 36 (GNOME 42.1)

`dmesg` output:
https://gist.github.com/krnhotwings/b9dd2816d746d8f863b6e95ddfaa2581

**Comment by qzed** [comment]
> It's at this point where I get stuck. I tried looking through the various `/dev/hidrawX` devices using `hid-recorder`, but none are related to the type cover's folding functionality.

Generally, one HID device is split into multiple /dev/input devices, so those events should probably be sent over the keybord HID device.

**Comment by qzed** [comment]
Ah wait, you're getting those events from "Intel HID 5 button array", right? That should be handled by a separate driver: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel/hid.c. So that might need some adaption. Only had a quick look but this may be a start: https://github.com/torvalds/linux/blob/master/drivers/platform/x86/intel/hid.c#L112-L126.

**Comment by krnhotwings** [comment]
Phew, okay. As someone who doesn't know what they're doing, I managed to get tablet mode to work with the cover folded back! The issue is indeed the VGBS allow list. It was a bit of an ordeal to both figure out what I was doing and do it with a live Fedora USB stick since I've reinstalled Win10 on my SGO due to various usability issues in Fedora 36 (mostly Wayland, from my understanding...) Anywho, documenting whatever combination of keyboard presses that got things to work here:

(Did this on a separate F36 computer because there's not enough space on the default partition size, and I didn't want to mess around with resizing partitions.)
```sh
dnf download --source kernel-5.17.5-300.fc36 # As of 2021-06-04, F36 Workstation USB uses this kernel version
mkdir blah
rpm -i --root blah kernel-5.17.5-300.fc36.src.rpm
cd blah
tar xvf linux-5.17.5.tar.xz
```

On the SGO1, disable SecureBoot, boot into the F36 Live, connect the OS to your network, transfer the above resulting `linux-5.17.5` directory to the home directory of the live session (e.g. with `rsync`.) From the SGO1:

```sh
sudo dnf install kernel-devel-`uname -r`
cd linux-5.17.5
make oldconfig
make prepare
make scripts
nano drivers/platform/x86/intel/hid.c # Make changes (see codeblock below)
```

Add the following to `dmi_vgbs_allow_list`:
```
	{
		.matches = {
			DMI_MATCH(DMI_SYS_VENDOR, "Microsoft Corporation"),
			DMI_MATCH(DMI_PRODUCT_NAME, "Surface Go"),
		},
	},
```
(Note: It seems to be unnecessary to add the device info to `button_array_table`.)

Build and install:
```sh
make -C /lib/modules/`uname -r`/build M=`pwd`/drivers/platform/x86/intel modules
sudo rmmod intel_hid
sudo insmod drivers/platform/x86/intel/intel-hid.ko
```

Test cover fold auto-rotation and on-screen keyboard.

At this point, not sure how to proceed.

**Comment by qzed** [comment]
Nice work! Now you're on your way to become a kernel developer!

> (Note: It seems to be unnecessary to add the device info to button_array_table.)

As far as I can tell, the driver provides a couple of different buttons and switches. I guess if power/volume buttons work without that, then they're not handled via this driver, or at least that (sub-)interface.

> At this point, not sure how to proceed.

Submit it upstream! So what you'd want to do for that is bring it in proper patch form and then send it in.

Ideally, you start off with the respective upstream tree that you're submitting it to. In your case, that's https://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86.git/, specifically the `for-next` branch. So clone that (e.g. via `git clone https://git.kernel.org/pub/scm/linux/kernel/git/pdx86/platform-drivers-x86.git --branch for-next`) and apply your change.

Next, commit it. There are a couple of formalities to obey here: First, the subject line should contain the respective prefix of the subsystem and driver. You can look at commit logs for that, so it should look like `platform/x86/intel: hid:` (or `platform/x86: intel-hid:`, which seems to be the old prefix). So your commit subject/title line should be  something along the lines of `platform/x86/intel: hid: Add Surface Go to VGBS allow list` (feel free to change that if you come up with something better). Your commit should further contain a small text describing what that commit is intended to do (i.e. enable tablet-mode switch support on the Go). Lastly, you'll have to add a `Signed-off-by: Your Name <your email@xy.z>` line. Note that that needs to be the same email you're going to use to submit the patch. If you have your mail and name set up in git, you can also use `git commit -s` to automatically add this line. Also, anonymous contributions are unfortunately not allowed.

Now that you have a commit, you can generate a patch from it via `git format-patch -1`. It's best to check this patch before submission via `./scripts/checkpatch.pl --strict *.patch` for any style issues. If you encounter any, you should fix those.

Finally, it's time for submission. First, you need to figure out who to send it to. For that, you can use `./scripts/get_maintainer.pl *.patch`. This will spit out a list of maintainers and mailing lists and their addresses. Lastly, you can set up git to send the patch. This should be explained in the links below or in the git documentation. Then use `git send-email *.patch` to send in the mail. Here, you need to specify who to send it to with the `--to` and `--cc` options. Add the names and addresses returned by the `get_maintainer` script in the usual `"some name <some-address>"` format. You can use the `--dry-run` option to make sure everything is in order (e.g. subject line and addresses are picked up correctly).

For a full overview on how to submit a patch, there's also https://www.kernel.org/doc/html/latest/process/submitting-patches.html and https://kernelnewbies.org/FirstKernelPatch.

Also feel free to send a PR to https://github.com/linux-surface/kernel. I'll pick that up from there and integrate it into the patches here in this repo (or alternatively, I can also just apply the patch once you've submitted it).

**Comment by krnhotwings** [comment]
I've sent off the patch, but I'm not sure if I've done it correctly or not because it's not being listed [here](https://www.spinics.net/lists/platform-driver-x86/), which is linked from the vger.kernel.org. Not sure how frequently the archive is updated.

**Comment by qzed** [comment]
@krnhotwings Usually it's there in a couple of minutes. Although it might take a bit longer if traffic across the lists is high.

> edit: Oh... didn't realize that I got a bounce-back for [alex.hung@canonical.com](mailto:alex.hung@canonical.com). It appears that user no longer exists, so I suppose that also means that the maintainer for drivers/platform/x86/intel/hid.c would need to be updated.

The message should still go to everyone else. I assume Hans might notice the bounce as well when replying, but it might be a good idea to bring that up in a reply as well.

**Comment by qzed** [comment]
It's online now: [link to patchwork](https://patchwork.kernel.org/project/platform-driver-x86/patch/20220607213654.5567-1-krnhotwings@gmail.com/).

**Comment by krnhotwings** [comment]
Nice, I think we're all set. Thanks for the guidance; I've learned quite a bit!

**Comment by qzed** [comment]
Latest kernels include the patch.
