### ISSUE TITLE
AMD Surface 4 laptop keyboard not usable before login screen for disk decryption/open boot menu

### ISSUE THREAD

**Issue by Phibedy** [linux-surface/linux-surface#839]
Windows surface 4 amd laptop
UEFI-Version: 3.103.140
Ubuntu 22.04 LTS

What I read:
* https://github.com/linux-surface/linux-surface/issues/216
* https://github.com/linux-surface/linux-surface/wiki/Surface-Laptop-4
* https://gitlab.freedesktop.org/drm/amd/-/issues/1204
* [IOMMU](https://github.com/linux-surface/linux-surface/discussions/480#discussioncomment-1932546)

What I did:
* Installed everything as said in the wiki
* changed `GRUB_CMDLINE_LINUX=""` to GRUB_CMDLINE_LINUX="amd_iommu=off iommu=off"

It would be great if 
```
Each device comes with its own set of quirks that need some tweaking. Visit the [Hardware](https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features) page, and look at your device's wiki page to find more instructions.
```
would be not in "Post-Installation" because I thought that I messed up the installation because I was getting a black screen on booting becaucase I had to change `GRUB_CMDLINE_LINUX=""` to GRUB_CMDLINE_LINUX="amd_iommu=off iommu=off`

Of course I should have read the whole page at first, but it seemed to be a nice "step by step guide" (which it really is, thank you for that) that I just followed so I missed that information :)

[Description of the bug or feature]
I am using LVM with encryption (full disk). The problem is, that the keyboard is not working before the encryption is done.
With an external keyboard I can also choose between the different kernel version etc. which is not possible because the F2-key does nothing on startup. I can enter the bios with "windows + F4" but the "F2" key does not open the boot menu.

The interesting part is, that if I enter the bios -> close it (restart) -> the boot menu shows up without pressing F2 and I can use the keyboard to choose the version. But after choosing the version the unlock disk prompt shows and I can not use the keyboard to put in the password. I have to connect one via usb.

<details><summary>`dmesg` output</summary>
https://pastebin.com/nKCapJ4j
</details>

Thank you for your help :)

**Comment by Phibedy** [comment]
Ah I just found this: https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption
I will give it a try :)

**Comment by Phibedy** [comment]
I can't update initramfs

I added a file in `etc/initramfs-tools/conf.d/`
content:
```
add_drivers+=" surface_hid_core surface_hid surface_aggregator_registry surface_aggregator pinctrl_amd 8250_dw"
````

console output:
```
Surface-Laptop-4:/etc/initramfs-tools/conf.d$ sudo update-initramfs -u
update-initramfs: Generating /boot/initrd.img-5.17.9-surface
/usr/sbin/mkinitramfs: 1: /etc/initramfs-tools/conf.d/linux-surface-disk-encryption.conf: add_drivers+= surface_hid surface_aggregator_registry surface_aggregator pinctrl_amd 8250_dw: not found
```

even if I only add  `surface_hid_core` it can't find it.

Would be great if someknow could give me a hint what I am missing :)

**Comment by qzed** [comment]
IIRC the `add_drivers` directive is for dracut, According to [this](http://manpages.ubuntu.com/manpages/kinetic/man5/initramfs.conf.5.html) you may want to look for a `MODULES` variable, so if it's the same as on Arch you want `MODULES=(surface_hid_core surface_hid ...)`. It should be described in `/etc/initramfs-tools/initramfs.conf`, I think.

One additional note: I've noticed that I forgot to update that page, you'll also need to add the `surface_aggregator_hub` module.

**Comment by Phibedy** [comment]
@qzed 

Thank you, it works :rocket: 

For completion I added 

```
surface_hid_core
surface_hid
surface_aggregator_registry
surface_aggregator_hub
surface_aggregator
pinctrl_amd
8250_dw
```
to ´/etc/initramfs-tools/modules`

**Comment by Schykle** [comment]
Hopefully I'm not necromancing this thread in a bad way!

I'm running into the same issue on my SL4(AMD), but I'm using Fedora Silverblue, not Ubuntu/Fedora/etc.

There seems to be some slight differences in this particular process due to the immutable deployment as far as I'm aware? Is there some potential guidance for how this should be done?

**Comment by m1nicrusher** [comment]
For Fedora instead of using ```update-initramfs``` you'll need ```dracut```. Is that the part you couldn't follow their method?

**Comment by tomreyn** [comment]
Thanks for your efforts. Related issue on an Intel Gen11 Surface Laptop 4 (Model 1950):

[Ubuntu bug 2007050: Check for Microsoft Surface keyboard modules when generating initrd](https://bugs.launchpad.net/ubuntu/+source/initramfs-tools/+bug/2007050)

**Comment by qzed** [comment]
This seems to be solved (https://github.com/linux-surface/linux-surface/issues/839#issuecomment-1140287888), so I'm closing this.

I can't really speak to any initram-generator-specific hooks for including the modules. Having something like that would be nice, but it's beyond the scope of this project.
