### ISSUE TITLE
Module build error on Fedora

### ISSUE THREAD

**Issue by quo** [linux-surface/linux-surface#843]
I don't use Fedora myself, but apparently the ithc module fails to build with kernel 5.17.9-2.surface.fc36.x86_64, see: https://github.com/quo/ithc-linux/issues/6

The problem seems to be that CONFIG_CC_VERSION_TEXT is getting double quoted.

A bit of Googling led me to a possible solution here:
https://www.spinics.net/linux/fedora/fedora-kernel/msg13900.html

**Comment by qzed** [comment]
So it seems like we should change

https://github.com/linux-surface/linux-surface/blob/fbeb52975fb8ae88d3293e2b20b2cb72e0b19cee/pkg/fedora/kernel-surface/kernel-surface.spec#L305-L310

@StollD ?

**Comment by StollD** [comment]
I always kinda assumed this was an upstream bug .. idk why.

I applied the change that @quo linked, thank you!

**Comment by qzed** [comment]
New kernels are building and should be available later today.

**Comment by qzed** [comment]
New kernels are available, so I'm going to close this. If anyone still experiences this issue feel free to comment and ping me and I'll open it up again.
