### ISSUE TITLE
SP8 Tablet mode

### ISSUE THREAD

**Issue by j4ckgrey** [linux-surface/linux-surface#848]
Hi there, since we already have SP8 touch and pen support working with ithc and iptsd experimental, I was wondering if I can get a proper tablet mode working on my device. Any advice regarding the matter? thanks in advance.

**Comment by j4ckgrey** [comment]
> From the kernel side of things, `SW_TABLET_MODE` should already be supported. You can verify that this works with `evtest`. The rest depends on the desktop environment.

I have the feeling that I must install Archlinux to test everything properly 😁

**Comment by qzed** [comment]
The `evtest` tool should be available on pretty much any distribution.

**Comment by qzed** [comment]
The kernel does not enforce anything. It just provides an input event. And I don't know whether KDE does something with that. I know that Gnome does (or at least tries to do...).

**Comment by j4ckgrey** [comment]
> The kernel does not enforce anything. It just provides an input event. And I don't know whether KDE does something with that. I know that Gnome does (or at least tries to do...).

Thanks, mate. Will install Gnome today and check it out.

**Comment by NP-chaonay** [comment]
I think SLS using similar system for tablet mode (GPIO), but as I check value from /sys/class/gpio (export every pin, see every pins value, both edge detection of none,falling,rising,both) and from pinctrl (im not sure about this but as check no output different on different device mode). And some of GPIO pins is locked from accessing.

I assume that the one that locked contains info about it or it contains in pinctrl driver.
I think driver developer find internal wokring (which I think not done completely) and then implement to input class event, and then X11/Wayland can using it.

**Comment by qzed** [comment]
SP8 tablet mode should work via https://github.com/linux-surface/kernel/blob/v5.18-surface-devel/drivers/platform/surface/surface_kip_tablet_switch.c. That uses the type cover interface of SAM. Unfortunately that (or something like this) didn't work when I had someone test it on the SLS.

if the SLS behaves like the other devices, I'd assume tablet mode events are also sent via the SAM module, just using a different interface. That way, they could also differentiate between the tent mode thing and full tablet mode. They do that on the Surface Books already, and the SP8 also has different values for different type cover positions (see [here](https://github.com/linux-surface/kernel/blob/v5.18-surface-devel/drivers/platform/surface/surface_kip_tablet_switch.c#L21-L27)). So I doubt it's just a simple GPIO pin.

**Comment by qzed** [comment]
I'm still not convinced about GPIOs. Normally, they are declared in ACPI (`GpioIo(...)`/`GpioInt(...)`), but the SLS doesn't seem to show any GPIO for tablet mode. Maybe they're re-using `MSBT`/`MSHW0040`, but that's normally for power and volume buttons as GPIO keys.

Also, don't get confused about the `GPIO Laptop or Slate Indicator Driver`, I have the same on my SB2 but that doesn't use GPIOs for tablet mode. As far as I can tell, that just looks like an indicator that tablet mode is supported on the device.

**Comment by qzed** [comment]
If you want to, you can try logging SAM events on Windows with IRPMon. See https://github.com/linux-surface/surface-aggregator-module/wiki/Development.

**Comment by NP-chaonay** [comment]
> I'm still not convinced about GPIOs. Normally, they are declared in ACPI (`GpioIo(...)`/`GpioInt(...)`), but the SLS doesn't seem to show any GPIO for tablet mode. Maybe they're re-using `MSBT`/`MSHW0040`, but that's normally for power and volume buttons as GPIO keys.
> 
> Also, don't get confused about the `GPIO Laptop or Slate Indicator Driver`, I have the same on my SB2 but that doesn't use GPIOs for tablet mode. As far as I can tell, that just looks like an indicator that tablet mode is supported on the device.

Thanks, so if that true then I am tricked by driver name and description.

**Comment by j4ckgrey** [comment]
I got one question, why S7+ marked as tablet mode supported in the Kernel Matrix? If so, they both are very similar

**Comment by qzed** [comment]
The type cover on the SP8 and SP7+ are completely different. SP8 (like SPX) communicates via SAM whereas SP7+ and earlier use USB.

**Comment by qzed** [comment]
Also the wiki should probably get updated since https://github.com/linux-surface/kernel/blob/v5.18-surface-devel/drivers/platform/surface/surface_kip_tablet_switch.c should provide tablet mode info. Would be good if someone could confirm that with evtest though... so far I've tested the driver only on my SPX.

**Comment by qzed** [comment]
> Thanks, so if that true then I am tricked by driver name and description.

If I remember correctly, the `GPIO Laptop or Slate Indicator Driver` should be this: https://github.com/linux-surface/acpidumps/blob/master/surface_laptop_studio_1/ssdt10.dsl#L1092-L1100 in ACPI. So it's just a device node without any data or hardware associated to it.

**Comment by qzed** [comment]
Ah right, sorry. Just run `sudo evtest` (should be provided by the `evtest` package on Ubuntu) and select the `KIP` / tablet mode switch device (or something named along those lines). Then fold the type cover back and/or disconnect it. You should see `SW_TABLET_MODE` events in the command output and its value should change to `1` if the cover is folded back/disconnected and `0` if it's in laptop mode.

**Comment by j4ckgrey** [comment]
> Ah right, sorry. Just run `sudo evtest` (should be provided by the `evtest` package on Ubuntu) and select the `KIP` / tablet mode switch device (or something named along those lines). Then fold the type cover back and/or disconnect it. You should see `SW_TABLET_MODE` events in the command output and its value should change to `1` if the cover is folded back/disconnected and `0` if it's in laptop mode.

should also work on Manjaro Gnome? I currentl run Manjaro Gnome

**Comment by qzed** [comment]
Yeah, should also work there, but the package might be named differently.

**Comment by j4ckgrey** [comment]
I will just give all the output here

**Comment by j4ckgrey** [comment]
I did mkdir, and the command went through but it didnt work. This was the output
![PXL_20220610_193140468](https://user-images.githubusercontent.com/47457650/173120567-54f28df7-2978-4cef-ae30-fc5c13e288ab.jpg)

**Comment by j4ckgrey** [comment]
I ran it, but nothing really came out when i did what tou said

![PXL_20220610_194617445](https://user-images.githubusercontent.com/47457650/173122551-0be2c204-57f5-46e8-a98c-d0526f512998.jpg)

**Comment by qzed** [comment]
You're using the original type cover for that device, right? And you tried to fold the cover fully back? Can you try disconnecting and re-connecting it while keeping `evtest` running?

**Comment by j4ckgrey** [comment]
> You're using the original type cover for that device, right? And you tried to fold the cover fully back? Can you try disconnecting and re-connecting it while keeping `evtest` running?

Sorry, i dont have the cover at all..... Im using wireless keyboard and mouse

**Comment by qzed** [comment]
Ahhh okay yeah in that case the Surface Aggregator interface won't work, sorry. That interface is for the typecover only.

For an external keyboard and mouse, tablet mode needs to be decided by the desktop environment. I believe Gnome has some heuristics on that.

**Comment by j4ckgrey** [comment]
I reinstalled ubuntu, its much easier for me than Manjaro, regarding the ithc and iptsd! So far they work good. I also installed gnome desktop which gives me the screen keyboard option whenever no keyboard is connected, so i think so far so good.
I just beed auto rotate and 120hz, i keep searching online, if i get any solution will share it here, and if you reach any news please just drop a comment and of course if you need to test anything im available 😁

> Ahhh okay yeah in that case the Surface Aggregator interface won't work, sorry. That interface is for the typecover only.
> 
> For an external keyboard and mouse, tablet mode needs to be decided by the desktop environment. I believe Gnome has some heuristics on that.

**Comment by j4ckgrey** [comment]
> I'm going to close this then.

Hi there, just wanted to say that i got the keyboard and the tablet mode works, so i believe you can mark this one out
