### ISSUE TITLE
Install displaylink drivers with linux-surface kernel

### ISSUE THREAD

**Issue by lennertcc** [linux-surface/linux-surface#856]
Hello,
I installed Fedora 36 on a Surface Laptop 1 and switched to the linux-surface kernel using the guide in this repo.

From there I am trying to install the displaylink drivers from https://github.com/displaylink-rpm/displaylink-rpm but I'm stuck on installing evdi-1.11.0. The error occurs when running `sudo dkms build evdi/1.11.0` as it cannot find the kernel headers. 

Error message:
Error! Your kernel headers for kernel 5.18.4-1.surface.fc36.x86_64 cannot be found at /lib/modules/5.18.4-1.surface.fc36.x86_64/build or /lib/modules/5.18.4-1.surface.fc36.x86_64/source.
Please install the linux-headers-5.18.4-1.surface.fc36.x86_64 package or use the --kernelsourcedir option to tell DKMS where it's located.

Can anyone provide any insight on how to proceed?

### Environment

- Hardware model:  Surface Laptop 1 (X86)
- Kernel version: Linux Surface.home 5.18.4-1.surface.fc36.x86_64 # 1 SMP PREEMPT_DYNAMIC Thu Jun 16 18:38:49 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: Fedora 36

**Comment by NP-chaonay** [comment]
each kernel build have header for building driver/kernel module

on debian linux-surface repo, it also have linux header package, so I think on fedora will also have (as who maintain linux-surface mostly using fedora not debians/ubuntu)

so you have to find if the linux-surface repo contains header package.

**Comment by qzed** [comment]
On Fedora, that's `kernel-surface-devel`.

**Comment by lennertcc** [comment]
> On Fedora, that's `kernel-surface-devel`.

Thanks! I’ve been browsing that repo but did not recognize that package by name as the header package.
