### ISSUE TITLE
Complete system freeze on Xorg start (SLS)

### ISSUE THREAD

**Issue by dbeal-eth** [linux-surface/linux-surface#857]
I recently updated my Linux surface kernel. Unfortunately, when I attempt to start my X session (with `startx`), the entire system freezes before Xorg finishes starting. I am not able to switch to another TTY or (as far as I know) take any other action to restore the system other than holding the power button.

I already installed the newly required kernel module `ithc` driver and verified it is loaded with `lsmod` .

No Xorg logs are recorded, and nothing out of the ordinary is displayed on-screen when the system freezes. It simply freezes the display and no further action can be taken.

Also after I completed this most recent update, the kernel is logging much more than it used to to the tty. Not sure what that is about.

### Environment

- Hardware model: Surface Laptop Studio
- Kernel version: Linux version 5.18.4-arch1-1-surface (linux-surface@archlinux) (gcc (GCC) 12.1.0, GNU ld (GNU Binutils) 2.38) # 1 SMP PREEMPT_DYNAMIC
- Distribution: Arch Linux

<details><summary>`dmesg` output</summary>

see pastebin https://pastebin.com/3aUNKxya

</details>

**Comment by NP-chaonay** [comment]
so does kernel panic?

there is one of ways to know, login in console and play sound in loop in alsa hw:0,0 device (using alsa, pulseaudio dont work)  and then login on xorg. if sound is lost or repeat-from-audio-buffer as beep-alike mean that kernel is hang or panic.

maybe try to modprobe -r ithc first

for another way of debugging what does recent surface kernel version that it works

5.18.4 seem to just adding sls tablet mode

**Comment by dbeal-eth** [comment]
> 

Will try the sound thing when I get a chance, that's a cool trick.

I will get the most recent working surface kernel as well, when I get a chance.

I forgot to mention, I already tried starting xorg without having ithc enabled. That's the reason why I checked to install it in the first place.

**Comment by dbeal-eth** [comment]
> so does kernel panic?
> 
> there is one of ways to know, login in console and play sound in loop in alsa hw:0,0 device (using alsa, pulseaudio dont work) and then login on xorg. if sound is lost or repeat-from-audio-buffer as beep-alike mean that kernel is hang or panic.
> 

hey so I verified its not a kernel panic with the following steps:

1. run `speakertest` command. Observe white noise sound playing
2. switch to another TTY using Ctrl-Alt-F2
3. Log in and run `startx`

Result: Sound continues playing but freeze occurs as described above. Also, the keyboard doesnt seem to be working (If I enter another TTY using the keyboard I would expect to hear the sound stop because I'm not logged in, but that does not occur)

**Comment by NP-chaonay** [comment]
>   (If I enter another TTY using the keyboard I would expect to hear the sound stop because I'm not logged in, but that does not occur)

if you playing sound through alsa via hardware direct, then switching tty dont interrupt the sound, that seem to work with systemd or user manager thing; alsa dont support that;

So for example if you using music player with ALSA method on hw:0,0 (with help of pasuspender); if you switch to another tty, the sound dont stopped. That's why I recommended to using alsa hw direct instead of console pulseaudio. Because if tty session's user is changed, then the sound lost, and no longer debuggable.

So let goto the main topic, does your SLS have dGPU; misconfig seem to have Xorg/Wayland crash (and SLS dont have sysrq so only way to know if system is wholely crashed or not and to interact system is to using SSH or GUI remote-desktop (if it works))

**Comment by dbeal-eth** [comment]
> So let goto the main topic, does your SLS have dGPU; misconfig seem to have Xorg/Wayland crash (and SLS dont have sysrq so only way to know if system is wholely crashed or not and to interact system is to using SSH or GUI remote-desktop (if it works) or using something that debuggable like alsa audio)

problem solved!

Upon inspecting my laptop's devices, I realized that it has both "Intel Iris" and "NVIDIA 3050 Ti" (probably the dGPU that you describe), but this whole time I have been using the NVIDIA display driver as my main.

So to fix the problem, I took the following actions:

```
pacman -S xf86-video-intel
modprobe -r nvidia
```

after that, I successfully started xorg

Obv if I want to use the nvidia driver I can just configure bumblebee or primusrun or whatever the dual GPU tool to use is these days, but now everything makes a lot more sense.

Thanks @NP-chaonay for your help!

**Comment by NP-chaonay** [comment]
> > So let goto the main topic, does your SLS have dGPU; misconfig seem to have Xorg/Wayland crash (and SLS dont have sysrq so only way to know if system is wholely crashed or not and to interact system is to using SSH or GUI remote-desktop (if it works) or using something that debuggable like alsa audio)
> 
> problem solved!
> 
> Upon inspecting my laptop's devices, I realized that it has both "Intel Iris" and "NVIDIA 3050 Ti" (probably the dGPU that you describe), but this whole time I have been using the NVIDIA display driver as my main.
> 
> So to fix the problem, I took the following actions:
> 
> ```
> pacman -S xf86-video-intel
> modprobe -r nvidia
> ```
> 
> after that, I successfully started xorg
> 
> Obv if I want to use the nvidia driver I can just configure bumblebee or primusrun or whatever the dual GPU tool to use is these days, but now everything makes a lot more sense.
> 
> Thanks @NP-chaonay for your help!

in you case, if using nvidia not noveau.

if nvidia prime is configured properly, you can use whole desktop with nvidia.
if cannot be fixed it, then you have alternative way to avoid nvidia by set to on-demand or intel mode in nvidia-prime.

but alternatively you can using bumblebee (idk if that project be inactive/discontinue) or using noveau (if dual gpu setup is done correctly, if you using noveau, it will setup as discrete gpu and you have to set DRI app environmental var (this work same way as nvidia-prime on-demand mode); perhaps I think one can setup only nvidia render on noveau but idk.)
