### ISSUE TITLE
Fedora's 5.18.4-1 build size is oddly too big

### ISSUE THREAD

**Issue by Nexxkinn** [linux-surface/linux-surface#858]
The recent 5.18 kernel build for Fedora distro are unnecessarily way too big compared to other distro and previous kernel versions.
https://github.com/linux-surface/linux-surface/releases/tag/fedora-36-5.18.4-1

864 MB compared to 71 MB on 5.17.14 and 67 MB on ubuntu distro
### Environment

- Hardware model: 
- Kernel version: 
- Distribution:

**Comment by qzed** [comment]
New kernels are available now and they're normal size again.
