### ISSUE TITLE
SP8 - Screen flickering

### ISSUE THREAD

**Issue by aleksfadini** [linux-surface/linux-surface#862]
Using xorg and i3 with dotfiles that work on other machines (including SP6!) I get constant flickering, as if the brightness was oscillating btw the current value and a much lower value, multiple times each second. Adjusting brightness up and down stop this flickering for about a second. 

The flickering can be even seen in this video.
It does not happen in Windows 11.

### Environment
Hardware model: Surface Pro 8
Kernel version: 5.18.5-arch1-1-surface
Distribution: Arch Linux

<details><summary>`xorg.log` output</summary>

https://pastebin.com/YSjPmxkf

</details>

https://user-images.githubusercontent.com/16273381/175164786-0c619214-63ec-434d-a0ca-3b93859acddc.mp4

**Comment by aleksfadini** [comment]
I solved this issue myself, by installing intel microcode. That was entirely the cause of constant flickering.
Refer to this for more details: https://wiki.archlinux.org/title/microcode

on arch, all I needed to do is this:

```
sudo pacman -S intel-ucode
sudo grub-mkconfig -o /boot/grub/grub.cfg

```

and reboot.

**Comment by aleksfadini** [comment]
leaving it here for reference, as others may have the same issue on the SP8

**Comment by j4ckgrey** [comment]
> 

How do you run it on ubuntu?

**Comment by aleksfadini** [comment]
I'm using arch, not Ubuntu

**Comment by j4ckgrey** [comment]
> I'm using arch, not Ubuntu

I know, i have the flickering as well while using ubuntu on xorg and wanted to fix it, 5hought you know how to give these commands in ubuntu

**Comment by aleksfadini** [comment]
It seems easy enough on Ubuntu. 
https://linux-packages.com/ubuntu-focal-fossa/package/intel-microcode

In general, Google how to install intel-microcode on Ubuntu or post on your distro forums for further help. It seems to be as easy as

sudo apt install intel-microcode

**Comment by NP-chaonay** [comment]
> > I'm using arch, not Ubuntu
> 
> I know, i have the flickering as well while using ubuntu on xorg and wanted to fix it, 5hought you know how to give these commands in ubuntu

for grub update on ubuntu you just use ```update-grub``` however some package configurating, require update-grub to be auto run when install, but I still recommended to re run update-grub for making thing sure

[j4ckgrey](https://github.com/j4ckgrey)

**Comment by j4ckgrey** [comment]
Thank you, guys. Appreciate the help. One side question, could you fix the touch keyboard to work on apps while running wayland?

**Comment by NP-chaonay** [comment]
> Thank you, guys. Appreciate the help. One side question, could you fix the touch keyboard to work on apps while running wayland? It's a general wayland bug, not surface kernel

on gnome-shell 42.2 wayland, now osk on touch is not working like  version 42.1, only some cae such as text search in gnome overview is bring up osk, but on gedit, it is no longer bring it up on touch (gedit is wayland). so you have to manually swipe up from screen to bring osk. this all dont require to force enable in accessibility settings.

**Comment by aleksfadini** [comment]
Could it be that Intel microcode in Ubuntu is not updated to the latest? 
In Arch it was updated this May

https://archlinux.org/packages/extra/

**Comment by fiafrate** [comment]
> Could you check you installed this one?
> 
> https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/releases/tag/microcode-20220510

Yes it should be the same:

https://packages.ubuntu.com/jammy/intel-microcode

> Also, if it's the same issue I had, changing the brightness also stopped flickering for around one second.

Yes it does in fact stop for a fraction of a second

**Comment by aleksfadini** [comment]
Looks the same. Other than checking that the microcode is loaded properly (with `dmesg | grep microcode`) I have no other ideas. That's what fixed it for me.

**Comment by fiafrate** [comment]
Actually the output of  `sudo dmesg | grep microcode` reads
```
[    0.000000] microcode: microcode updated early to revision 0xa4, date = 2022-02-01
[    0.793166] microcode: sig=0x806c1, pf=0x80, revision=0xa4
[    0.793255] microcode: Microcode Update Driver: v2.2.
```
even though it seems that I have installed the latest: `apt list intel-microcode` shows

`intel-microcode/jammy-updates,jammy-security,now 3.20220510.0ubuntu0.22.04.1 amd64 [installed]`

Thanks for your help!

**Comment by aleksfadini** [comment]
I'm not familiar with Ubuntu, but it seems you installed the package but didn't implement the new microcode. Did you refresh your grub? I'd advise to look at the Ubuntu microcode docs and do all the steps.

**Comment by aleksfadini** [comment]
> > > I'm using arch, not Ubuntu
> > 
> > 
> > I know, i have the flickering as well while using ubuntu on xorg and wanted to fix it, 5hought you know how to give these commands in ubuntu
> 
> for grub update on ubuntu you just use `update-grub` however some package configurating, require update-grub to be auto run when install, but I still recommended to re run update-grub for making thing sure
> 
> [j4ckgrey](https://github.com/j4ckgrey)

@fiafrate as you can see, even reading this thread more carefully might prove fruitful.

**Comment by fiafrate** [comment]
> You might be just a ‘grub-update‘ away.

Nope, already done that multiple times. Maybe people more familiar with ubuntu can help. Thanks a lot!

**Comment by zed-wong** [comment]
> > You might be just a ‘grub-update‘ away.
> 
> Nope, already done that multiple times. Maybe people more familiar with ubuntu can help. Thanks a lot!

I'm facing the same issue. `grub-update` didn't work.

**Comment by fiafrate** [comment]
Apparently my issue was caused by "Panel Self Refresh (PSR), a power saving feature used by Intel iGPUs is known to cause flickering in some instances" as mentioned [here](https://wiki.archlinux.org/title/intel_graphics). So it does not seem to be a distribution related issue after all.
The workaround to disable this feature is to add "i915.enable_psr=0" to the default GRUB command line in /etc/defaults/grub, so that it looks like 
```GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_psr=0"```
followed by a GRUB update.

**Comment by Irlee** [comment]
I think it may cased by PSR, however, this problem also occurs in Windows11（SP7) . When I updated the intel Iris Plus Graphics driver, the situation still didn't improve. I uninstalled ubuntu22.04 for SP7, because I will not use dual systems for a while in the future. This problem still occurs sometimes, but it's not as obvious. I'm starting to suspect that there might be a hardware problem. After that I downloaded WSL of ubuntu22.04 in microsoft store. Everything goes well.

**Comment by WolfGangsta** [comment]
An extra data point--this flickering occured on my SP5 (2017) running Ubuntu 23.04, GNOME on Wayland. Move the mouse, it stops; wait a second, it starts again, just as described on the other models. I haven't noticed anything amiss on my Windows 10 partition.

> Apparently my issue was caused by "Panel Self Refresh (PSR), a power saving feature used by Intel iGPUs is known to cause flickering in some instances" as mentioned [here](https://wiki.archlinux.org/title/intel_graphics). So it does not seem to be a distribution related issue after all. The workaround to disable this feature is to add "i915.enable_psr=0" to the default GRUB command line in /etc/defaults/grub, so that it looks like `GRUB_CMDLINE_LINUX_DEFAULT="quiet splash i915.enable_psr=0"` followed by a GRUB update.

Followed these instructions (I believe you meant /etc/default/grub, sans the s). The flicker's gone, thank you!

Asking as a kernel know-nothing: can this fix be applied to the kernel by default?

**Comment by christiaan78** [comment]
Adding another successful fix. Had the same after installing Ubuntu on my Surface Pro 4 laptop. Flickering when I stopped moving the mouse. Editing the grub like mentioned (adding "i915.enable_psr=0), doing a grub update (sudo update-grub) and rebooting fixed the issue for me.

**Comment by Maxwellads** [comment]
Yet another successful fix on my Surface Book Gen1. It never flickered before I used it for a while, then ANY Linux distribution would have this issue. I think the flickering somehow damaged my screen, making it to have some areas "burnt". Maybe we should disable it as default.
