### ISSUE TITLE
Can I delete old kernels?

### ISSUE THREAD

**Issue by olyop** [linux-surface/linux-surface#867]
I have been following this [guide](https://ask.fedoraproject.org/t/old-kernels-removal/7026/2) on how to remove old unused kernels from linux (Fedora 36, Surface Laptop 3).

I just wanted to check if it would interfere with the custom surface kernel in any way and if this is a good idea?

```bash
$ rpm -q kernel-core
kernel-core-5.16.8-300.fc36.x86_64
kernel-core-5.17.5-300.fc36.x86_64
kernel-core-5.18.6-200.fc36.x86_64

$ uname -a
Linux surface 5.18.7-1.surface.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jun 25 23:36:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by qzed** [comment]
As far as I know, Fedora only ever keeps 3 versions around. You can change that with config options to two, but I wouldn't recommend to remove all old kernels or remove all stock kernels completely. In case of problems you can then still fall back to those.
