### ISSUE TITLE
[SP7P] [BUG] Type Cover not working when reconnected to Surface.

### ISSUE THREAD

**Issue by Pairman** [linux-surface/linux-surface#882]
[Description of the bug or feature]

Type Cover is not working when reconnected to the device. However reboot the device or turn off and on the screen (or in other words suspend and wake again) can fix it. The device can actually detect the reconnection, judging by the "Lock Screen Rotation" option of GNOME disappearing from control center.

### Environment

- Hardware model: Surface Pro 7 Plus (i5-1135G7, 8g RAM) ; Surface Type Cover
- Kernel version: ```Linux fedora 5.18.11-1.surface.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 21 02:40:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```
- Distribution: Fedora Linux 36 (Workstation Edition) ; GNOME 42.3 ; Wayland

[Dmesg output]
[demsg.txt](https://github.com/linux-surface/linux-surface/files/9234207/demsg.txt)

**Comment by NP-chaonay** [comment]
why so idk if this unimplented or wrong implmented or bug that when discconnected

it transform to non-tablet mode.

but if I not wrong, I think I see similar issues in this repo

**Comment by Pairman** [comment]
Update: This issue seems to only happen for the first time after boot. After going through a suspend, the surface type cover can be normally detected and work after detachments

**Comment by qzed** [comment]
Sounds a bit similar to #685

**Comment by Pairman** [comment]
Not encountering this for quite some times, so I'm closing this issue.
