### ISSUE TITLE
(SLS) Wifi is not able to do init-config when booting Linux from Windows hibernation with Wifi remained enabled

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/linux-surface#886]
I using iwlwifi on SLS on Ubuntu 22.04 LTS
the problem is similar to #30

when I do hibernate on Windows, and start system, wifi is not appeared. (and in dmesg will reported error about something but I will tell later #TODO# ) 

I have not try do 2nd rebooting to Linux nor trying hard reset
which both of them I will test them. #TODO#

But If I shutdown/reboot from Windows or hibernate from Windows with Wifi disabled.
everything go fine.

_Originally posted by @NP-chaonay in https://github.com/linux-surface/linux-surface/issues/30#issuecomment-1206037552_

**Comment by NP-chaonay** [comment]
seem to be solve by using new intel driver in Windows
idk if this 100% fixed
but it seem that driver do the job before hibernate is don in windows side

**Comment by Hades32** [comment]
@NP-chaonay what driver exactly are you using? I have all updates installed available via WU and I still have the issue

**Comment by NP-chaonay** [comment]
@Hades32

> @NP-chaonay what driver exactly are you using? I have all updates installed available via WU and I still have the issue

https://www.intel.com/content/www/us/en/support/intel-driver-support-assistant.html
