### ISSUE TITLE
Any way to manually install the Surface Kernel files?

### ISSUE THREAD

**Issue by FlailAway** [linux-surface/linux-surface#888]
[Description of the bug or feature]

### Environment

- Hardware model: 
GO 3
- Kernel version: 
5.4.0-91
- Distribution: 
Linux Mint + MATE 20.3
<details><summary>`dmesg` output</summary>
No Internet with semi-fixed GO-3 20-miles from home. Out in the boonies it runs a well pump for cattle.

I am having touch screen issues (no right-click) with stock Mint+MATE.

Where can I get the actual kernel files to manually install? I looked at the .zip but only patches. Can I path the current one somehow?
e.g. 
  amd64/linux-headers-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb
  amd64/linux-headers-5.7.7-050707_5.7.7-050707.202007010943_all.deb
  amd64/linux-image-unsigned-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb
  amd64/linux-modules-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb

```
please provide a copy of `dmesg` here if possible

```

</details>

**Comment by FlailAway** [comment]
WTF: It cut off my description etc. Here it is.
*************************************************
No Internet with semi-fixed GO-3 20-miles from home. Out in the boonies it runs a well pump for cattle.

I am having touch screen issues (no right-click) with stock Mint+MATE-20.3 and would like to try the surface kernel.

Can I get the actual kernel files to manually installl?
e.g. 
  amd64/linux-headers-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb
  amd64/linux-headers-5.7.7-050707_5.7.7-050707.202007010943_all.deb
  amd64/linux-image-unsigned-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb
  amd64/linux-modules-5.7.7-050707-generic_5.7.7-050707.202007010943_amd64.deb

**Comment by qzed** [comment]
Kernel packages are available in the ["releases"](https://github.com/linux-surface/linux-surface/releases) section. See e.g. https://github.com/linux-surface/linux-surface/releases/tag/debian-5.18.16-1 for Debian-based distros.

**Comment by FlailAway** [comment]
Great, thanks I'll grab a set.

**Comment by NP-chaonay** [comment]
> touch screen issues (no right-click)

maybe it depends on DE and what program is used, and X11/Wayland system

@FlailAway
