### ISSUE TITLE
SP7 Not charging.

### ISSUE THREAD

**Issue by platyna1992** [linux-surface/linux-surface#891]
Hi, 
I just recently installed linux on my Surface pro7. I noticed a problem with charging on Ubuntu kernel. I tried to install different flvors of Ubuntu and still have same issue. My surface will only charge up to 50% and later status is being changed for not charging and I can tell it is not charging as back of the device is cold. 
Is there anything that check or do to check why it is not charging? Just to point out battery is healthy and working correctly on Windows and it does not matter if I charge through USB-C or actually charger.

**Comment by qzed** [comment]
That sounds like you have the battery limiter enabled. This is implemented in firmware and you can change that in UEFI. Does Windows actually charge above 50%?

**Comment by platyna1992** [comment]
When I installed windows it does charge to 100% but on linux is it not possible. Can you please let me know where and how to change it?

**Comment by qzed** [comment]
See https://docs.microsoft.com/en-us/surface/battery-limit#enabling-battery-limit-in-surface-uefi-surface-pro-4-and-later. Make sure that is disabled.

**Comment by platyna1992** [comment]
I have just figured it out myself. I did not know that surfaces have battery limiters. Thanks for your help I thought I have problem with the kernel.

**Comment by NP-chaonay** [comment]
> When I installed windows it does charge to 100% but on linux is it not possible. Can you please let me know where and how to change it?


I think something wrong about firmware does linux interfere efi variable or something alike.

AS I search in SLS, there is variable call "BatteryLimitMode" in efivar

**Comment by platyna1992** [comment]
Thanks for help I managed to sort it out.

**Comment by qzed** [comment]
@NP-chaonay I think with the "smart charging" thing, Windows might show a charge of 100% even though it's really only 50%. On my old SB2 and the SPX (both don't have the "smart charging" thing but still have a battery limiter), when I enable the battery limiter Windows correctly shows 50% at maximum.

Yes, I've seen the EFI variable too. That essentially shows whether the battery limiter is enabled or not.

I don't really see how this is a Linux driver problem: The driver does show the _actual_ battery percentage. IMHO it should max out at 50% if the battery limiter is enabled and not show a false 100%. But I don't know how the "smart charging" thing is handled, or even how that works exactly. So maybe we're missing something there.
