### ISSUE TITLE
error during compiling new drivers

### ISSUE THREAD

**Issue by davidndian** [linux-surface/linux-surface#896]
after installing new drivers for wifi i was getting the following errors please help

┌──(㉿kali)-[~/rtl8188eus]
└─$ sudo make              
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.0-kali5-amd64/build M=/home//rtl8188eus  modules
make[1]: Entering directory '/usr/src/linux-headers-5.18.0-kali5-amd64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.3.0-3) 11.3.0
  You are using:           gcc-11 (Debian 11.3.0-5) 11.3.0
  CC [M]  /home//rtl8188eus/os_dep/osdep_service.o
/home//rtl8188eus/os_dep/osdep_service.c: In function ‘thread_exit’:
/home//rtl8188eus/os_dep/osdep_service.c:1271:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
 1271 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
/home//rtl8188eus/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
/home//rtl8188eus/os_dep/osdep_service.c:2450:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2450 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
      |                     ~~~~~~~^~~~~~~~~~
/home//rtl8188eus/os_dep/osdep_service.c:899:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  899 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
      |                  ~~~~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-5.18.0-kali5-common/scripts/Makefile.build:293: /home//rtl8188eus/os_dep/osdep_service.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.18.0-kali5-common/Makefile:1858: /home//rtl8188eus] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.18.0-kali5-amd64'
make: *** [Makefile:2058: modules] Error 2

**Comment by qzed** [comment]
The error you posted seems to come from a Kali Linux kernel, so this looks like a problem with that distribution / kernel. Apart from that:
- What device are you using?
- What kernel are you running (`uname -a`)?
- What drivers are you trying to install exactly (link would be great)?
- Why are you trying to install drivers manually, is there no support in the kernel?

**Comment by davidndian** [comment]
found the  following steps which rectified  errors even though you see some while compiling just see the end result which stated drivers installed

**Comment by davidndian** [comment]
@qzed  i was trying to install drivers for Tp Link TNw227 wifi adapter on kali linux latest version .error rectified.
Thankyou for responding

**Comment by j3m1ap7** [comment]
> found the following steps which rectified errors even though you see some while compiling just see the end result which stated drivers installed ![image](https://user-images.githubusercontent.com/111057228/184144264-22938da0-dac9-4d1f-a6e7-dd974bb2370a.png)

After a Kernel update 5.18+, the compiler got crazy and it was impossible to compile any driver for RTL8188EUS 

Thank you. Finally, it worked with updated drivers for RTL8188EUS from https://github.com/KanuX-14/rtl8188eus
Script build.sh solved any problem!
