### ISSUE TITLE
Pop-OS: apt update looking for i386 packages in surface linux repo

### ISSUE THREAD

**Issue by alexanderi96** [linux-surface/linux-surface#90]
Hi everyone! after loading the linux surface repository in the apt source list as described in the wiki, I noticed this error each time I run an apt update.

`N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://tmsp.io/fs/repos/debian/linux-surface release InRelease' doesn't support architecture 'i386'`

I managed to fix this error just editing the linux surface source list file in `/etc/apt/sources.list.d/linux-surface.list` and adding `[arch=amd64]` between deb and the repo link.

Is this the correct way to fix the issue or should it be fixed server side?
### Environment

- Hardware model: Surface Pro 5 (2017)
- Kernel version: 5.3.18
- Distribution: pop-os

**Comment by archseer** [comment]
Thanks for the report! I added `[arch=amd64]` to the [wiki guide](https://github.com/linux-surface/linux-surface/wiki/Package-Repositories).
