### ISSUE TITLE
SP8 LTE and Keyboard Functionality in Feature Matrix

### ISSUE THREAD

**Issue by m1nicrusher** [linux-surface/linux-surface#900]
Hi everyone,

I have an Surface Pro 8 with LTE.

First of all, I can confirm LTE is working out of the box with Fedora 36, with default generic kernel 5.17.5.
I think it would be better to discuss first before changing the Wiki.

Proof:
<img src="https://user-images.githubusercontent.com/19246983/185282405-4f494cdf-798b-444a-8d5d-f32f8e63c4d7.png" width="400">
<img src="https://user-images.githubusercontent.com/19246983/185282337-2ad9a92f-c5c8-4d37-89a8-f75abcba751d.png" width="400">

Then, I would like to say that for me, with generic kernel 5.17.5 on Fedora, the Signature Keyboard Cover doesn't work at all. I had to use external mouse and keyboard to complete installation.
So I think we should note "requires linux-surface kernel" at least. Or is anyone's keyboard works?

Cheers

**Comment by qzed** [comment]
> Then, I would like to say that for me, with generic kernel 5.17.5 on Fedora, the Signature Keyboard Cover doesn't work at all.

That is to be expected. TypeCover support will be upstream in v6.0. Feel free to edit the wiki.

**Comment by m1nicrusher** [comment]
Thank you! Wiki edited.
