### ISSUE TITLE
Surface Go: Touchscreen partially not responding

### ISSUE THREAD

**Issue by rdtm443** [linux-surface/linux-surface#901]
Surface Go, Ubuntu 22.04, Kernel 5.18.16-surface

Hello guys

The touchscreen seems to have two bars of unresponsive area, as per this picture:

![image](https://user-images.githubusercontent.com/25002690/185459066-bc9eb840-de9b-42f9-aa94-2582c9efad13.png)

Any idea? The problem occurs wheter i use a pen or just the finger...

Surface Go has been used only for a few times, so i hardly believe that it could be a hardware issue. 

Thanks.

Best regards

**Comment by qzed** [comment]
Unfortunately this does look like a hardware issue though. On the Go line, the touchscreen is a fairly standard HID device, so there's no processing done by us (like with IPTSd for the newer non-Go devices). If you want to make absolutely sure, you should check whether the problem also exists in Windows.

**Comment by rdtm443** [comment]
> Unfortunately this does look like a hardware issue though. On the Go line, the touchscreen is a fairly standard HID device, so there's no processing done by us (like with IPTSd for the newer non-Go devices). If you want to make absolutely sure, you should check whether the problem also exists in Windows.

Thanks a lot for your quick reply ! In the meanwhile I could 'test' the touchscreen in BIOS (as I only have Ubuntu installed...). And yeah it really seems to be a hardware issue. Thanks a lot for the details though. 

Cool project !
