### ISSUE TITLE
[SP6] [QUESTION] How to make camera working with Telegram permanently?

### ISSUE THREAD

**Issue by farline99** [linux-surface/linux-surface#904]
On my SP6 cameras are working, but only with QCam. I tried to create GSTreamer loopback and it worked as expected, virtual camera is working f.e. with Telegram. But it works only when pipeline is on, if I close Konsole and stop pipeline camera Telegram can't find camera again. The question is how I can make this loopback permanent?)

### Environment
- Hardware model: Surface Pro 6.
- Kernel version: Linux 5.18.16-arch1-1-surface.
- Distribution: Arch Linux with KDE Plasma.

**Comment by qzed** [comment]
You will need to set up the pipeline every time you want to use the camera. However, if I remember correctly, there was some daemon of sorts that would detect when an application tried to access the camera via gstreamer and set up the pipeline on-demand. Unfortunately, I don't have a link to that and it isn't detailed in the wiki, but I think it was mentioned somewhere in #91. So you might want to look through that.

**Comment by farline99** [comment]
Thanks for answer. Maybe you are talking about v4l2relayd? People wrote that it is solution, but I don't know how to use it properly, so will wait for some easy implementation. Anyway, guys, you are the best, your work is awesome, Linux on Surface is really cool ;)

**Comment by qzed** [comment]
That sounds like it. Unfortunately I've never used it, so I too have no idea how to set it up correctly. I'll try to have a look at it if I can find some time.

**Comment by farline99** [comment]
Thank youuu ❤️

**Comment by kbingham** [comment]
Could you try telegram with libcamerify ?
I'd be interested to know if it does/doesn't work. I think it depends on if it's using webrtc directly (which I suspect it does). So it will need the NV12 support patches. There is some progess there, but it's probably a long time until webrtc merges it, and it makes it to the distros :S


See https://github.com/linux-surface/linux-surface/issues/546 and https://bugzilla.mozilla.org/show_bug.cgi?id=1761519
