### ISSUE TITLE
SLS/SP8/... Implement Display Resolution/Refresh Rate alike OEM configuration

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/linux-surface#905]
This issue for at least SLS/SP8 and many devices mentioning about these issue in the list:

- Some resolution have refresh rate config that available in Windows but not in Linux
- Same as above but serious (for ex: on Windows we have 120/60hz but in Linux we got only 60 or 120/90)
- Some resolution is not available on Linux but it existed on Windows
- Just like 3 above but it is existed in Linux but cannot using as it leads to blank screen or displaying problem such as unreadable displaying / screen flickering / some serious problem such as kernel hang / graphic subsystem or even driver hang/auto-reset

Does we have any config overriding for Surface panel, I think we should not rely on EDID alone, we should have some metadata can making overriding config too.

Even it not include in linux-surface/upstream, at least it is also enough that we have at least not-diffcult-to-do instruction to go on.

Ok let me explain my problem on SLS Ubuntu 22.04 LTS on the next comment

**Comment by NP-chaonay** [comment]
the related problem on SP8: #825 #859 
the related problem on SLS: #817

**Comment by NP-chaonay** [comment]
i dont know if this diffcult to do so or not, or it requires SAM/... reverse eng?

**Comment by NP-chaonay** [comment]
I wonder if file in Surface driver pack helps debug on this

**Comment by NP-chaonay** [comment]
I recommended to fix in Wayland first

as I afraid that X11 wont using real screen mode for that set resolution/refresh rate or have something complex adjusting about it (graphic system that affect refresh rate and resolution list and how it work)

so we should test and fix on Wayland first then in X11.

**Comment by NP-chaonay** [comment]
From my SLS I guess that

1)
the EDID file seem to only specific for 2400 1600 on both 120hz and 60hz (I guess from EDID, if I not guess wrong).
and refresh rate that set by EDID is interpreted by Windows and apply it for all resolution
while Linux apply only the native resolution because that EDID only tell for native resolution.

2) I think Windows just using what available in EDID for real screen mode that why when we set to another resolution, the real screen resolution is not changed, just desktop resolution. I think that why 120/60hz still exist across every res. in Windows list, because maybe Windows just using real resolution that on EDID (which only have 2400x1600 120/60hz)., so the RR. from that real res. would apply on another virual res. appeeared in list.

3)
For resolution list in Windows, yeah that is not in EDID, so I think that getting from Intel driver (on Linux if I not recall it wrong, it tell the same info (and if not wrong again same informatione 100% or nearly) in file named "mode" in folder name of display port (SLS is using ```eDP-1```, that file is parted of i915 drm if I not recall it wrong again).

4) to conclude 2+3
4.1) on Windows, refresh rate of each resolution got from EDID
4.2) on Windows, resolution appeared in list may got from Intel driver like it got from the mentioned file in sysfs.

ok if I will do this testing if I say all correct, and will be updated here and in new comment

**Comment by StollD** [comment]
Kinda hard to keep track of everything, since there are now like 4 issues about this, but didnt someone mention that it works fine on the older ubuntu default kernel?

In that case this would be caused by an upstream change to i915 and should be reported there.

**Comment by NP-chaonay** [comment]
> In that case this would be caused by an upstream change to i915 and should be reported there.

so does that is the cause that make Linux resolution/refresh rate list is not same as on Windows?

output of Wayland and xrandr is not same as on Windows anyway on SLS

**Comment by NP-chaonay** [comment]
> Kinda hard to keep track of everything,

I intend to gather SP8/SLS problem (and maybe less importance problem of other device about 2nd sub-issue that I have said recently) to become this single issue.


So it is up to #825 and #859 if he/she want to close their issue or not, however that is not my problem

I just making this issue to link their problem and my problem and potential problem to be here.

So in case someone want to solve my any issues (such as Linux res/RF. list is not same as Windows), would go to this directly (unless they want to split too)

**Comment by m1nicrusher** [comment]
@StollD 

> but didn't someone mention that it works fine on the older ubuntu default kernel?

I think you might had misunderstood my comment in #817 where I said I could change refresh rate on (Fedora) livecd.
Firstly I believe you thought I was using Ubuntu, but I was using Fedora 36 and the default kernel is quite new.
Secondly what I meant on #817 was I was able to **change** refresh rates (60Hz 25Hz 30Hz etc.) but I didn't say I had **120Hz** option. If I didn't remember wrong, before I install linux-surface I don't have 120Hz available. But I'll verify sometime if livecd can use 120Hz.

> In that case this would be caused by an upstream change to i915 and should be reported there.
I do believe this (wrong EDID) is a kernel issue rather than linux-surface issue.

However,
> Kinda hard to keep track of everything,

Maybe we should figure out what has linux-surface done to enables 120Hz?

Let me sum things up on SLS
- Kernel reports wrong EDID (both generic and linux-surface)
- On native resolution, generic kernel can change refresh rate but no 120Hz
- On native resolution, linux-surface enables 120Hz but refresh rate is locked to 120Hz.

If there's anything wrong, feel free to point it out making it clearer.

**Comment by qzed** [comment]
> Maybe we should figure out what has linux-surface done to enables 120Hz?

We don't have any patches targeting the display/GPU stack, so if anything it's either a difference between kernel versions or a difference between configs (or maybe patches if the respective distro kernel ships some that we don't). It would be good if you could pin that down.

> * Kernel reports wrong EDID (both generic and linux-surface)

What is our ground-truth for the EDID. Do we have one from Windows? EDID is normally reported by the panel (assuming it's eDP or something similar with an aux channel), so if there's a difference between Windows and Linux then either the EDID handling in Linux is wrong and it messes something up along the way or Windows "fixes up" the EDID somehow. I'm not sure, but maybe there's a way to query the EDID directly via the aux channel... (normally that's I2C).

The EDID posted in https://github.com/linux-surface/linux-surface/issues/817#issuecomment-1134299340 (and decoded in the comment below) seems reasonable to me and is what I'd assume should come from the panel directly. It does show a variable refresh rate from 30Hz to 120Hz. @NP-chaonay how did you get that?

**Comment by StollD** [comment]
@NP-chaonay you have Ubuntu right? Could you test the new 5.19 build of the surface kernel? There were some commits to i915 in 5.19 that I feel might help.

https://github.com/torvalds/linux/commit/c19909d037b640a5e3580c68f420e7ba058c68e4

What I think might have caused this in the first place (from 5.16):

https://github.com/torvalds/linux/commit/00fc3787d277299c39a7c35290e79375c6de9f24

(The fixed mode that is referenced in those commits appears to be the prefered mode of the display, set in the EDID)

**Comment by NP-chaonay** [comment]
> @NP-chaonay you have Ubuntu right? Could you test the new 5.19 build of the surface kernel? There were some commits to i915 in 5.19 that I feel might help.
> 
> [torvalds/linux@c19909d](https://github.com/torvalds/linux/commit/c19909d037b640a5e3580c68f420e7ba058c68e4)
> 
> What I think might have caused this in the first place (from 5.16):
> 
> [torvalds/linux@00fc378](https://github.com/torvalds/linux/commit/00fc3787d277299c39a7c35290e79375c6de9f24)
> 
> (The fixed mode that is referenced in those commits appears to be the prefered mode of the display, set in the EDID)

ok thanks since I updated it every week and it is coincidence that I will update it today. so let me tell result tomorrow.

**Comment by NP-chaonay** [comment]
> @NP-chaonay you have Ubuntu right? Could you test the new 5.19 build of the surface kernel? There were some commits to i915 in 5.19 that I feel might help.
> 
> [torvalds/linux@c19909d](https://github.com/torvalds/linux/commit/c19909d037b640a5e3580c68f420e7ba058c68e4)
> 
> What I think might have caused this in the first place (from 5.16):
> 
> [torvalds/linux@00fc378](https://github.com/torvalds/linux/commit/00fc3787d277299c39a7c35290e79375c6de9f24)
> 
> (The fixed mode that is referenced in those commits appears to be the prefered mode of the display, set in the EDID)

```
root@np-chaonay-l2l:/home/np-chaonay# uname -a
Linux np-chaonay-l2l 5.19.2-surface #1 SMP PREEMPT_DYNAMIC Fri Aug 19 21:38:42 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@np-chaonay-l2l:/home/np-chaonay# cat /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-5.19.2-surface root=UUID=10f55171-ae45-4fcd-8257-a45442a4f84c ro quiet splash resume=UUID=10f55171-ae45-4fcd-8257-a45442a4f84c resume_offset=13373440 mitigations=off intremap=nosid enable_rc6=7 i915.mitigations=off iwlwifi.11n_disable=0 iwlwifi.fw_restart=Y iwlwifi.uapsd_disable=1 iwlwifi.bt_coex_active=Y iwlwifi.led_mode=0 iwlwifi.power_save=Y iwlwifi.power_level=5 iwlwifi.disable_11ac=N iwlwifi.disable_11ax=N iwlmvm.power_scheme=3 snd_hda_intel.power_save_controller=Y snd_hda_intel.position_fix=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 pcie_aspm.policy=powersupersave pcie_aspm=force
root@np-chaonay-l2l:/home/np-chaonay# 
```

not work, the two problem existed (X11 resolution selected fail not have been tested but later)
- Native resolution still using 120hz no 60hz option in GNOME-shell Wayland
- Another resolution still giving options of 120/90/60 hz which not same as on Windows

**Comment by NP-chaonay** [comment]
idk if this have to do with Ubuntu sysctl?

**Comment by NP-chaonay** [comment]
> Let me sum things up on SLS
> 
> * Kernel reports wrong EDID (both generic and linux-surface)
> * On native resolution, generic kernel can change refresh rate but no 120Hz
> * On native resolution, linux-surface enables 120Hz but refresh rate is locked to 120Hz.
> 
> If there's anything wrong, feel free to point it out making it clearer.

here is for SLS

1) EDID wrong? idk how can I compare what Windows and Linux gives? dont Linux send the one directly from monitor? does edid is not a raw value? if yes then why it is only 1 file, if Linux/driver have do modify to that file, it should have 2 file: 1 for raw directly from monitor and 2 for system/kernel/driver modification.

2) On native resolution, 120hz works well on both kernel but 60hz is available only in generic kernel (tested on last month idk if new ubuntu kernel change this behaviour)

**Comment by NP-chaonay** [comment]
**Reply to qzed**
> We don't have any patches targeting the display/GPU stack, so if anything it's either a difference between kernel versions or a difference between configs (or maybe patches if the respective distro kernel ships some that we don't). It would be good if you could pin that down.

well yeah that is one of my thought. it eiter or both of kernel modifying and kernel config including live config such as sysctl or even i915 parameter/fw file. Interesting point...

> @NP-chaonay how did you get that?

sorry I cannot remember but to make thing sure I will  get EDID from Windows instead. and put it here.
For that comment I will reedit to make an link toward the new file.

**Comment by NP-chaonay** [comment]
> <img alt="image" width="281" src="https://user-images.githubusercontent.com/17851493/185627437-2409cfd3-34d9-478e-9c65-45a04a4ed7f3.png">
> 
> this is on SLS, when I set it to 1600x900 it apeear that real screen mode is 2400x1600 @ 60 while desktop res is 1600x900 @ 60
> I think this may also same as other device

now my idea about how we should fix the problem:
maybe that
- let Linux using real mode on either 120/60 hz of native resolution (we need to fix problem about 120/60hz not available on each device first)
- for using another lower resolution, let Wayland/X11/Desktop_Environement simulate rendering canvas can upscaling to real mode

I think this two match how Surface panel work on Windows.

I think this way is appied across Surface devices

**Comment by StollD** [comment]
This appears like a related upstream issue (just look at all the issues that got closed as a duplicate of it): https://gitlab.freedesktop.org/drm/intel/-/issues/125

Some more changes to i915 regarding VRR panels from linux 6.0:

* https://github.com/torvalds/linux/commit/6e939738da208bcc0e4dc794519e18cad85bca73
* https://patchwork.freedesktop.org/patch/487833/

Quote from the issue linked above that picked my eye:

> It is by design that we only accept the panel native resolution, and use the GPU panel fitter instead of the one on the panel. We use the panel preferred mode from the EDID for determining the native mode. It is somewhat by accident that we also only accept the refresh rate from the panel native mode. Likely the preferred mode invariably had the highest refresh rate the panel supported in the past, but 300 Hz might not be the best default option, so panel vendors list 60 Hz as the preferred refresh rate. So here we are.

> Finally, there's a workaround that I think could work. Make a copy of the panel EDID, edit it to drop the preferred mode bit from the 60 Hz mode, and add it to the 300 Hz mode. Save it to e.g. /lib/firmware/my-edid. Then use the drm.edid_firmware=eDP-1:my-edid module parameter to force the named connector (in this case eDP-1, modify to match yours, to use the EDID from the file. I am aware it will be a PITA to edit the EDID, but https://git.linuxtv.org/edid-decode.git might be helpful. I'm sorry I can't be of more help at this time. :(

https://gitlab.freedesktop.org/drm/intel/-/issues/125#note_975535

**Comment by NP-chaonay** [comment]
>It is by design that we only accept the panel native resolution, and use the GPU panel fitter instead of the one on the panel. We use the panel preferred mode from the EDID for determining the native mode. It is somewhat by accident that we also only accept the refresh rate from the panel native mode. Likely the preferred mode invariably had the highest refresh rate the panel supported in the past, but 300 Hz might not be the best default option, so panel vendors list 60 Hz as the preferred refresh rate. So here we are.

Thanks, so I can conclude that the preferred mode is different across Surface device so
SP8 maybe 60Hz
and
SLS maybe 120hz

ok but it still not answer my doubt about the lower resolution and have it 120/90/60hz on my SLS

so I think that the native resolution and lower resolution is using different implementation? yeah it should be since X11 dont work on lower resolution (this must be retest soon)

**Comment by m1nicrusher** [comment]
> Likely the preferred mode invariably had the highest refresh rate the panel supported in the past, but 300 Hz might not be the best default option, so panel vendors list 60 Hz as the preferred refresh rate. So here we are.

Yes that makes a lot sense to me. Take an example of my ROG 27" 4K 144Hz monitor, regardless of plugging in what device, it will always be 4K@60Hz by default. I'll have to manually change to 144Hz. And maybe that's the case of SP8 using 60Hz only by default.

**Comment by StollD** [comment]
> ok but it still not answer my doubt about the lower resolution and have it 120/90/60hz on my SLS

The commit I linked allows modes with different vsync timings. Since there are only two modes on SLS, I am assuming that both have different timings, and the 60hz option is dropped.

I would assume that Intel doesn't have that restriction in lower resolutions (maybe its a byproduct of how they handle VRR, and they disable VRR for lower resolutions). What I dont understand is why 90hz is in there, given that it is not in the EDID, and absolutely needs VRR to look good.

**Comment by NP-chaonay** [comment]
> I am assuming that both have different timings, and the 60hz option is dropped.

may correct since in EDID may have two entry of same resolution but 120hz and 60hz for each, and yeah 60hz is dropped maybe because what you have said about ```Quote from the issue linked above that picked my eye:```

> (maybe its a byproduct of how they handle VRR, and they disable VRR for lower resolutions).

sorry, but TBH I started to not understand about these, however VRR on Windows work even non-native.

> What I dont understand is why 90hz is in there

yeah, maybe Intel driver problem on how to interpret EDID and something about monitor panel stuff. I think the thing that should be is to have similar like Windows that
- Native resolution have both 120/60
- Lower resolution is have both 120/60
- And if possible: lower resolution but still using real mode of native resolution, and any lower resolution will be upscaled by driver not compositor/X11.

**Comment by m1nicrusher** [comment]
Hey guys, I just noticed that on newer generic kernel. 60Hz option disappeared. So it should be an upstream issue rather than a linux-surface issue.

![image](https://user-images.githubusercontent.com/19246983/185833430-edc5db30-7fec-4a30-9328-20cfc3bcddae.png)
![image](https://user-images.githubusercontent.com/19246983/185833478-57f30654-57c6-47c0-b02c-4bbaa89c8742.png)

**Comment by NP-chaonay** [comment]
ok so if it an upstream issue and it should be fixed by there, so let this closed first

if that is fixed and problem is still persist or have some sub-issues still existed, I will reopen
