### ISSUE TITLE
[SP8] Keyboard does not work on LUKS password entry

### ISSUE THREAD

**Issue by tlf30** [linux-surface/linux-surface#911]
When booting, at the password entry to deencrypt LUKS volumn, the surface keyboard does not work. 

### Environment
- Hardware model: SP8
- Kernel version: `Linux surface2 5.19.2-surface #1 SMP PREEMPT_DYNAMIC Fri Aug 19 21:38:42 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Distribution: Ubuntu 22.04.1 LTS

<details><summary>`dmesg` output</summary>
https://gist.github.com/tlf30/823c64bf8ee75ae67d669f32c718414b

</details>

**Comment by NP-chaonay** [comment]
pls see 
https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption
maybe you need to reinstall

and I just readjusting Installation instructions wiki page. (from given picture)
<img width="702" alt="image" src="https://user-images.githubusercontent.com/17851493/186107206-97daec7a-2d42-4263-989a-b876adbe54e0.png">

**Comment by m1nicrusher** [comment]
> maybe you need to reinstall

You shouldn't need to, just hook a USB keyboard to unlock the disk, and follow the instruction should be fine.

**Comment by v4rakh** [comment]
Same experience here. Added everything to my `MODULES`, but no luck. I always need to unlock via external keyboard.

**Comment by tlf30** [comment]
OK finally got this working.
For anyone running ubuntu 22:
1. Edit `/etc/initramfs-tools/modules`
2. Add the following module lines to the file:
```
btrfs
i915
surface_aggregator
surface_aggregator_registry
surface_aggregator_hub
surface_hid_core
8250_dw
surface_hid
surface_kbd
intel_lpss
intel_lpss_pci
pinctrl_tigerlake
```

**Comment by NP-chaonay** [comment]
if I not missed something

```
# FS not need for KBD to work
btrfs
# driver module not need for KBD to work
i915
```

**Comment by hardwareadictos** [comment]
Good Morning.

I'm having the same issue with SGO 1st gen. ¿Can someone help me? It's also happening on the Operating system intermittently. Seems a kernel issue as it happens on the stock Distros Kernels.

**Comment by ofvlad** [comment]
For anyone else who winds up here via google, I needed something to do with my hands while watching Mystery Men today, started with dumping the contents of `lsmod` into my `MODULES=()` and whittled it down to this minimum set:

```
MODULES=( 8250_dw intel_lpss_pci surface_hid surface_aggregator_registry usbhid vfat )
```

removing any of those makes my SL4's keyboard not work for luks passphrase entry.
