### ISSUE TITLE
Fixing README.md to indicate about disk encryption

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/linux-surface#912]
<img width="739" alt="image" src="https://user-images.githubusercontent.com/17851493/186107869-cf86257e-4ba4-4e37-a8df-246390b20734.png">

This is what I just recently chnage to installtion instruction wiki paeg.

And I think it is appropriate to put the alike statement into README

> For disk encryption, you need to follow instruction from the warning notice in [the section "Installation" in the given wiki page](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#installation)

any comment about adjusting the content in the picture and/or about README?

**Comment by qzed** [comment]
I've added a sentence about it to the readme. Thanks!
