### ISSUE TITLE
Auto Rotation BUG

### ISSUE THREAD

**Issue by m1nicrusher** [linux-surface/linux-surface#915]
On Wayland, auto rotation option is only available when in tablet mode. The option disappear when in PC mode (TypeCover keyboard deployed).

When not in tablet mode, although the option disappear, and although I lock rotation in tablet mode, it will still rotate to portrait mode, but not rotating back to landscape. I had to remove keyboard and rotate back or manually go into settings to set it back to landscape.

It's happening on both my SP8 and SLS. On SP8 I can go into tablet mode and rotate back but in SLS it's much difficult since I will need to fold the screen and also the device is quite heavy.

In tablet mode, it's working normally.

This is an annoying problem because it triggers every time when I put my laptop / tablet into my bag. When I take it out, sometimes it will be in portrait mode.

### Environment

- Hardware model: Surface Pro 8 / Surface Laptop Studio
- Kernel version: 5.18.18-1.surface.fc36.x86_64
- Distribution: Fedora 36

<details><summary>`dmesg` output</summary>

```
Is dmesg necessary for this kind of issue?

```

</details>

**Comment by m1nicrusher** [comment]
If my description is hard to understand I'll put a short video later on to better demonstrate.

**Comment by NP-chaonay** [comment]
I think this is GNOME-shell bug,
but let me try later.

I think should report to GNOME-shell repo's issue page instead

**Comment by NP-chaonay** [comment]
ok 
```
np-chaonay@np-chaonay-l2l:~$ gnome-shell --version
GNOME Shell 42.2
np-chaonay@np-chaonay-l2l:~$ 
```

so this is the result
1) everything normal except when put in tablet mode even lock rotation is on as the latest setting, it auto rotate to the current orientation. however this done at once time. In lock settings turned on , putting not-tablet-mode dont do this auto-rotate thing.

So I think something is wrong about your driver/hw idk

**Comment by m1nicrusher** [comment]
Yup, it is confirmed to be a GNOME bug on Wayland session. @NP-chaonay I think you don't have much issue maybe because you're on X11.

But for further reference here's the upstream issue report: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4932

**Comment by NP-chaonay** [comment]
so maybe some different config /environement that affect different behaviour
