### ISSUE TITLE
Wifi stop working on Surface Pro 2017

### ISSUE THREAD

**Issue by KenMizz** [linux-surface/linux-surface#92]
The wifi stop working in random time, It happens when I downloading something
### Environment

- Hardware model:  Surface Pro 2017
- Kernel version: Linux pop-os 5.3.18-surface #1 SMP Fri Dec 27 23:37:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Distribution:  Pop!_OS(Ubuntu)

<details><summary>`dmesg` output</summary>

```

```

</details>

sorry for my poor english, its not my first language

**Comment by mmalmeida** [comment]
Seems to be the same issue as #70

**Comment by qzed** [comment]
Agreed, let's keep this in #70.
