### ISSUE TITLE
Surface Pen doesn´t work

### ISSUE THREAD

**Issue by Brody91** [linux-surface/linux-surface#922]
Greetings!
I've only recently started using Fedora (+ Surface kernel) and I'm having a problem with my Surface Pen not working. Furthermore, my Bluetooth Surface Mobile Mouse occasionally drops out.
Unfortunately I don't have much experience with Linux and hope you can help me.

<details>
<summary>dmeg IPTS</summary>
<ul>

[    4.680981] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[    4.683330] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Device 045E:099F ready
[    5.595882] input: IPTS Touch as /devices/virtual/input/input41
[    5.596924] input: IPTS Stylus as /devices/virtual/input/input42
[  206.081313] input: IPTS Touch as /devices/virtual/input/input54
[  206.081632] input: IPTS Stylus as /devices/virtual/input/input55
</ul>
</details>

<details>
<summary>dmeg hidraw</summary>
<ul>

[    1.852220] hid-generic 0003:045E:09C0.0001: input,hiddev96,hidraw0: USB HID v1.11 Keyboard [Microsoft Surface Type Cover] on usb-0000:00:14.0-8/input0
[    2.110518] hid-multitouch 0003:045E:09C0.0001: input,hiddev96,hidraw0: USB HID v1.11 Keyboard [Microsoft Surface Type Cover] on usb-0000:00:14.0-8/input0
[    3.391896] hid-generic 001F:8087:0AC2.0002: hidraw1: <UNKNOWN> HID v2.00 Device [hid-ishtp 8087:0AC2] on
[   22.809570] hid-generic 0005:045E:095D.0003: input,hidraw1: BLUETOOTH HID v1.03 Mouse [Surface Mobile Mouse] on 80:45:dd:f1:93:9c
[   39.928128] hid-generic 0005:045E:0921.0004: input,hidraw2: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 80:45:dd:f1:93:9c
[   98.307922] hid-generic 0005:045E:0921.0005: input,hidraw2: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 80:45:dd:f1:93:9c
[  671.490034] hid-generic 0005:045E:0921.0006: input,hidraw2: BLUETOOTH HID v0.30 Keyboard [Surface Pen] on 80:45:dd:f1:93:9c
</ul>
</details>

<details>
<summary>evtest</summary>
<ul>

No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0:	Lid Switch
/dev/input/event1:	Microsoft Surface Type Cover Keyboard
/dev/input/event2:	Microsoft Surface Type Cover Mouse
/dev/input/event3:	Microsoft Surface Type Cover Consumer Control
/dev/input/event4:	Microsoft Surface Type Cover UNKNOWN
/dev/input/event5:	Microsoft Surface Type Cover Touchpad
/dev/input/event6:	Microsoft Surface Type Cover UNKNOWN
/dev/input/event7:	Microsoft Surface Type Cover UNKNOWN
/dev/input/event8:	Microsoft Surface Type Cover UNKNOWN
/dev/input/event9:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event10:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event11:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event12:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event13:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event14:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event15:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event16:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event17:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event18:	Microsoft Surface Type Cover Tablet Mode Switch
/dev/input/event19:	Video Bus
/dev/input/event20:	PC Speaker
/dev/input/event21:	gpio-keys
/dev/input/event22:	gpio-keys
/dev/input/event23:	HDA Intel PCH Mic
/dev/input/event24:	HDA Intel PCH Headphone
/dev/input/event25:	HDA Intel PCH HDMI/DP,pcm=3
/dev/input/event26:	HDA Intel PCH HDMI/DP,pcm=7
/dev/input/event27:	HDA Intel PCH HDMI/DP,pcm=8
/dev/input/event28:	HDA Intel PCH HDMI/DP,pcm=9
/dev/input/event29:	HDA Intel PCH HDMI/DP,pcm=10
/dev/input/event30:	HDA Intel PCH HDMI/DP,pcm=11
/dev/input/event31:	HDA Intel PCH HDMI/DP,pcm=12
/dev/input/event256:	IPTS Touch
/dev/input/event257:	IPTS Stylus
/dev/input/event258:	Surface Mobile Mouse
/dev/input/event259:	Surface Mobile Mouse Keyboard
/dev/input/event260:	Surface Mobile Mouse
/dev/input/event261:	Surface Mobile Mouse
/dev/input/event262:	Surface Mobile Mouse
/dev/input/event265:	IPTS Touch
/dev/input/event266:	IPTS Stylus
</ul>
</details>

<details>
<summary>hidraw1</summary>
<ul>

[Brody@sp7-fedora ~]$ sudo iptsd /dev/hidraw1
[sudo] password for Brody: 
Connected to device 045E:099F
</ul>
</details>

<details>
<summary>cmdline</summary>
<ul>

BOOT_IMAGE=(hd0,gpt5)/vmlinuz-5.18.11-1.surface.fc36.x86_64 root=UUID=bd428d79-07b8-4e7a-8be2-3370730a8b21 ro rootflags=subvol=root quiet intel_iommu=off
</ul>
</details>

<details>
<summary>Systemctl satuts IPTS</summary>
<ul>

● iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-09-06 12:57:52 EDT; 4h 36min left
       Docs: https://github.com/linux-surface/iptsd
   Main PID: 827 (iptsd)
      Tasks: 1 (limit: 8892)
     Memory: 440.0K
        CPU: 685ms
     CGroup: /system.slice/iptsd.service
             └─ 827 /usr/bin/iptsd
</ul>
</details>

**Comment by StollD** [comment]
You are neither running the ipts kernel driver from the master branch, nor the iptsd from the master branch. The versions in the repo don't support the stylus on Surface Pro 7.

**Comment by NP-chaonay** [comment]
> > You are neither running the ipts kernel driver from the master branch, nor the iptsd from the master branch. The versions in the repo don't support the stylus on Surface Pro 7.
> 
> Thank you for your response. I suppose I should start with this? https://github.com/linux-surface/iptsd/blob/master/README.md or am I wrong about that?

it is indicated in https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#feature-matrix

that SP7 pen support using compiled from github source of linux-surface/intel-precise-touch and linux-surface/iptsd (for latter part, you can grab prebuilt pkg)

see README of its corresponding for instruction
