### ISSUE TITLE
Please, I need Help. Reboot and Stuck on "initramfs" command line (Failed to load the ZFS Module) . 

### ISSUE THREAD

**Issue by Special-Niewbie** [linux-surface/linux-surface#942]
I will try to be detailed and concise to disregard where I am encountering my problem.

**SYSTEM**
- Hardware model: `Surface Laptop Studio (Intel Core i7-11370H), NVIDIA GeForce RTX 3050 Ti, 32GB RAM , etc.`
- Kernel version: `5.15.0-48-generic`
- Kernel Surface going to build version: `5.9.10-surface`
- Distribution: `Ubuntu 22.04.1 LTS `
- Disk Encryption: `YES `
- Secure Boot: `YES `
- File System: `ZFS `

By following the steps that I find in the **Installation and Setup** section, and once the Ubuntu installation is finished with the _Secure Boot active_ and the _Disk Encryption_, Ubuntu boots without problems.  
Once, I get to the Desktop (by entering all the passwords necessary to enter on it) I continue with the installation of the modules suggested in this section - https://github.com/linux-surface/linux-surface/wiki/Disk-Encryption.  

After that I restart the OS, and the keyboard will works even when I have to put the password in the Decryption section of the Disk (otherwise the build-in keyboard doesn't work only in this step).  Once back into the Desktop, from the Terminal I start installing the DKMS-ZFS as suggested by the Installation and Setup guide, with the following commands:

```
sudo apt-get update -y
sudo apt-get install -y zfs-dkms
```

After this, following the Guide in the **Installation and Setup** section, from the Terminal I start to install the keys and packages to build the New Surface `5.9.10-surface` Kernel; after this step I proceed with the installation of the Secure Boot key with the following command:

`sudo apt install linux-surface-secureboot-mok`

Upgrade the GRUB:

`sudo update-grub`

Once all the steps have been completed, I restart the operating system and enter to the new MOK password ( password suggested previously in the Terminal) in the Enroll MOK section, press ok and everything proceeds successfully.

Continuing I should see the GRUB Menu section, but I am stopped with a Problem that says Failed to load ZFS modules `(initramfs)_ `....

Arrived here, I can either just reboot the PC and return to the GRUB Menu where I can choose the Ubuntu Normal Kernel `5.15.0-48-generice` and Ubuntu starts normally; or choose the New Kernel Surface but with the "`initramfs`" error.

This is the picture error:

![image](https://user-images.githubusercontent.com/64843123/193017971-e39b3050-b6c1-4f96-a17f-4ba74e979137.jpg)

What can I do at this point?

**Comment by NP-chaonay** [comment]
ok in that point of the system state (from given pict),

if the surface keyboard driver is loaded, I think you can type exit and enter and boot normally (idk but maybe)

otherwise connect outside keyboard then try type exit and enter to boot normally

if booting is normally then we can see in dmesg why zfs module is failed to load

oh it is important that do not remove the old generic kernel that  it work, as I think the old one still work because zfs-dkms is not install to initramfs of that kernel version

**Comment by Special-Niewbie** [comment]
> ok in that point of the system state (from given pict),
> 
> if the surface keyboard driver is loaded, I think you can type exit and enter and boot normally (idk but maybe)
> 
> otherwise connect outside keyboard then try type exit and enter to boot normally
> 
> if booting is normally then we can see in dmesg why zfs module is failed to load
> 
> oh it is important that do not remove the old generic kernel that it work, as I think the old one still work because zfs-dkms is not install to initramfs of that kernel version

Thank you for your reply @NP-chaonay , yes I can use the Build-In Keyboard as I installed the Modules.

The Result if I write `exit `and than `enter` are as below Picture (Sorry for a bit blurry pic):

![IMG_20220929_202831](https://user-images.githubusercontent.com/64843123/193032654-5541a3ec-1d95-46d9-b413-bae4d6d93473.jpg)

**Comment by qzed** [comment]
It looks like the ZFS module can't be found or loaded (`Failed to load ZFS modules`). I assume that's causing an issue because you have a ZFS root (or other essential) partition? As indicated by one of the error messages, you can try running `/sbin/modprobe zfs` in the initramfs (that's where you get dropped to), but I assume that is also going to fail.

The issue is probably that ZFS is a DKMS module, meaning it needs to be recompiled for each kernel update. That recompilation has likely failed for the latest update. That means that you need to boot into a kernel where that still works (e.g., the standard Ubuntu-distributed kernel). You should be able to select that in a submenu in GRUB (I think pressing F2 should bring that up).

Once you've booted into a kernel you can check with `sudo dkms status` whether the ZFS DKMS module is successfully installed and compiled.

**Comment by Special-Niewbie** [comment]
> It looks like the ZFS module can't be found or loaded (`Failed to load ZFS modules`). I assume that's causing an issue because you have a ZFS root (or other essential) partition? As indicated by one of the error messages, you can try running `/sbin/modprobe zfs` in the initramfs (that's where you get dropped to), but I assume that is also going to fail.
> 
> The issue is probably that ZFS is a DKMS module, meaning it needs to be recompiled for each kernel update. That recompilation has likely failed for the latest update. That means that you need to boot into a kernel where that still works (e.g., the standard Ubuntu-distributed kernel). You should be able to select that in a submenu in GRUB (I think pressing F2 should bring that up).
> 
> Once you've booted into a kernel you can check with `sudo dkms status` whether the ZFS DKMS module is successfully installed and compiled.

Yes, I can boot on Ubuntu normally, if I switch to the Kernel back to the standard....

By entering to the Original Kernel Ubuntu and write the suggested command `sudo dkms status`, I got the below result:

![Schermata del 2022-09-29 21-03-38](https://user-images.githubusercontent.com/64843123/193039473-027f07d2-3a2c-4e84-91e8-3c9a2fa89de0.png)

**Comment by qzed** [comment]
Well, that's a new warning message for me ...

I think normally DKMS should show all kernel versions and I can't see the Surface kernel here. Maybe the warnings for the "generic" kernel cause the command to abort early?

So I think we should first address those. I guess you could try to reinstall it the module via
```
sudo dkms install -m zfs -v 2.1.4 -k 5.15.0-48-generic --force
```

**Comment by Special-Niewbie** [comment]
> Well, that's a new warning message for me ...
> 
> I think normally DKMS should show all kernel versions and I can't see the Surface kernel here. Maybe the warnings for the "generic" kernel cause the command to abort early?
> 
> So I think we should first address those. I guess you could try to reinstall it the module via
> 
> ```
> sudo dkms install -m zfs -v 2.1.4 -k 5.15.0-48-generic --force
> ```
> 
> Edit: While doing that, make sure that it doesn't report any errors or other warnings.

But if I listed out the all the Kernel installed , it seems that everything it's successfully there....look:

 
![Schermata del 2022-09-29 21-14-56](https://user-images.githubusercontent.com/64843123/193041509-1664b02d-7029-45ef-a8b3-cec848d11688.png)

**Comment by Special-Niewbie** [comment]
> Well, that's a new warning message for me ...
> 
> I think normally DKMS should show all kernel versions and I can't see the Surface kernel here. Maybe the warnings for the "generic" kernel cause the command to abort early?
> 
> So I think we should first address those. I guess you could try to reinstall it the module via
> 
> ```
> sudo dkms install -m zfs -v 2.1.4 -k 5.15.0-48-generic --force
> ```
> 
> Edit: While doing that, make sure that it doesn't report any errors or other warnings.

The result it's as below:

![Schermata del 2022-09-29 21-19-27](https://user-images.githubusercontent.com/64843123/193042573-9c336372-3992-41fe-98a0-7326c518d12b.png)

Next?

**Comment by qzed** [comment]
Hmm, can you try using `--force-version-override` instead of `--force`? Alternatively you could run
```
sudo dkms uninstall -m zfs -v 2.1.4 -k 5.15.0-48-generic
```
and then
```
sudo dkms install -m zfs -v 2.1.4 -k 5.15.0-48-generic
```

**Comment by Special-Niewbie** [comment]
> Yes, I do believe that the kernel is installed. Just somehow `dkms status` doesn't work the way I thought it should or it exits early and doesn't list all kernels. That's why I think we should try to get rid of those warnings first.
> 
> Alternatively, you can try to run
> 
> ```
> sudo dkms install -m zfs -v 2.1.4 -k 5.19.10-surface
> ```
> 
> (or maybe `5.19.10-surface-1`) which should attempt to install the module for the Surface kernel. I assume this will probably print some error message, so it would be great if you could provide those.

Okay, with Surface Force Kernel comes out some error, I attach the lines into the below txt file:

[Error DKMS.txt](https://github.com/linux-surface/linux-surface/files/9675030/Error.DKMS.txt)

Let me know please, if I need to proceed with the above commands with `-force-version-override`?!

Thank you to support me :)

**Comment by Special-Niewbie** [comment]
Also, as per my understanding, the `zfs-dkms` it differ from normal `dkms` installation as the warning message of `zfs-dkms` shows .I don't know if could be this the reason or what. I found in internet the same message as below:

![Uz1U4](https://user-images.githubusercontent.com/64843123/193047832-7d6245e5-3793-4467-9168-339ef2217933.png)

I don't know if could be the useful info....

**Comment by qzed** [comment]
Okay, so it's some incompatibility between the kernel version and the ZFS module. It seems to officially only support kernels up to v5.17. So you will need a newer ZFS version.

Unfortunately I'm not entirely sure how to best do that on Ubuntu. Ubuntu 22.10 provides a v2.1.5 ZFS package (https://packages.ubuntu.com/kinetic/zfs-dkms), but that officially also only supports up to v5.18 kernels. It might be possible to manually install that, but I'm not sure whether this would work.

The easiest alternative is probably downgrading the Surface kernels to a working version (you can manually download one at the [releases](https://github.com/linux-surface/linux-surface/releases) page).

**Comment by qzed** [comment]
> Also, as per my understanding, the `zfs-dkms` it differ from normal `dkms` installation as the warning message of `zfs-dkms` shows .I don't know if could be this the reason or what. I found in internet the same message as below:
> 
> [...]
> 
> I don't know if could be the useful info....

This is the unfortunate licensing problem around ZFS and also the reason why it's an external DKMS module and not built into the kernel (like pretty much all other drivers). So in a sense that's the root problem, which necessitates ZFS being handled externally, which in turn causes these incompatibilities as it's not being updated in sync with the kernel.

**Comment by Special-Niewbie** [comment]
> First, I think you will need an older version since you are already running `5.19.10`. Do you remember the last version that it worked with?
> 
> Second, you only need the `linux-headers-<version>...` and the `linux-image-<version>...` packages. The other ones are just "meta" packages for automatic kernel updates. If you manually install the packages with the version in their name, it shouldn't get removed automatically with an update. You may however need to manually select that new version in GRUB when you boot.

No worries, I still on preparation stage of my laptop we can experiment as much as we like.

As per my first post the Ubuntu it's running under `Kernel version: 5.15.0-48-generic` and the one `5.19.10` it's the New build surface that doesn't work.

Now I try to install the packages that you told me and go back to you with results.....

**Comment by Special-Niewbie** [comment]
> 

With those deb package , it install but doesn't show any new kernel no where, i check even on the list of available Kernel by Terminal.

If the situation it's not that easy, there is a more simple way to make an Ubuntu media installation with included the new Kernel for Surface? At least I can perform it from the installation stage instead of to include after,,,,,,

Or other any way, like to keep not decrypted hard disk at the beginning, and once I finished everything with the new installation Kernel (so I perform everything without zfs file system but with the normal ext4 file system), I will encrypt the Disk after?

As I feel, the `zfs` file system it brings me extra and incompatible work here.

**Comment by Special-Niewbie** [comment]
> Which versions did you install? As I've said, you already have the 5.19.10 Surface kernel installed. You could try [5.19.8](https://github.com/linux-surface/linux-surface/releases/tag/debian-5.19.8-1) or some earlier version.

Sorry , my bad, I miss understood, I have tried the **5.19.8** installed and show up to the list...but when I try to boot into the new Kernel it gives me the same error as 5.19.10.

Other idea how can I get more simple, this installation working? 
The disk I need Encrypted and I would like to keep Ubuntu Distro, any idea friend?!

**Comment by qzed** [comment]
If that's an option for you, you could drop zfs for ext4 (or btrfs if you need more features). Via LVM/LUKS any filesystem should support encryption.

**Comment by Special-Niewbie** [comment]
Hello everyone, 

this time I performed a new installation with Encryption file system Ext4/LVM, and I confirm that everything was installed smoothly without errors.
To whom would like to have the Encrypted Disk in them system ,I suggest you (for now) to avoid the Encryption by ZFS for the problem GNU Licenses between OpenZFS and Linux; as make more complicated or impossible for now to build a new Surface Kernel in your system (If you have any doubt, please watch the history of this topic).

Special Thanks to @qzed  !!!

**Comment by Ifiht** [comment]
@Special-Niewbie I know you've moved on, but for the record I was able to resolve this using @qzed's suggestion, followed all the steps for [Installation & Setup](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup), except ___after running___
`sudo apt install linux-image-surface linux-headers-surface libwacom-surface iptsd`  
I downloaded all the [5.19.2 kernel packages](https://github.com/linux-surface/linux-surface/releases/tag/debian-5.19.2-1) from GitHub releases to my Downloads folder & installed over the newer versions with  
`sudo dpkg -i Downloads/*`

Currently running ZFS with encryption & secure boot, kernel `5.19.2-surface x86_64 GNU/Linux` like a charm :100:
