### ISSUE TITLE
Rotation is to sensitive

### ISSUE THREAD

**Issue by Gansgar** [linux-surface/linux-surface#95]
The rotation sensor is much to sensitive. When driving on a train, the screen will constantly switch between portrait and upside portrait mode, even though the screen on my SB2 is attached to the keyboard and in landscape due to the left and right jerking motion of the wagon. 

I'm unsure if this is the responsibility of the kernel or the UI and how it responds on other hardware platforms. Please direct me in the right direction here.

As a solution I could think of an 2D vector with a rolling average.

### Environment

- Hardware model: Surface Book 2 without GPU
- Kernel version: 5.3.18-surface
- Distribution: Ubuntu with Gnome Desktop

**Comment by qzed** [comment]
The kernel only reports raw values (from the 3d acceleration sensor in this case, I think), so unless they are wrong this is not an issue in the kernel (you could try and check this via `/sys/bus/iio`). AFAIK most desktop environments use [`iio-sensor-proxy`](https://gitlab.freedesktop.org/hadess/iio-sensor-proxy/) to determine the orientation, so you might want to look at that.

There's also `SW_TABLET_MODE`, which is a switch/input event indicating if a 2-in-1 device is currently in tablet mode or in normal laptop mode. _Ideally_ desktop environments would consider that and set a rotation lock accordingly, but Gnome doesn't seem to do that (haven't checked on others). Also note that if you're on Gnome you can set a rotation lock.

**Comment by Gansgar** [comment]
Thanks. I thought that it would be not the problematic of the kernel. But it was worth a try.
