### ISSUE TITLE
CP210x as ttyUSBx?

### ISSUE THREAD

**Issue by rdtm443** [linux-surface/linux-surface#956]
Hello folks

I am using the latest kernel from this repo for my Surface Go with ubuntu 22.04 installed.

Furthermore, I am using the Arduino IDE to compile and flash some sketches to a ESP32 board with a CP2104. The problem now is, that the ESP gets recognized as PEB_USB_01 instead of CP210x / ttyUSBx. It can be fixed by following this guide: 

[https://unix.stackexchange.com/questions/75558/ubuntu-make-fails-with-no-such-file-or-directory-lib-modules-3-4-0-build]()

The problem is, that after updating the kernel, I will have to start afresh with getting the CP210x to work.

Is there a way to make it really permanent, i.e. include it in your kernel itself? Or is there another, easier way to make it work?

Many thanks in advance!

**Comment by qzed** [comment]
There should already be a CP210x driver in the kernel ([here](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/cp210x.c)), which does look like it supports the CP2104. Did you check that you really need to compile an external driver and not just load the module manually (or something similar)? If there are issues with that you should probably ask around upstream, e.g., the kernel bugzilla if that subsystem uses that. I doubt anyone here will be able to help you, sorry.

Regarding external kernel modules: Those always have to be built for the specific kernel you intend to use them with. There's no way around that. Utilities like DKMS can help simplify and automate that.

**Comment by rdtm443** [comment]
> There should already be a CP210x driver in the kernel ([here](https://github.com/torvalds/linux/blob/master/drivers/usb/serial/cp210x.c)), which does look like it supports the CP2104. Did you check that you really need to compile an external driver and not just load the module manually (or something similar)? If there are issues with that you should probably ask around upstream, e.g., the kernel bugzilla if that subsystem uses that. I doubt anyone here will be able to help you, sorry.
> 
> Regarding external kernel modules: Those always have to be built for the specific kernel you intend to use them with. There's no way around that. Utilities like DKMS can help simplify and automate that.
> 
> 

Thank you very much for your quick and lengthy reply, I highly appreciate that! 

Well, the problem is the VID/PID of the device, that has to be added to cp210x.c, in order to be recognized as such.. 

But maybe I will find another way around this.

Anyways, you are right, it has basically nothing to do with the surface kernel. So I will close the issue.

And, thanks again!

**Comment by qzed** [comment]
Adding the VID/PID should be fairly simple, so you could consider writing a patch for that yourself and sending it in upstream. Or again, just ask the maintainers of that driver to add that. The `./scripts/get_maintainer.pl` script outputs
```
Johan Hovold <johan@kernel.org> (maintainer:USB SERIAL SUBSYSTEM)
Greg Kroah-Hartman <gregkh@linuxfoundation.org> (supporter:USB SUBSYSTEM)
linux-usb@vger.kernel.org (open list:USB SERIAL SUBSYSTEM)
```
So that's where you could start.
