### ISSUE TITLE
No cameras listed on SB2 15" with Kernel 6.0.1 and Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by quantum-devcraft** [linux-surface/linux-surface#966]
I upgraded by SB 2 to Ubuntu 22.04 and my camera isn't working since. Both the front and the back camera used to work earlier.

Running cam --list throws the following error

<pre>[1:12:48.662681736] [18517]  INFO Camera camera_manager.cpp:294 libcamera v0.0.0+2948-a000a1f6
[1:12:48.664036489] [18518] ERROR MediaDevice media_device.cpp:724 /dev/media0[ipu3-cio2]: Failed to find pad with id: 51
[1:12:48.664270371] [18518]  INFO DeviceEnumerator device_enumerator.cpp:218 Unable to populate media device /dev/media0 (Invalid argument), skipping
Available cameras:
</pre>
### Environment

- Hardware model: Surface Book 2 15: 
- Kernel version:6.0.1
- Distribution: Ubuntu

I have looked at the other issues with camera https://github.com/linux-surface/linux-surface/issues/876 and https://github.com/linux-surface/linux-surface/issues/91 and neither of them seemed to be related. What should I do to get the cameras working? Is there anything I can do to help debug this issue? I am not a Linux expert so looking for some help on next steps.

**Comment by qzed** [comment]
Cameras work on my SB2 with https://github.com/kbingham/libcamera/commit/a83aed77 on v6.0.1. I think the libcamera version you're using is quite old (according to https://github.com/kbingham/libcamera/commit/a000a1f6 it's from August 2021), can you try updating it?

**Comment by quantum-devcraft** [comment]
Thanks a lot @qzed. Upgrading libcamera did the trick. Closing the issue
