### ISSUE TITLE
SB2 IPTS touchscreen not working on 5.5

### ISSUE THREAD

**Issue by chasecovello** [linux-surface/linux-surface#97]
I'm opening a new issue for this issue specifically.

I haven't been able to get IPTS on the Surface Book 2 to work under kernel 5.5. The kernel module loads and X detects the touchscreen device, but it doesn't generate any libinput events. IPTS works fine on 5.3.18. I haven't been able to make sense of the Xorg logs, which are attached here.

One thing mentioned in another thread was whether it works on Wayland. It doesn't. Maybe the kernel/userspace interface changed between 5.3 and 5.5?

[Xorg.0.log.linux-5.3.txt](https://github.com/linux-surface/linux-surface/files/4240431/Xorg.0.log.linux-5.3.txt)
[Xorg.0.log.linux-5.5.txt](https://github.com/linux-surface/linux-surface/files/4240432/Xorg.0.log.linux-5.5.txt)

**Comment by TheTimeWalker** [comment]
Did you also build and install this driver: https://github.com/linux-surface/intel-precise-touch
This is needed for 5.3+ as the way IPTS works has changed

**Comment by hapm** [comment]
As of now intel_ipts will not work under 5.5, because intel disabled guc in kernel 5.4+.
You'll need the [driver that doesn't need guc submission](https://github.com/linux-surface/intel-precise-touch/blob/master/README.md). Little caviar: the driver currently doesn't support multitouch (yet).

**Comment by chasecovello** [comment]
Thanks! I got it to work with the `singletouch=y` parameter. See https://github.com/linux-surface/linux-surface/issues/94#issuecomment-590118336.
