### ISSUE TITLE
Support for Surface Pro 9

### ISSUE THREAD

**Issue by qzed** [linux-surface/linux-surface#984]
CC @aj3423.

Could you (or anyone with a SP9) run the following tests:

### Preparation:

1. Clone github.com/linux-surface/surface-aggregator-module and `cd` into it.
2. Run `sudo modprobe surface_aggregator_cdev`

### For Battery/Charger

Run the following commands and post the output of each
```
sudo ./scripts/ssam/ctrl.py request 0x02 0x01 0x02 0x01 0x01
sudo ./scripts/ssam/ctrl.py request 0x02 0x01 0x0d 0x01 0x01
```

### For Internal HID Devices

Run the following command for `$x` = 0 until `$x` = 10 and post the output of each
```
sudo ./scripts/ssam/hid.py hid-get-descriptor 1 $x 0
```

### For Type-Cover HID Devices

Run the following command for `$x` = 0 until `$x` = 10 and post the output of each
```
sudo ./scripts/ssam/hid.py hid-get-descriptor 2 $x 0
```

**Comment by aj3423** [comment]
**For Battery/Charger**
It doesn't print anything

**For Internal HID Devices**
```
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 0 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 1 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 2 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 3 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 4 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 5 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 6 0
[9, 33, 17, 1, 0, 1, 34, 108, 12]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 7 0
[9, 33, 17, 1, 0, 1, 34, 109, 0]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 8 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 9 0
[]
~/Downloads/surface-aggregator-module > ./scripts/ssam/hid.py hid-get-descriptor 1 10 0
[]
~/Downloads/surface-aggregator-module > 
```

**For Type-Cover HID Devices**
I don't have a type-cover keyboard yet, I'll update this when I buy one. Currently it shows "timeout" for all 0~10:
```
Traceback (most recent call last):
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/hid.py", line 133, in <module>
    main()
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/hid.py", line 125, in main
    dump_raw_data(dev.get_device_descriptor(entry))
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/hid.py", line 47, in get_device_descriptor
    done, part = self._get_device_descriptor_part(entry, len(data), n)
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/hid.py", line 57, in _get_device_descriptor_part
    resp = self.ctrl.request(rqst)
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/libssam.py", line 355, in request
    return _request(self.fd, request)
  File "/root/Downloads/surface-aggregator-module/scripts/ssam/libssam.py", line 263, in _request
    raise OSError(-raw.status, errno.errorcode.get(-raw.status))
TimeoutError: [Errno 110] ETIMEDOUT
```

**Comment by qzed** [comment]
> It doesn't print anything

I've messed up the commands and fixed them in the post above. I've forgot the `request` argument, so it should be
```
sudo ./scripts/ssam/ctrl.py request 0x02 0x01 0x02 0x01 0x01
sudo ./scripts/ssam/ctrl.py request 0x02 0x01 0x0d 0x01 0x01
```

Could you run those again? Thanks!

**Comment by qzed** [comment]
> I don't have a type-cover keyboard yet, I'll update this when I buy one. Currently it shows "timeout" for all 0~10:

That's the expected behavior with typecover disconnected. I think we'll unfortunately need one to check if they've changed anything compared to the SP8. I somewhat doubt it but I want to make sure.

**Comment by aj3423** [comment]
@qzed That comment is now updated with the output.

**Comment by qzed** [comment]
There's a work-in-progress branch for the SP9 at https://github.com/linux-surface/surface-aggregator-module/tree/devices/sp9. Thanks to @aj3423's testing, the battery status and platform profile should now work. I'll integrate those bits into the kernel later today.

The typecover still needs testing/validation so that I can hook up the right nodes, but we should get it up and running as soon as we have that.

**Comment by aj3423** [comment]
@qzed Type-Cover section updated.

**Comment by qzed** [comment]
@aj3423 Thanks!

Last thing to test: We need to make sure that the events are still enabled/disabled the same way. For that, can you go through the following steps?

1. Same preparation as above (clone repo and run `sudo modprobe surface_aggregator_cdev`
2. Open a window with `dmesg -w` to the side.
3. Run
    ```
    sudo ./scripts/ssam/evreg.py reg2-disable 0x15 0x00 0x03
    ```
    It's possible that events for the touchpad were already enabled before and due to that you can maybe already see some "unhandled event" messages in the dmesg log. This command should disable events for the touchpad.
   
   Now try using the touchpad (just that, don't touch the keyboard keys). You should see no "unhandled event" messages or other messages showing up in the dmesg log as a result of that.
4. Run
    ```
    sudo ./scripts/ssam/evreg.py reg2-enable 0x15 0x00 0x03
    ```
    This command should enable events for the touchpad.
    
    Try using the touchpad again. You should now see a bunch of "unhandled event" messages every time you touch it.
5. Run
    ```
    sudo ./scripts/ssam/evreg.py reg2-disable 0x15 0x00 0x03
    ```
    again. This command should disable touchpad events again.

    Try using the touchpad for a last time to confirm that dmesg isn't showing any "unhandled event" messages any more.

If that works for the touchpad, it'll also work for the keyboard and the other HID devices of the typecover.

**Comment by aj3423** [comment]
@qzed 
1. run `dmesg -w`
	There is one "unhandled event":
	> `[    4.523494] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x02, tc: 0x02, tid: 0x01, cid: 0x1a, iid: 0x01)`

2. Disable. `./scripts/ssam/evreg.py reg2-disable 0x15 0x00 0x03` shows result `00`. 
	Yes, there is no output when being touched or pressed.

3. Enable. `/scripts/ssam/evreg.py reg2-enable 0x15 0x00 0x03`  shows `00`.
	- The first time it's touched, there is an 
		> surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x02, cid: 0x00, iid: 0x03)
	- After that, there is no more event output, no matter being touched or pressed.
	- After several minutes, touch it again, there is another "unhandled event", same as previous, no more output in a period of time even being used.
	- The above behavior repeats.

4. Disable it again, shows `00`, no more output when being used.

5. When it's enabled, press <space> bar, there is no output.

**Comment by qzed** [comment]
Okay, I've pushed a new update to https://github.com/linux-surface/surface-aggregator-module (branch `devices/sp9`). With that, keyboard and touchpad should work. Could you give that a try? In particular, also try detaching and re-attaching it and see if that works fine.

If that works, can you also check that the tablet-mode switch works by checking the similarly-named input device with `evtest` while folding the typecover back and forth (and also detaching it). This should send a SW_TABLET_MODE event to enable/disable tablet mode.

**Comment by qzed** [comment]
To sum up our discussion on Matrix: Keyboard and touchpad now work. I'll include support for that later in the kernel after I've cleaned up the commits a bit.

However, the "old" tablet mode switch via the KIP subsystem doesn't work any more. It looks like that is now handled via the POS subsystem, similar to the Surface Laptop Studio. Unfortunately, the posture states are different. For the SLS, we have
```c
enum ssam_pos_state {
	SSAM_POS_POSTURE_LID_CLOSED = 0x00,
	SSAM_POS_POSTURE_LAPTOP     = 0x01,
	SSAM_POS_POSTURE_SLATE      = 0x02,
	SSAM_POS_POSTURE_TABLET     = 0x03,
};
```
whereas for the SP9 the old values seem to be used:
```c
enum ssam_kip_cover_state {
	SSAM_KIP_COVER_STATE_DISCONNECTED  = 0x01,
	SSAM_KIP_COVER_STATE_CLOSED        = 0x02,
	SSAM_KIP_COVER_STATE_LAPTOP        = 0x03,
	SSAM_KIP_COVER_STATE_FOLDED_CANVAS = 0x04,
	SSAM_KIP_COVER_STATE_FOLDED_BACK   = 0x05,
};
```

So we need to find a way to check which set of values to use inside the POS tablet switch driver, or we need to encode that info in the device node for the tablet switch device.

The source ID for the SP9 is `0`. According to https://github.com/linux-surface/linux-surface/issues/851#issuecomment-1155882239, the source ID for the SLS is `3` (@NP-chaonay, can you verify that again by running `./ctrl.py request 0x26 0x01 0x01 0x00 0x01`?). So if this hasn't changed, this would indicate that `0` is for the type-cover and `3` for the SLS, so we can differentiate the different mappings via that.

**Comment by NP-chaonay** [comment]
> (@NP-chaonay, can you verify that again by running ./scripts/ssam/ctrl.py request 0x26 0x01 0x01 0x00 0x01?). So if this hasn't changed, this would indicate that 0 is for the type-cover and 3 for the SLS, so we can differentiate the different mappings via that.

ok so I have put the result in Linux-Matrix

**Comment by qzed** [comment]
Thanks!

**Comment by qzed** [comment]
I've sent the first patches upstream: https://patchwork.kernel.org/project/platform-driver-x86/list/?series=694888. These add support for battery/charger status, keyboard, and touchpad. I'll have a look at the tablet mode switch in the next days.

**Comment by qzed** [comment]
I'm closing this as SAM (typecover, battery/charger-status, performance profiles, ...) stuff should be supported now. Touch I believe too with ITHC and IPTSd from the GitHub repos directly.

Feel free to open a new issue if there are any remaining problems (I think the shutdown issue still needs to be addressed?).

**Comment by NP-chaonay** [comment]
According to #1010 

It seem detected that the modified version of  surface_gpe making lid work.

So I wonder if changing surface_gpe for SP9 will able to address shutdown and power operation problem

**Comment by qzed** [comment]
I finally got around to implementing tablet-mode switch support on the SP9. @aj3423 Do you still have Linux installed and are willing to help test this? CC @Zavon (as you're on the tester list).

To test this:
1. Clone https://github.com/linux-surface/surface-aggregator-module/, cd into the directory and check out the `feature/sp9-tabletsw` branch:
   ```
   git clone https://github.com/linux-surface/surface-aggregator-module.git
   cd surface-aggregator-module
   git checkout feature/sp9-tabletsw
   ```
2. Build the module
   ```
   cd module
   make clean all
   ```
3. Unload the built-in module and load the new ons:
   ```
   sudo modprobe -r surface_aggregator_tabletsw
   sudo insmod src/clients/surface_aggregator_tabletsw.ko
   ```

After that, you can test it by running `sudo evtest`. There should now be a `POS Tablet Mode Switch`. Select that and try flipping the typecover around. You should see events appearing when the "tablet mode" is turned on/off.

**Comment by qzed** [comment]
The next releases should contain support for the tablet-mode switch. That should be the last SP9 specific SAM related item. For other problems please see existing issues or open a new one.
