### ISSUE TITLE
Error: linux-surface.db

### ISSUE THREAD

**Issue by chris122380** [linux-surface/linux-surface#994]
When trying to update the linux-surface repository on Manjaro I am getting the following error:

> sudo pamac upgrade --force-refresh 

gives the following error.:

> Error: linux-surface.db: linux-surface: signature from "linux-surface" is invalid

### Environment

- Hardware model: Surface Pro 4
- Kernel version: 6.0.8-arch1-3-surface
- Distribution: Manjaro Linux x86_64 

<details>

[dmesg.txt](https://github.com/linux-surface/linux-surface/files/10080022/dmesg.txt)

I tried re-installing the signed packages

>  curl -s https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc \
    | sudo pacman-key --add -

>  sudo pacman-key --finger 56C464BAAC421453

>  sudo pacman-key --lsign-key 56C464BAAC421453

but this made no difference. 

</details>

**Comment by qzed** [comment]
Unfortunately I can't reproduce this in a new Arch container. Did you have the repository set up before or is this the first time you've set them up (on this OS install)? Were there any errors for any of the the `pacman-key` commands? Lastly, does running `curl -s https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc` by itself (without the pipe) work and print the key?

**Comment by urbenlegend** [comment]
I am running into this exact issue. There were no issues importing the key using the steps listed in [the installation instructions](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#Arch) and pacman seemed to run fine. However, Pamac (the GUI software package manager) doesn't seem to like it and complains about a `invalid or corrupted database (PGP signature)` when attempting to refresh databases. Attempting to install any packages gives a `Error: linux-surface: signature from "Linux-Surface Package Signer (signing-key for packages in linux-surface package repositories) <luzmaximilian@gmail.com>" is invalid` message.

Deleting `/var/lib/pacman/sync/linux-surface.db.sig` seems to workaround the issue, but it comes back the next time you run `pacman` in the terminal. Is there a special thing I need to set in Pamac to get this working?

**Comment by qzed** [comment]
This is a duplicate of https://github.com/linux-surface/linux-surface/issues/746. Unfortunately I still haven't been able to reproduce this, even on manjaro.
